-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Peroth'arn", {
	[105442] = {"blue","yellow"},
	[105493] = {"blue","yellow"},
	[105544] = {"blue","red"},
	["eyes"] = "green",
})

BigWigs:AddSounds("Peroth'arn", {
	[105442] = "long",
	[105493] = "long",
	[105544] = "alert",
	["eyes"] = "info",
})

BigWigs:AddColors("Queen Azshara WellOfEternity", {
	[-3969] = {"green","orange"},
	[-3968] = "yellow",
})

BigWigs:AddSounds("Queen Azshara WellOfEternity", {
	[-3969] = "long",
	[-3968] = "alert",
})

BigWigs:AddColors("Mannoroth and Varo'then", {
	[-4287] = "cyan",
})

BigWigs:AddSounds("Mannoroth and Varo'then", {
	[-4287] = "info",
})

BigWigs:AddColors("Well Of Eternity Trash", {
})

BigWigs:AddSounds("Well Of Eternity Trash", {
})
