-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("The Lost Dwarves", {
	[369563] = "purple",
	[369573] = "yellow",
	[369602] = "orange",
	[369677] = {"blue","yellow"},
	[369791] = "red",
	[375286] = {"blue","red"},
	[375924] = "orange",
})

BigWigs:AddSounds("The Lost Dwarves", {
	[369563] = "alert",
	[369573] = "alarm",
	[369602] = "warning",
	[369677] = "alert",
	[369791] = "alarm",
	[375286] = {"alert","underyou"},
	[375924] = "long",
})

BigWigs:AddColors("Bromach", {
	[369605] = "cyan",
	[369660] = "green",
	[369675] = "red",
	[369700] = "yellow",
	[369703] = "orange",
	[369754] = "red",
})

BigWigs:AddSounds("Bromach", {
	[369605] = "long",
	[369660] = "info",
	[369675] = "alert",
	[369700] = "info",
	[369703] = "alarm",
	[369754] = "alert",
})

BigWigs:AddColors("Sentinel Talondras", {
	[372600] = {"green","red","yellow"},
	[372623] = {"blue","yellow"},
	[372701] = "orange",
	[372718] = {"blue","red"},
	[372719] = {"green","orange","red"},
})

BigWigs:AddSounds("Sentinel Talondras", {
	[372600] = {"info","long"},
	[372623] = "alert",
	[372701] = "alarm",
	[372718] = "alert",
	[372719] = {"info","long","warning"},
})

BigWigs:AddColors("Emberon", {
	[368990] = "cyan",
	[369038] = "green",
	[369043] = "green",
	[369061] = "purple",
	[369110] = "orange",
})

BigWigs:AddSounds("Emberon", {
	[368990] = "long",
	[369038] = "info",
	[369043] = "info",
	[369061] = "alarm",
	[369110] = "alert",
})

BigWigs:AddColors("Chrono-Lord Deios", {
	[375727] = "purple",
	[376049] = "orange",
	[376208] = "yellow",
	[376325] = "blue",
	[377405] = {"blue","red"},
})

BigWigs:AddSounds("Chrono-Lord Deios", {
	[375727] = "alarm",
	[376049] = "alarm",
	[376208] = {"info","long"},
	[376325] = "underyou",
	[377405] = "alert",
})

BigWigs:AddColors("Uldaman: Legacy of Tyr Trash", {
	[369328] = "red",
	[369335] = "purple",
	[369337] = "blue",
	[369365] = {"blue","orange","red"},
	[369366] = {"blue","orange"},
	[369400] = {"red","yellow"},
	[369409] = {"blue","purple"},
	[369411] = "red",
	[369465] = "orange",
	[369675] = "red",
	[369811] = "orange",
	[369823] = {"red","yellow"},
	[377500] = {"red","yellow"},
	[377724] = "green",
	[377732] = "purple",
	[377738] = {"blue","yellow"},
	[381593] = "red",
	[382578] = "orange",
	[386104] = "green",
})

BigWigs:AddSounds("Uldaman: Legacy of Tyr Trash", {
	[369328] = "long",
	[369335] = "alarm",
	[369337] = "underyou",
	[369365] = {"alert","warning"},
	[369366] = "alarm",
	[369400] = "alert",
	[369409] = "alarm",
	[369411] = "alarm",
	[369465] = "info",
	[369675] = "alert",
	[369811] = "alarm",
	[369823] = {"alert","warning"},
	[377500] = "alert",
	[377724] = "info",
	[377732] = "alarm",
	[377738] = "alert",
	[381593] = "alarm",
	[382578] = "alarm",
	[386104] = "info",
})
