-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Maiden of Virtue", {
	[227508] = "yellow",
	[227789] = {"blue","green","red"},
	[227800] = "yellow",
	[227809] = {"blue","red"},
	[227823] = {"orange","red"},
})

BigWigs:AddSounds("Maiden of Virtue", {
	[227508] = "warning",
	[227789] = {"alarm","info","warning"},
	[227800] = "alarm",
	[227823] = {"alarm","alert"},
})

BigWigs:AddColors("Opera Hall: Wikket", {
	[227410] = "orange",
	[227447] = "yellow",
	[227477] = "orange",
	[227776] = "red",
})

BigWigs:AddSounds("Opera Hall: Wikket", {
	[227410] = "warning",
	[227447] = "info",
	[227477] = "alert",
	[227776] = "long",
})

BigWigs:AddColors("Opera Hall: Westfall Story", {
	[227453] = "orange",
	[227568] = "yellow",
	[227777] = "red",
	[227783] = "orange",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Opera Hall: Westfall Story", {
	[227453] = "alert",
	[227568] = "alarm",
	[227777] = "warning",
	[227783] = "info",
	["stages"] = "long",
})

BigWigs:AddColors("Opera Hall: Beautiful Beast", {
	[227985] = {"blue","purple"},
	[227987] = {"red","yellow"},
	[228019] = "orange",
	[228025] = "red",
	[228221] = {"blue","yellow"},
	[228225] = "yellow",
	[232153] = "orange",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Opera Hall: Beautiful Beast", {
	[227985] = "alarm",
	[227987] = {"alert","warning"},
	[228019] = "alert",
	[228025] = "warning",
	[228221] = {"alert","warning"},
	[228225] = "warning",
	[232153] = "info",
	["stages"] = "long",
})

BigWigs:AddColors("Attumen the Huntsman", {
	[227363] = "orange",
	[227365] = "yellow",
	[227493] = "red",
	[228852] = "orange",
	[228895] = "red",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Attumen the Huntsman", {
	[227363] = "alarm",
	[227365] = "alert",
	[227493] = "alarm",
	[228852] = "info",
	[228895] = "long",
	["stages"] = {"info","long"},
})

BigWigs:AddColors("Moroes", {
	[227463] = {"blue","orange"},
	[227545] = "orange",
	[227578] = "red",
	[227616] = "red",
	[227646] = {"blue","yellow"},
	[227672] = "red",
	[227736] = "yellow",
	[227742] = {"blue","orange"},
	[227851] = {"blue","orange","purple"},
	[227872] = {"cyan","yellow"},
	["cc"] = "cyan",
})

BigWigs:AddSounds("Moroes", {
	[227463] = "warning",
	[227545] = "warning",
	[227578] = "warning",
	[227616] = "info",
	[227646] = {"long","underyou"},
	[227672] = "alarm",
	[227742] = "info",
	[227851] = {"alarm","warning"},
	[227872] = "info",
	["cc"] = "info",
})

BigWigs:AddColors("The Curator", {
	[227254] = {"cyan","green"},
	[227267] = "yellow",
	[227279] = {"blue","orange"},
})

BigWigs:AddSounds("The Curator", {
	[227254] = {"info","long"},
	[227267] = "info",
	[227279] = {"alert","underyou"},
})

BigWigs:AddColors("Shade of Medivh", {
	[227592] = {"blue","orange"},
	[227615] = {"orange","red"},
	[227628] = "purple",
	[227779] = {"blue","yellow"},
	[228269] = {"blue","red","yellow"},
	[228334] = {"cyan","yellow"},
})

BigWigs:AddSounds("Shade of Medivh", {
	[227592] = {"alarm","warning"},
	[227615] = "alert",
	[227628] = "alert",
	[227779] = {"long","warning"},
	[228269] = {"long","warning"},
	[228334] = {"info","long"},
})

BigWigs:AddColors("Mana Devourer", {
	[227297] = "orange",
	[227457] = "orange",
	[227502] = "blue",
	[227523] = {"blue","yellow"},
	[227618] = "red",
})

BigWigs:AddSounds("Mana Devourer", {
	[227297] = "long",
	[227457] = "alarm",
	[227523] = {"info","underyou"},
	[227618] = "warning",
})

BigWigs:AddColors("Viz'aduum the Watcher", {
	[229083] = {"blue","red","yellow"},
	[229151] = "yellow",
	[229159] = {"blue","red"},
	[229248] = {"blue","orange"},
	[229284] = "orange",
	[229905] = "blue",
	[230066] = "red",
	[230084] = {"green","orange"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("Viz'aduum the Watcher", {
	[229083] = {"alert","info"},
	[229151] = "alarm",
	[229159] = "warning",
	[229248] = "alarm",
	[229905] = "underyou",
	[230066] = "alarm",
	[230084] = {"info","long"},
	["stages"] = "long",
})

BigWigs:AddColors("Nightbane", {
	[228785] = "red",
	[228790] = {"green","red"},
	[228792] = {"green","red"},
	[228796] = {"blue","red"},
	[228808] = {"blue","orange"},
	[228829] = {"blue","orange"},
	[228834] = "red",
	[228835] = {"blue","orange"},
	[228837] = "yellow",
	[229307] = "yellow",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Nightbane", {
	[228785] = "alert",
	[228790] = "info",
	[228792] = "info",
	[228796] = "warning",
	[228808] = {"alarm","alert"},
	[228829] = "info",
	[228835] = "alarm",
	[228837] = "warning",
	[229307] = "alarm",
	["stages"] = "long",
})

BigWigs:AddColors("Karazhan Trash", {
	[227966] = "yellow",
	[227999] = "yellow",
	[228278] = "red",
	[228279] = "yellow",
	[228280] = {"blue","orange"},
	[228528] = "yellow",
	[228575] = "red",
	[228576] = {"blue","orange"},
	[228603] = "purple",
	[228625] = "yellow",
	[229489] = {"green","red"},
	[241828] = "red",
})

BigWigs:AddSounds("Karazhan Trash", {
	[227966] = "alarm",
	[227999] = "alert",
	[228278] = "warning",
	[228279] = "warning",
	[228280] = "warning",
	[228528] = "alarm",
	[228575] = "alert",
	[228576] = "warning",
	[228603] = "alert",
	[228625] = "alert",
	[229489] = {"info","long"},
	[241828] = "warning",
})
