-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Warlord Parjesh", {
	[191900] = "yellow",
	[192053] = "blue",
	[192072] = "yellow",
	[192094] = {"blue","red"},
	[192131] = {"blue","red"},
	[196563] = "yellow",
	[197064] = "orange",
	[197502] = "green",
})

BigWigs:AddSounds("Warlord Parjesh", {
	[191900] = "alert",
	[192053] = "alarm",
	[192072] = "info",
	[192094] = "warning",
	[192131] = "alarm",
	[196563] = "info",
	[197064] = "alert",
	[197502] = {"long","warning"},
})

BigWigs:AddColors("Lady Hatecoil", {
	[193597] = "orange",
	[193611] = "yellow",
	[193682] = "red",
	[193698] = "blue",
	[196610] = "yellow",
})

BigWigs:AddSounds("Lady Hatecoil", {
	[193597] = "warning",
	[193611] = "alert",
	[193682] = "info",
	[193698] = "alarm",
})

BigWigs:AddColors("Serpentrix", {
	[191855] = {"blue","red"},
	[191873] = "yellow",
})

BigWigs:AddSounds("Serpentrix", {
	[191855] = "alarm",
	[191873] = "long",
})

BigWigs:AddColors("King Deepbeard", {
	[193018] = "blue",
	[193051] = "yellow",
	[193093] = "orange",
	[193152] = {"blue","red"},
})

BigWigs:AddSounds("King Deepbeard", {
	[193018] = "warning",
	[193051] = "long",
	[193093] = "info",
	[193152] = "alert",
})

BigWigs:AddColors("Wrath of Azshara", {
	[192617] = "yellow",
	[192675] = "orange",
	[192706] = {"blue","red"},
	[192985] = "green",
	[197365] = {"blue","red"},
})

BigWigs:AddSounds("Wrath of Azshara", {
	[192617] = "warning",
	[192675] = "alert",
	[192706] = "alarm",
	[192985] = "long",
	[197365] = "alarm",
})

BigWigs:AddColors("Eye of Azshara Trash", {
	[195046] = "yellow",
	[195109] = "yellow",
	[195129] = "red",
	[195284] = "yellow",
	[196027] = "yellow",
	[196127] = "yellow",
	[196870] = "yellow",
	[197105] = {"blue","yellow"},
	[225089] = "orange",
})

BigWigs:AddSounds("Eye of Azshara Trash", {
	[195046] = "alarm",
	[195109] = "alarm",
	[195129] = {"info","warning"},
	[195284] = "long",
	[196027] = "alarm",
	[196127] = "long",
	[196870] = "long",
	[197105] = "info",
	[225089] = "warning",
})
