-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Speaker Davenruth", {
	[434281] = "orange",
	[440205] = "yellow",
	[443482] = "red",
	[443837] = "orange",
	[444408] = "yellow",
	[444479] = "red",
})

BigWigs:AddSounds("Speaker Davenruth", {
	[434281] = "alarm",
	[440205] = "alert",
	[443482] = "alert",
	[443837] = "alarm",
	[444408] = "long",
	[444479] = "alert",
})

BigWigs:AddColors("Speaker Wicke", {
	[434281] = "orange",
	[443837] = "orange",
	[444408] = "yellow",
	[444479] = "red",
	[470592] = "red",
	[470593] = "yellow",
})

BigWigs:AddSounds("Speaker Wicke", {
	[434281] = "alarm",
	[443837] = "alarm",
	[444408] = "long",
	[444479] = "alert",
	[470592] = "alert",
	[470593] = "alert",
})

BigWigs:AddColors("Speaker Halven", {
	[443837] = "red",
	[443840] = "yellow",
	[443908] = "orange",
})

BigWigs:AddSounds("Speaker Halven", {
	[443837] = "alarm",
	[443840] = "long",
	[443908] = "alarm",
})

BigWigs:AddColors("Cult Leaders", {
	[434740] = "yellow",
	[443482] = {"red","yellow"},
	[458874] = "orange",
})

BigWigs:AddSounds("Cult Leaders", {
	[434740] = "info",
	[443482] = {"alert","info"},
	[458874] = "alarm",
})
