-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Cragpie", {
	[359016] = "red",
	[390943] = "yellow",
	[470612] = {"blue","orange"},
})

BigWigs:AddSounds("Cragpie", {
	[359016] = {"alert","info"},
	[390943] = "long",
	[470612] = {"alert","info"},
})

BigWigs:AddColors("Leviathan Caller", {
	[442422] = {"green","red"},
	[446079] = "cyan",
})

BigWigs:AddSounds("Leviathan Caller", {
	[442422] = {"info","warning"},
	[446079] = "long",
})

BigWigs:AddColors("Mirror Master Murkna", {
	[445860] = "cyan",
})

BigWigs:AddSounds("Mirror Master Murkna", {
	[445860] = "info",
})
