-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("General Umbriss", {
	[74634] = "orange",
	[74670] = {"blue","red"},
	[74846] = {"blue","yellow"},
	[74853] = {"cyan","yellow"},
	[447261] = "purple",
	[448847] = "yellow",
	[448877] = "orange",
})

BigWigs:AddSounds("General Umbriss", {
	[74670] = "alert",
	[74853] = "long",
	[447261] = "alert",
	[448847] = "long",
	[448877] = "alarm",
})

BigWigs:AddColors("Forgemaster Throngus", {
	[74908] = "red",
	[74976] = "blue",
	[74981] = "red",
	[74987] = "blue",
	[75007] = "red",
	[75056] = {"blue","orange"},
	[447395] = "orange",
	[449444] = "red",
	[449474] = {"blue","yellow"},
	[449687] = {"green","purple"},
	[457664] = "cyan",
})

BigWigs:AddSounds("Forgemaster Throngus", {
	[74908] = "alert",
	[74976] = "long",
	[74981] = "alert",
	[74987] = "alarm",
	[75007] = "alert",
	[447395] = "alarm",
	[449444] = "alert",
	[449474] = "alert",
	[449687] = {"info","warning"},
	[457664] = "info",
})

BigWigs:AddColors("Drahga Shadowburner", {
	[75218] = "yellow",
	[82850] = {"blue","red"},
	[90950] = "red",
	[447966] = "red",
	[448013] = "yellow",
	[448105] = "red",
	[450095] = {"blue","red"},
	[456751] = "orange",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Drahga Shadowburner", {
	[75218] = "info",
	[82850] = "warning",
	[90950] = "alarm",
	[447966] = "alert",
	[448013] = "info",
	[448105] = "alarm",
	[450095] = "alert",
	[456751] = "alarm",
	["stages"] = "long",
})

BigWigs:AddColors("Erudax", {
	[75664] = "orange",
	[75755] = "red",
	[75763] = "red",
	[448057] = {"blue","red"},
	[449939] = "orange",
	[450077] = "yellow",
	[450087] = "blue",
	[450088] = "cyan",
	[450100] = "purple",
	["summon"] = "yellow",
})

BigWigs:AddSounds("Erudax", {
	[75664] = "alert",
	[75755] = "alarm",
	[75763] = "warning",
	[448057] = "alarm",
	[449939] = "info",
	[450077] = "alert",
	[450087] = "alarm",
	[450088] = "long",
	[450100] = "alert",
})

BigWigs:AddColors("Grim Batol Trash", {
	[76711] = "red",
	[451224] = {"blue","orange"},
	[451241] = "purple",
	[451364] = "purple",
	[451378] = "purple",
	[451387] = "cyan",
	[451391] = {"blue","cyan","orange"},
	[451395] = "blue",
	[451612] = {"blue","red"},
	[451614] = "blue",
	[451871] = "red",
	[451939] = "yellow",
	[451965] = "yellow",
	[451971] = "purple",
	[456696] = "orange",
	[456711] = "orange",
	[456713] = "red",
	[462216] = "yellow",
})

BigWigs:AddSounds("Grim Batol Trash", {
	[76711] = "alert",
	[451224] = "alert",
	[451241] = "alert",
	[451364] = "alert",
	[451378] = "alert",
	[451387] = "info",
	[451391] = {"alarm","info"},
	[451395] = "alert",
	[451612] = "alert",
	[451614] = "underyou",
	[451871] = "alert",
	[451939] = "alarm",
	[451965] = "info",
	[451971] = "alert",
	[456696] = "alarm",
	[456711] = "alarm",
	[456713] = "alarm",
	[462216] = "alarm",
})
