-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Alleria Windrunner", {
	[298691] = "cyan",
	[308278] = "orange",
	[308669] = "red",
	[309648] = "red",
	[309819] = "yellow",
	[312260] = "orange",
})

BigWigs:AddSounds("Alleria Windrunner", {
	[298691] = "long",
	[308278] = "alarm",
	[308669] = "alarm",
	[309648] = "alert",
	[309819] = "warning",
	[312260] = "info",
})

BigWigs:AddColors("Slavemaster Ul'rok", {
	[298691] = "cyan",
	[298866] = "orange",
})

BigWigs:AddSounds("Slavemaster Ul'rok", {
	[298691] = "long",
	[298866] = "alarm",
})

BigWigs:AddColors("Therum Deepforge", {
	[305708] = "orange",
	[309671] = "red",
})

BigWigs:AddSounds("Therum Deepforge", {
	[305708] = "info",
	[309671] = "alarm",
})

BigWigs:AddColors("Overlord Mathias Shaw", {
	[308669] = "red",
	[308681] = "cyan",
	[311530] = "yellow",
})

BigWigs:AddSounds("Overlord Mathias Shaw", {
	[308669] = "alarm",
	[308681] = "info",
	[311530] = "long",
})

BigWigs:AddColors("Magister Umbric", {
	[309373] = "orange",
	[309451] = {"cyan","green"},
	[309648] = "red",
})

BigWigs:AddSounds("Magister Umbric", {
	[309373] = "warning",
	[309451] = {"info","long"},
	[309648] = "alert",
})

BigWigs:AddColors("Horrific Vision of Stormwind Trash", {
	[86736] = "orange",
	[264398] = "yellow",
	[296492] = "orange",
	[296510] = "cyan",
	[296537] = "red",
	[296669] = {"blue","yellow"},
	[296718] = "orange",
	[296911] = "red",
	[297315] = "yellow",
	[298033] = "red",
	[298074] = "orange",
	[298584] = "cyan",
	[306583] = {"blue","green"},
	[306770] = "red",
	[307870] = "green",
	[308265] = {"blue","red"},
	[308305] = "orange",
	[308308] = {"blue","yellow"},
	[308346] = "orange",
	[308366] = "red",
	[308375] = "red",
	[308380] = "orange",
	[308406] = "orange",
	[308432] = {"blue","yellow"},
	[308481] = "orange",
	[308575] = "red",
	[308801] = "yellow",
	[308862] = "orange",
	[308878] = "cyan",
	[308967] = "orange",
	[308998] = "red",
	[309882] = "orange",
	[311390] = "blue",
	[311399] = "orange",
	[311456] = "yellow",
	[311996] = "cyan",
	[1223111] = {"blue","yellow"},
	[1223112] = "red",
})

BigWigs:AddSounds("Horrific Vision of Stormwind Trash", {
	[86736] = "info",
	[264398] = "alarm",
	[296492] = "alarm",
	[296510] = "info",
	[296537] = "alert",
	[296669] = {"info","underyou"},
	[296718] = "alarm",
	[296911] = "alarm",
	[297315] = "alert",
	[298033] = "warning",
	[298074] = "alarm",
	[298584] = "info",
	[306583] = {"alert","info"},
	[306770] = "alarm",
	[307870] = "info",
	[308265] = {"info","warning"},
	[308305] = "alarm",
	[308308] = "alarm",
	[308346] = "alarm",
	[308366] = "alert",
	[308375] = "alert",
	[308380] = "info",
	[308406] = "alarm",
	[308432] = "info",
	[308481] = "alarm",
	[308575] = "alert",
	[308801] = "alarm",
	[308862] = "alarm",
	[308878] = "info",
	[308967] = "alert",
	[308998] = "alert",
	[309882] = "alarm",
	[311390] = "info",
	[311399] = "alarm",
	[311456] = "warning",
	[311996] = "long",
	[1223111] = "alarm",
	[1223112] = "alert",
})
