-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("King Gobbamak", {
	[297254] = "orange",
	[297257] = {"blue","yellow"},
	[297261] = "red",
})

BigWigs:AddSounds("King Gobbamak", {
	[297254] = "alert",
	[297257] = "info",
	[297261] = "alarm",
})

BigWigs:AddColors("Gunker", {
	[297834] = "orange",
	[297835] = "orange",
	[297985] = "orange",
	[298212] = "red",
	[298259] = {"blue","orange"},
})

BigWigs:AddSounds("Gunker", {
	[297834] = "alert",
	[297835] = "alert",
	[297985] = "alert",
	[298212] = "alarm",
	[298259] = "warning",
})

BigWigs:AddColors("Trixie & Naeno", {
	[298571] = "yellow",
	[298651] = "red",
	[298940] = "orange",
	[298946] = "orange",
	[299153] = {"blue","red"},
	[302682] = {"blue","orange"},
})

BigWigs:AddSounds("Trixie & Naeno", {
	[298571] = "info",
	[298651] = "alert",
	[298940] = "alert",
	[298946] = "alert",
	[299153] = "info",
	[302682] = "alarm",
})

BigWigs:AddColors("HK-8 Aerial Oppression Unit", {
	[295445] = "orange",
	[295536] = "red",
	[296080] = "cyan",
	[301351] = "orange",
	[302274] = {"blue","orange"},
	[303885] = {"blue","orange"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("HK-8 Aerial Oppression Unit", {
	[295445] = "alarm",
	[295536] = "alert",
	[296080] = "long",
	[301351] = "alarm",
	[302274] = "info",
	[303885] = "info",
	["stages"] = "long",
})

BigWigs:AddColors("Tussle Tonks", {
	[282801] = {"cyan","green"},
	[283422] = {"blue","orange"},
	[285152] = {"blue","yellow"},
	[1215065] = "purple",
	[1215102] = "yellow",
	[1216431] = "red",
	[1216443] = "cyan",
})

BigWigs:AddSounds("Tussle Tonks", {
	[282801] = "info",
	[283422] = "alarm",
	[285152] = "alert",
	[1215065] = "alarm",
	[1215102] = "info",
	[1216431] = "long",
	[1216443] = "long",
})

BigWigs:AddColors("K.U.-J.0.", {
	[291930] = "yellow",
	[291946] = "red",
	[291973] = {"blue","orange"},
	[294929] = {"blue","purple"},
})

BigWigs:AddSounds("K.U.-J.0.", {
	[291930] = "info",
	[291946] = "alarm",
	[291973] = "alert",
	[294929] = {"alert","warning"},
})

BigWigs:AddColors("Machinist's Garden", {
	[285440] = "red",
	[285454] = {"blue","orange","red"},
	[294853] = "cyan",
	[294855] = {"blue","yellow"},
})

BigWigs:AddSounds("Machinist's Garden", {
	[285440] = "alarm",
	[285454] = {"alert","info"},
	[294853] = "long",
	[294855] = "alert",
})

BigWigs:AddColors("King Mechagon", {
	[283551] = "yellow",
	[291613] = "orange",
	[291626] = {"blue","red"},
	[291865] = "orange",
	[291928] = {"blue","red"},
	[292264] = {"blue","red"},
	[292290] = "purple",
	["button"] = {"blue","cyan"},
	["hardmode"] = "yellow",
	["stages"] = "cyan",
})

BigWigs:AddSounds("King Mechagon", {
	[283551] = "long",
	[291613] = "info",
	[291626] = {"alarm","warning"},
	[291865] = "alarm",
	[291928] = "alert",
	[292264] = "alert",
	[292290] = "warning",
	["button"] = "warning",
	["hardmode"] = "long",
	["stages"] = "long",
})

BigWigs:AddColors("Operation: Mechagon Trash", {
	[284219] = {"blue","orange","yellow"},
	[293683] = "green",
	[293729] = "yellow",
	[293827] = "red",
	[293861] = "orange",
	[293930] = "red",
	[293986] = "red",
	[294103] = "orange",
	[294195] = {"blue","yellow"},
	[294884] = "orange",
	[295169] = "yellow",
	[297128] = "red",
	[297133] = "yellow",
	[299438] = {"blue","purple"},
	[299474] = {"blue","red"},
	[299475] = "red",
	[299502] = {"blue","orange","red"},
	[299525] = "orange",
	[299588] = {"orange","red"},
	[300087] = "yellow",
	[300102] = "yellow",
	[300129] = "red",
	[300159] = "orange",
	[300171] = "red",
	[300177] = "yellow",
	[300188] = {"blue","red"},
	[300207] = "orange",
	[300414] = {"orange","red"},
	[300424] = "red",
	[300436] = "yellow",
	[300514] = {"orange","red"},
	[300650] = {"blue","orange","yellow"},
	[300687] = "orange",
	[300764] = "orange",
	[300777] = "red",
	[301088] = "red",
	[301667] = "red",
	[301681] = "orange",
	[303941] = "yellow",
	[1215409] = "yellow",
	[1215411] = "purple",
	[1215412] = "red",
	[1217819] = {"blue","orange"},
})

BigWigs:AddSounds("Operation: Mechagon Trash", {
	[284219] = {"alert","info"},
	[293683] = "info",
	[293729] = "alert",
	[293827] = "alert",
	[293861] = "alarm",
	[293930] = "info",
	[293986] = "alarm",
	[294103] = "alarm",
	[294195] = "alert",
	[294884] = "alarm",
	[295169] = "long",
	[297128] = "alarm",
	[297133] = "info",
	[299438] = "info",
	[299474] = "alert",
	[299475] = "alarm",
	[299502] = {"alert","info"},
	[299525] = "info",
	[299588] = {"alert","info"},
	[300087] = "alert",
	[300102] = "info",
	[300129] = "alarm",
	[300159] = "alarm",
	[300171] = "alarm",
	[300177] = "info",
	[300188] = "alarm",
	[300207] = "info",
	[300414] = {"alarm","alert"},
	[300424] = "alarm",
	[300436] = "alert",
	[300514] = {"alert","info"},
	[300650] = {"alert","info"},
	[300687] = "alarm",
	[300764] = "alert",
	[300777] = "alarm",
	[301088] = "alert",
	[301667] = "alarm",
	[301681] = "alarm",
	[303941] = "info",
	[1215409] = "alarm",
	[1215411] = "alert",
	[1215412] = "info",
	[1217819] = "alert",
})
