-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("The Golden Serpent", {
	[265773] = {"blue","orange"},
	[265781] = "red",
	[265910] = "purple",
	[265923] = "yellow",
})

BigWigs:AddSounds("The Golden Serpent", {
	[265773] = "warning",
	[265781] = "alarm",
	[265910] = "alert",
	[265923] = "long",
})

BigWigs:AddColors("Mchimba the Embalmer", {
	[267618] = {"blue","orange"},
	[267639] = "red",
	[267702] = {"blue","green","yellow"},
})

BigWigs:AddSounds("Mchimba the Embalmer", {
	[267618] = "alarm",
	[267639] = "warning",
	[267702] = {"info","long"},
})

BigWigs:AddColors("The Council of Tribes", {
	[266206] = "yellow",
	[266231] = {"blue","orange"},
	[266237] = "purple",
	[266951] = {"blue","red"},
	[267060] = "yellow",
	[267273] = "orange",
	["stages"] = "cyan",
})

BigWigs:AddSounds("The Council of Tribes", {
	[266206] = "alert",
	[266231] = "alarm",
	[266237] = "alarm",
	[266951] = "warning",
	[267060] = "long",
	[267273] = "alarm",
	["stages"] = "long",
})

BigWigs:AddColors("Dazar, The First King", {
	[268586] = "purple",
	[268932] = {"blue","orange"},
	[269231] = "blue",
	[269369] = "red",
	["stages"] = {"cyan","yellow"},
})

BigWigs:AddSounds("Dazar, The First King", {
	[268586] = "alarm",
	[268932] = "long",
	[269231] = "alert",
	[269369] = "warning",
	["stages"] = "info",
})

BigWigs:AddColors("King's Rest Trash", {
	[269931] = {"blue","orange"},
	[269936] = "blue",
	[269972] = "red",
	[269976] = "orange",
	[270003] = "red",
	[270016] = "orange",
	[270084] = "yellow",
	[270284] = {"blue","orange"},
	[270482] = "yellow",
	[270487] = {"blue","purple"},
	[270492] = {"blue","cyan","orange"},
	[270499] = {"blue","cyan"},
	[270503] = "blue",
	[270506] = {"blue","red"},
	[270507] = {"blue","cyan","red"},
	[270514] = "orange",
	[270865] = {"blue","yellow"},
	[270872] = "orange",
	[270891] = {"blue","orange"},
	[270901] = {"cyan","red"},
	[270920] = {"blue","yellow"},
	[270928] = {"blue","orange"},
	[270931] = "blue",
	[271555] = {"blue","orange"},
	[271564] = "blue",
	[271640] = {"blue","orange"},
	["healing_tide_totem"] = "red",
})

BigWigs:AddSounds("King's Rest Trash", {
	[269931] = {"alarm","alert"},
	[269936] = "alert",
	[269972] = "warning",
	[269976] = {"alarm","info"},
	[270003] = "alarm",
	[270016] = "info",
	[270084] = "alarm",
	[270284] = {"alarm","alert"},
	[270482] = "alert",
	[270487] = "long",
	[270492] = {"alarm","info"},
	[270499] = "info",
	[270503] = "alert",
	[270506] = "warning",
	[270507] = {"alert","warning"},
	[270514] = "long",
	[270865] = "alarm",
	[270872] = "alert",
	[270891] = {"alert","long"},
	[270901] = {"info","warning"},
	[270920] = {"long","warning"},
	[270928] = {"alarm","alert"},
	[270931] = "alert",
	[271555] = "warning",
	[271564] = "alert",
	[271640] = "alarm",
	["healing_tide_totem"] = "warning",
})
