-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Elder Nadox", {
	[-6042] = "red",
	[56130] = {"blue","yellow"},
})

BigWigs:AddSounds("Elder Nadox", {
})

BigWigs:AddColors("Prince Taldaram", {
	[55931] = "red",
	[59513] = {"blue","green","red"},
})

BigWigs:AddSounds("Prince Taldaram", {
	[59513] = "warning",
})

BigWigs:AddColors("Jedoga Shadowseeker", {
	[60029] = "red",
})

BigWigs:AddSounds("Jedoga Shadowseeker", {
})

BigWigs:AddColors("Amanitar", {
	[57055] = "yellow",
})

BigWigs:AddSounds("Amanitar", {
	[57055] = "info",
})

BigWigs:AddColors("Herald Volazj", {
	[57496] = "red",
	[59978] = {"blue","yellow"},
})

BigWigs:AddSounds("Herald Volazj", {
})

BigWigs:AddColors("Ahn'kahet Trash", {
	[13338] = {"blue","yellow"},
	[56728] = {"blue","red"},
	[59102] = "red",
})

BigWigs:AddSounds("Ahn'kahet Trash", {
	[13338] = "alarm",
	[56728] = "alert",
	[59102] = {"long","warning"},
})
