-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Blightbone", {
	[320596] = {"blue","red"},
	[320630] = {"blue","cyan"},
	[320631] = "red",
	[320637] = "yellow",
	[320655] = "purple",
})

BigWigs:AddSounds("Blightbone", {
	[320596] = {"alarm","warning"},
	[320630] = "warning",
	[320631] = "warning",
	[320637] = "long",
	[320655] = "alert",
})

BigWigs:AddColors("Amarth, The Harvester", {
	[320012] = "purple",
	[320171] = "yellow",
	[321226] = "cyan",
	[321247] = "red",
	[328667] = "red",
	[333488] = "orange",
})

BigWigs:AddSounds("Amarth, The Harvester", {
	[320012] = "info",
	[320171] = "alert",
	[321226] = "long",
	[321247] = "warning",
	[328667] = "alert",
	[333488] = "alarm",
})

BigWigs:AddColors("Surgeon Stitchflesh", {
	[320200] = {"blue","orange"},
	[320358] = "cyan",
	[320359] = "cyan",
	[320376] = "purple",
	[322681] = {"blue","green","red"},
	[327100] = "blue",
	[334476] = {"blue","yellow"},
	[334488] = "purple",
	[343556] = {"blue","red"},
})

BigWigs:AddSounds("Surgeon Stitchflesh", {
	[320200] = "alert",
	[320358] = "info",
	[320359] = "long",
	[320376] = "alert",
	[322681] = {"info","warning"},
	[327100] = "underyou",
	[334476] = {"alarm","underyou"},
	[334488] = "alert",
	[343556] = "warning",
})

BigWigs:AddColors("Nalthor the Rimebinder", {
	[320772] = "red",
	[320788] = {"blue","orange","red"},
	[321368] = {"cyan","green"},
	[321894] = {"blue","yellow"},
	[328181] = {"blue","yellow"},
})

BigWigs:AddSounds("Nalthor the Rimebinder", {
	[320772] = "warning",
	[320788] = {"alarm","alert"},
	[321368] = {"alert","info"},
	[321894] = "long",
	[328181] = "alert",
})

BigWigs:AddColors("The Necrotic Wake Trash", {
	[320464] = "purple",
	[320696] = "purple",
	[320822] = "yellow",
	[321780] = "yellow",
	[321807] = "purple",
	[322756] = "red",
	[323347] = {"blue","yellow"},
	[323471] = {"blue","yellow"},
	[324293] = "orange",
	[324323] = "purple",
	[324372] = "orange",
	[324387] = "yellow",
	[324394] = "purple",
	[327130] = "red",
	[327240] = "orange",
	[327396] = {"blue","orange"},
	[328667] = "red",
	[333477] = "red",
	[333479] = {"blue","yellow"},
	[334748] = "red",
	[335141] = {"green","red"},
	[335143] = "red",
	[338353] = "orange",
	[338357] = "purple",
	[338456] = "purple",
	[338606] = {"blue","yellow"},
	[343470] = "yellow",
	[345623] = "orange",
})

BigWigs:AddSounds("The Necrotic Wake Trash", {
	[320464] = "alert",
	[320696] = "alert",
	[320822] = "info",
	[321780] = "alert",
	[321807] = "alert",
	[322756] = "alarm",
	[323347] = "info",
	[323471] = "info",
	[324293] = "alarm",
	[324323] = "alert",
	[324372] = "alarm",
	[324387] = "alert",
	[324394] = "alert",
	[327130] = "alert",
	[327240] = "alarm",
	[327396] = "alarm",
	[328667] = "alert",
	[333477] = "alarm",
	[333479] = "alert",
	[334748] = "alert",
	[335141] = {"alert","info","warning"},
	[335143] = "alert",
	[338353] = "alert",
	[338357] = "info",
	[338456] = "alert",
	[338606] = {"info","warning"},
	[343470] = "alert",
	[345623] = "alarm",
})
