-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Skycap'n Kragg", {
	[255952] = "yellow",
	[256005] = "yellow",
	[256016] = "blue",
	[256056] = "cyan",
	[256060] = "red",
	[256106] = "orange",
	[272046] = "orange",
})

BigWigs:AddSounds("Skycap'n Kragg", {
	[255952] = "alert",
	[256005] = "info",
	[256016] = "underyou",
	[256056] = "long",
	[256060] = "warning",
	[256106] = "alert",
	[272046] = "alarm",
})

BigWigs:AddColors("Council o' Captains", {
	[256589] = "orange",
	[256979] = {"blue","red"},
	[258338] = {"blue","cyan","yellow"},
	[258381] = "red",
	[264608] = {"blue","green","purple"},
	[265088] = {"blue","green","purple"},
	[265168] = {"blue","green","red"},
	[267522] = "orange",
	[267533] = "orange",
	[272902] = {"blue","green"},
})

BigWigs:AddSounds("Council o' Captains", {
	[256589] = "long",
	[256979] = "alert",
	[258338] = {"alert","info"},
	[258381] = "warning",
	[264608] = {"alarm","info"},
	[265088] = {"alarm","info"},
	[265168] = {"alarm","info","underyou"},
	[267522] = "alert",
	[267533] = "alert",
	[272902] = "info",
})

BigWigs:AddColors("Ring of Booty", {
	[256358] = {"blue","yellow"},
	[256363] = {"blue","orange"},
	[256405] = "red",
	[256489] = "cyan",
	[256552] = "blue",
	[257829] = {"blue","cyan","green"},
	[257904] = "yellow",
})

BigWigs:AddSounds("Ring of Booty", {
	[256358] = "alarm",
	[256363] = "alert",
	[256405] = "warning",
	[256489] = "info",
	[256552] = "underyou",
	[257829] = "info",
	[257904] = "alert",
})

BigWigs:AddColors("Harlan Sweete", {
	[257278] = {"purple","yellow"},
	[257305] = {"blue","orange"},
	[257314] = {"blue","yellow"},
	[257316] = "red",
	[413136] = {"blue","yellow"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("Harlan Sweete", {
	[257278] = "alert",
	[257305] = "alarm",
	[257314] = {"alert","warning"},
	[257316] = "info",
	[413136] = "alert",
	["stages"] = "long",
})

BigWigs:AddColors("Freehold Trash", {
	[257272] = {"blue","yellow"},
	[257397] = {"red","yellow"},
	[257426] = "orange",
	[257436] = "blue",
	[257732] = "red",
	[257736] = "orange",
	[257739] = "blue",
	[257756] = "orange",
	[257775] = {"blue","yellow"},
	[257784] = "red",
	[257870] = "orange",
	[257899] = {"red","yellow"},
	[257908] = {"blue","purple"},
	[258181] = "orange",
	[258199] = "yellow",
	[258323] = {"blue","yellow"},
	[258672] = "orange",
	[258777] = "orange",
	[272402] = {"blue","orange"},
	[274383] = {"blue","yellow"},
	[274400] = "red",
	[274507] = {"blue","yellow"},
	[274555] = "blue",
})

BigWigs:AddSounds("Freehold Trash", {
	[257272] = {"alert","underyou"},
	[257397] = {"alert","warning"},
	[257426] = "alarm",
	[257436] = "alert",
	[257732] = "alarm",
	[257736] = "warning",
	[257739] = "warning",
	[257756] = "alarm",
	[257775] = "alert",
	[257784] = "warning",
	[257870] = "alarm",
	[257899] = {"alert","info"},
	[257908] = {"alert","warning"},
	[258181] = "alarm",
	[258199] = "alarm",
	[258323] = "alert",
	[258672] = "alarm",
	[258777] = "alarm",
	[272402] = "alert",
	[274383] = {"alarm","info"},
	[274400] = "alarm",
	[274507] = {"alarm","alert"},
	[274555] = {"alert","warning"},
})
