-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Selin Fireheart", {
	[44320] = "red",
})

BigWigs:AddSounds("Selin Fireheart", {
	[44320] = "info",
})

BigWigs:AddColors("Vexallus", {
	[-5085] = "red",
	[44335] = {"blue","orange"},
})

BigWigs:AddSounds("Vexallus", {
})

BigWigs:AddColors("Priestess Delrissa", {
	[13323] = {"blue","orange"},
	[27621] = "yellow",
	[44141] = {"blue","red"},
	[44178] = "red",
	[46192] = {"blue","yellow"},
	[46193] = {"blue","yellow"},
})

BigWigs:AddSounds("Priestess Delrissa", {
})

BigWigs:AddColors("Kael'thas Sunstrider Magisters' Terrace", {
	[-5180] = "yellow",
	[-5167] = "red",
	[36819] = "red",
	[44194] = "orange",
	[44224] = "green",
})

BigWigs:AddSounds("Kael'thas Sunstrider Magisters' Terrace", {
	[36819] = "long",
	[44194] = "info",
})

BigWigs:AddColors("Magisters' Terrace Trash", {
	[44475] = {"blue","orange"},
	[44644] = "orange",
	[44765] = {"blue","yellow"},
})

BigWigs:AddSounds("Magisters' Terrace Trash", {
	[44475] = "alert",
	[44644] = {"alert","warning"},
	[44765] = "alarm",
})
