-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Hungarfen", {
	[-6008] = {"blue","orange","yellow"},
	[34168] = {"blue","orange"},
})

BigWigs:AddSounds("Hungarfen", {
	[-6008] = {"alarm","alert"},
	[34168] = {"info","underyou","warning"},
})

BigWigs:AddColors("Ghaz'an", {
	[15716] = {"green","orange"},
	[34268] = {"blue","red"},
	[38737] = "blue",
})

BigWigs:AddSounds("Ghaz'an", {
	[15716] = {"info","long"},
	[34268] = "warning",
	[38737] = "alert",
})

BigWigs:AddColors("Swamplord Musel'ek", {
	[31429] = {"blue","red"},
	[31615] = {"blue","yellow"},
	[34971] = {"blue","orange"},
})

BigWigs:AddSounds("Swamplord Musel'ek", {
	[31429] = "warning",
	[31615] = "alarm",
	[34971] = "long",
})

BigWigs:AddColors("The Black Stalker", {
	[31704] = {"blue","orange"},
	[31715] = {"blue","green","red"},
	[31717] = {"blue","yellow"},
})

BigWigs:AddSounds("The Black Stalker", {
	[31715] = "warning",
})
