-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Kryxis the Voracious", {
	[319650] = "purple",
	[319654] = "orange",
	[319685] = "yellow",
	[319713] = {"blue","red"},
})

BigWigs:AddSounds("Kryxis the Voracious", {
	[319650] = "alarm",
	[319654] = "alert",
	[319685] = "alert",
	[319713] = "alarm",
})

BigWigs:AddColors("Executor Tarvold", {
	[322554] = {"blue","orange"},
	[322574] = "yellow",
	[323551] = {"blue","orange"},
	[328494] = {"blue","yellow"},
})

BigWigs:AddSounds("Executor Tarvold", {
	[322554] = "alert",
	[322574] = "info",
	[323551] = {"alert","underyou"},
	[328494] = "info",
})

BigWigs:AddColors("Grand Proctor Beryllia", {
	[325254] = "orange",
	[325360] = "red",
	[326039] = "yellow",
	[328737] = "blue",
})

BigWigs:AddSounds("Grand Proctor Beryllia", {
	[325254] = "alert",
	[325360] = "long",
	[326039] = "alert",
	[328737] = "info",
})

BigWigs:AddColors("General Kaal", {
	[322903] = "red",
	[323821] = "orange",
	[323845] = {"blue","orange"},
})

BigWigs:AddSounds("General Kaal", {
	[322903] = "warning",
	[323821] = "alert",
	[323845] = "alert",
})

BigWigs:AddColors("Sanguine Depths Trash", {
	[320991] = "red",
	[321105] = "yellow",
	[321178] = "red",
	[322429] = "orange",
	[322433] = {"orange","yellow"},
	[324086] = "green",
	[324089] = "green",
	[326827] = {"green","red"},
	[326836] = {"blue","orange","red"},
	[328170] = "red",
	[334326] = "red",
	[334329] = "orange",
	[334377] = "red",
	[334558] = "orange",
	[334918] = "yellow",
	[335305] = {"blue","orange","yellow"},
	[335308] = "purple",
	[341331] = "green",
})

BigWigs:AddSounds("Sanguine Depths Trash", {
	[320991] = "alarm",
	[321105] = "alert",
	[321178] = "alarm",
	[322429] = "alert",
	[322433] = {"alert","warning"},
	[324086] = "info",
	[324089] = "info",
	[326827] = {"info","warning"},
	[326836] = {"alert","warning"},
	[328170] = "alarm",
	[334326] = "alarm",
	[334329] = "alert",
	[334377] = "alarm",
	[334558] = "alert",
	[334918] = "alert",
	[335305] = "alert",
	[335308] = "alarm",
	[341331] = "info",
})
