-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Temple Guardian Anhuur", {
	[74938] = {"red","yellow"},
	[75592] = {"blue","yellow"},
})

BigWigs:AddSounds("Temple Guardian Anhuur", {
	[74938] = "long",
	[75592] = "alert",
})

BigWigs:AddColors("Anraphet", {
	[75603] = {"blue","orange"},
	[75609] = "blue",
	[75622] = "red",
	[76184] = {"blue","yellow"},
})

BigWigs:AddSounds("Anraphet", {
	[75622] = "alarm",
	[76184] = "alert",
})

BigWigs:AddColors("Isiset", {
	[-2556] = {"cyan","green"},
	[74045] = "blue",
	[74135] = "blue",
	[74137] = "red",
	[74373] = "yellow",
})

BigWigs:AddSounds("Isiset", {
	[-2556] = "info",
	[74045] = "alert",
	[74135] = "alert",
	[74137] = "alarm",
})

BigWigs:AddColors("Ammunae", {
	[75790] = "yellow",
	[76043] = {"blue","orange","red"},
	[80968] = {"blue","yellow"},
})

BigWigs:AddSounds("Ammunae", {
	[75790] = "info",
	[76043] = {"alarm","alert"},
	[80968] = "long",
})

BigWigs:AddColors("Rajh", {
	[-2863] = "blue",
	[-2862] = "orange",
	[-2861] = "yellow",
	[76355] = {"cyan","green"},
})

BigWigs:AddSounds("Rajh", {
	[-2863] = "warning",
	[76355] = "long",
})
