-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Amalgam of Souls", {
	[194956] = "purple",
	[194966] = {"blue","orange"},
	[195254] = {"blue","yellow"},
	[196078] = "cyan",
	[196587] = "orange",
	[196930] = "yellow",
})

BigWigs:AddSounds("Amalgam of Souls", {
	[194956] = {"alert","warning"},
	[194966] = "alarm",
	[195254] = "alarm",
	[196078] = "long",
	[196587] = "alarm",
	[196930] = "alert",
})

BigWigs:AddColors("Illysanna Ravencrest", {
	[197418] = "purple",
	[197478] = {"blue","red"},
	[197546] = {"blue","yellow"},
	[197696] = {"blue","red"},
	[197797] = "yellow",
	[197974] = "orange",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Illysanna Ravencrest", {
	[197418] = "alert",
	[197478] = "alarm",
	[197546] = "alert",
	[197696] = "alarm",
	[197797] = "alert",
	[197974] = "alarm",
	["stages"] = "long",
})

BigWigs:AddColors("Smashspite", {
	[198073] = "yellow",
	[198079] = {"blue","orange"},
	[198245] = "purple",
	[198446] = {"blue","red"},
	[224188] = "green",
})

BigWigs:AddSounds("Smashspite", {
	[198073] = "alert",
	[198079] = {"alarm","warning"},
	[198245] = "alert",
	[198446] = {"alarm","alert"},
	[224188] = "info",
})

BigWigs:AddColors("Kurtalos Ravencrest", {
	[198635] = "purple",
	[198641] = "orange",
	[198820] = "yellow",
	[199143] = "orange",
	[199193] = "cyan",
	[199368] = "green",
	[201733] = {"blue","red"},
	[202019] = "yellow",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Kurtalos Ravencrest", {
	[198635] = "alert",
	[198641] = "alert",
	[198820] = "alarm",
	[199143] = "info",
	[199193] = "long",
	[199368] = "info",
	[201733] = "alert",
	[202019] = {"alert","warning"},
	["stages"] = "long",
})

BigWigs:AddColors("Black Rook Hold Trash", {
	[194966] = {"blue","orange"},
	[196916] = "orange",
	[200084] = {"blue","orange","yellow"},
	[200105] = "cyan",
	[200248] = "yellow",
	[200261] = "orange",
	[200291] = "orange",
	[200343] = "red",
	[200784] = "yellow",
	[200913] = "orange",
	[203163] = {"blue","orange"},
	[204896] = "red",
	[214001] = "orange",
	[214003] = "purple",
	[225573] = "red",
	[225908] = {"blue","yellow"},
	[227913] = "yellow",
})

BigWigs:AddSounds("Black Rook Hold Trash", {
	[194966] = "alarm",
	[196916] = "alarm",
	[200084] = "alert",
	[200105] = "info",
	[200248] = "alert",
	[200261] = "alarm",
	[200291] = "alert",
	[200343] = "alarm",
	[200784] = "alert",
	[200913] = "alarm",
	[203163] = {"alert","warning"},
	[204896] = "alert",
	[214001] = "alarm",
	[214003] = "alert",
	[225573] = "warning",
	[225908] = {"alert","warning"},
	[227913] = "alert",
})
