-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Aqu'sirr", {
	[264101] = "yellow",
	[264166] = {"blue","orange"},
	[264526] = {"blue","orange"},
	[264560] = {"blue","yellow"},
	[265001] = "orange",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Aqu'sirr", {
	[264101] = "alert",
	[264166] = "warning",
	[264526] = "info",
	[264560] = "alarm",
	[265001] = "alarm",
	["stages"] = "long",
})

BigWigs:AddColors("Tidesage Coucil", {
	[267818] = "orange",
	[267830] = "yellow",
	[267891] = {"blue","cyan"},
	[267899] = "red",
	[267901] = "red",
	[267905] = "cyan",
})

BigWigs:AddSounds("Tidesage Coucil", {
	[267818] = "alert",
	[267830] = "info",
	[267891] = {"info","long"},
	[267899] = "alarm",
	[267901] = "warning",
	[267905] = "long",
})

BigWigs:AddColors("Lord Stormsong", {
	[268347] = "yellow",
	[268896] = {"blue","orange"},
	[269097] = "orange",
	[269131] = {"blue","green","red"},
	[274714] = "blue",
})

BigWigs:AddSounds("Lord Stormsong", {
	[268347] = "alert",
	[268896] = "alert",
	[269097] = "alarm",
	[269131] = {"info","warning"},
	[274714] = "alarm",
})

BigWigs:AddColors("Vol'zith the Whisperer", {
	[267037] = {"blue","cyan"},
	[267360] = "red",
	[267385] = "orange",
	[269399] = "yellow",
})

BigWigs:AddSounds("Vol'zith the Whisperer", {
	[267037] = "info",
	[267360] = "long",
	[267385] = "alarm",
	[269399] = "alert",
})

BigWigs:AddColors("Shrine of the Storm Trash", {
	[267977] = "yellow",
	[267981] = "red",
	[268027] = "orange",
	[268030] = "red",
	[268050] = "orange",
	[268177] = "orange",
	[268184] = "yellow",
	[268187] = "orange",
	[268211] = "yellow",
	[268214] = {"blue","orange"},
	[268233] = {"blue","yellow"},
	[268239] = "orange",
	[268273] = {"orange","purple"},
	[268309] = "red",
	[268322] = {"blue","orange","yellow"},
	[268375] = "yellow",
	[268391] = "orange",
	[274437] = "red",
	[274631] = "orange",
	[274633] = {"blue","purple"},
	[276265] = "yellow",
	[276268] = "orange",
	[276292] = "red",
	[276297] = {"blue","orange"},
})

BigWigs:AddSounds("Shrine of the Storm Trash", {
	[267977] = "alert",
	[267981] = "alert",
	[268027] = "alarm",
	[268030] = "alert",
	[268050] = "alarm",
	[268177] = "alert",
	[268184] = "info",
	[268187] = "alert",
	[268211] = "info",
	[268214] = "alert",
	[268233] = "info",
	[268239] = "alert",
	[268273] = "alert",
	[268309] = "alert",
	[268322] = {"alert","info"},
	[268375] = "info",
	[268391] = "alert",
	[274437] = "alert",
	[274631] = "alert",
	[274633] = "info",
	[276265] = "info",
	[276268] = "alarm",
	[276292] = "alarm",
	[276297] = "alarm",
})
