-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Grand Warlock Nethekurse", {
	[30496] = "blue",
	[30500] = {"blue","orange"},
	[30502] = {"green","red"},
})

BigWigs:AddSounds("Grand Warlock Nethekurse", {
	[30496] = "alarm",
	[30502] = "info",
})

BigWigs:AddColors("Blood Guard Porung", {
	[15496] = "blue",
})

BigWigs:AddSounds("Blood Guard Porung", {
	[15496] = "alert",
})

BigWigs:AddColors("Warbringer O'mrogg", {
	[-5894] = {"blue","yellow"},
})

BigWigs:AddSounds("Warbringer O'mrogg", {
	[-5894] = "warning",
})

BigWigs:AddColors("Warchief Kargath Bladefist", {
	[-5899] = "yellow",
})

BigWigs:AddSounds("Warchief Kargath Bladefist", {
	[-5899] = "warning",
})

BigWigs:AddColors("The Shattered Halls Trash", {
	[12542] = {"blue","red"},
	[15615] = {"blue","yellow"},
	[30980] = {"blue","yellow"},
	[35943] = "orange",
	[36020] = {"blue","red"},
	[36033] = {"blue","yellow"},
})

BigWigs:AddSounds("The Shattered Halls Trash", {
	[12542] = "alert",
	[15615] = "alarm",
	[30980] = "alarm",
	[35943] = "long",
	[36033] = "alarm",
})
