-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Coin-Operated Crowd Pummeler", {
	[256493] = {"blue","green"},
	[262347] = "red",
	[269493] = "cyan",
	[271784] = "yellow",
	[271867] = "purple",
	[271903] = "purple",
	[1217294] = "orange",
})

BigWigs:AddSounds("Coin-Operated Crowd Pummeler", {
	[256493] = {"alarm","info"},
	[262347] = "alert",
	[269493] = "long",
	[271784] = "info",
	[271867] = "alarm",
	[271903] = "info",
	[1217294] = "alarm",
})

BigWigs:AddColors("Azerokk", {
	[257582] = {"blue","red"},
	[257593] = "cyan",
	[258622] = {"blue","orange"},
	[271698] = "yellow",
	[275907] = "red",
})

BigWigs:AddSounds("Azerokk", {
	[257582] = "warning",
	[257593] = "info",
	[258622] = {"long","underyou"},
	[271698] = "info",
	[275907] = "alarm",
})

BigWigs:AddColors("Rixxa Fluxflame", {
	[259856] = {"blue","orange"},
	[259940] = {"blue","yellow"},
	[270042] = {"blue","red"},
	[275992] = "cyan",
})

BigWigs:AddSounds("Rixxa Fluxflame", {
	[259856] = "info",
	[259940] = "alert",
	[270042] = {"long","underyou"},
	[275992] = "alarm",
})

BigWigs:AddColors("Mogul Razdunk", {
	[260280] = "yellow",
	[260813] = {"blue","orange"},
	[271456] = {"blue","orange"},
	[276229] = "red",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Mogul Razdunk", {
	[260280] = "alert",
	[260813] = {"alarm","warning"},
	[271456] = "alert",
	[276229] = "long",
	["stages"] = {"info","long"},
})

BigWigs:AddColors("The MOTHERLODE!! Trash", {
	[262092] = "orange",
	[262377] = {"blue","yellow"},
	[262383] = "cyan",
	[263202] = "red",
	[263215] = "orange",
	[263628] = "purple",
	[267354] = "yellow",
	[267433] = "yellow",
	[268362] = "orange",
	[268702] = "red",
	[268712] = "red",
	[268797] = {"blue","orange","red"},
	[268846] = "yellow",
	[269090] = "orange",
	[269302] = "red",
	[269313] = "yellow",
	[269429] = "red",
	[280604] = {"blue","red","yellow"},
	[472041] = {"blue","orange"},
	[473168] = "yellow",
	[473304] = "orange",
	[1213139] = "yellow",
	[1214751] = {"blue","red"},
	[1214754] = "orange",
	[1215411] = "purple",
	[1217279] = {"blue","yellow"},
})

BigWigs:AddSounds("The MOTHERLODE!! Trash", {
	[262092] = "alert",
	[262377] = "info",
	[262383] = "info",
	[263202] = "alert",
	[263215] = "alert",
	[263628] = "alert",
	[267354] = "alert",
	[267433] = "warning",
	[268362] = "alarm",
	[268702] = "warning",
	[268712] = "alarm",
	[268797] = {"alarm","warning"},
	[268846] = "alarm",
	[269090] = "alarm",
	[269302] = "warning",
	[269313] = "info",
	[269429] = "alert",
	[280604] = {"alert","info"},
	[472041] = {"alarm","underyou"},
	[473168] = "long",
	[473304] = "alarm",
	[1213139] = "info",
	[1214751] = "info",
	[1214754] = "alarm",
	[1215411] = "alert",
	[1217279] = "alarm",
})
