-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Krik'thir the Gatewatcher", {
	[28747] = "red",
	[52592] = {"blue","yellow"},
})

BigWigs:AddSounds("Krik'thir the Gatewatcher", {
})

BigWigs:AddColors("Hadronox", {
	[53030] = "orange",
	[53400] = "yellow",
})

BigWigs:AddSounds("Hadronox", {
})

BigWigs:AddColors("Anub'arakAN", {
	[-6359] = "cyan",
	[53472] = "yellow",
})

BigWigs:AddSounds("Anub'arakAN", {
	[53472] = "warning",
})
