-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Ook-Ook", {
	[106648] = "blue",
	[106651] = "cyan",
	[106807] = "red",
})

BigWigs:AddSounds("Ook-Ook", {
	[106648] = "alert",
	[106651] = "info",
	[106807] = {"alarm","long"},
})

BigWigs:AddColors("Hoptallus", {
	[112944] = "red",
	[112992] = {"blue","yellow"},
	[114291] = "orange",
})

BigWigs:AddSounds("Hoptallus", {
	[112944] = "alarm",
	[112992] = {"alert","long"},
	[114291] = "alert",
})

BigWigs:AddColors("Yan-Zhu the Uncasked", {
	[-5658] = "red",
	[106546] = {"blue","yellow"},
	[106563] = {"green","orange"},
	[106851] = {"blue","yellow"},
	[114451] = "orange",
	[114548] = {"blue","red"},
	[115003] = "red",
	["summon"] = "cyan",
})

BigWigs:AddSounds("Yan-Zhu the Uncasked", {
	[-5658] = "long",
	[106546] = "alarm",
	[106563] = {"alert","info"},
	[106851] = {"alarm","warning"},
	[114451] = "warning",
	[114548] = "alert",
	[115003] = "long",
})
