-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Heartsbane Triad", {
	[260703] = "orange",
	[260741] = {"blue","orange"},
	[260773] = "red",
	[260805] = "cyan",
	[260907] = {"blue","orange"},
	[268086] = "blue",
})

BigWigs:AddSounds("Heartsbane Triad", {
	[260703] = "alarm",
	[260741] = {"alarm","alert"},
	[260773] = "warning",
	[260805] = "long",
	[260907] = "alarm",
	[268086] = {"alert","warning"},
})

BigWigs:AddColors("Soulbound Goliath", {
	[260508] = "purple",
	[260512] = "yellow",
	[260541] = "cyan",
	[260569] = "blue",
	[267907] = {"blue","orange"},
})

BigWigs:AddSounds("Soulbound Goliath", {
	[260508] = "alert",
	[260512] = "alert",
	[260541] = "long",
	[260569] = "underyou",
	[267907] = "alarm",
})

BigWigs:AddColors("Raal the Gluttonous", {
	[264694] = {"blue","yellow"},
	[264734] = "purple",
	[264923] = "orange",
	[264931] = "cyan",
	[265005] = "red",
})

BigWigs:AddSounds("Raal the Gluttonous", {
	[264694] = {"alert","underyou"},
	[264734] = "warning",
	[264923] = "alarm",
	[264931] = "long",
	[265005] = "info",
})

BigWigs:AddColors("Lord and Lady Waycrest", {
	[261438] = "purple",
	[261440] = {"blue","red"},
	[261447] = "cyan",
	[268278] = "red",
	[268306] = "orange",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Lord and Lady Waycrest", {
	[261438] = "alert",
	[261440] = "alarm",
	[261447] = "info",
	[268278] = "alert",
	[268306] = "alarm",
	["stages"] = {"info","long"},
})

BigWigs:AddColors("Gorak Tul", {
	[266181] = "orange",
	[266198] = {"cyan","green"},
	[266225] = "red",
	[266266] = "yellow",
	[268202] = {"blue","red","yellow"},
})

BigWigs:AddSounds("Gorak Tul", {
	[266181] = "warning",
	[266198] = "info",
	[266225] = "alert",
	[266266] = "long",
	[268202] = {"alarm","alert"},
})

BigWigs:AddColors("Waycrest Manor Trash", {
	[263891] = {"blue","red","yellow"},
	[263905] = "yellow",
	[263943] = {"blue","orange"},
	[263959] = "red",
	[263961] = "yellow",
	[264038] = {"blue","orange"},
	[264050] = "yellow",
	[264105] = {"blue","orange"},
	[264150] = "orange",
	[264390] = "red",
	[264396] = "yellow",
	[264407] = "orange",
	[264456] = "yellow",
	[264520] = "yellow",
	[264525] = "orange",
	[265346] = "orange",
	[265352] = "orange",
	[265368] = "cyan",
	[265372] = "purple",
	[265407] = "red",
	[265741] = "yellow",
	[265759] = "orange",
	[265760] = "purple",
	[265876] = "red",
	[265880] = {"blue","orange"},
	[265881] = "yellow",
	[266036] = "yellow",
	[271174] = "orange",
	[278444] = "yellow",
})

BigWigs:AddSounds("Waycrest Manor Trash", {
	[263891] = {"alarm","warning"},
	[263905] = "alert",
	[263943] = "alert",
	[263959] = "warning",
	[263961] = "info",
	[264038] = "alarm",
	[264050] = "alert",
	[264105] = "alarm",
	[264150] = "alarm",
	[264390] = "warning",
	[264396] = "alert",
	[264407] = "warning",
	[264456] = "alert",
	[264520] = "alert",
	[264525] = "alarm",
	[265346] = "alarm",
	[265352] = "alarm",
	[265368] = "alert",
	[265372] = "alarm",
	[265407] = "alarm",
	[265741] = "alert",
	[265759] = "warning",
	[265760] = "alert",
	[265876] = "warning",
	[265880] = "alarm",
	[265881] = "alert",
	[266036] = "alert",
	[271174] = "alarm",
	[278444] = "warning",
})
