-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Ol' Waxbeard", {
	[422116] = {"blue","orange"},
	[422163] = {"blue","red"},
	[422245] = "purple",
	[429093] = {"cyan","yellow"},
})

BigWigs:AddSounds("Ol' Waxbeard", {
	[422116] = "alarm",
	[422163] = {"info","warning"},
	[422245] = "alert",
	[429093] = {"info","long"},
})

BigWigs:AddColors("Blazikon", {
	[421817] = {"blue","yellow"},
	[421910] = "cyan",
	[423109] = "red",
	[424212] = {"blue","orange"},
	[425394] = "cyan",
	[443835] = "purple",
})

BigWigs:AddSounds("Blazikon", {
	[421817] = "long",
	[421910] = {"info","warning"},
	[423109] = "alarm",
	[424212] = {"alarm","underyou"},
	[425394] = "info",
	[443835] = "warning",
})

BigWigs:AddColors("The Candle King", {
	[420659] = "cyan",
	[420696] = {"blue","orange"},
	[421067] = "blue",
	[421653] = "blue",
	[422648] = {"blue","yellow"},
	[426145] = "red",
})

BigWigs:AddSounds("The Candle King", {
	[420659] = "info",
	[420696] = "alert",
	[421067] = "underyou",
	[421653] = "info",
	[422648] = {"alarm","warning"},
	[426145] = "warning",
})

BigWigs:AddColors("The Darkness", {
	[426943] = "yellow",
	[427011] = {"blue","red"},
	[427025] = "orange",
	[427157] = "cyan",
	[427176] = "red",
	[428266] = "yellow",
})

BigWigs:AddSounds("The Darkness", {
	[426943] = "warning",
	[427011] = "alarm",
	[427025] = "alarm",
	[427157] = "alert",
	[427176] = "alert",
	[428266] = "long",
})

BigWigs:AddColors("Darkflame Cleft Trash", {
	[422393] = "yellow",
	[422541] = "cyan",
	[423501] = "orange",
	[424322] = "red",
	[425536] = "yellow",
	[426260] = "orange",
	[426261] = "yellow",
	[426295] = "red",
	[426619] = {"blue","red"},
	[426883] = "orange",
	[428019] = {"blue","red","yellow"},
	[428066] = "yellow",
	[428650] = {"blue","red"},
	[430171] = "yellow",
	[440652] = {"blue","orange"},
	[469620] = {"blue","purple"},
	[1218117] = "yellow",
	[1218131] = {"blue","cyan"},
	["minecart"] = {"cyan","green"},
})

BigWigs:AddSounds("Darkflame Cleft Trash", {
	[422393] = "alert",
	[422541] = "info",
	[423501] = "alarm",
	[424322] = "alert",
	[425536] = "alert",
	[426260] = "alarm",
	[426261] = "alarm",
	[426295] = "alert",
	[426619] = {"alarm","info"},
	[426883] = "alarm",
	[428019] = "alert",
	[428066] = "info",
	[428650] = "warning",
	[430171] = "info",
	[440652] = {"alarm","underyou"},
	[469620] = {"alert","warning"},
	[1218117] = "alert",
	[1218131] = {"info","underyou"},
	["minecart"] = {"info","long"},
})
