-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Under-Lord Vik'tis", {
	[448634] = "orange",
	[448644] = "red",
	[448663] = "yellow",
})

BigWigs:AddSounds("Under-Lord Vik'tis", {
	[448634] = "alarm",
	[448644] = "long",
	[448663] = "alert",
})
