-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Pyroguard Emberseer", {
})

BigWigs:AddSounds("Pyroguard Emberseer", {
})

BigWigs:AddColors("Rhahk'Zor", {
	[6304] = "purple",
	[450515] = "orange",
})

BigWigs:AddSounds("Rhahk'Zor", {
	[6304] = "alert",
	[450515] = "alarm",
})

BigWigs:AddColors("Sneed", {
	[5141] = "cyan",
	[6713] = "purple",
	[7399] = "yellow",
})

BigWigs:AddSounds("Sneed", {
	[5141] = "long",
	[6713] = "alert",
	[7399] = "info",
})

BigWigs:AddColors("Gilnid", {
	[5159] = {"blue","orange","red"},
	[5213] = {"blue","orange","red"},
	[450542] = "cyan",
})

BigWigs:AddSounds("Gilnid", {
	[5159] = {"alarm","alert"},
	[5213] = {"alert","info"},
	[450542] = "long",
})

BigWigs:AddColors("Mr. Smite", {
	[-29823] = "cyan",
	[-29813] = "cyan",
	[6432] = "cyan",
	[6435] = "purple",
	[450550] = "red",
})

BigWigs:AddSounds("Mr. Smite", {
	[-29823] = "long",
	[-29813] = "long",
	[6432] = "long",
	[6435] = "alarm",
	[450550] = "alert",
})

BigWigs:AddColors("Captain Greenskin", {
	[5208] = {"blue","orange","purple"},
	[450550] = "red",
})

BigWigs:AddSounds("Captain Greenskin", {
	[5208] = {"alarm","info"},
	[450550] = "alert",
})

BigWigs:AddColors("Edwin VanCleef", {
	[5200] = "cyan",
	[450564] = "yellow",
})

BigWigs:AddSounds("Edwin VanCleef", {
	[5200] = "long",
	[450564] = "info",
})

BigWigs:AddColors("Cookie", {
	[5174] = "red",
	[6306] = {"blue","orange","yellow"},
})

BigWigs:AddSounds("Cookie", {
	[5174] = "warning",
	[6306] = "alert",
})

BigWigs:AddColors("Grimroot", {
	[460509] = {"blue","orange"},
	[460703] = {"green","yellow"},
	[460727] = {"green","red"},
	["adds"] = "cyan",
})

BigWigs:AddSounds("Grimroot", {
	[460509] = {"alarm","underyou"},
	[460703] = "alert",
	[460727] = "long",
	["adds"] = "info",
})

BigWigs:AddColors("Destructor's Wraith", {
	[460401] = "red",
	[462226] = "orange",
	[462250] = {"blue","yellow"},
})

BigWigs:AddSounds("Destructor's Wraith", {
	[460401] = "warning",
	[462226] = "alarm",
	[462250] = "alert",
})

BigWigs:AddColors("Zilbagob", {
	[460403] = "orange",
	[460408] = {"blue","red","yellow"},
})

BigWigs:AddSounds("Zilbagob", {
	[460403] = "warning",
	[460408] = {"alarm","alert"},
})

BigWigs:AddColors("Pyranis", {
	[460545] = {"cyan","green"},
	[460577] = "orange",
	[460666] = "yellow",
	[460671] = "yellow",
	[460676] = "red",
})

BigWigs:AddSounds("Pyranis", {
	[460545] = {"info","long"},
	[460577] = "alert",
	[460666] = "alert",
	[460671] = "alarm",
	[460676] = "alert",
})

BigWigs:AddColors("Diathorus the Seeker", {
	[460755] = {"green","red"},
	[460756] = {"blue","yellow"},
	[460766] = {"blue","orange"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("Diathorus the Seeker", {
	[460755] = "alarm",
	[460756] = "alert",
	[460766] = "info",
	["stages"] = "long",
})

BigWigs:AddColors("Hellscream's Phantom", {
	[460084] = {"blue","purple"},
	[460119] = "purple",
	[460254] = "orange",
})

BigWigs:AddSounds("Hellscream's Phantom", {
	[460084] = "alert",
	[460119] = "info",
	[460254] = "alarm",
})

BigWigs:AddColors("Tendris Warpwood", {
	[5568] = "yellow",
	[22924] = "red",
	[22994] = {"blue","orange","yellow"},
})

BigWigs:AddSounds("Tendris Warpwood", {
	[22924] = "alert",
	[22994] = {"alarm","alert"},
})

BigWigs:AddColors("Illyanna Ravenoak", {
	[22910] = "orange",
	[22911] = {"blue","red"},
	[22914] = "yellow",
	[30933] = "red",
})

BigWigs:AddSounds("Illyanna Ravenoak", {
	[22910] = "info",
	[22911] = "alarm",
	[22914] = "alert",
	[30933] = "alarm",
})

BigWigs:AddColors("Magister Kalendris", {
	[7645] = {"blue","yellow"},
	[22917] = "cyan",
})

BigWigs:AddSounds("Magister Kalendris", {
	[7645] = "alert",
	[22917] = "info",
})

BigWigs:AddColors("Immol'thar", {
	[5568] = "orange",
	[22899] = "cyan",
	[22950] = {"blue","yellow"},
	[451127] = "cyan",
	[452516] = "orange",
})

BigWigs:AddSounds("Immol'thar", {
	[22899] = "info",
	[22950] = "alert",
	[451127] = "info",
})

BigWigs:AddColors("Prince Tortheldrin", {
	[22995] = {"blue","cyan"},
	[67037] = "orange",
})

BigWigs:AddSounds("Prince Tortheldrin", {
	[22995] = "info",
	[67037] = "alarm",
})

BigWigs:AddColors("Guard Mol'dar", {
	[8269] = "cyan",
	[11972] = {"blue","orange"},
	[14516] = "purple",
	[15749] = {"blue","yellow"},
})

BigWigs:AddSounds("Guard Mol'dar", {
	[8269] = "long",
	[11972] = "alarm",
	[14516] = "alert",
	[15749] = "alert",
})

BigWigs:AddColors("Stomper Kreeg", {
	[15578] = "yellow",
	[16740] = "red",
	[22833] = "purple",
	[22835] = "cyan",
})

BigWigs:AddSounds("Stomper Kreeg", {
	[15578] = "alert",
	[16740] = "alert",
	[22833] = "alarm",
	[22835] = "long",
})

BigWigs:AddColors("King Gordok", {
	[15572] = "purple",
	[16727] = "red",
	[16856] = "purple",
	[22886] = {"blue","yellow"},
})

BigWigs:AddSounds("King Gordok", {
	[15572] = "alert",
	[16727] = "alarm",
	[16856] = "alarm",
	[22886] = "info",
})

BigWigs:AddColors("Lethtendris", {
	[11962] = "orange",
	[13338] = {"blue","yellow"},
	[15744] = "yellow",
	[16247] = {"blue","yellow"},
	[17228] = "red",
	[22710] = "yellow",
	[22713] = {"blue","orange"},
})

BigWigs:AddSounds("Lethtendris", {
	[11962] = "alert",
	[13338] = "alert",
	[15744] = "alert",
	[16247] = "alert",
	[17228] = "alert",
	[22710] = "alert",
	[22713] = "alert",
})

BigWigs:AddColors("Hydrospawn", {
	[22419] = "red",
	[22421] = "orange",
	[22714] = "cyan",
})

BigWigs:AddSounds("Hydrospawn", {
	[22419] = "alert",
	[22421] = "alarm",
	[22714] = "info",
})

BigWigs:AddColors("Zevrim Thornhoof", {
	[17228] = "red",
	[22478] = "orange",
	[22651] = {"blue","yellow"},
})

BigWigs:AddSounds("Zevrim Thornhoof", {
	[17228] = "alert",
	[22478] = "alert",
	[22651] = "alarm",
})

BigWigs:AddColors("Alzzin the Wildshaper", {
	[7948] = "yellow",
	[10101] = "purple",
	[22415] = "orange",
	[22661] = "yellow",
	[22662] = {"blue","orange","red"},
	[22689] = {"blue","orange"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("Alzzin the Wildshaper", {
	[7948] = "warning",
	[10101] = "alert",
	[22415] = "alert",
	[22661] = "alert",
	[22662] = {"alarm","alert"},
	[22689] = "alarm",
	["stages"] = "long",
})

BigWigs:AddColors("Dire Maul Trash", {
})

BigWigs:AddSounds("Dire Maul Trash", {
})

BigWigs:AddColors("Kaigy Maryla", {
	[1220410] = {"blue","purple"},
	[1222942] = {"blue","yellow"},
	[1222943] = "orange",
})

BigWigs:AddSounds("Kaigy Maryla", {
	[1220410] = "alert",
	[1222942] = "info",
	[1222943] = "alarm",
})

BigWigs:AddColors("Sairuh Maryla", {
	[1220853] = "red",
	[1220855] = "yellow",
	[1220862] = "orange",
	[1220882] = "cyan",
})

BigWigs:AddSounds("Sairuh Maryla", {
	[1220853] = "alert",
	[1220855] = "alarm",
	[1220862] = "alarm",
	[1220882] = "long",
})

BigWigs:AddColors("Barian Maryla", {
	[1220515] = "red",
	[1220517] = "green",
	[1220519] = "cyan",
	[1220920] = "orange",
	[1220926] = {"blue","red"},
})

BigWigs:AddSounds("Barian Maryla", {
	[1220515] = "alert",
	[1220517] = "info",
	[1220519] = "info",
	[1220920] = "alarm",
	[1220926] = "alert",
})

BigWigs:AddColors("Creeping Malison", {
	[1220836] = {"blue","purple"},
	[1220843] = "orange",
	[1221325] = "green",
})

BigWigs:AddSounds("Creeping Malison", {
	[1220836] = "alert",
	[1220843] = "alarm",
	[1221325] = "long",
})

BigWigs:AddColors("Trizivast", {
	[1222563] = "red",
	[1222564] = "red",
	[1223459] = "yellow",
	[1223460] = "purple",
	[1223462] = "orange",
})

BigWigs:AddSounds("Trizivast", {
	[1222563] = "alert",
	[1222564] = "info",
	[1223459] = "alert",
	[1223460] = "alert",
	[1223462] = "alarm",
})

BigWigs:AddColors("Hans and Greta", {
	[1222567] = "orange",
	[1222570] = "purple",
	[1222578] = {"blue","red","yellow"},
	[1223456] = "yellow",
})

BigWigs:AddSounds("Hans and Greta", {
	[1222567] = "alarm",
	[1222570] = "alert",
	[1222578] = {"alert","info"},
	[1223456] = "alert",
})

BigWigs:AddColors("Goblins", {
	[744] = {"blue","red"},
	[16170] = "red",
	[27758] = "yellow",
})

BigWigs:AddSounds("Goblins", {
	[744] = "alert",
	[16170] = "info",
	[27758] = "alert",
})

BigWigs:AddColors("Harbinger of Sin", {
	[1219387] = "red",
	[1219420] = "cyan",
	[1220927] = "yellow",
	[1222775] = "orange",
})

BigWigs:AddSounds("Harbinger of Sin", {
	[1219387] = "alert",
	[1219420] = "long",
	[1220927] = "warning",
	[1222775] = "alarm",
})

BigWigs:AddColors("Kharon", {
	[1217694] = "red",
	[1217952] = "cyan",
	[1218038] = {"blue","yellow"},
	[1218089] = {"blue","orange"},
})

BigWigs:AddSounds("Kharon", {
	[1217694] = "warning",
	[1217952] = "info",
	[1218038] = {"alarm","info"},
	[1218089] = "alert",
})

BigWigs:AddColors("Unk'omon", {
	[1220515] = "red",
	[1221577] = {"blue","yellow"},
	[1221578] = "green",
})

BigWigs:AddSounds("Unk'omon", {
	[1220515] = "alert",
	[1221577] = "alarm",
	[1221578] = "info",
})

BigWigs:AddColors("Dark Rider", {
	[1219814] = "yellow",
	[1220939] = {"cyan","orange"},
	[1223264] = "red",
})

BigWigs:AddSounds("Dark Rider", {
	[1219814] = "info",
	[1220939] = "alarm",
	[1223264] = "alarm",
})

BigWigs:AddColors("Hearthsinger Forresten", {
	[16244] = "yellow",
	[16798] = {"blue","orange","red"},
})

BigWigs:AddSounds("Hearthsinger Forresten", {
	[16244] = "alert",
	[16798] = {"alarm","alert"},
})

BigWigs:AddColors("The Unforgiven", {
	[14907] = "yellow",
	[122832] = {"blue","yellow"},
})

BigWigs:AddSounds("The Unforgiven", {
	[14907] = "alert",
	[122832] = "alert",
})

BigWigs:AddColors("Timmy the Cruel", {
	[8599] = "cyan",
	[12021] = {"blue","red"},
	[17470] = "purple",
})

BigWigs:AddSounds("Timmy the Cruel", {
	[8599] = "long",
	[12021] = "alarm",
	[17470] = "alert",
})

BigWigs:AddColors("Commander Malor", {
	[12734] = "orange",
	[15493] = "red",
	[16172] = "purple",
	[17228] = "red",
})

BigWigs:AddSounds("Commander Malor", {
	[12734] = {"alarm","alert"},
	[15493] = "alert",
	[16172] = "alert",
	[17228] = "alert",
})

BigWigs:AddColors("Willey Hopebreaker", {
	[10101] = "purple",
	[17279] = "cyan",
	[110762] = "purple",
})

BigWigs:AddSounds("Willey Hopebreaker", {
	[10101] = "alert",
	[17279] = "info",
	[110762] = "alert",
})

BigWigs:AddColors("Instructor Galford", {
	[17274] = "red",
	[17293] = {"blue","orange","yellow"},
	[17366] = "yellow",
	[33975] = "red",
})

BigWigs:AddSounds("Instructor Galford", {
	[17274] = "alert",
	[17293] = {"alarm","alert"},
	[17366] = "alarm",
	[33975] = "alert",
})

BigWigs:AddColors("Balnazzar", {
	[12098] = {"blue","cyan","red"},
	[13704] = "yellow",
	[17286] = "orange",
	[17287] = "red",
	[17405] = {"blue","cyan","orange"},
	[80750] = "red",
	[452927] = "orange",
	[452928] = {"blue","cyan","red"},
})

BigWigs:AddSounds("Balnazzar", {
	[12098] = {"alert","info"},
	[13704] = "info",
	[17286] = "info",
	[17287] = "alert",
	[17405] = {"info","warning"},
	[80750] = "alert",
	[452927] = "alarm",
	[452928] = {"alert","info"},
})

BigWigs:AddColors("Baroness Anastari", {
	[16867] = {"blue","yellow"},
	[17244] = {"blue","green","yellow"},
	[18327] = "orange",
})

BigWigs:AddSounds("Baroness Anastari", {
	[16867] = "info",
	[17244] = {"info","warning"},
	[18327] = "alarm",
})

BigWigs:AddColors("Nerub'enkan", {
	[4962] = {"blue","yellow"},
	[6016] = "purple",
	[17235] = "cyan",
})

BigWigs:AddSounds("Nerub'enkan", {
	[4962] = "alarm",
	[6016] = "alert",
	[17235] = "info",
})

BigWigs:AddColors("Maleki the Pallid", {
	[16869] = {"blue","red","yellow"},
	[17620] = "orange",
})

BigWigs:AddSounds("Maleki the Pallid", {
	[16869] = {"alert","warning"},
	[17620] = "alert",
})

BigWigs:AddColors("Magistrate Barthilas", {
	[10887] = "red",
	[14099] = "purple",
	[16791] = "yellow",
	[455596] = "orange",
})

BigWigs:AddSounds("Magistrate Barthilas", {
	[10887] = "alert",
	[14099] = "alarm",
	[16791] = "info",
	[455596] = "alarm",
})

BigWigs:AddColors("Ramstein the Gorger", {
	[5568] = "yellow",
	[17307] = {"blue","purple"},
})

BigWigs:AddSounds("Ramstein the Gorger", {
	[5568] = "info",
	[17307] = "alert",
})

BigWigs:AddColors("Postmaster Malown", {
	[6253] = "purple",
	[12741] = {"blue","yellow"},
})

BigWigs:AddSounds("Postmaster Malown", {
	[6253] = "alert",
	[12741] = "alert",
})

BigWigs:AddColors("Lord Aurius Rivendare", {
	[17434] = "red",
	[17471] = "yellow",
	[17473] = "cyan",
})

BigWigs:AddSounds("Lord Aurius Rivendare", {
	[17434] = "alert",
	[17473] = "info",
})

BigWigs:AddColors("Theka the Martyr", {
	[8600] = {"blue","orange","yellow"},
	[15654] = {"blue","yellow"},
	[17228] = "red",
	[450933] = {"blue","yellow"},
})

BigWigs:AddSounds("Theka the Martyr", {
	[8600] = {"alarm","alert"},
	[15654] = "alarm",
	[17228] = "alert",
	[450933] = "warning",
})

BigWigs:AddColors("Antu'sul", {
	[8376] = "cyan",
	[11020] = {"blue","yellow"},
	[11894] = "cyan",
	[11895] = "red",
	[11899] = "red",
	[15501] = "blue",
	[15982] = "red",
	[16006] = "orange",
})

BigWigs:AddSounds("Antu'sul", {
	[8376] = "info",
	[11020] = "alarm",
	[11894] = "info",
	[11895] = "alert",
	[11899] = "alert",
	[15982] = "alert",
	[16006] = "alarm",
})

BigWigs:AddColors("Hydromancer Velratha", {
	[12491] = "red",
	[15245] = "orange",
	[15982] = "red",
	[78802] = "purple",
})

BigWigs:AddSounds("Hydromancer Velratha", {
	[12491] = "alert",
	[15245] = "alarm",
	[15982] = "alert",
	[78802] = "alarm",
})

BigWigs:AddColors("Witch Doctor Zum'rah", {
	[11086] = "cyan",
	[15982] = "red",
	[17228] = "red",
})

BigWigs:AddSounds("Witch Doctor Zum'rah", {
	[11086] = "info",
	[15982] = "alert",
	[17228] = "alert",
})

BigWigs:AddColors("Gahz'rilla", {
	[11836] = {"blue","red","yellow"},
	[11902] = "orange",
})

BigWigs:AddSounds("Gahz'rilla", {
	[11836] = {"alert","warning"},
	[11902] = "alarm",
})

BigWigs:AddColors("Nekrum & Sezz'ziz", {
	[8362] = {"orange","yellow"},
	[8600] = {"blue","orange","yellow"},
	[12039] = "red",
	[13704] = "yellow",
})

BigWigs:AddSounds("Nekrum & Sezz'ziz", {
	[8362] = {"alarm","alert"},
	[8600] = {"alarm","alert"},
	[12039] = "alert",
	[13704] = "info",
})

BigWigs:AddColors("Chief Ukorz Sandscalp", {
	[8269] = "orange",
	[15496] = "blue",
	[454632] = "red",
})

BigWigs:AddSounds("Chief Ukorz Sandscalp", {
	[8269] = "alert",
	[15496] = "alarm",
	[454632] = "alert",
})
