-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Mennu the Betrayer", {
	[31991] = "yellow",
	[34980] = "orange",
})

BigWigs:AddSounds("Mennu the Betrayer", {
})

BigWigs:AddColors("Rokmar the Crackler", {
	[31948] = {"blue","yellow"},
	[34970] = {"green","red"},
	[38801] = {"blue","orange"},
})

BigWigs:AddSounds("Rokmar the Crackler", {
})

BigWigs:AddColors("Quagmirran", {
	[38153] = {"blue","red"},
})

BigWigs:AddSounds("Quagmirran", {
})

BigWigs:AddColors("The Slave Pens Trash", {
	[15655] = {"blue","red"},
	[31554] = {"blue","yellow"},
	[32173] = {"blue","orange"},
	[33787] = {"blue","yellow"},
	[34984] = {"blue","red"},
	[39378] = "orange",
})

BigWigs:AddSounds("The Slave Pens Trash", {
	[15655] = "alarm",
	[31554] = "long",
	[32173] = "info",
	[33787] = "info",
	[34984] = "alert",
	[39378] = "alarm",
})

BigWigs:AddColors("Ahune", {
	[45954] = {"green","red"},
	["warmup"] = "cyan",
})

BigWigs:AddSounds("Ahune", {
	[45954] = {"info","long"},
	["warmup"] = "info",
})
