-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Essence of Order", {
	[134225] = "orange",
	[134234] = "yellow",
})

BigWigs:AddSounds("Essence of Order", {
	[134225] = "long",
	[134234] = "alert",
})

BigWigs:AddColors("Kanrethad Ebonlocke", {
	[1098] = "cyan",
	[138559] = "orange",
	[138560] = {"blue","green"},
	[138561] = "blue",
	[138564] = {"green","red"},
	[138685] = "yellow",
	[138751] = "yellow",
	[138755] = "yellow",
	[138789] = "yellow",
	[139060] = "orange",
})

BigWigs:AddSounds("Kanrethad Ebonlocke", {
	[138559] = "long",
	[138560] = "alarm",
	[138561] = "alert",
	[138564] = "warning",
	[139060] = "warning",
})
