-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Commander Kolurg/Stoutbeard", {
	[38618] = "orange",
})

BigWigs:AddSounds("Commander Kolurg/Stoutbeard", {
	[38618] = "info",
})

BigWigs:AddColors("Grand Magus Telestra", {
	[-7395] = "green",
	[47731] = {"blue","orange"},
})

BigWigs:AddSounds("Grand Magus Telestra", {
	[47731] = "alert",
})

BigWigs:AddColors("Anomalus", {
	[47743] = "yellow",
})

BigWigs:AddSounds("Anomalus", {
})

BigWigs:AddColors("Ormorok the Tree-Shaper", {
	[47981] = "yellow",
	[48017] = "red",
})

BigWigs:AddSounds("Ormorok the Tree-Shaper", {
})

BigWigs:AddColors("Keristrasza", {
	[8599] = "red",
	[48095] = "blue",
	[48179] = "orange",
	[50997] = {"blue","yellow"},
})

BigWigs:AddSounds("Keristrasza", {
	[8599] = "info",
	[48095] = "alarm",
})

BigWigs:AddColors("The Nexus Trash", {
	[30849] = {"blue","yellow"},
	[47779] = {"blue","orange"},
})

BigWigs:AddSounds("The Nexus Trash", {
	[30849] = "alarm",
	[47779] = "alert",
})
