-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Rhahk'Zor", {
	[6304] = "purple",
	[450515] = "orange",
})

BigWigs:AddSounds("Rhahk'Zor", {
	[6304] = "alert",
	[450515] = "alarm",
})

BigWigs:AddColors("Sneed", {
	[5141] = "cyan",
	[6713] = "purple",
	[7399] = "yellow",
})

BigWigs:AddSounds("Sneed", {
	[5141] = "long",
	[6713] = "alert",
	[7399] = "info",
})

BigWigs:AddColors("Gilnid", {
	[5159] = {"blue","orange","red"},
	[5213] = {"blue","orange","red"},
	[450542] = "cyan",
})

BigWigs:AddSounds("Gilnid", {
	[5159] = {"alarm","alert"},
	[5213] = {"alert","info"},
	[450542] = "long",
})

BigWigs:AddColors("Mr. Smite", {
	[-29823] = "cyan",
	[-29813] = "cyan",
	[6432] = "cyan",
	[6435] = "purple",
	[450550] = "red",
})

BigWigs:AddSounds("Mr. Smite", {
	[-29823] = "long",
	[-29813] = "long",
	[6432] = "long",
	[6435] = "alarm",
	[450550] = "alert",
})

BigWigs:AddColors("Captain Greenskin", {
	[5208] = {"blue","orange","purple"},
	[450550] = "red",
})

BigWigs:AddSounds("Captain Greenskin", {
	[5208] = {"alarm","info"},
	[450550] = "alert",
})

BigWigs:AddColors("Edwin VanCleef", {
	[5200] = "cyan",
	[450564] = "yellow",
})

BigWigs:AddSounds("Edwin VanCleef", {
	[5200] = "long",
	[450564] = "info",
})

BigWigs:AddColors("Cookie", {
	[5174] = "red",
	[6306] = {"blue","orange","yellow"},
})

BigWigs:AddSounds("Cookie", {
	[5174] = "warning",
	[6306] = "alert",
})
