-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Wise Mari", {
	[-6327] = {"green","red"},
	[106653] = "blue",
	[115167] = "blue",
	[397785] = "red",
	[397797] = {"blue","yellow"},
	["stages"] = "green",
})

BigWigs:AddSounds("Wise Mari", {
	[-6327] = {"alarm","info"},
	[106653] = "underyou",
	[115167] = "underyou",
	[397785] = "warning",
	[397797] = {"alarm","alert","underyou"},
	["stages"] = "info",
})

BigWigs:AddColors("Lorewalker Stonestep", {
	[-5549] = {"green","orange","red"},
	[396150] = "blue",
	[396152] = {"blue","green"},
	["stages"] = "green",
})

BigWigs:AddSounds("Lorewalker Stonestep", {
	[-5549] = {"alert","info","long","warning"},
	[396150] = {"alarm","alert","info"},
	[396152] = "info",
	["stages"] = "info",
})

BigWigs:AddColors("Liu Flameheart", {
	[106823] = {"blue","purple"},
	[106841] = {"blue","purple"},
	[106856] = "orange",
	[106864] = "orange",
	[107110] = {"blue","orange"},
	[118540] = "blue",
	[396907] = "purple",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Liu Flameheart", {
	[106823] = "alert",
	[106841] = "alert",
	[106856] = "alarm",
	[106864] = "alarm",
	[107110] = {"alarm","underyou"},
	[118540] = "underyou",
	[396907] = "alarm",
	["stages"] = {"info","long"},
})

BigWigs:AddColors("Sha of Doubt", {
	[106113] = {"blue","yellow"},
	[117665] = {"cyan","green","orange"},
})

BigWigs:AddSounds("Sha of Doubt", {
	[106113] = "alarm",
	[117665] = {"info","long"},
})

BigWigs:AddColors("Temple of the Jade Serpent Trash", {
	[110125] = {"blue","red"},
	[114646] = "purple",
	[395859] = "red",
	[395872] = {"blue","yellow"},
	[396001] = "orange",
	[396018] = {"purple","red"},
	[396020] = {"orange","yellow"},
	[396073] = "yellow",
	[397878] = "red",
	[397881] = "orange",
	[397889] = "yellow",
	[397899] = "orange",
	[397911] = {"blue","yellow"},
	[397914] = "red",
	[397931] = "purple",
	[398300] = "orange",
})

BigWigs:AddSounds("Temple of the Jade Serpent Trash", {
	[110125] = "alert",
	[114646] = "alert",
	[395859] = "warning",
	[395872] = {"alert","warning"},
	[396001] = "alarm",
	[396018] = {"alert","info"},
	[396020] = {"alarm","alert"},
	[396073] = "warning",
	[397878] = "long",
	[397881] = "alarm",
	[397889] = "alert",
	[397899] = "alarm",
	[397911] = {"alert","warning"},
	[397914] = "alert",
	[397931] = "alert",
	[398300] = "alarm",
})
