-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Grimroot", {
	[460509] = {"blue","orange"},
	[460703] = {"green","yellow"},
	[460727] = {"green","red"},
	["adds"] = "cyan",
})

BigWigs:AddSounds("Grimroot", {
	[460509] = {"alarm","underyou"},
	[460703] = "alert",
	[460727] = "long",
	["adds"] = "info",
})

BigWigs:AddColors("Destructor's Wraith", {
	[460401] = "red",
	[462226] = "orange",
	[462250] = {"blue","yellow"},
})

BigWigs:AddSounds("Destructor's Wraith", {
	[460401] = "warning",
	[462226] = "alarm",
	[462250] = "alert",
})

BigWigs:AddColors("Zilbagob", {
	[460403] = "orange",
	[460408] = {"blue","red","yellow"},
})

BigWigs:AddSounds("Zilbagob", {
	[460403] = "warning",
	[460408] = {"alarm","alert"},
})

BigWigs:AddColors("Pyranis", {
	[460545] = {"cyan","green"},
	[460577] = "orange",
	[460666] = "yellow",
	[460671] = "yellow",
	[460676] = "red",
})

BigWigs:AddSounds("Pyranis", {
	[460545] = {"info","long"},
	[460577] = "alert",
	[460666] = "alert",
	[460671] = "alarm",
	[460676] = "alert",
})

BigWigs:AddColors("Diathorus the Seeker", {
	[460755] = {"green","red"},
	[460756] = {"blue","yellow"},
	[460766] = {"blue","orange"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("Diathorus the Seeker", {
	[460755] = "alarm",
	[460756] = "alert",
	[460766] = "info",
	["stages"] = "long",
})

BigWigs:AddColors("Hellscream's Phantom", {
	[460084] = {"blue","purple"},
	[460119] = "purple",
	[460254] = "orange",
})

BigWigs:AddSounds("Hellscream's Phantom", {
	[460084] = "alert",
	[460119] = "info",
	[460254] = "alarm",
})
