-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Vizier Jin'bak", {
	[-5960] = "blue",
	[-5959] = "red",
	[-5958] = "yellow",
})

BigWigs:AddSounds("Vizier Jin'bak", {
	[-5960] = "alert",
	[-5959] = "alarm",
	[-5958] = "info",
})

BigWigs:AddColors("Commander Vo'jak", {
	[-6287] = {"blue","red"},
	[120778] = "blue",
	[120789] = {"blue","yellow"},
})

BigWigs:AddSounds("Commander Vo'jak", {
	[-6287] = {"alert","long"},
	[120778] = "warning",
	[120789] = "alarm",
})

BigWigs:AddColors("General Pa'valak", {
	[-5946] = "yellow",
	[119875] = "red",
	[124283] = "orange",
})

BigWigs:AddSounds("General Pa'valak", {
	[-5946] = "info",
	[119875] = "alert",
	[124283] = "alarm",
})

BigWigs:AddColors("Wing Leader Ner'onok", {
	[-6205] = {"blue","green"},
	[121284] = {"green","orange"},
	[121443] = "blue",
	["stages"] = "yellow",
})

BigWigs:AddSounds("Wing Leader Ner'onok", {
	[-6205] = {"alarm","info"},
	[121284] = {"long","warning"},
	[121443] = "alert",
})
