-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Erekem", {
	[54479] = "yellow",
	[54481] = "orange",
	[54516] = "red",
})

BigWigs:AddSounds("Erekem", {
	[54479] = "alert",
	[54481] = "warning",
	[54516] = "long",
})

BigWigs:AddColors("Moragg", {
	[54396] = {"blue","orange"},
})

BigWigs:AddSounds("Moragg", {
	[54396] = "alert",
})

BigWigs:AddColors("Ichoron", {
	[54241] = "orange",
	[54306] = {"green","yellow"},
	[54312] = "red",
})

BigWigs:AddSounds("Ichoron", {
	[54306] = {"info","long"},
	[54312] = {"alarm","alert"},
})

BigWigs:AddColors("Xevozz", {
	[54102] = "red",
	[54160] = "purple",
})

BigWigs:AddSounds("Xevozz", {
	[54102] = "alert",
	[54160] = {"info","warning"},
})

BigWigs:AddColors("Lavanthor", {
	[-7491] = "red",
	[54249] = {"blue","orange"},
	[54282] = "purple",
})

BigWigs:AddSounds("Lavanthor", {
	[-7491] = {"long","warning"},
	[54249] = "alarm",
	[54282] = "alert",
})

BigWigs:AddColors("Zuramat the Obliterator", {
	[54361] = {"blue","yellow"},
	[54524] = {"green","orange","red"},
})

BigWigs:AddSounds("Zuramat the Obliterator", {
	[54361] = "long",
	[54524] = {"alarm","alert","info","warning"},
})

BigWigs:AddColors("Cyanigosa", {
	[58688] = "purple",
	[58693] = "blue",
	[58694] = "yellow",
	[59374] = {"blue","red"},
})

BigWigs:AddSounds("Cyanigosa", {
	[58688] = "alert",
	[58693] = "alarm",
	[58694] = "info",
	[59374] = "alert",
})

BigWigs:AddColors("The Violet Hold Trash", {
	["portals"] = "yellow",
})

BigWigs:AddSounds("The Violet Hold Trash", {
	["portals"] = "info",
})
