-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Trollgore", {
	[49637] = {"blue","orange"},
	[49639] = "red",
	[59803] = "yellow",
})

BigWigs:AddSounds("Trollgore", {
})

BigWigs:AddColors("Novos the Summoner", {
	[47346] = "blue",
	[49034] = "blue",
	[50089] = {"blue","orange"},
	[59910] = "yellow",
	["adds"] = "yellow",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Novos the Summoner", {
	[47346] = "alert",
	[49034] = "alert",
	["adds"] = "info",
})

BigWigs:AddColors("King Dred", {
	[48878] = {"blue","purple"},
	[59416] = "cyan",
})

BigWigs:AddSounds("King Dred", {
	[48878] = "alarm",
	[59416] = "info",
})

BigWigs:AddColors("The Prophet Tharon'ja", {
	[49527] = {"blue","orange"},
	[59971] = "blue",
	["stages"] = "cyan",
})

BigWigs:AddSounds("The Prophet Tharon'ja", {
	[59971] = "underyou",
})
