-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Hymdall", {
	[191284] = "red",
	[193092] = "purple",
	[193235] = {"blue","orange"},
})

BigWigs:AddSounds("Hymdall", {
	[191284] = "long",
	[193092] = "alarm",
	[193235] = {"alert","underyou"},
})

BigWigs:AddColors("Hyrja", {
	[192018] = "purple",
	[192048] = {"blue","yellow"},
	[192307] = "orange",
	[200901] = "orange",
})

BigWigs:AddSounds("Hyrja", {
	[192018] = "alert",
	[192048] = "alarm",
	[192307] = "long",
	[200901] = "long",
})

BigWigs:AddColors("Fenryr", {
	[196512] = "red",
	[196543] = "orange",
	[196838] = {"blue","orange"},
	[197558] = {"blue","yellow"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("Fenryr", {
	[196512] = "alert",
	[196543] = "alert",
	[196838] = "warning",
	[197558] = "alarm",
	["stages"] = "long",
})

BigWigs:AddColors("God-King Skovald", {
	[193659] = {"blue","red"},
	[193668] = "purple",
	[193702] = "blue",
	[193783] = {"cyan","green"},
	[193826] = "orange",
})

BigWigs:AddSounds("God-King Skovald", {
	[193659] = "alarm",
	[193668] = {"alarm","alert"},
	[193702] = "underyou",
	[193783] = "info",
	[193826] = "long",
})

BigWigs:AddColors("Odyn", {
	[197961] = {"orange","yellow"},
	[198077] = "red",
	[198263] = "red",
	[200988] = "orange",
	[201215] = "yellow",
	["warmup"] = "cyan",
})

BigWigs:AddSounds("Odyn", {
	[197961] = {"alarm","warning"},
	[198077] = "alert",
	[198263] = "long",
	[200988] = "alert",
	[201215] = "info",
	["warmup"] = "info",
})

BigWigs:AddColors("Halls of Valor Trash", {
	[191508] = "red",
	[192158] = "orange",
	[192288] = "yellow",
	[192563] = "red",
	[198745] = "yellow",
	[198888] = "purple",
	[198892] = {"blue","red"},
	[198931] = "red",
	[198934] = "yellow",
	[198959] = "yellow",
	[199034] = {"blue","yellow"},
	[199050] = "purple",
	[199090] = "orange",
	[199146] = "yellow",
	[199210] = "orange",
	[199341] = "red",
	[199726] = "red",
	[199805] = "blue",
	[200901] = "orange",
	[200969] = "yellow",
	[210875] = "red",
	[215430] = {"blue","orange"},
	[215433] = "red",
})

BigWigs:AddSounds("Halls of Valor Trash", {
	[191508] = "alarm",
	[192158] = "long",
	[192288] = "alert",
	[192563] = "alarm",
	[198745] = "alert",
	[198888] = "alarm",
	[198892] = {"alert","underyou"},
	[198931] = "alert",
	[198934] = "alarm",
	[198959] = "alert",
	[199034] = "alert",
	[199050] = "alarm",
	[199090] = "alarm",
	[199146] = "alarm",
	[199210] = "alarm",
	[199341] = "alarm",
	[199726] = "alert",
	[199805] = {"alarm","underyou"},
	[200901] = "long",
	[200969] = "info",
	[210875] = "alarm",
	[215430] = "alarm",
	[215433] = "alarm",
})
