-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Chrono Lord Deja", {
})

BigWigs:AddSounds("Chrono Lord Deja", {
})

BigWigs:AddColors("Temporus", {
	[31458] = "red",
	[38592] = "orange",
})

BigWigs:AddSounds("Temporus", {
	[31458] = "warning",
})

BigWigs:AddColors("Aeonus", {
	[37605] = "orange",
})

BigWigs:AddSounds("Aeonus", {
})

BigWigs:AddColors("The Black Morass Trash", {
	["wave"] = "yellow",
})

BigWigs:AddSounds("The Black Morass Trash", {
	["wave"] = "info",
})
