-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Shirrak the Dead Watcher", {
	[-5041] = {"blue","yellow"},
})

BigWigs:AddSounds("Shirrak the Dead Watcher", {
})

BigWigs:AddColors("Exarch Maladaar", {
	[32346] = {"blue","orange"},
	["avatar"] = {"red","yellow"},
})

BigWigs:AddSounds("Exarch Maladaar", {
	["avatar"] = "info",
})
