-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Vexamus", {
	[385958] = "purple",
	[386173] = {"blue","yellow"},
	[386544] = "yellow",
	[388537] = "red",
	[391977] = {"blue","orange"},
})

BigWigs:AddSounds("Vexamus", {
	[385958] = "alarm",
	[386173] = "alarm",
	[386544] = "long",
	[388537] = "alert",
	[391977] = "alert",
})

BigWigs:AddColors("Overgrown Ancient", {
	[388544] = "purple",
	[388623] = "red",
	[388796] = "yellow",
	[388923] = "orange",
	[389033] = {"blue","red"},
	[396640] = "yellow",
	[396721] = "green",
})

BigWigs:AddSounds("Overgrown Ancient", {
	[388544] = "alert",
	[388623] = "alarm",
	[388796] = "long",
	[388923] = "long",
	[389033] = "alert",
	[396640] = "warning",
	[396721] = "info",
})

BigWigs:AddColors("Crawth", {
	[376448] = {"green","red"},
	[376467] = {"green","red"},
	[376997] = "purple",
	[377004] = "yellow",
	[377034] = "orange",
	[377182] = "cyan",
	[389481] = "cyan",
	[389483] = "cyan",
})

BigWigs:AddSounds("Crawth", {
	[376448] = {"info","long"},
	[376467] = {"info","long"},
	[376997] = "alert",
	[377004] = "warning",
	[377034] = "alarm",
	[377182] = "long",
	[389481] = "info",
	[389483] = "info",
})

BigWigs:AddColors("Echo of Doragosa", {
	[374352] = {"blue","yellow"},
	[374361] = "orange",
	[388822] = "red",
	[388901] = "blue",
	[389011] = "blue",
	[439488] = "cyan",
})

BigWigs:AddSounds("Echo of Doragosa", {
	[374352] = "alert",
	[374361] = "alarm",
	[388822] = "alarm",
	[388901] = "underyou",
	[389011] = "info",
	[439488] = "info",
})

BigWigs:AddColors("Algeth'ar Academy Trash", {
	[377383] = "orange",
	[377389] = "red",
	[377912] = "red",
	[377991] = "purple",
	[378003] = "orange",
	[387843] = {"blue","yellow"},
	[387910] = {"blue","orange"},
	[387955] = {"blue","orange"},
	[388392] = "red",
	[388863] = "yellow",
	[388911] = "purple",
	[388976] = "orange",
	[388984] = {"blue","red"},
	[389501] = "green",
	[389512] = "green",
	[389516] = "green",
	[389521] = "green",
	[389536] = "green",
	[390912] = "orange",
	[396812] = "red",
})

BigWigs:AddSounds("Algeth'ar Academy Trash", {
	[377383] = "alarm",
	[377389] = "warning",
	[377912] = "alarm",
	[377991] = "alert",
	[378003] = "alarm",
	[387843] = {"alert","info"},
	[387910] = {"alarm","underyou"},
	[387955] = "alert",
	[388392] = "alert",
	[388863] = "alert",
	[388911] = "alarm",
	[388976] = "alarm",
	[388984] = {"alarm","alert"},
	[389501] = "info",
	[389512] = "info",
	[389516] = "info",
	[389521] = "info",
	[389536] = "info",
	[390912] = "alarm",
	[396812] = "alert",
})
