-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Bogpiper", {
	[427710] = "orange",
	[453897] = "yellow",
	[454213] = "red",
	[470582] = "red",
})

BigWigs:AddSounds("Bogpiper", {
	[427710] = "alarm",
	[453897] = "long",
	[454213] = "alarm",
	[470582] = "alert",
})
