-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Zekvir", {
	[450451] = "orange",
	[450492] = "yellow",
	[450505] = {"blue","red"},
	[450519] = "orange",
	[450568] = "cyan",
	[450597] = "orange",
	[453937] = "cyan",
})

BigWigs:AddSounds("Zekvir", {
	[450451] = "alarm",
	[450492] = "alarm",
	[450505] = {"alert","info"},
	[450519] = "alarm",
	[450568] = "long",
	[450597] = "warning",
	[453937] = "warning",
})

BigWigs:AddColors("Zekvir 2", {
	[450449] = "red",
	[450451] = "orange",
	[450492] = "yellow",
	[450505] = {"blue","red"},
	[450519] = "orange",
	[450568] = "cyan",
	[450597] = "orange",
	[450872] = "yellow",
	[450914] = "red",
	[451003] = "cyan",
	[451782] = "orange",
	[453937] = "cyan",
})

BigWigs:AddSounds("Zekvir 2", {
	[450449] = "warning",
	[450451] = "alarm",
	[450492] = "alarm",
	[450505] = {"alert","info"},
	[450519] = "alarm",
	[450568] = "long",
	[450597] = "warning",
	[450872] = "long",
	[450914] = "warning",
	[451003] = "long",
	[451782] = "alarm",
	[453937] = "warning",
})
