-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Drakos the Interrogator", {
	[50774] = "red",
})

BigWigs:AddSounds("Drakos the Interrogator", {
	[50774] = "alarm",
})

BigWigs:AddColors("Varos Cloudstrider", {
	[-7442] = "cyan",
	[51021] = "blue",
	[51054] = {"blue","red"},
})

BigWigs:AddSounds("Varos Cloudstrider", {
	[-7442] = "info",
	[51021] = "underyou",
})

BigWigs:AddColors("Mage-Lord Urom", {
	[51103] = "blue",
	[51110] = "yellow",
	[51121] = {"blue","orange"},
})

BigWigs:AddSounds("Mage-Lord Urom", {
	[51103] = "underyou",
	[51110] = "alarm",
	[51121] = "alert",
})

BigWigs:AddColors("Ley-Guardian Eregos", {
	[51162] = "red",
	[51170] = "yellow",
})

BigWigs:AddSounds("Ley-Guardian Eregos", {
})
