-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Houndmaster Braun", {
	[114259] = "orange",
	[116140] = {"green","yellow"},
})

BigWigs:AddSounds("Houndmaster Braun", {
	[114259] = "alert",
	[116140] = {"alert","info"},
})

BigWigs:AddColors("Armsmaster Harlan", {
	[-5378] = "cyan",
	[111216] = {"green","orange"},
	[111217] = "purple",
})

BigWigs:AddSounds("Armsmaster Harlan", {
	[-5378] = "info",
	[111216] = {"info","warning"},
})

BigWigs:AddColors("Flameweaver Koegler", {
	[113364] = "red",
	[113641] = {"green","yellow"},
	[113682] = "orange",
})

BigWigs:AddSounds("Flameweaver Koegler", {
	[113364] = "info",
	[113641] = "long",
	[113682] = "alert",
})
