-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Zereketh the Unbound", {
	[36119] = "blue",
	[36123] = {"blue","orange"},
	[39005] = "red",
})

BigWigs:AddSounds("Zereketh the Unbound", {
	[36119] = "alert",
})

BigWigs:AddColors("Dalliah the Doomsayer", {
	[36175] = {"blue","red"},
	[39009] = {"blue","yellow"},
	[39013] = "orange",
})

BigWigs:AddSounds("Dalliah the Doomsayer", {
	[36175] = "alert",
})

BigWigs:AddColors("Wrath-Scryer Soccothrates", {
	[-5293] = {"blue","orange","red"},
	[35759] = {"blue","yellow"},
})

BigWigs:AddSounds("Wrath-Scryer Soccothrates", {
})

BigWigs:AddColors("Harbinger Skyriss", {
	[-5335] = {"cyan","green"},
	[36924] = {"blue","red"},
	[37162] = {"blue","orange"},
	[39415] = {"blue","yellow"},
})

BigWigs:AddSounds("Harbinger Skyriss", {
})

BigWigs:AddColors("The Arcatraz Trash", {
	[36700] = {"blue","orange"},
	[36778] = {"blue","yellow"},
	[36866] = {"blue","red"},
	[36886] = {"blue","orange"},
	[38815] = "yellow",
	[38903] = "red",
})

BigWigs:AddSounds("The Arcatraz Trash", {
	[36700] = "alert",
	[36778] = "alarm",
	[36866] = "warning",
	[36886] = "long",
	[38815] = "alarm",
	[38903] = "warning",
})
