-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Prince Keleseth", {
	[48400] = {"blue","red"},
})

BigWigs:AddSounds("Prince Keleseth", {
	[48400] = "warning",
})

BigWigs:AddColors("Skarvald & Dalronn", {
	[43650] = {"blue","yellow"},
	["stages"] = "green",
})

BigWigs:AddSounds("Skarvald & Dalronn", {
	["stages"] = "info",
})

BigWigs:AddColors("Ingvar the Plunderer", {
	[42669] = "yellow",
	[42708] = "red",
	[42730] = {"blue","orange"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("Ingvar the Plunderer", {
	[42708] = "warning",
	[42730] = "alarm",
})
