-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Shadowcrown", {
	[425264] = "purple",
	[426735] = {"blue","yellow"},
	[428086] = "red",
	[445996] = "orange",
	[451026] = "cyan",
	[453140] = {"blue","orange"},
	[453212] = "purple",
})

BigWigs:AddSounds("Shadowcrown", {
	[425264] = "alarm",
	[426735] = "alert",
	[428086] = "alert",
	[445996] = "long",
	[451026] = "warning",
	[453140] = {"long","underyou"},
	[453212] = "alarm",
})

BigWigs:AddColors("Anub'ikkaj", {
	[426787] = "yellow",
	[426860] = {"blue","orange"},
	[427001] = "purple",
	[452127] = {"blue","cyan"},
})

BigWigs:AddSounds("Anub'ikkaj", {
	[426787] = "alert",
	[426860] = "alarm",
	[427001] = "alarm",
	[452127] = "info",
})

BigWigs:AddColors("Rasha'nan Dawnbreaker", {
	[434089] = "orange",
	[434407] = "red",
	[434655] = {"blue","cyan","green"},
	[435793] = "purple",
	[448213] = "orange",
	[448888] = "yellow",
	[449528] = "green",
	[449734] = {"green","yellow"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("Rasha'nan Dawnbreaker", {
	[434089] = "alert",
	[434407] = "alert",
	[434655] = {"info","long"},
	[435793] = "warning",
	[448213] = "alarm",
	[448888] = "alert",
	[449528] = "info",
	[449734] = {"alert","info"},
	["stages"] = "long",
})

BigWigs:AddColors("The Dawnbreaker Trash", {
	[431304] = "red",
	[431309] = {"blue","orange","red"},
	[431349] = {"blue","red"},
	[431364] = {"blue","yellow"},
	[431491] = "purple",
	[431494] = "purple",
	[431637] = "purple",
	[432448] = {"blue","orange"},
	[432520] = "orange",
	[432565] = "yellow",
	[446615] = "cyan",
	[449042] = "green",
	[450756] = "red",
	[450854] = "orange",
	[451091] = "green",
	[451097] = "red",
	[451098] = "orange",
	[451102] = "yellow",
	[451107] = {"blue","yellow"},
	[451112] = "yellow",
	[451117] = "purple",
	[451119] = {"blue","red"},
})

BigWigs:AddSounds("The Dawnbreaker Trash", {
	[431304] = "alert",
	[431309] = {"alert","info"},
	[431349] = "alarm",
	[431364] = "alert",
	[431491] = "alert",
	[431494] = "alarm",
	[431637] = "alert",
	[432448] = "alarm",
	[432520] = "alert",
	[432565] = "alarm",
	[446615] = "info",
	[449042] = "info",
	[450756] = "warning",
	[450854] = "alarm",
	[451091] = "info",
	[451097] = "alert",
	[451098] = "alarm",
	[451102] = "alert",
	[451107] = "alarm",
	[451112] = "info",
	[451117] = "alarm",
	[451119] = {"alarm","alert"},
})
