-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Maulspike", {
	[1214614] = "purple",
	[1214620] = "cyan",
	[1214656] = "red",
	[1214680] = "orange",
})

BigWigs:AddSounds("Maulspike", {
	[1214614] = "alert",
	[1214620] = "info",
	[1214656] = "alert",
	[1214680] = "alarm",
})

BigWigs:AddColors("Spinshroom", {
	[415406] = "yellow",
	[415492] = "red",
	[415495] = "blue",
	[415499] = "green",
	[425315] = "orange",
})

BigWigs:AddSounds("Spinshroom", {
	[415406] = "long",
	[415492] = "alarm",
	[415495] = "underyou",
	[415499] = "info",
	[425315] = "alarm",
})
