-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Hakkar the Soulflayer", {
	[322736] = "purple",
	[322746] = {"blue","red"},
	[322759] = "orange",
	[323569] = "blue",
})

BigWigs:AddSounds("Hakkar the Soulflayer", {
	[322736] = "alert",
	[322746] = "warning",
	[322759] = "alarm",
	[323569] = "underyou",
})

BigWigs:AddColors("The Manastorms", {
	[320132] = {"blue","red"},
	[320141] = "red",
	[320787] = "yellow",
	[320823] = "orange",
	[321061] = "red",
	[323877] = {"blue","red"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("The Manastorms", {
	[320132] = {"alert","warning"},
	[320141] = "long",
	[320787] = "info",
	[320823] = "info",
	[321061] = "long",
	[323877] = "warning",
	["stages"] = "long",
})

BigWigs:AddColors("Dealer Xy'exa", {
	[320230] = "orange",
	[321948] = {"blue","red"},
	[323687] = "blue",
})

BigWigs:AddSounds("Dealer Xy'exa", {
	[320230] = "long",
	[321948] = "warning",
	[323687] = "alarm",
})

BigWigs:AddColors("Mueh'zala", {
	[325258] = "yellow",
	[325725] = "blue",
	[326171] = "red",
	[327646] = "yellow",
	[334970] = "cyan",
})

BigWigs:AddSounds("Mueh'zala", {
	[325258] = "warning",
	[325725] = "alarm",
	[326171] = "long",
	[327646] = "alert",
	[334970] = "info",
})

BigWigs:AddColors("De Other Side Trash", {
	[328740] = "yellow",
	[331548] = "purple",
	[331846] = {"blue","orange"},
	[331927] = "yellow",
	[332084] = "red",
	[332157] = "blue",
	[332605] = "yellow",
	[332608] = {"blue","orange"},
	[332612] = "red",
	[332672] = {"blue","yellow"},
	[332678] = {"blue","purple"},
	[332706] = "red",
	[333227] = {"green","red"},
	[333250] = "blue",
	[333787] = "red",
	[334051] = "orange",
	[340026] = "orange",
	["soporific_shimmerdust"] = "blue",
})

BigWigs:AddSounds("De Other Side Trash", {
	[328740] = "alarm",
	[331548] = "alert",
	[331846] = {"alarm","alert"},
	[331927] = "warning",
	[332084] = "warning",
	[332157] = "alarm",
	[332605] = "alert",
	[332608] = "alarm",
	[332612] = "warning",
	[332672] = {"alarm","info"},
	[332678] = "alert",
	[332706] = "warning",
	[333227] = {"alert","info","warning"},
	[333250] = "underyou",
	[333787] = "warning",
	[334051] = "alert",
	[340026] = "alert",
	["soporific_shimmerdust"] = {"alarm","warning"},
})

BigWigs:AddColors("Halkias, the Sin-Stained Goliath", {
	[322711] = "red",
	[322936] = "purple",
	[322943] = "yellow",
	[323001] = "blue",
	[339237] = {"blue","orange"},
})

BigWigs:AddSounds("Halkias, the Sin-Stained Goliath", {
	[322711] = "warning",
	[322936] = "alert",
	[322943] = "alarm",
	[323001] = "underyou",
	[339237] = "alert",
})

BigWigs:AddColors("Echelon", {
	[319733] = "cyan",
	[319941] = {"blue","orange"},
	[326389] = {"blue","orange"},
	[328206] = "yellow",
})

BigWigs:AddSounds("Echelon", {
	[319733] = "long",
	[319941] = {"alarm","warning"},
	[326389] = {"alert","underyou"},
	[328206] = "info",
})

BigWigs:AddColors("High Adjudicator Aleez", {
	[323538] = "red",
	[323597] = "cyan",
	[323650] = {"blue","green","yellow"},
	[329340] = "orange",
	[1236512] = {"blue","orange"},
})

BigWigs:AddSounds("High Adjudicator Aleez", {
	[323538] = "alert",
	[323597] = "long",
	[323650] = {"info","warning"},
	[329340] = "alarm",
	[1236512] = "alarm",
})

BigWigs:AddColors("Lord Chamberlain", {
	[323142] = "yellow",
	[323236] = "orange",
	[328791] = "red",
	[329104] = "cyan",
	[1236973] = "red",
})

BigWigs:AddSounds("Lord Chamberlain", {
	[323142] = "alert",
	[323236] = "alarm",
	[328791] = "warning",
	[329104] = "long",
	[1236973] = "alarm",
})

BigWigs:AddColors("Halls of Atonement Trash", {
	[325701] = {"blue","orange"},
	[325876] = {"blue","orange"},
	[326409] = "yellow",
	[326441] = "orange",
	[326450] = {"purple","red"},
	[326638] = {"blue","red"},
	[326794] = "cyan",
	[326847] = "orange",
	[326891] = "blue",
	[326997] = "orange",
	[1235060] = {"blue","purple"},
	[1235326] = "yellow",
	[1235762] = {"blue","orange","yellow"},
	[1235766] = "purple",
	[1236614] = "yellow",
	[1237071] = "purple",
	[1237602] = "blue",
})

BigWigs:AddSounds("Halls of Atonement Trash", {
	[325701] = "alert",
	[325876] = {"alarm","info"},
	[326409] = "warning",
	[326441] = "alarm",
	[326450] = {"alert","warning"},
	[326638] = "alert",
	[326794] = "long",
	[326847] = "alarm",
	[326891] = "underyou",
	[326997] = "alarm",
	[1235060] = {"info","warning"},
	[1235326] = "warning",
	[1235762] = {"alarm","info"},
	[1235766] = "alert",
	[1236614] = "info",
	[1237071] = "alert",
	[1237602] = {"info","warning"},
})

BigWigs:AddColors("Ingra Maloch", {
	[323057] = "orange",
	[323059] = {"cyan","green"},
	[323137] = "yellow",
	[323149] = "orange",
	[323177] = "red",
	[323250] = "blue",
	[328756] = "red",
})

BigWigs:AddSounds("Ingra Maloch", {
	[323057] = "alert",
	[323059] = {"info","long"},
	[323137] = "alarm",
	[323149] = "info",
	[323177] = "alarm",
	[323250] = "underyou",
	[328756] = "warning",
})

BigWigs:AddColors("Mistcaller", {
	[321828] = "blue",
	[321834] = "orange",
	[321891] = {"blue","red"},
	[336499] = "cyan",
	[341709] = "yellow",
})

BigWigs:AddSounds("Mistcaller", {
	[321828] = "warning",
	[321834] = "alarm",
	[321891] = {"alert","warning"},
	[336499] = "long",
	[341709] = "alert",
})

BigWigs:AddColors("Tred'ova", {
	[322450] = "cyan",
	[322527] = "green",
	[322550] = "yellow",
	[322563] = {"blue","yellow"},
	[322614] = {"blue","green","purple"},
	[322654] = "yellow",
	[326309] = "blue",
	[463602] = "orange",
})

BigWigs:AddSounds("Tred'ova", {
	[322450] = "long",
	[322527] = "info",
	[322550] = "info",
	[322563] = "warning",
	[322614] = {"alert","info"},
	[322654] = "alert",
	[326309] = "underyou",
	[463602] = "alarm",
})

BigWigs:AddColors("Mists of Tirna Scithe Trash", {
	[321968] = "red",
	[322486] = {"blue","yellow"},
	[322557] = {"blue","purple","yellow"},
	[322569] = "red",
	[322938] = "red",
	[322968] = "yellow",
	[324776] = "orange",
	[324909] = "yellow",
	[324914] = {"orange","red"},
	[324923] = "orange",
	[325021] = {"blue","yellow"},
	[325224] = {"blue","yellow"},
	[325418] = {"blue","orange"},
	[326017] = "blue",
	[326021] = "yellow",
	[326046] = {"orange","red"},
	[326090] = {"blue","orange"},
	[340160] = "orange",
	[340189] = "cyan",
	[340208] = "purple",
	[340279] = {"blue","orange","yellow"},
	[340289] = "purple",
	[340300] = "purple",
	[340304] = "red",
	[340305] = "orange",
	[340544] = "red",
	[460092] = "yellow",
	[463217] = "purple",
	[463248] = {"blue","red"},
	[463256] = {"blue","orange"},
})

BigWigs:AddSounds("Mists of Tirna Scithe Trash", {
	[321968] = "alarm",
	[322486] = "alert",
	[322557] = {"alert","info"},
	[322569] = "alert",
	[322938] = "alert",
	[322968] = "alarm",
	[324776] = "alert",
	[324909] = "long",
	[324914] = {"alert","warning"},
	[324923] = "alarm",
	[325021] = "alert",
	[325224] = "alarm",
	[325418] = "alert",
	[326017] = "underyou",
	[326021] = "alarm",
	[326046] = {"alert","warning"},
	[326090] = "alert",
	[340160] = "alarm",
	[340189] = "info",
	[340208] = "alert",
	[340279] = {"alarm","info"},
	[340289] = "alert",
	[340300] = "alert",
	[340304] = "alarm",
	[340305] = "alarm",
	[340544] = "alert",
	[460092] = "alert",
	[463217] = "alert",
	[463248] = "alert",
	[463256] = {"alarm","underyou"},
})

BigWigs:AddColors("Globgrog", {
	[324490] = "yellow",
	[324527] = "red",
	[324667] = "orange",
})

BigWigs:AddSounds("Globgrog", {
	[324490] = "long",
	[324527] = "warning",
	[324667] = "alarm",
})

BigWigs:AddColors("Doctor Ickus", {
	[67382] = "yellow",
	[321406] = "orange",
	[322358] = "red",
	[329110] = {"blue","purple","yellow"},
	[329217] = "yellow",
	[332617] = "cyan",
})

BigWigs:AddSounds("Doctor Ickus", {
	[67382] = "long",
	[321406] = "warning",
	[322358] = "alarm",
	[329110] = {"alert","info"},
	[329217] = "alarm",
	[332617] = "info",
})

BigWigs:AddColors("Domina Venomblade", {
	[325245] = {"blue","yellow"},
	[325552] = {"blue","purple"},
	[332313] = "cyan",
	[336258] = "blue",
	[336301] = {"blue","green","red"},
})

BigWigs:AddSounds("Domina Venomblade", {
	[325245] = "warning",
	[325552] = "alert",
	[332313] = "long",
	[336258] = "alarm",
	[336301] = {"alarm","info"},
})

BigWigs:AddColors("Margrave Stradama", {
	[322232] = "yellow",
	[322304] = "cyan",
	[322475] = "green",
	["stages"] = "green",
})

BigWigs:AddSounds("Margrave Stradama", {
	[322232] = "alert",
	[322304] = "info",
	[322475] = "long",
})

BigWigs:AddColors("Plaguefall Trash", {
	[318949] = "red",
	[319898] = "red",
	[320512] = {"blue","yellow"},
	[320517] = "yellow",
	[321935] = "red",
	[323572] = "red",
	[327233] = "red",
	[327515] = {"blue","yellow"},
	[327584] = "yellow",
	[327882] = {"blue","yellow"},
	[327995] = "red",
	[328016] = "orange",
	[328177] = "orange",
	[328180] = {"blue","orange","yellow"},
	[328338] = "red",
	[328429] = {"blue","yellow"},
	[328475] = "red",
	[329239] = "orange",
	[330069] = {"blue","yellow"},
	[330092] = {"blue","green","orange"},
	[330403] = "red",
	[330786] = "orange",
	[330816] = "yellow",
	[335882] = {"blue","green","yellow"},
	[336451] = "orange",
	["summon_stealthlings"] = "red",
})

BigWigs:AddSounds("Plaguefall Trash", {
	[318949] = "alarm",
	[319898] = "alarm",
	[320512] = "alert",
	[320517] = "alert",
	[321935] = "alarm",
	[323572] = "alarm",
	[327233] = "alarm",
	[327515] = "alert",
	[327584] = "long",
	[327882] = "alert",
	[327995] = "alarm",
	[328016] = "alert",
	[328177] = "alert",
	[328180] = {"alert","info"},
	[328338] = "alert",
	[328429] = "alert",
	[328475] = "alarm",
	[329239] = "alert",
	[330069] = {"alert","warning"},
	[330092] = {"info","long"},
	[330403] = "alarm",
	[330786] = "alert",
	[330816] = "info",
	[335882] = {"alert","info","underyou","warning"},
	[336451] = "alert",
	["summon_stealthlings"] = "warning",
})

BigWigs:AddColors("Kryxis the Voracious", {
	[319650] = "purple",
	[319654] = "orange",
	[319685] = "yellow",
	[319713] = {"blue","red"},
})

BigWigs:AddSounds("Kryxis the Voracious", {
	[319650] = "alarm",
	[319654] = "alert",
	[319685] = "alert",
	[319713] = "alarm",
})

BigWigs:AddColors("Executor Tarvold", {
	[322554] = {"blue","orange"},
	[322574] = "yellow",
	[323551] = {"blue","orange"},
	[328494] = {"blue","yellow"},
})

BigWigs:AddSounds("Executor Tarvold", {
	[322554] = "alert",
	[322574] = "info",
	[323551] = {"alert","underyou"},
	[328494] = "info",
})

BigWigs:AddColors("Grand Proctor Beryllia", {
	[325254] = "orange",
	[325360] = "red",
	[326039] = "yellow",
	[328737] = "blue",
})

BigWigs:AddSounds("Grand Proctor Beryllia", {
	[325254] = "alert",
	[325360] = "long",
	[326039] = "alert",
	[328737] = "info",
})

BigWigs:AddColors("General Kaal", {
	[322903] = "red",
	[323821] = "orange",
	[323845] = {"blue","orange"},
})

BigWigs:AddSounds("General Kaal", {
	[322903] = "warning",
	[323821] = "alert",
	[323845] = "alert",
})

BigWigs:AddColors("Sanguine Depths Trash", {
	[320991] = "red",
	[321105] = "yellow",
	[321178] = "red",
	[322429] = "orange",
	[322433] = {"orange","yellow"},
	[324086] = "green",
	[324089] = "green",
	[326827] = {"green","red"},
	[326836] = {"blue","orange","red"},
	[328170] = "red",
	[334326] = "red",
	[334329] = "orange",
	[334377] = "red",
	[334558] = "orange",
	[334918] = "yellow",
	[335305] = {"blue","orange","yellow"},
	[335308] = "purple",
	[341331] = "green",
})

BigWigs:AddSounds("Sanguine Depths Trash", {
	[320991] = "alarm",
	[321105] = "alert",
	[321178] = "alarm",
	[322429] = "alert",
	[322433] = {"alert","warning"},
	[324086] = "info",
	[324089] = "info",
	[326827] = {"info","warning"},
	[326836] = {"alert","warning"},
	[328170] = "alarm",
	[334326] = "alarm",
	[334329] = "alert",
	[334377] = "alarm",
	[334558] = "alert",
	[334918] = "alert",
	[335305] = "alert",
	[335308] = "alarm",
	[341331] = "info",
})

BigWigs:AddColors("Kin-Tara", {
	[320966] = "purple",
	[321009] = {"blue","yellow"},
	[324368] = "cyan",
	[327481] = {"blue","orange"},
	[331251] = {"blue","red"},
})

BigWigs:AddSounds("Kin-Tara", {
	[320966] = "alarm",
	[321009] = {"alert","underyou"},
	[324368] = "long",
	[327481] = "alert",
	[331251] = {"alert","warning"},
})

BigWigs:AddColors("Ventunax", {
	[324146] = "yellow",
	[324205] = "red",
	[334485] = "cyan",
})

BigWigs:AddSounds("Ventunax", {
	[324146] = "alert",
	[324205] = "warning",
	[334485] = "long",
})

BigWigs:AddColors("Oryphrion", {
	[324046] = "yellow",
	[324427] = "red",
	[324608] = "yellow",
	[334053] = {"blue","red"},
	["stages"] = {"cyan","green","orange"},
})

BigWigs:AddSounds("Oryphrion", {
	[324046] = "alert",
	[324427] = "warning",
	[324608] = "alert",
	[334053] = "warning",
	["stages"] = {"info","long"},
})

BigWigs:AddColors("Devos, Paragon of Doubt", {
	[322818] = {"blue","green","yellow"},
	[323943] = {"blue","orange"},
	[334625] = "yellow",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Devos, Paragon of Doubt", {
	[322818] = {"alarm","info"},
	[323943] = "alert",
	[334625] = "warning",
	["stages"] = "long",
})

BigWigs:AddColors("Spires of Ascension Trash", {
	[317661] = {"blue","yellow"},
	[317936] = "orange",
	[317963] = {"blue","orange","yellow"},
	[317985] = "red",
	[327332] = {"blue","yellow"},
	[327413] = "red",
	[327648] = "orange",
	[327655] = {"blue","yellow"},
	[328288] = {"blue","yellow"},
	[328295] = "orange",
	[328458] = "red",
	[328462] = "orange",
})

BigWigs:AddSounds("Spires of Ascension Trash", {
	[317661] = "alert",
	[317936] = "alert",
	[317963] = "alert",
	[317985] = "alarm",
	[327332] = "info",
	[327413] = "alert",
	[327648] = "alert",
	[327655] = "info",
	[328288] = "info",
	[328295] = "alert",
	[328458] = "alarm",
	[328462] = "alert",
})

BigWigs:AddColors("Zo'phex the Sentinel", {
	[345770] = {"blue","green"},
	[345990] = {"blue","green","red"},
	[346204] = {"blue","yellow"},
	[348128] = "purple",
	[348350] = {"blue","orange"},
	[1236348] = "orange",
})

BigWigs:AddSounds("Zo'phex the Sentinel", {
	[345770] = {"alarm","info"},
	[345990] = {"alert","info","warning"},
	[346204] = {"alert","underyou"},
	[348128] = "alert",
	[348350] = {"alert","warning"},
	[1236348] = "alarm",
})

BigWigs:AddColors("The Grand Menagerie", {
	[349627] = {"blue","yellow"},
	[349663] = "red",
	[349797] = "orange",
	[349934] = "purple",
	[349954] = {"blue","yellow"},
	[349987] = "yellow",
	[350010] = "green",
	[350037] = "cyan",
	[350045] = "blue",
	[350086] = {"blue","orange"},
	[350101] = {"blue","red"},
	["warmup"] = "cyan",
})

BigWigs:AddSounds("The Grand Menagerie", {
	[349627] = "info",
	[349663] = "alarm",
	[349797] = "alarm",
	[349934] = "alert",
	[349954] = "alert",
	[349987] = "long",
	[350010] = "info",
	[350037] = "info",
	[350045] = "underyou",
	[350086] = {"alarm","underyou"},
	[350101] = {"alert","info"},
	["warmup"] = "long",
})

BigWigs:AddColors("Mailroom Mayhem", {
	[346286] = "yellow",
	[346296] = "green",
	[346329] = "blue",
	[346742] = "red",
	[346947] = "yellow",
	[346962] = {"blue","orange"},
	["delivery_portal"] = "cyan",
})

BigWigs:AddSounds("Mailroom Mayhem", {
	[346286] = "alert",
	[346296] = "info",
	[346329] = "underyou",
	[346742] = "alert",
	[346947] = "long",
	[346962] = "alarm",
	["delivery_portal"] = "info",
})

BigWigs:AddColors("Myza's Oasis", {
	[350916] = "purple",
	[350919] = "orange",
	[350922] = "red",
	[353706] = "yellow",
	[353783] = "yellow",
	[355438] = "red",
	[356482] = "orange",
	[357404] = "red",
	[357436] = "yellow",
	[357542] = "orange",
	[359019] = "green",
	[359028] = "purple",
	[1241032] = {"green","yellow"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("Myza's Oasis", {
	[350916] = "alert",
	[350919] = "alarm",
	[350922] = "warning",
	[353706] = "long",
	[353783] = "info",
	[355438] = "info",
	[356482] = "alarm",
	[357404] = "alert",
	[357436] = "info",
	[357542] = "alarm",
	[359019] = "info",
	[359028] = "alert",
	[1241032] = {"info","long"},
	["stages"] = "long",
})

BigWigs:AddColors("So'azmi", {
	[1245579] = "yellow",
	[1245634] = "cyan",
	[1245669] = "red",
	[1245752] = "red",
	[1248209] = "purple",
})

BigWigs:AddSounds("So'azmi", {
	[1245579] = "warning",
	[1245634] = "info",
	[1245669] = "alert",
	[1245752] = "alert",
	[1248209] = "alert",
})

BigWigs:AddColors("Hylbrande", {
	[346116] = "purple",
	[346766] = {"cyan","green"},
	[346957] = {"blue","orange"},
	[347094] = "red",
	[353312] = "yellow",
	[358131] = "red",
	["vault_purifier"] = "yellow",
})

BigWigs:AddSounds("Hylbrande", {
	[346116] = "alert",
	[346766] = "long",
	[346957] = {"underyou","warning"},
	[347094] = "alarm",
	[353312] = "info",
	[358131] = "alert",
	["vault_purifier"] = "info",
})

BigWigs:AddColors("Timecap'n Hooktail", {
	[347149] = "purple",
	[352345] = {"blue","red"},
	[358947] = "blue",
	[1240102] = {"blue","orange"},
})

BigWigs:AddSounds("Timecap'n Hooktail", {
	[347149] = {"alarm","info"},
	[352345] = "warning",
	[358947] = "underyou",
	[1240102] = "info",
})

BigWigs:AddColors("So'leah", {
	[350796] = "orange",
	[350804] = {"blue","green"},
	[350875] = "red",
	[351086] = {"cyan","green"},
	[351096] = "yellow",
	[351119] = "red",
	[351124] = "yellow",
	[351646] = "orange",
	[353635] = "red",
	[357190] = {"blue","orange"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("So'leah", {
	[350796] = "alert",
	[350804] = {"alert","info"},
	[350875] = "info",
	[351086] = "long",
	[351096] = "alert",
	[351119] = "warning",
	[351124] = "alert",
	[351646] = "alarm",
	[353635] = "alarm",
	["stages"] = "long",
})

BigWigs:AddColors("Tazavesh Trash", {
	[347716] = "purple",
	[347721] = "yellow",
	[347775] = "red",
	[352796] = "purple",
	[355048] = "purple",
	[355057] = {"red","yellow"},
	[355132] = "cyan",
	[355234] = "orange",
	[355429] = "yellow",
	[355464] = "orange",
	[355473] = "orange",
	[355477] = "purple",
	[355479] = {"blue","red"},
	[355577] = {"blue","red"},
	[355584] = "orange",
	[355637] = {"blue","orange"},
	[355640] = "yellow",
	[355642] = "red",
	[355830] = "yellow",
	[355888] = "purple",
	[355891] = "cyan",
	[355900] = "orange",
	[355915] = {"blue","yellow"},
	[355934] = "red",
	[355980] = "yellow",
	[356001] = {"blue","yellow"},
	[356133] = {"purple","red"},
	[356404] = "red",
	[356407] = {"orange","yellow"},
	[356537] = "red",
	[356548] = "yellow",
	[356929] = "cyan",
	[356942] = {"blue","purple","yellow"},
	[356967] = "purple",
	[357029] = {"blue","yellow"},
	[357197] = "orange",
	[357226] = "orange",
	[357229] = "red",
	[357238] = "cyan",
	[357260] = "yellow",
	[357508] = "yellow",
	[357512] = {"blue","red"},
	[368661] = {"blue","yellow"},
	[1240821] = "yellow",
	[1240912] = "purple",
	[1244443] = "yellow",
	[1244650] = "orange",
	["trading_game"] = "green",
})

BigWigs:AddSounds("Tazavesh Trash", {
	[347716] = "alert",
	[347721] = "warning",
	[347775] = "alert",
	[352796] = "alert",
	[355048] = "alert",
	[355057] = {"alert","warning"},
	[355132] = "info",
	[355234] = "alarm",
	[355429] = "alert",
	[355464] = "alarm",
	[355473] = "alarm",
	[355477] = "alert",
	[355479] = {"alert","warning"},
	[355577] = {"alert","underyou"},
	[355584] = "alarm",
	[355637] = "alert",
	[355640] = "info",
	[355642] = "alert",
	[355830] = "info",
	[355888] = "alert",
	[355891] = "info",
	[355900] = "alarm",
	[355915] = "alert",
	[355934] = {"alert","info"},
	[355980] = "warning",
	[356001] = {"alarm","underyou"},
	[356133] = {"alert","warning"},
	[356404] = "alarm",
	[356407] = "warning",
	[356537] = "warning",
	[356548] = "info",
	[356929] = "info",
	[356942] = "alert",
	[356967] = "alert",
	[357029] = "alarm",
	[357197] = "alarm",
	[357226] = "alarm",
	[357229] = "alarm",
	[357238] = "info",
	[357260] = "warning",
	[357508] = "info",
	[357512] = {"alert","warning"},
	[368661] = "alert",
	[1240821] = "alarm",
	[1240912] = "alert",
	[1244443] = "info",
	[1244650] = "alarm",
	["trading_game"] = "info",
})

BigWigs:AddColors("An Affront of Challengers", {
	[320069] = "purple",
	[320182] = "yellow",
	[333231] = {"blue","yellow"},
	[1215600] = {"blue","red"},
	[1215738] = "orange",
	[1215741] = "red",
})

BigWigs:AddSounds("An Affront of Challengers", {
	[320069] = "alert",
	[320182] = "long",
	[333231] = "info",
	[1215600] = {"alert","info"},
	[1215738] = "alarm",
	[1215741] = "info",
})

BigWigs:AddColors("Gorechop", {
	[318406] = "orange",
	[321447] = "blue",
	[322795] = "yellow",
	[323515] = "purple",
	[323750] = "blue",
})

BigWigs:AddSounds("Gorechop", {
	[318406] = "alarm",
	[321447] = "underyou",
	[322795] = "long",
	[323515] = "alert",
	[323750] = "underyou",
})

BigWigs:AddColors("Xav the Unfallen", {
	[317231] = "red",
	[320114] = {"blue","cyan"},
	[320644] = "purple",
	[320729] = "orange",
	[331618] = {"green","red"},
	[339415] = "yellow",
})

BigWigs:AddSounds("Xav the Unfallen", {
	[317231] = "alarm",
	[320114] = {"info","long"},
	[320644] = "alert",
	[320729] = "alarm",
	[331618] = {"alert","info"},
	[339415] = "warning",
})

BigWigs:AddColors("Kul'tharok", {
	[473513] = "yellow",
	[474087] = "purple",
	[474298] = "cyan",
	[1215787] = {"blue","orange"},
	[1223803] = {"blue","red"},
})

BigWigs:AddSounds("Kul'tharok", {
	[473513] = "long",
	[474087] = "alarm",
	[474298] = "warning",
	[1215787] = {"info","underyou"},
	[1223803] = "alert",
})

BigWigs:AddColors("Mordretha, the Endless Empress", {
	[323608] = "orange",
	[323825] = "yellow",
	[323831] = {"blue","yellow"},
	[324079] = "purple",
	[324449] = "red",
	[339550] = "orange",
	[339573] = "cyan",
	[339706] = "red",
})

BigWigs:AddSounds("Mordretha, the Endless Empress", {
	[323608] = "alarm",
	[323825] = "alert",
	[323831] = {"info","warning"},
	[324079] = "alert",
	[324449] = "info",
	[339550] = "alarm",
	[339573] = "long",
	[339706] = "alarm",
})

BigWigs:AddColors("Theater Of Pain Trash", {
	[317605] = "orange",
	[321039] = "orange",
	[330532] = {"blue","yellow"},
	[330562] = "red",
	[330565] = "purple",
	[330586] = "purple",
	[330614] = {"blue","orange","yellow"},
	[330697] = {"blue","purple"},
	[330716] = "orange",
	[330725] = {"blue","yellow"},
	[330868] = "red",
	[331223] = {"blue","orange"},
	[331237] = "yellow",
	[331288] = "purple",
	[331316] = "purple",
	[333241] = "orange",
	[333294] = "orange",
	[333299] = {"blue","yellow"},
	[333827] = "yellow",
	[333845] = "purple",
	[333861] = {"blue","red"},
	[334023] = "orange",
	[336995] = {"blue","red"},
	[341902] = {"red","yellow"},
	[341949] = {"blue","yellow"},
	[341969] = "orange",
	[341977] = "red",
	[342103] = "blue",
	[342135] = "yellow",
	[342675] = "red",
	[1215850] = "red",
})

BigWigs:AddSounds("Theater Of Pain Trash", {
	[317605] = "alarm",
	[321039] = "alarm",
	[330532] = "alert",
	[330562] = "warning",
	[330565] = "alert",
	[330586] = "alert",
	[330614] = {"alarm","info"},
	[330697] = "alert",
	[330716] = "long",
	[330725] = "alert",
	[330868] = {"alert","warning"},
	[331223] = {"alarm","underyou"},
	[331237] = "long",
	[331288] = "alert",
	[331316] = "alert",
	[333241] = {"alarm","warning"},
	[333294] = "alarm",
	[333299] = "info",
	[333827] = "alert",
	[333845] = "alert",
	[333861] = {"alert","warning"},
	[334023] = "alarm",
	[336995] = {"alarm","underyou"},
	[341902] = {"alert","warning"},
	[341949] = "alert",
	[341969] = "warning",
	[341977] = "alert",
	[342103] = "underyou",
	[342135] = "warning",
	[342675] = "alert",
	[1215850] = "alarm",
})

BigWigs:AddColors("Blightbone", {
	[320596] = {"blue","red"},
	[320630] = {"blue","cyan"},
	[320631] = "red",
	[320637] = "yellow",
	[320655] = "purple",
})

BigWigs:AddSounds("Blightbone", {
	[320596] = {"alarm","warning"},
	[320630] = "warning",
	[320631] = "warning",
	[320637] = "long",
	[320655] = "alert",
})

BigWigs:AddColors("Amarth, The Harvester", {
	[320012] = "purple",
	[320171] = "yellow",
	[321226] = "cyan",
	[321247] = "red",
	[328667] = "red",
	[333488] = "orange",
})

BigWigs:AddSounds("Amarth, The Harvester", {
	[320012] = "info",
	[320171] = "alert",
	[321226] = "long",
	[321247] = "warning",
	[328667] = "alert",
	[333488] = "alarm",
})

BigWigs:AddColors("Surgeon Stitchflesh", {
	[320200] = {"blue","orange"},
	[320358] = "cyan",
	[320359] = "cyan",
	[320376] = "purple",
	[322681] = {"blue","green","red"},
	[327100] = "blue",
	[334476] = {"blue","yellow"},
	[334488] = "purple",
	[343556] = {"blue","red"},
})

BigWigs:AddSounds("Surgeon Stitchflesh", {
	[320200] = "alert",
	[320358] = "info",
	[320359] = "long",
	[320376] = "alert",
	[322681] = {"info","warning"},
	[327100] = "underyou",
	[334476] = {"alarm","underyou"},
	[334488] = "alert",
	[343556] = "warning",
})

BigWigs:AddColors("Nalthor the Rimebinder", {
	[320772] = "red",
	[320788] = {"blue","orange","red"},
	[321368] = {"cyan","green"},
	[321894] = {"blue","yellow"},
	[328181] = {"blue","yellow"},
})

BigWigs:AddSounds("Nalthor the Rimebinder", {
	[320772] = "warning",
	[320788] = {"alarm","alert"},
	[321368] = {"alert","info"},
	[321894] = "long",
	[328181] = "alert",
})

BigWigs:AddColors("The Necrotic Wake Trash", {
	[320464] = "purple",
	[320696] = "purple",
	[320822] = "yellow",
	[321780] = "yellow",
	[321807] = "purple",
	[322756] = "red",
	[323347] = {"blue","yellow"},
	[323471] = {"blue","yellow"},
	[324293] = "orange",
	[324323] = "purple",
	[324372] = "orange",
	[324387] = "yellow",
	[324394] = "purple",
	[327130] = "red",
	[327240] = "orange",
	[327396] = {"blue","orange"},
	[328667] = "red",
	[333477] = "red",
	[333479] = {"blue","yellow"},
	[334748] = "red",
	[335141] = {"green","red"},
	[335143] = "red",
	[338353] = "orange",
	[338357] = "purple",
	[338456] = "purple",
	[338606] = {"blue","yellow"},
	[343470] = "yellow",
	[345623] = "orange",
})

BigWigs:AddSounds("The Necrotic Wake Trash", {
	[320464] = "alert",
	[320696] = "alert",
	[320822] = "info",
	[321780] = "alert",
	[321807] = "alert",
	[322756] = "alarm",
	[323347] = "info",
	[323471] = "info",
	[324293] = "alarm",
	[324323] = "alert",
	[324372] = "alarm",
	[324387] = "alert",
	[324394] = "alert",
	[327130] = "alert",
	[327240] = "alarm",
	[327396] = "alarm",
	[328667] = "alert",
	[333477] = "alarm",
	[333479] = "alert",
	[334748] = "alert",
	[335141] = {"alert","info","warning"},
	[335143] = "alert",
	[338353] = "alert",
	[338357] = "info",
	[338456] = "alert",
	[338606] = {"info","warning"},
	[343470] = "alert",
	[345623] = "alarm",
})
