-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Forgemaster Garfrost", {
	[68789] = "red",
	[70381] = {"blue","yellow"},
})

BigWigs:AddSounds("Forgemaster Garfrost", {
	[68789] = "alarm",
	[70381] = "alert",
})

BigWigs:AddColors("Ick & Krick", {
	[68987] = {"blue","yellow"},
	[68989] = "orange",
	[69263] = "red",
	[70274] = "blue",
})

BigWigs:AddSounds("Ick & Krick", {
	[68987] = "alert",
	[70274] = "underyou",
})

BigWigs:AddColors("Scourgelord Tyrannus", {
	[69167] = "red",
	[69172] = {"blue","yellow"},
	[69275] = {"blue","red"},
})

BigWigs:AddSounds("Scourgelord Tyrannus", {
	[69172] = "alert",
	[69275] = "alarm",
})
