-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Grand Vizier Ertan", {
	[86292] = {"blue","green","orange","yellow"},
	[86340] = "yellow",
	[413151] = "yellow",
	[413562] = "red",
})

BigWigs:AddSounds("Grand Vizier Ertan", {
	[86292] = {"alert","info","long","underyou"},
	[86340] = "info",
	[413151] = "info",
	[413562] = "alarm",
})

BigWigs:AddColors("Altairus", {
	[-2425] = "cyan",
	[88282] = "green",
	[88286] = "red",
	[88308] = "orange",
	[413275] = "blue",
	[413295] = "yellow",
})

BigWigs:AddSounds("Altairus", {
	[-2425] = "alert",
	[88282] = "info",
	[88286] = "alarm",
	[88308] = "alarm",
	[413275] = "underyou",
	[413295] = "warning",
})

BigWigs:AddColors("Asaad", {
	[86911] = "green",
	[86930] = "red",
	[87618] = {"blue","red","yellow"},
	[87622] = {"blue","orange"},
	[96260] = "cyan",
	[413264] = "cyan",
})

BigWigs:AddSounds("Asaad", {
	[86911] = "info",
	[86930] = "alarm",
	[87618] = {"alert","warning"},
	[87622] = "alarm",
	[96260] = "alert",
	[413264] = "alert",
})

BigWigs:AddColors("The Vortex Pinnacle Trash", {
	[87761] = "red",
	[87762] = {"blue","orange"},
	[87772] = "orange",
	[87779] = "yellow",
	[88170] = "red",
	[88171] = "blue",
	[88182] = {"blue","purple"},
	[88186] = {"orange","red"},
	[88194] = "yellow",
	[410870] = "yellow",
	[410873] = {"blue","red"},
	[410999] = "orange",
	[411001] = "red",
	[411002] = "yellow",
	[411005] = "orange",
	[411012] = "orange",
	[411910] = "green",
	[413385] = {"blue","red"},
	[413387] = "orange",
})

BigWigs:AddSounds("The Vortex Pinnacle Trash", {
	[87761] = "alert",
	[87762] = {"alert","warning"},
	[87772] = "alert",
	[87779] = "warning",
	[88170] = "alert",
	[88171] = "underyou",
	[88182] = "alert",
	[88186] = "alert",
	[88194] = "long",
	[410870] = "alert",
	[410873] = "alert",
	[410999] = "alarm",
	[411001] = "alarm",
	[411002] = "long",
	[411005] = "alarm",
	[411012] = "alarm",
	[411910] = "info",
	[413385] = {"alarm","underyou"},
	[413387] = "alarm",
})
