-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Ambassador Hellmaw", {
})

BigWigs:AddSounds("Ambassador Hellmaw", {
})

BigWigs:AddColors("Blackheart the Inciter", {
	[33676] = {"red","yellow"},
})

BigWigs:AddSounds("Blackheart the Inciter", {
	[33676] = "alarm",
})

BigWigs:AddColors("Grandmaster Vorpil", {
	[-5267] = "orange",
	[38791] = {"blue","red"},
})

BigWigs:AddSounds("Grandmaster Vorpil", {
})

BigWigs:AddColors("Murmur", {
	[33923] = "red",
	[38794] = {"blue","yellow"},
})

BigWigs:AddSounds("Murmur", {
	[38794] = "alarm",
})
