-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Meathook", {
	[52696] = {"blue","red"},
})

BigWigs:AddSounds("Meathook", {
})

BigWigs:AddColors("Salramm the Fleshcrafter", {
	[58845] = {"blue","red"},
})

BigWigs:AddSounds("Salramm the Fleshcrafter", {
})

BigWigs:AddColors("Chrono-Lord Epoch", {
	[52772] = {"blue","red"},
})

BigWigs:AddSounds("Chrono-Lord Epoch", {
	[52772] = "alert",
})

BigWigs:AddColors("Mal'Ganis", {
	[52721] = {"blue","red"},
	[52723] = "orange",
})

BigWigs:AddSounds("Mal'Ganis", {
	[52723] = "info",
})

BigWigs:AddColors("Infinite Corruptor", {
	[60588] = {"blue","red"},
})

BigWigs:AddSounds("Infinite Corruptor", {
})

BigWigs:AddColors("The Culling of Stratholme Trash", {
})

BigWigs:AddSounds("The Culling of Stratholme Trash", {
})
