-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Shroomsprew", {
	[363194] = "blue",
	[415406] = "yellow",
	[415492] = "red",
	[415495] = "blue",
	[415499] = "green",
	[425315] = "orange",
})

BigWigs:AddSounds("Shroomsprew", {
	[363194] = "underyou",
	[415406] = "long",
	[415492] = "alarm",
	[415495] = "underyou",
	[415499] = "info",
	[425315] = "alarm",
})

BigWigs:AddColors("Waxface", {
	[450128] = {"blue","orange"},
	[450142] = "red",
	[450330] = {"blue","yellow"},
})

BigWigs:AddSounds("Waxface", {
	[450128] = {"alarm","underyou"},
	[450142] = "alert",
	[450330] = "alert",
})
