-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Researcher Ven'kex", {
	[446832] = "cyan",
	[447143] = "red",
	[447187] = "orange",
	[463408] = "cyan",
})

BigWigs:AddSounds("Researcher Ven'kex", {
	[446832] = "info",
	[447143] = "alert",
	[447187] = "alarm",
	[463408] = "info",
})

BigWigs:AddColors("Researcher Xik'vik", {
	[447143] = "red",
	[447187] = "orange",
})

BigWigs:AddSounds("Researcher Xik'vik", {
	[447143] = "alert",
	[447187] = "alarm",
})

BigWigs:AddColors("Torque Clankfire and Sprok", {
	[1215015] = "orange",
	[1215033] = "yellow",
	[1215084] = "red",
	[1215090] = "cyan",
})

BigWigs:AddSounds("Torque Clankfire and Sprok", {
	[1215015] = "alarm",
	[1215033] = "long",
	[1215084] = "alert",
	[1215090] = "info",
})
