-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Baron Ashbury", {
	[93423] = "red",
	[93581] = {"blue","orange"},
	[93757] = "yellow",
})

BigWigs:AddSounds("Baron Ashbury", {
	[93757] = "long",
})

BigWigs:AddColors("Baron Silverlaine", {
	[93857] = {"red","yellow"},
})

BigWigs:AddSounds("Baron Silverlaine", {
})

BigWigs:AddColors("Commander Springvale", {
	[93687] = "blue",
	[93844] = "orange",
	[93852] = {"blue","red"},
})

BigWigs:AddSounds("Commander Springvale", {
	[93687] = "alert",
	[93844] = "alarm",
})

BigWigs:AddColors("Lord Walden", {
	[93505] = "red",
	[93527] = "yellow",
	[93617] = {"blue","cyan","orange"},
	[93689] = "cyan",
	[93697] = "red",
})

BigWigs:AddSounds("Lord Walden", {
	[93617] = {"info","warning"},
	[93689] = "info",
})

BigWigs:AddColors("Lord Godfrey", {
	[93520] = {"blue","red"},
	[93629] = {"blue","orange"},
	[93675] = {"blue","yellow"},
	[93707] = "cyan",
})

BigWigs:AddSounds("Lord Godfrey", {
	[93520] = {"alert","long"},
	[93629] = "alarm",
	[93707] = "info",
})
