-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Trial of the King", {
	[-6024] = {"blue","yellow"},
	[-6017] = {"blue","yellow"},
	[119922] = "orange",
	[119981] = "orange",
	[120100] = "yellow",
	[120195] = {"blue","red"},
	[123655] = {"blue","red"},
})

BigWigs:AddSounds("Trial of the King", {
	[-6024] = "alert",
	[-6017] = "alarm",
	[119922] = "alarm",
	[119981] = "alarm",
	[120100] = "long",
	[120195] = "alarm",
	[123655] = "alert",
})

BigWigs:AddColors("Gekkan", {
	[118903] = {"blue","red"},
	[118963] = {"blue","purple","yellow"},
	[118988] = {"blue","red"},
	["heal"] = "orange",
	["stages"] = "green",
})

BigWigs:AddSounds("Gekkan", {
	[118963] = "warning",
	[118988] = "alarm",
	["heal"] = "alert",
	["stages"] = "info",
})

BigWigs:AddColors("Xin the Weaponmaster", {
	[-5974] = "cyan",
	[-5973] = "red",
	[-5972] = "cyan",
	[-5971] = "cyan",
	[119684] = "purple",
})

BigWigs:AddSounds("Xin the Weaponmaster", {
	[-5974] = "long",
	[-5973] = "alert",
	[-5972] = "long",
	[-5971] = "long",
	[119684] = "alarm",
})
