-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Fungarian Delve Trash", {
	[372529] = "orange",
	[414944] = "red",
	[424704] = "yellow",
	[424750] = {"blue","yellow"},
	[424773] = "red",
	[424798] = "orange",
	[424891] = "orange",
	[425040] = "red",
	[425042] = "orange",
	[1217589] = "orange",
})

BigWigs:AddSounds("Fungarian Delve Trash", {
	[372529] = "alarm",
	[414944] = "alert",
	[424704] = "alarm",
	[424750] = {"alarm","info"},
	[424773] = "alert",
	[424798] = "alarm",
	[424891] = "alarm",
	[425040] = "alert",
	[425042] = "alarm",
	[1217589] = "alarm",
})

BigWigs:AddColors("Goblin Delve Trash", {
	[472842] = {"blue","yellow"},
	[473537] = "orange",
	[473541] = "red",
	[473550] = "orange",
	[473684] = "yellow",
	[473696] = "orange",
	[473972] = "yellow",
	[473995] = "yellow",
	[474001] = "red",
	[474004] = "orange",
	[1213656] = "yellow",
})

BigWigs:AddSounds("Goblin Delve Trash", {
	[472842] = "info",
	[473537] = "alert",
	[473541] = "alarm",
	[473550] = "alarm",
	[473684] = "alarm",
	[473696] = "alarm",
	[473972] = "alarm",
	[473995] = "alarm",
	[474001] = "alert",
	[474004] = "alarm",
	[1213656] = "info",
})

BigWigs:AddColors("Kobold Delve Trash", {
	[445191] = {"blue","red"},
	[445210] = "orange",
	[448399] = {"red","yellow"},
	[448528] = "orange",
	[449071] = "orange",
})

BigWigs:AddSounds("Kobold Delve Trash", {
	[445191] = {"alert","info"},
	[445210] = "alarm",
	[448399] = {"alert","info"},
	[448528] = "alarm",
	[449071] = "alarm",
})

BigWigs:AddColors("Kobyss Delve Trash", {
	[374898] = "red",
	[430037] = "red",
	[433040] = "yellow",
	[440622] = "yellow",
	[445252] = "red",
	[445407] = {"blue","red"},
	[445492] = "orange",
	[445771] = "orange",
	[445774] = "red",
	[455932] = "orange",
})

BigWigs:AddSounds("Kobyss Delve Trash", {
	[374898] = "info",
	[430037] = "alert",
	[433040] = "info",
	[440622] = "alert",
	[445252] = "alarm",
	[445407] = {"info","warning"},
	[445492] = "alarm",
	[445771] = "alarm",
	[445774] = "alert",
	[455932] = "alarm",
})

BigWigs:AddColors("Nerubian Delve Trash", {
	[433410] = "orange",
	[433448] = "yellow",
	[449318] = "red",
	[450197] = "yellow",
	[450509] = "purple",
	[450546] = {"blue","green","red"},
	[450637] = "yellow",
	[450714] = "orange",
})

BigWigs:AddSounds("Nerubian Delve Trash", {
	[433410] = "alarm",
	[433448] = "info",
	[449318] = "alert",
	[450197] = "alarm",
	[450509] = "alarm",
	[450546] = "alert",
	[450637] = "info",
	[450714] = "alarm",
})

BigWigs:AddColors("Nightfall Delve Trash", {
	[434281] = "yellow",
	[434740] = "yellow",
	[440205] = "yellow",
	[441129] = {"blue","cyan"},
	[443292] = "orange",
	[443482] = "red",
})

BigWigs:AddSounds("Nightfall Delve Trash", {
	[434281] = "alarm",
	[434740] = "info",
	[440205] = "alert",
	[441129] = "alarm",
	[443292] = "alarm",
	[443482] = "alert",
})

BigWigs:AddColors("Old God Delve Trash", {
	[455662] = "blue",
	[474155] = "blue",
	[474206] = "orange",
	[474223] = "purple",
	[474228] = "red",
	[474325] = "cyan",
	[474482] = "yellow",
	[474511] = "purple",
})

BigWigs:AddSounds("Old God Delve Trash", {
	[455662] = "underyou",
	[474155] = "underyou",
	[474206] = "alarm",
	[474223] = "alert",
	[474228] = "alert",
	[474325] = "long",
	[474482] = "alarm",
	[474511] = "alert",
})

BigWigs:AddColors("The Underkeep Trash", {
	[448155] = "orange",
	[448161] = "yellow",
	[448179] = "red",
	[450637] = "yellow",
	[450714] = "orange",
	[451913] = {"blue","red"},
	[453149] = "yellow",
})

BigWigs:AddSounds("The Underkeep Trash", {
	[448155] = "alarm",
	[448161] = "info",
	[448179] = "alert",
	[450637] = "info",
	[450714] = "alarm",
	[451913] = {"alarm","underyou"},
	[453149] = "alert",
})

BigWigs:AddColors("Underpin Rares", {
	[418295] = "yellow",
	[418297] = "red",
	[433045] = "yellow",
	[1213497] = "red",
	[1213852] = "orange",
	[1214147] = {"cyan","yellow"},
	[1214238] = "red",
	[1214246] = "purple",
	[1216790] = "orange",
	[1216794] = "red",
	[1216805] = "red",
	[1216806] = "orange",
	[1216937] = "cyan",
	[1217301] = "red",
	[1217326] = "yellow",
	[1217361] = "orange",
	[1217371] = "red",
	[1217418] = "cyan",
	[1217449] = "cyan",
	[1217452] = "cyan",
	[1217510] = "cyan",
	[1218017] = "orange",
	[1218039] = "yellow",
	[1218061] = "red",
	[1220869] = "purple",
})

BigWigs:AddSounds("Underpin Rares", {
	[418295] = "alarm",
	[418297] = "alert",
	[433045] = "warning",
	[1213497] = "info",
	[1213852] = "alarm",
	[1214147] = {"info","long"},
	[1214238] = "alert",
	[1214246] = "alarm",
	[1216790] = "alarm",
	[1216794] = "alert",
	[1216805] = "alert",
	[1216806] = "alarm",
	[1216937] = "warning",
	[1217301] = "alarm",
	[1217326] = "alarm",
	[1217361] = "alert",
	[1217371] = "alarm",
	[1217418] = "info",
	[1217449] = "info",
	[1217452] = "info",
	[1217510] = "info",
	[1218017] = "alarm",
	[1218039] = "alarm",
	[1218061] = "alert",
	[1220869] = "alert",
})
