-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Instructor Chillheart", {
	[111209] = "orange",
	[111441] = "cyan",
	[111610] = {"blue","yellow"},
	[111631] = {"blue","red"},
	[111854] = "cyan",
})

BigWigs:AddSounds("Instructor Chillheart", {
	[111209] = "alarm",
	[111441] = "long",
	[111610] = "alert",
	[111631] = "alert",
	[111854] = "info",
})

BigWigs:AddColors("Jandice Barov", {
	[-5535] = {"cyan","green"},
	[114059] = "orange",
	[114062] = "purple",
})

BigWigs:AddSounds("Jandice Barov", {
	[-5535] = {"info","long"},
	[114059] = "alarm",
	[114062] = "alarm",
})

BigWigs:AddColors("Rattlegore", {
	[113765] = "purple",
	[113996] = {"green","red"},
	[113999] = "yellow",
})

BigWigs:AddSounds("Rattlegore", {
	[113765] = "info",
	[113996] = {"alarm","info"},
	[113999] = "alert",
})

BigWigs:AddColors("Lilian Voss", {
	[111570] = "orange",
	[111775] = "red",
	[115350] = {"blue","yellow"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("Lilian Voss", {
	[111570] = "long",
	[111775] = "alert",
	[115350] = {"alert","warning"},
	["stages"] = "long",
})

BigWigs:AddColors("Darkmaster Gandling", {
	[113143] = "cyan",
	[113395] = {"blue","red"},
})

BigWigs:AddSounds("Darkmaster Gandling", {
	[113143] = "long",
	[113395] = "info",
})
