-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Vexamus", {
	[385958] = "purple",
	[386173] = {"blue","yellow"},
	[386544] = "yellow",
	[388537] = "red",
	[391977] = {"blue","orange"},
})

BigWigs:AddSounds("Vexamus", {
	[385958] = "alarm",
	[386173] = "alarm",
	[386544] = "long",
	[388537] = "alert",
	[391977] = "alert",
})

BigWigs:AddColors("Overgrown Ancient", {
	[388544] = "purple",
	[388623] = "red",
	[388796] = "yellow",
	[388923] = "orange",
	[389033] = {"blue","red"},
	[396640] = "yellow",
	[396721] = "green",
})

BigWigs:AddSounds("Overgrown Ancient", {
	[388544] = "alert",
	[388623] = "alarm",
	[388796] = "long",
	[388923] = "long",
	[389033] = "alert",
	[396640] = "warning",
	[396721] = "info",
})

BigWigs:AddColors("Crawth", {
	[376448] = {"green","red"},
	[376467] = {"green","red"},
	[376997] = "purple",
	[377004] = "yellow",
	[377034] = "orange",
	[377182] = "cyan",
	[389481] = "cyan",
	[389483] = "cyan",
})

BigWigs:AddSounds("Crawth", {
	[376448] = {"info","long"},
	[376467] = {"info","long"},
	[376997] = "alert",
	[377004] = "warning",
	[377034] = "alarm",
	[377182] = "long",
	[389481] = "info",
	[389483] = "info",
})

BigWigs:AddColors("Echo of Doragosa", {
	[374352] = {"blue","yellow"},
	[374361] = "orange",
	[388822] = "red",
	[388901] = "blue",
	[389011] = "blue",
	[439488] = "cyan",
})

BigWigs:AddSounds("Echo of Doragosa", {
	[374352] = "alert",
	[374361] = "alarm",
	[388822] = "alarm",
	[388901] = "underyou",
	[389011] = "info",
	[439488] = "info",
})

BigWigs:AddColors("Algeth'ar Academy Trash", {
	[377383] = "orange",
	[377389] = "red",
	[377912] = "red",
	[377991] = "purple",
	[378003] = "orange",
	[387843] = {"blue","yellow"},
	[387910] = {"blue","orange"},
	[387955] = {"blue","orange"},
	[388392] = "red",
	[388863] = "yellow",
	[388911] = "purple",
	[388976] = "orange",
	[388984] = {"blue","red"},
	[389501] = "green",
	[389512] = "green",
	[389516] = "green",
	[389521] = "green",
	[389536] = "green",
	[390912] = "orange",
	[396812] = "red",
})

BigWigs:AddSounds("Algeth'ar Academy Trash", {
	[377383] = "alarm",
	[377389] = "warning",
	[377912] = "alarm",
	[377991] = "alert",
	[378003] = "alarm",
	[387843] = {"alert","info"},
	[387910] = {"alarm","underyou"},
	[387955] = "alert",
	[388392] = "alert",
	[388863] = "alert",
	[388911] = "alarm",
	[388976] = "alarm",
	[388984] = {"alarm","alert"},
	[389501] = "info",
	[389512] = "info",
	[389516] = "info",
	[389521] = "info",
	[389536] = "info",
	[390912] = "alarm",
	[396812] = "alert",
})

BigWigs:AddColors("Hackclaw's War-Band", {
	[377827] = {"blue","orange"},
	[377950] = "yellow",
	[377965] = "red",
	[378029] = "red",
	[378208] = {"blue","red"},
	[381444] = {"blue","red"},
	[381470] = "yellow",
	[381694] = {"blue","green","purple"},
})

BigWigs:AddSounds("Hackclaw's War-Band", {
	[377827] = {"alarm","long"},
	[377950] = "warning",
	[377965] = "long",
	[378029] = "alert",
	[378208] = "alarm",
	[381444] = {"alert","warning"},
	[381470] = "alert",
	[381694] = {"info","warning"},
})

BigWigs:AddColors("Treemouth", {
	[376811] = {"blue","yellow"},
	[376934] = "red",
	[377559] = "purple",
	[377859] = "orange",
	[378022] = {"blue","green","red"},
	[378054] = "blue",
	[383875] = "blue",
	[390968] = "red",
})

BigWigs:AddSounds("Treemouth", {
	[376811] = "alert",
	[376934] = "info",
	[377559] = "alarm",
	[377859] = "alarm",
	[378022] = {"info","long"},
	[378054] = "underyou",
	[383875] = "info",
	[390968] = "warning",
})

BigWigs:AddColors("Gutshot", {
	[384353] = "purple",
	[384416] = {"blue","orange"},
	[384577] = {"blue","purple"},
	[384633] = "red",
	[384827] = "orange",
	[385359] = {"blue","green","red","yellow"},
})

BigWigs:AddSounds("Gutshot", {
	[384353] = "alert",
	[384416] = {"alarm","alert"},
	[384577] = {"alarm","warning"},
	[384633] = "warning",
	[384827] = "long",
	[385359] = {"alarm","alert","info"},
})

BigWigs:AddColors("Decatriarch Wratheye", {
	[373917] = "purple",
	[373944] = "yellow",
	[373960] = "red",
	[376170] = "orange",
})

BigWigs:AddSounds("Decatriarch Wratheye", {
	[373917] = "alert",
	[373944] = "warning",
	[373960] = "long",
	[376170] = "alarm",
})

BigWigs:AddColors("Brackenhide Hollow Trash", {
	[367484] = {"blue","red","yellow"},
	[367500] = "red",
	[367503] = {"blue","orange"},
	[368081] = {"blue","yellow"},
	[368287] = {"blue","orange"},
	[372141] = "blue",
	[372711] = "red",
	[373897] = "yellow",
	[373929] = "purple",
	[373943] = "orange",
	[374057] = "yellow",
	[374245] = "blue",
	[374544] = {"blue","red"},
	[374569] = "orange",
	[382555] = {"blue","orange"},
	[382712] = "red",
	[383087] = {"blue","orange","yellow"},
	[383399] = {"blue","yellow"},
	[384847] = "yellow",
	[384854] = "orange",
	[384974] = {"blue","red"},
	[385029] = "yellow",
	[385827] = "yellow",
	[385832] = {"blue","red"},
	[388046] = "orange",
	[388060] = {"blue","red"},
	["captive_tuskarr_freed"] = "green",
})

BigWigs:AddSounds("Brackenhide Hollow Trash", {
	[367484] = {"alert","info","warning"},
	[367500] = "warning",
	[367503] = "alarm",
	[368081] = "alert",
	[368287] = {"alarm","underyou"},
	[372141] = "underyou",
	[372711] = "alert",
	[373897] = "alert",
	[373929] = "alarm",
	[373943] = "alarm",
	[374057] = "warning",
	[374245] = "underyou",
	[374544] = "alarm",
	[374569] = "alarm",
	[382555] = {"alarm","underyou"},
	[382712] = "alarm",
	[383087] = {"alarm","alert"},
	[383399] = {"long","underyou"},
	[384847] = "info",
	[384854] = "alarm",
	[384974] = {"alert","warning"},
	[385029] = "alert",
	[385827] = "warning",
	[385832] = "alert",
	[388046] = "alarm",
	[388060] = "alarm",
	["captive_tuskarr_freed"] = "info",
})

BigWigs:AddColors("Chronikar", {
	[401421] = "orange",
	[413013] = {"green","purple"},
	[413142] = {"blue","yellow"},
})

BigWigs:AddSounds("Chronikar", {
	[401421] = "alert",
	[413013] = {"alarm","info"},
	[413142] = "alarm",
})

BigWigs:AddColors("Manifested Timeways", {
	[405431] = "yellow",
	[405696] = {"blue","orange"},
	[414303] = "purple",
	[414307] = "purple",
})

BigWigs:AddSounds("Manifested Timeways", {
	[405431] = "long",
	[405696] = "alert",
	[414303] = "alarm",
	[414307] = "warning",
})

BigWigs:AddColors("Blight of Galakrond", {
	[406886] = "orange",
	[407147] = "blue",
	[407159] = "purple",
	[407406] = {"blue","red"},
	[407978] = "yellow",
	[408029] = {"blue","cyan","yellow"},
	[408141] = {"blue","orange"},
	[418346] = {"blue","yellow"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("Blight of Galakrond", {
	[406886] = "alert",
	[407147] = "underyou",
	[407159] = "alarm",
	[407406] = "info",
	[407978] = "long",
	[408029] = {"alert","info"},
	[408141] = "alarm",
	[418346] = "warning",
	["stages"] = "long",
})

BigWigs:AddColors("Iridikron the Stonescaled", {
	[409261] = {"blue","orange"},
	[409456] = {"green","red"},
	[409635] = "orange",
	[414184] = "red",
	[414535] = "yellow",
})

BigWigs:AddSounds("Iridikron the Stonescaled", {
	[409261] = {"alert","warning"},
	[409456] = {"alert","info"},
	[409635] = "alarm",
	[414184] = {"long","warning"},
	[414535] = "long",
})

BigWigs:AddColors("Tyr, the Infinite Keeper", {
	[400641] = "yellow",
	[400642] = "cyan",
	[400681] = {"blue","red"},
	[401248] = "purple",
	[401482] = "orange",
	[406543] = "blue",
	[408183] = {"blue","red"},
})

BigWigs:AddSounds("Tyr, the Infinite Keeper", {
	[400641] = "alert",
	[400642] = {"info","long"},
	[400681] = "alert",
	[401248] = "alarm",
	[401482] = "alarm",
	[406543] = "info",
	[408183] = "warning",
})

BigWigs:AddColors("Morchie", {
	[401200] = "blue",
	[401667] = {"blue","red"},
	[403891] = "cyan",
	[404364] = "orange",
	[404916] = "purple",
	[405279] = "yellow",
	[406481] = "green",
})

BigWigs:AddSounds("Morchie", {
	[401200] = "warning",
	[401667] = "alert",
	[403891] = "long",
	[404364] = "alarm",
	[404916] = "alarm",
	[405279] = "alert",
	[406481] = "info",
})

BigWigs:AddColors("Time-Lost Battlefield", {
	[408227] = "orange",
	[410235] = {"blue","red"},
	[410254] = "purple",
	[418046] = "cyan",
	[418047] = "cyan",
	[418054] = "orange",
	[418059] = "purple",
})

BigWigs:AddSounds("Time-Lost Battlefield", {
	[408227] = "alarm",
	[410235] = {"alarm","warning"},
	[410254] = "alert",
	[418046] = "info",
	[418047] = "info",
	[418054] = "alarm",
	[418059] = "alert",
})

BigWigs:AddColors("The Infinite Dragonflight", {
	[410904] = "yellow",
	[412027] = {"blue","yellow"},
	[416139] = "purple",
	[416152] = "red",
	[416264] = "red",
	[417413] = "blue",
	["stages"] = "cyan",
})

BigWigs:AddSounds("The Infinite Dragonflight", {
	[410904] = "alert",
	[412027] = "alert",
	[416139] = "alarm",
	[416152] = "info",
	[416264] = "long",
	[417413] = "underyou",
	["stages"] = "info",
})

BigWigs:AddColors("Dawn of the Infinite Trash", {
	[407124] = "red",
	[407125] = "orange",
	[407205] = {"blue","orange"},
	[407535] = "cyan",
	[407891] = "yellow",
	[407906] = "blue",
	[411300] = "yellow",
	[411407] = "red",
	[411952] = "orange",
	[411958] = "yellow",
	[411994] = "red",
	[412012] = "yellow",
	[412063] = "orange",
	[412129] = "orange",
	[412136] = "orange",
	[412156] = "orange",
	[412200] = "purple",
	[412215] = "orange",
	[412378] = "red",
	[412806] = "orange",
	[412922] = {"blue","red","yellow"},
	[413024] = "yellow",
	[413529] = "orange",
	[413544] = {"blue","purple","yellow"},
	[413607] = "red",
	[413621] = {"blue","orange","red"},
	[413622] = "yellow",
	[415437] = "red",
	[415769] = {"blue","yellow"},
	[415770] = "red",
	[415773] = "orange",
	[417002] = "blue",
	[417011] = "yellow",
	[417481] = "red",
	[418200] = {"blue","red","yellow"},
	[418684] = "cyan",
	[419351] = "purple",
	[419511] = "red",
	[419516] = {"blue","orange","yellow"},
	["rift_stability"] = "green",
})

BigWigs:AddSounds("Dawn of the Infinite Trash", {
	[407124] = "alert",
	[407125] = "alarm",
	[407205] = {"alarm","warning"},
	[407535] = "info",
	[407891] = "warning",
	[407906] = "underyou",
	[411300] = "alert",
	[411407] = "long",
	[411952] = "alarm",
	[411958] = "alert",
	[411994] = "alert",
	[412012] = "alert",
	[412063] = "alarm",
	[412129] = "alarm",
	[412136] = "alarm",
	[412156] = "alarm",
	[412200] = "alarm",
	[412215] = "alarm",
	[412378] = "warning",
	[412806] = "alarm",
	[412922] = {"alarm","info"},
	[413024] = "info",
	[413529] = "alarm",
	[413544] = "alert",
	[413607] = "alert",
	[413621] = {"alarm","info"},
	[413622] = "long",
	[415437] = "alert",
	[415769] = "alert",
	[415770] = "alert",
	[415773] = "alarm",
	[417002] = "underyou",
	[417011] = "warning",
	[417481] = "alert",
	[418200] = "alert",
	[418684] = "info",
	[419351] = "alarm",
	[419511] = "alert",
	[419516] = {"alarm","alert"},
	["rift_stability"] = "info",
})

BigWigs:AddColors("Watcher Irideus", {
	[383840] = {"cyan","green","yellow"},
	[384014] = "orange",
	[384351] = "yellow",
	[384524] = "purple",
	[389179] = {"blue","red"},
	[389446] = "red",
})

BigWigs:AddSounds("Watcher Irideus", {
	[383840] = {"info","long"},
	[384014] = "alert",
	[384351] = "long",
	[384524] = "alarm",
	[389179] = "alert",
	[389446] = "alarm",
})

BigWigs:AddColors("Gulping Goliath", {
	[374389] = {"blue","red"},
	[385187] = "yellow",
	[385442] = "yellow",
	[385531] = {"blue","red"},
	[385551] = "orange",
	[385743] = "orange",
})

BigWigs:AddSounds("Gulping Goliath", {
	[374389] = {"alert","warning"},
	[385187] = "long",
	[385442] = "alert",
	[385531] = "alarm",
	[385551] = "alarm",
	[385743] = "info",
})

BigWigs:AddColors("Khajin the Unyielding", {
	[385963] = {"blue","purple"},
	[386559] = "yellow",
	[386757] = "red",
	[390111] = "orange",
})

BigWigs:AddSounds("Khajin the Unyielding", {
	[385963] = "alert",
	[386559] = "long",
	[386757] = "warning",
	[390111] = "alarm",
})

BigWigs:AddColors("Primal Tsunami", {
	[387504] = "purple",
	[387559] = "yellow",
	[388424] = "red",
	[388882] = "yellow",
	[389875] = "purple",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Primal Tsunami", {
	[387504] = "alert",
	[387559] = "alarm",
	[388424] = "alert",
	[388882] = "alert",
	[389875] = {"alert","warning"},
	["stages"] = {"info","long"},
})

BigWigs:AddColors("Halls of Infusion Trash", {
	[374045] = "yellow",
	[374073] = "orange",
	[374339] = "red",
	[374389] = {"blue","red"},
	[374563] = "orange",
	[374699] = "red",
	[374724] = {"blue","yellow"},
	[374741] = "orange",
	[374823] = "cyan",
	[375079] = "orange",
	[375351] = "purple",
	[375384] = "orange",
	[376171] = "red",
	[377341] = "yellow",
	[377402] = {"red","yellow"},
	[390290] = "orange",
	[391241] = {"cyan","green"},
	[391471] = "green",
	[391634] = "red",
	[393432] = "purple",
	[395694] = {"red","yellow"},
	[437719] = "yellow",
})

BigWigs:AddSounds("Halls of Infusion Trash", {
	[374045] = "warning",
	[374073] = "alarm",
	[374339] = "alert",
	[374389] = {"alert","warning"},
	[374563] = "alarm",
	[374699] = "warning",
	[374724] = "alert",
	[374741] = "alarm",
	[374823] = "long",
	[375079] = "alarm",
	[375351] = "alarm",
	[375384] = "alarm",
	[376171] = "alert",
	[377341] = "alert",
	[377402] = {"alert","warning"},
	[390290] = "alarm",
	[391241] = "info",
	[391471] = "info",
	[391634] = "long",
	[393432] = "alarm",
	[395694] = {"alarm","alert"},
	[437719] = "alert",
})

BigWigs:AddColors("Chargath, Bane of Scales", {
	[373424] = "yellow",
	[373733] = "yellow",
	[373742] = "orange",
	[375056] = {"green","red"},
	[388523] = "green",
})

BigWigs:AddSounds("Chargath, Bane of Scales", {
	[373424] = "alert",
	[373733] = "alert",
	[373742] = "alarm",
	[375056] = {"info","long"},
	[388523] = "info",
})

BigWigs:AddColors("Forgemaster Gorek", {
	[374533] = "purple",
	[374635] = "red",
	[374839] = {"blue","yellow"},
	[374969] = "orange",
})

BigWigs:AddSounds("Forgemaster Gorek", {
	[374533] = "alarm",
	[374635] = "long",
	[374839] = "alert",
	[374969] = "alarm",
})

BigWigs:AddColors("Magmatusk", {
	[374365] = "orange",
	[375068] = "orange",
	[375251] = {"blue","yellow"},
	[375439] = {"blue","red"},
	[375535] = "orange",
	[375890] = "red",
	[391457] = {"green","purple"},
})

BigWigs:AddSounds("Magmatusk", {
	[374365] = "long",
	[375068] = "alert",
	[375251] = "alarm",
	[375439] = "alarm",
	[375535] = "alarm",
	[375890] = "alert",
	[391457] = {"alert","info"},
})

BigWigs:AddColors("Warlord Sargha", {
	[376780] = {"green","orange"},
	[377018] = {"blue","orange"},
	[377204] = "red",
	[377477] = "yellow",
	[377522] = {"blue","red"},
	[391762] = {"blue","orange"},
	["magical_implements"] = {"blue","green"},
})

BigWigs:AddSounds("Warlord Sargha", {
	[376780] = {"info","long"},
	[377018] = "alert",
	[377204] = "alarm",
	[377477] = "alert",
	[377522] = "warning",
	[391762] = "alert",
	["magical_implements"] = "info",
})

BigWigs:AddColors("Neltharus Trash", {
	[372201] = "orange",
	[372223] = "yellow",
	[372225] = "yellow",
	[372296] = "yellow",
	[372311] = "yellow",
	[372461] = {"blue","yellow"},
	[372561] = {"blue","red","yellow"},
	[372971] = "purple",
	[373084] = "red",
	[374451] = {"blue","green"},
	[376186] = "orange",
	[376200] = "yellow",
	[378282] = "red",
	[378818] = "yellow",
	[378827] = "orange",
	[379406] = "red",
	[381663] = "red",
	[382708] = "orange",
	[382791] = {"green","red"},
	[383651] = "yellow",
	[384161] = {"blue","red","yellow"},
	[384597] = "purple",
	[395427] = "red",
})

BigWigs:AddSounds("Neltharus Trash", {
	[372201] = "alarm",
	[372223] = "alert",
	[372225] = "alert",
	[372296] = "long",
	[372311] = "alarm",
	[372461] = "alert",
	[372561] = {"alarm","alert"},
	[372971] = "alert",
	[373084] = "alarm",
	[374451] = "info",
	[376186] = "alarm",
	[376200] = "long",
	[378282] = "warning",
	[378818] = "alert",
	[378827] = "alarm",
	[379406] = "alarm",
	[381663] = "long",
	[382708] = "alarm",
	[382791] = "info",
	[383651] = "alert",
	[384161] = "alert",
	[384597] = "alert",
	[395427] = "warning",
})

BigWigs:AddColors("Melidrussa Chillworn", {
	[372682] = {"blue","red"},
	[372851] = {"blue","yellow"},
	[372988] = "green",
	[373046] = "yellow",
	[373680] = {"green","red"},
	[396044] = "orange",
})

BigWigs:AddSounds("Melidrussa Chillworn", {
	[372682] = {"alert","warning"},
	[372851] = {"alarm","alert"},
	[372988] = "info",
	[373046] = "long",
	[373680] = {"info","long"},
	[396044] = "alarm",
})

BigWigs:AddColors("Kokia Blazehoof", {
	[372107] = {"blue","yellow"},
	[372858] = "purple",
	[372863] = "orange",
	[373017] = "red",
	[373087] = "orange",
})

BigWigs:AddSounds("Kokia Blazehoof", {
	[372107] = "alarm",
	[372858] = "alert",
	[372863] = "long",
	[373017] = "warning",
	[373087] = "alarm",
})

BigWigs:AddColors("Kyrakka and Erkhart Stormvein", {
	[381512] = {"blue","purple"},
	[381516] = "red",
	[381517] = "yellow",
	[381525] = "orange",
	[381602] = "red",
	[381862] = "blue",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Kyrakka and Erkhart Stormvein", {
	[381512] = {"alarm","alert"},
	[381516] = "warning",
	[381517] = "alert",
	[381525] = "alarm",
	[381602] = "alert",
	[381862] = "alarm",
	["stages"] = {"info","long"},
})

BigWigs:AddColors("Ruby Life Pools Trash", {
	[372047] = "purple",
	[372087] = "orange",
	[372696] = "orange",
	[372735] = "yellow",
	[372743] = "red",
	[373614] = "orange",
	[373692] = "red",
	[373693] = {"blue","yellow"},
	[373972] = "red",
	[385313] = {"blue","yellow"},
	[385536] = "yellow",
	[391050] = "yellow",
	[391723] = "orange",
	[391726] = "orange",
	[392394] = "purple",
	[392395] = "purple",
	[392451] = "red",
	[392486] = "orange",
	[392569] = "red",
	[392640] = {"blue","red"},
})

BigWigs:AddSounds("Ruby Life Pools Trash", {
	[372047] = "alert",
	[372087] = "alarm",
	[372696] = "alarm",
	[372735] = "alert",
	[372743] = "alert",
	[373614] = "alarm",
	[373692] = "alert",
	[373693] = "alert",
	[373972] = "info",
	[385313] = "alert",
	[385536] = "alert",
	[391050] = "info",
	[391723] = "alarm",
	[391726] = "alarm",
	[392394] = "alert",
	[392395] = "alert",
	[392451] = "alert",
	[392486] = "long",
	[392569] = "long",
	[392640] = "alert",
})

BigWigs:AddColors("Leymor", {
	[374364] = "yellow",
	[374567] = "orange",
	[374720] = "red",
	[374789] = "purple",
	[386660] = "orange",
})

BigWigs:AddSounds("Leymor", {
	[374364] = "info",
	[374567] = "alarm",
	[374720] = "alert",
	[374789] = "alert",
	[386660] = "alarm",
})

BigWigs:AddColors("Azureblade", {
	[372222] = "purple",
	[384132] = {"cyan","green"},
	[384223] = "yellow",
	[385578] = "red",
})

BigWigs:AddSounds("Azureblade", {
	[372222] = "alarm",
	[384132] = {"alert","info","long"},
	[384223] = "info",
	[385578] = "alarm",
})

BigWigs:AddColors("Telash Greywing", {
	[386781] = {"blue","orange"},
	[387151] = {"blue","orange"},
	[388008] = {"blue","orange","red"},
})

BigWigs:AddSounds("Telash Greywing", {
	[386781] = "alert",
	[387151] = {"alarm","alert"},
	[388008] = {"alert","long"},
})

BigWigs:AddColors("Umbrelskul", {
	[384699] = "red",
	[384978] = {"blue","purple"},
	[385075] = "yellow",
	[385399] = "yellow",
	[386746] = "orange",
})

BigWigs:AddSounds("Umbrelskul", {
	[384699] = "alarm",
	[384978] = "alert",
	[385075] = "info",
	[385399] = "alarm",
	[386746] = "long",
})

BigWigs:AddColors("The Azure Vault Trash", {
	[370764] = "purple",
	[370766] = "orange",
	[371358] = "red",
	[375596] = {"blue","orange","yellow"},
	[375649] = "blue",
	[375652] = "yellow",
	[377488] = "yellow",
	[386546] = "yellow",
	[387067] = "red",
	[387564] = "red",
	[391118] = "purple",
	[391136] = {"blue","orange"},
	[396991] = "red",
	[397726] = {"cyan","red"},
})

BigWigs:AddSounds("The Azure Vault Trash", {
	[370764] = "alarm",
	[370766] = "alarm",
	[371358] = "long",
	[375596] = "alarm",
	[375649] = "underyou",
	[375652] = "alert",
	[377488] = "alert",
	[386546] = "alert",
	[387067] = "alarm",
	[387564] = "alert",
	[391118] = "alarm",
	[391136] = "alarm",
	[396991] = "alert",
	[397726] = {"long","warning"},
})

BigWigs:AddColors("Granyth", {
	[385916] = "orange",
	[386320] = "red",
	[386490] = "red",
	[386530] = "green",
	[388283] = "red",
	[388817] = "yellow",
})

BigWigs:AddSounds("Granyth", {
	[385916] = "alarm",
	[386320] = "alert",
	[386490] = "warning",
	[386530] = "info",
	[388283] = "long",
	[388817] = "alert",
})

BigWigs:AddColors("The Raging Tempest", {
	[382628] = "blue",
	[384316] = "orange",
	[384620] = "red",
	[384686] = {"green","red","yellow"},
	[394875] = {"blue","red"},
})

BigWigs:AddSounds("The Raging Tempest", {
	[382628] = "info",
	[384316] = "alarm",
	[384620] = "long",
	[384686] = {"alert","info","warning"},
	[394875] = "warning",
})

BigWigs:AddColors("Teera and Maruuk", {
	[382670] = {"blue","red"},
	[382836] = "purple",
	[384808] = "orange",
	[385339] = "red",
	[385434] = "yellow",
	[386063] = "orange",
	[386547] = "yellow",
	[392198] = {"green","red"},
	[395669] = "blue",
})

BigWigs:AddSounds("Teera and Maruuk", {
	[382670] = "alarm",
	[382836] = "alert",
	[384808] = "alert",
	[385339] = "long",
	[385434] = "info",
	[386063] = "alarm",
	[386547] = "alert",
	[392198] = {"alert","info","warning"},
	[395669] = "underyou",
})

BigWigs:AddColors("Balakar Khan", {
	[375937] = "purple",
	[375943] = "red",
	[376634] = {"blue","yellow"},
	[376683] = "orange",
	[376827] = {"blue","purple","red"},
	[376864] = {"blue","yellow"},
	[376892] = "red",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Balakar Khan", {
	[375937] = "alert",
	[375943] = "alarm",
	[376634] = "alarm",
	[376683] = "alarm",
	[376827] = {"alert","warning"},
	[376864] = "alarm",
	[376892] = "alarm",
	["stages"] = "long",
})

BigWigs:AddColors("The Nokhud Offensive Trash", {
	[334610] = "blue",
	[372147] = "yellow",
	[373395] = "red",
	[382233] = "orange",
	[382277] = "red",
	[383823] = "yellow",
	[384336] = "orange",
	[384365] = "red",
	[384476] = "red",
	[386015] = "yellow",
	[386024] = "red",
	[386028] = "orange",
	[386223] = "yellow",
	[386694] = "orange",
	[387125] = "yellow",
	[387127] = {"blue","red"},
	[387411] = "red",
	[387440] = "cyan",
	[387596] = "yellow",
	[387614] = "orange",
	[395035] = "blue",
	[397394] = "purple",
	[436841] = "yellow",
})

BigWigs:AddSounds("The Nokhud Offensive Trash", {
	[334610] = "warning",
	[372147] = "alert",
	[373395] = {"alert","warning"},
	[382233] = "alarm",
	[382277] = "alarm",
	[383823] = "alert",
	[384336] = "alarm",
	[384365] = {"alert","warning"},
	[384476] = "long",
	[386015] = "alert",
	[386024] = "alarm",
	[386028] = "alarm",
	[386223] = "alert",
	[386694] = "alarm",
	[387125] = "alert",
	[387127] = "alert",
	[387411] = "alert",
	[387440] = "info",
	[387596] = "alert",
	[387614] = "alarm",
	[395035] = "alert",
	[397394] = {"alert","warning"},
	[436841] = "alert",
})

BigWigs:AddColors("The Lost Dwarves", {
	[369563] = "purple",
	[369573] = "yellow",
	[369602] = "orange",
	[369677] = {"blue","yellow"},
	[369791] = "red",
	[375286] = {"blue","red"},
	[375924] = "orange",
})

BigWigs:AddSounds("The Lost Dwarves", {
	[369563] = "alert",
	[369573] = "alarm",
	[369602] = "warning",
	[369677] = "alert",
	[369791] = "alarm",
	[375286] = {"alert","underyou"},
	[375924] = "long",
})

BigWigs:AddColors("Bromach", {
	[369605] = "cyan",
	[369660] = "green",
	[369675] = "red",
	[369700] = "yellow",
	[369703] = "orange",
	[369754] = "red",
})

BigWigs:AddSounds("Bromach", {
	[369605] = "long",
	[369660] = "info",
	[369675] = "alert",
	[369700] = "info",
	[369703] = "alarm",
	[369754] = "alert",
})

BigWigs:AddColors("Sentinel Talondras", {
	[372600] = {"green","red","yellow"},
	[372623] = {"blue","yellow"},
	[372701] = "orange",
	[372718] = {"blue","red"},
	[372719] = {"green","orange","red"},
})

BigWigs:AddSounds("Sentinel Talondras", {
	[372600] = {"info","long"},
	[372623] = "alert",
	[372701] = "alarm",
	[372718] = "alert",
	[372719] = {"info","long","warning"},
})

BigWigs:AddColors("Emberon", {
	[368990] = "cyan",
	[369038] = "green",
	[369043] = "green",
	[369061] = "purple",
	[369110] = "orange",
})

BigWigs:AddSounds("Emberon", {
	[368990] = "long",
	[369038] = "info",
	[369043] = "info",
	[369061] = "alarm",
	[369110] = "alert",
})

BigWigs:AddColors("Chrono-Lord Deios", {
	[375727] = "purple",
	[376049] = "orange",
	[376208] = "yellow",
	[376325] = "blue",
	[377405] = {"blue","red"},
})

BigWigs:AddSounds("Chrono-Lord Deios", {
	[375727] = "alarm",
	[376049] = "alarm",
	[376208] = {"info","long"},
	[376325] = "underyou",
	[377405] = "alert",
})

BigWigs:AddColors("Uldaman: Legacy of Tyr Trash", {
	[369328] = "red",
	[369335] = "purple",
	[369337] = "blue",
	[369365] = {"blue","orange","red"},
	[369366] = {"blue","orange"},
	[369400] = {"red","yellow"},
	[369409] = {"blue","purple"},
	[369411] = "red",
	[369465] = "orange",
	[369675] = "red",
	[369811] = "orange",
	[369823] = {"red","yellow"},
	[377500] = {"red","yellow"},
	[377724] = "green",
	[377732] = "purple",
	[377738] = {"blue","yellow"},
	[381593] = "red",
	[382578] = "orange",
	[386104] = "green",
})

BigWigs:AddSounds("Uldaman: Legacy of Tyr Trash", {
	[369328] = "long",
	[369335] = "alarm",
	[369337] = "underyou",
	[369365] = {"alert","warning"},
	[369366] = "alarm",
	[369400] = "alert",
	[369409] = "alarm",
	[369411] = "alarm",
	[369465] = "info",
	[369675] = "alert",
	[369811] = "alarm",
	[369823] = {"alert","warning"},
	[377500] = "alert",
	[377724] = "info",
	[377732] = "alarm",
	[377738] = "alert",
	[381593] = "alarm",
	[382578] = "alarm",
	[386104] = "info",
})
