-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("The Hoardmonger", {
})

BigWigs:AddSounds("The Hoardmonger", {
})

BigWigs:AddColors("Sentinel of Winter", {
})

BigWigs:AddSounds("Sentinel of Winter", {
})

BigWigs:AddColors("Nalorakk Den", {
})

BigWigs:AddSounds("Nalorakk Den", {
})

BigWigs:AddColors("Den of Nalorakk Trash", {
	["offerings_acquired"] = "green",
})

BigWigs:AddSounds("Den of Nalorakk Trash", {
	["offerings_acquired"] = "info",
})

BigWigs:AddColors("Arcanotron Custos", {
})

BigWigs:AddSounds("Arcanotron Custos", {
})

BigWigs:AddColors("Seranel Sunlash", {
})

BigWigs:AddSounds("Seranel Sunlash", {
})

BigWigs:AddColors("Gemellus", {
})

BigWigs:AddSounds("Gemellus", {
})

BigWigs:AddColors("Degentrius", {
})

BigWigs:AddSounds("Degentrius", {
})

BigWigs:AddColors("Muro'jin and Nekraxx", {
})

BigWigs:AddSounds("Muro'jin and Nekraxx", {
})

BigWigs:AddColors("Vordaza", {
})

BigWigs:AddSounds("Vordaza", {
})

BigWigs:AddColors("Rak'tul, Vessel of Souls", {
})

BigWigs:AddSounds("Rak'tul, Vessel of Souls", {
})

BigWigs:AddColors("Maisara Caverns Trash", {
	["prisoners_freed"] = "green",
})

BigWigs:AddSounds("Maisara Caverns Trash", {
	["prisoners_freed"] = "info",
})

BigWigs:AddColors("Kystia Manaheart", {
})

BigWigs:AddSounds("Kystia Manaheart", {
})

BigWigs:AddColors("Zaen Bladesorrow", {
})

BigWigs:AddSounds("Zaen Bladesorrow", {
})

BigWigs:AddColors("Xathuux the Annihilator", {
})

BigWigs:AddSounds("Xathuux the Annihilator", {
})

BigWigs:AddColors("Lithiel Cinderfury", {
})

BigWigs:AddSounds("Lithiel Cinderfury", {
})

BigWigs:AddColors("Murder Row Trash", {
	["snitches_interrogated"] = "green",
})

BigWigs:AddSounds("Murder Row Trash", {
	["snitches_interrogated"] = "info",
})

BigWigs:AddColors("Chief Corewright Kasreth", {
})

BigWigs:AddSounds("Chief Corewright Kasreth", {
})

BigWigs:AddColors("Corewarden Nysarra", {
})

BigWigs:AddSounds("Corewarden Nysarra", {
})

BigWigs:AddColors("Lothraxion", {
})

BigWigs:AddSounds("Lothraxion", {
})

BigWigs:AddColors("Lightblossom Trinity", {
})

BigWigs:AddSounds("Lightblossom Trinity", {
})

BigWigs:AddColors("Ikuzz the Light Hunter", {
})

BigWigs:AddSounds("Ikuzz the Light Hunter", {
})

BigWigs:AddColors("Lightwarden Ruia", {
})

BigWigs:AddSounds("Lightwarden Ruia", {
})

BigWigs:AddColors("Ziekett", {
})

BigWigs:AddSounds("Ziekett", {
})

BigWigs:AddColors("Taz'Rah", {
})

BigWigs:AddSounds("Taz'Rah", {
})

BigWigs:AddColors("Atroxus", {
})

BigWigs:AddSounds("Atroxus", {
})

BigWigs:AddColors("Charonus", {
})

BigWigs:AddSounds("Charonus", {
})

BigWigs:AddColors("Emberdawn", {
})

BigWigs:AddSounds("Emberdawn", {
})

BigWigs:AddColors("Derelict Duo", {
})

BigWigs:AddSounds("Derelict Duo", {
})

BigWigs:AddColors("Commander Kroluk", {
})

BigWigs:AddSounds("Commander Kroluk", {
})

BigWigs:AddColors("Restless Heart", {
})

BigWigs:AddSounds("Restless Heart", {
})
