-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Spiritflayer Jin'ma", {
})

BigWigs:AddSounds("Spiritflayer Jin'ma", {
})

BigWigs:AddColors("Hydrangea", {
})

BigWigs:AddSounds("Hydrangea", {
})

BigWigs:AddColors("Infiltrator Garand", {
})

BigWigs:AddSounds("Infiltrator Garand", {
})

BigWigs:AddColors("Voidscorned Vagrant", {
})

BigWigs:AddSounds("Voidscorned Vagrant", {
})

BigWigs:AddColors("Gladius Slaurna", {
})

BigWigs:AddSounds("Gladius Slaurna", {
})

BigWigs:AddColors("Chief-Arcanist Patram", {
})

BigWigs:AddSounds("Chief-Arcanist Patram", {
})

BigWigs:AddColors("Esuritus", {
})

BigWigs:AddSounds("Esuritus", {
})

BigWigs:AddColors("Infiltrator Gulkat", {
})

BigWigs:AddSounds("Infiltrator Gulkat", {
})

BigWigs:AddColors("Brightthorn", {
})

BigWigs:AddSounds("Brightthorn", {
})

BigWigs:AddColors("Gyrospore", {
})

BigWigs:AddSounds("Gyrospore", {
})

BigWigs:AddColors("Mycomight", {
})

BigWigs:AddSounds("Mycomight", {
})

BigWigs:AddColors("Lumenia", {
})

BigWigs:AddSounds("Lumenia", {
})

BigWigs:AddColors("Mul'tha'ul", {
})

BigWigs:AddSounds("Mul'tha'ul", {
})

BigWigs:AddColors("Antenorian", {
})

BigWigs:AddSounds("Antenorian", {
})

BigWigs:AddColors("Nullaeus", {
	[1280086] = "red",
	[1280087] = "orange",
	[1280088] = "yellow",
	["adds"] = "cyan",
})

BigWigs:AddSounds("Nullaeus", {
	[1280086] = "warning",
	[1280087] = "alarm",
	[1280088] = "info",
	["adds"] = "long",
})

BigWigs:AddColors("Blademaster Darza", {
})

BigWigs:AddSounds("Blademaster Darza", {
})

BigWigs:AddColors("Midnight Delve Trash", {
})

BigWigs:AddSounds("Midnight Delve Trash", {
})

BigWigs:AddColors("The Hoardmonger", {
	[1234233] = "yellow",
	[1235118] = "red",
	[1253268] = "orange",
})

BigWigs:AddSounds("The Hoardmonger", {
	[1234233] = "long",
	[1235118] = "alert",
	[1253268] = "alarm",
})

BigWigs:AddColors("Sentinel of Winter", {
	[1235548] = "red",
	[1235623] = "cyan",
	[1235783] = "orange",
})

BigWigs:AddSounds("Sentinel of Winter", {
	[1235548] = "alert",
	[1235623] = "info",
	[1235783] = "alarm",
})

BigWigs:AddColors("Nalorakk Den", {
	[1242860] = "red",
	[1243569] = "purple",
	[1255385] = "orange",
})

BigWigs:AddSounds("Nalorakk Den", {
	[1242860] = "info",
	[1243569] = "alert",
	[1255385] = "alarm",
})

BigWigs:AddColors("Den of Nalorakk Trash", {
	["offerings_acquired"] = "green",
})

BigWigs:AddSounds("Den of Nalorakk Trash", {
	["offerings_acquired"] = "info",
})

BigWigs:AddColors("Arcanotron Custos", {
	[474345] = "cyan",
	[474496] = "purple",
	[1214032] = "yellow",
	[1214081] = "orange",
})

BigWigs:AddSounds("Arcanotron Custos", {
	[474345] = {"info","long"},
	[474496] = "alert",
	[1214032] = "info",
	[1214081] = "alarm",
})

BigWigs:AddColors("Seranel Sunlash", {
	[1224903] = "orange",
	[1225787] = "yellow",
	[1248689] = "purple",
})

BigWigs:AddSounds("Seranel Sunlash", {
	[1224903] = "alarm",
	[1225787] = "alert",
	[1248689] = "info",
})

BigWigs:AddColors("Gemellus", {
	[1223847] = "cyan",
	[1224299] = "orange",
	[1253709] = "red",
	[1284954] = "yellow",
})

BigWigs:AddSounds("Gemellus", {
	[1223847] = "info",
	[1224299] = "alert",
	[1253709] = "info",
	[1284954] = "alert",
})

BigWigs:AddColors("Degentrius", {
	[1215897] = "yellow",
	[1280113] = "purple",
})

BigWigs:AddSounds("Degentrius", {
	[1215897] = "alert",
	[1280113] = "alarm",
})

BigWigs:AddColors("Muro'jin and Nekraxx", {
	[1243900] = "red",
	[1246666] = "yellow",
	[1260643] = "yellow",
	[1260731] = "orange",
	[1266480] = "purple",
})

BigWigs:AddSounds("Muro'jin and Nekraxx", {
	[1243900] = "alarm",
	[1246666] = "alert",
	[1260643] = "info",
	[1260731] = "alarm",
	[1266480] = "alert",
})

BigWigs:AddColors("Vordaza", {
	[1250708] = "yellow",
	[1251204] = "cyan",
	[1251554] = "purple",
	[1252054] = "orange",
})

BigWigs:AddSounds("Vordaza", {
	[1250708] = "long",
	[1251204] = "info",
	[1251554] = "alert",
	[1252054] = "alarm",
})

BigWigs:AddColors("Rak'tul, Vessel of Souls", {
	[1251023] = "purple",
	[1252676] = "orange",
	[1253788] = "yellow",
})

BigWigs:AddSounds("Rak'tul, Vessel of Souls", {
	[1251023] = "alert",
	[1252676] = "alarm",
	[1253788] = "long",
})

BigWigs:AddColors("Maisara Caverns Trash", {
	["prisoners_freed"] = "green",
})

BigWigs:AddSounds("Maisara Caverns Trash", {
	["prisoners_freed"] = "info",
})

BigWigs:AddColors("Kystia Manaheart", {
})

BigWigs:AddSounds("Kystia Manaheart", {
})

BigWigs:AddColors("Zaen Bladesorrow", {
	[474478] = "red",
	[474765] = "yellow",
	[1214357] = "orange",
	[1222795] = "purple",
})

BigWigs:AddSounds("Zaen Bladesorrow", {
	[474478] = "info",
	[474765] = "alert",
	[1214357] = "alarm",
	[1222795] = "alert",
})

BigWigs:AddColors("Xathuux the Annihilator", {
})

BigWigs:AddSounds("Xathuux the Annihilator", {
})

BigWigs:AddColors("Lithiel Cinderfury", {
})

BigWigs:AddSounds("Lithiel Cinderfury", {
})

BigWigs:AddColors("Murder Row Trash", {
	["snitches_interrogated"] = "green",
})

BigWigs:AddSounds("Murder Row Trash", {
	["snitches_interrogated"] = "info",
})

BigWigs:AddColors("Chief Corewright Kasreth", {
	[1251579] = "yellow",
	[1257509] = "cyan",
	[1264048] = "orange",
})

BigWigs:AddSounds("Chief Corewright Kasreth", {
	[1251579] = "alert",
	[1251772] = "info",
	[1257509] = "long",
	[1264048] = "alarm",
})

BigWigs:AddColors("Corewarden Nysarra", {
	[1247937] = "purple",
	[1249014] = "orange",
	[1252703] = "cyan",
	[1264439] = "yellow",
})

BigWigs:AddSounds("Corewarden Nysarra", {
	[1247937] = "alert",
	[1249014] = "alert",
	[1252703] = "info",
	[1264439] = "long",
})

BigWigs:AddColors("Lothraxion", {
	[1253855] = "yellow",
	[1253950] = "purple",
	[1255531] = "orange",
	[1257595] = "cyan",
})

BigWigs:AddSounds("Lothraxion", {
	[1253855] = "alarm",
	[1253950] = "alert",
	[1255531] = "alarm",
	[1257595] = "long",
})

BigWigs:AddColors("Nexus-Point Xenas Trash", {
})

BigWigs:AddSounds("Nexus-Point Xenas Trash", {
})

BigWigs:AddColors("Lightblossom Trinity", {
})

BigWigs:AddSounds("Lightblossom Trinity", {
})

BigWigs:AddColors("Ikuzz the Light Hunter", {
})

BigWigs:AddSounds("Ikuzz the Light Hunter", {
})

BigWigs:AddColors("Lightwarden Ruia", {
})

BigWigs:AddSounds("Lightwarden Ruia", {
})

BigWigs:AddColors("Ziekket", {
})

BigWigs:AddSounds("Ziekket", {
})

BigWigs:AddColors("Taz'Rah", {
})

BigWigs:AddSounds("Taz'Rah", {
})

BigWigs:AddColors("Atroxus", {
})

BigWigs:AddSounds("Atroxus", {
})

BigWigs:AddColors("Charonus", {
})

BigWigs:AddSounds("Charonus", {
})

BigWigs:AddColors("Emberdawn", {
	[465904] = "yellow",
	[466064] = "purple",
	[466556] = "orange",
})

BigWigs:AddSounds("Emberdawn", {
	[465904] = "long",
	[466064] = "alert",
	[466556] = "alarm",
})

BigWigs:AddColors("Derelict Duo", {
	[472736] = "yellow",
	[472745] = "orange",
	[472888] = "purple",
	[474105] = "red",
})

BigWigs:AddSounds("Derelict Duo", {
	[472736] = "long",
	[472745] = "alarm",
	[472888] = "alarm",
	[474105] = "alert",
})

BigWigs:AddColors("Commander Kroluk", {
	[467620] = "purple",
	[472081] = "orange",
	[1250851] = {"cyan","green"},
	[1253272] = "red",
})

BigWigs:AddSounds("Commander Kroluk", {
	[467620] = "alert",
	[472081] = "alarm",
	[1250851] = {"info","long"},
	[1253272] = "warning",
})

BigWigs:AddColors("Restless Heart", {
	[472556] = "cyan",
	[472662] = "purple",
	[474528] = "yellow",
	[1253986] = "red",
})

BigWigs:AddSounds("Restless Heart", {
	[472556] = "info",
	[472662] = "alert",
	[474528] = "long",
	[1253986] = "alarm",
})
