-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Rav'i", {
	[1296050] = "orange",
	[1296216] = "cyan",
	[1296220] = {"blue","yellow"},
	[1307703] = "purple",
	[1307894] = "red",
})

BigWigs:AddSounds("Rav'i", {
	[1296050] = "alarm",
	[1296216] = "long",
	[1296220] = {"alert","warning"},
	[1307703] = "info",
	[1307894] = "alarm",
})

BigWigs:AddColors("The Writhing Coil", {
	[1298949] = "purple",
	[1299053] = "red",
	[1299130] = "orange",
	[1299154] = "yellow",
	[1300044] = "red",
	[1300686] = "cyan",
})

BigWigs:AddSounds("The Writhing Coil", {
	[1298949] = "alert",
	[1299053] = "warning",
	[1299130] = "alarm",
	[1299154] = "alert",
	[1300044] = "alarm",
	[1300686] = "info",
})

BigWigs:AddColors("Zul'jan", {
	[1300876] = "cyan",
	[1301111] = "orange",
	[1301350] = "purple",
	[1301413] = "red",
})

BigWigs:AddSounds("Zul'jan", {
	[1300876] = "long",
	[1301111] = "alert",
	[1301350] = "alert",
	[1301413] = "alarm",
})

BigWigs:AddColors("Altar of Fangs Trash", {
})

BigWigs:AddSounds("Altar of Fangs Trash", {
})

BigWigs:AddColors("Spiritflayer Jin'ma", {
})

BigWigs:AddSounds("Spiritflayer Jin'ma", {
})

BigWigs:AddColors("Hydrangea", {
})

BigWigs:AddSounds("Hydrangea", {
})

BigWigs:AddColors("Infiltrator Garand", {
})

BigWigs:AddSounds("Infiltrator Garand", {
})

BigWigs:AddColors("Voidscorned Vagrant", {
})

BigWigs:AddSounds("Voidscorned Vagrant", {
})

BigWigs:AddColors("Gladius Slaurna", {
})

BigWigs:AddSounds("Gladius Slaurna", {
})

BigWigs:AddColors("Chief-Arcanist Patram", {
})

BigWigs:AddSounds("Chief-Arcanist Patram", {
})

BigWigs:AddColors("Esuritus", {
})

BigWigs:AddSounds("Esuritus", {
})

BigWigs:AddColors("Infiltrator Gulkat", {
})

BigWigs:AddSounds("Infiltrator Gulkat", {
})

BigWigs:AddColors("Brightthorn", {
})

BigWigs:AddSounds("Brightthorn", {
})

BigWigs:AddColors("Gyrospore", {
})

BigWigs:AddSounds("Gyrospore", {
})

BigWigs:AddColors("Mycomight", {
})

BigWigs:AddSounds("Mycomight", {
})

BigWigs:AddColors("Lumenia", {
})

BigWigs:AddSounds("Lumenia", {
})

BigWigs:AddColors("Mul'tha'ul", {
})

BigWigs:AddSounds("Mul'tha'ul", {
})

BigWigs:AddColors("Antenorian", {
})

BigWigs:AddSounds("Antenorian", {
})

BigWigs:AddColors("Nullaeus", {
	[1280086] = "red",
	[1280087] = "orange",
	[1280088] = "yellow",
	["adds"] = "cyan",
})

BigWigs:AddSounds("Nullaeus", {
	[1280086] = "warning",
	[1280087] = "alarm",
	[1280088] = "info",
	["adds"] = "long",
})

BigWigs:AddColors("Blademaster Darza", {
})

BigWigs:AddSounds("Blademaster Darza", {
})

BigWigs:AddColors("Azta'rec", {
})

BigWigs:AddSounds("Azta'rec", {
})

BigWigs:AddColors("Midnight Delve Trash", {
})

BigWigs:AddSounds("Midnight Delve Trash", {
})

BigWigs:AddColors("The Hoardmonger", {
	[1234233] = "yellow",
	[1235118] = "red",
	[1253268] = "orange",
})

BigWigs:AddSounds("The Hoardmonger", {
	[1234233] = "long",
	[1235118] = "alert",
	[1253268] = "alarm",
})

BigWigs:AddColors("Sentinel of Winter", {
	[1235548] = "red",
	[1235623] = "cyan",
	[1235656] = "yellow",
	[1235783] = "orange",
})

BigWigs:AddSounds("Sentinel of Winter", {
	[1235548] = "alert",
	[1235623] = "info",
	[1235656] = "long",
	[1235783] = "alarm",
})

BigWigs:AddColors("Nalorakk Den", {
	[1242860] = "red",
	[1243011] = "yellow",
	[1243569] = "orange",
	[1255385] = "orange",
})

BigWigs:AddSounds("Nalorakk Den", {
	[1242860] = "info",
	[1243011] = "long",
	[1243569] = "alarm",
	[1255385] = "alert",
})

BigWigs:AddColors("Den of Nalorakk Trash", {
	["offerings_acquired"] = "green",
})

BigWigs:AddSounds("Den of Nalorakk Trash", {
	["offerings_acquired"] = "info",
})

BigWigs:AddColors("Arcanotron Custos", {
	[474345] = "cyan",
	[474496] = "purple",
	[1214032] = "yellow",
	[1214081] = "orange",
})

BigWigs:AddSounds("Arcanotron Custos", {
	[474345] = {"info","long"},
	[474496] = "alert",
	[1214032] = "info",
	[1214081] = "alarm",
})

BigWigs:AddColors("Seranel Sunlash", {
	[1224903] = "orange",
	[1225193] = "red",
	[1225787] = {"blue","yellow"},
	[1248689] = "purple",
})

BigWigs:AddSounds("Seranel Sunlash", {
	[1224903] = "alarm",
	[1225193] = "warning",
	[1248689] = "info",
})

BigWigs:AddColors("Gemellus", {
	[1223847] = "cyan",
	[1224299] = "blue",
	[1253709] = "blue",
	[1284954] = "yellow",
})

BigWigs:AddSounds("Gemellus", {
	[1223847] = "info",
	[1224299] = "warning",
	[1284954] = "alert",
})

BigWigs:AddColors("Degentrius", {
	[1215087] = "red",
	[1215897] = "blue",
	[1280113] = "purple",
})

BigWigs:AddSounds("Degentrius", {
	[1215087] = "info",
	[1215897] = "warning",
	[1280113] = "alarm",
})

BigWigs:AddColors("Muro'jin and Nekraxx", {
	[1243900] = "yellow",
	[1246666] = "yellow",
	[1249479] = "red",
	[1249947] = "cyan",
	[1260643] = {"blue","yellow"},
	[1260731] = "orange",
	[1266480] = "purple",
})

BigWigs:AddSounds("Muro'jin and Nekraxx", {
	[1243900] = "long",
	[1246666] = "alert",
	[1249947] = "long",
	[1260731] = "alarm",
	[1266480] = "alert",
})

BigWigs:AddColors("Vordaza", {
	[1250708] = "yellow",
	[1251204] = "cyan",
	[1251554] = "purple",
	[1251775] = "blue",
	[1252054] = "orange",
})

BigWigs:AddSounds("Vordaza", {
	[1250708] = "long",
	[1251204] = "info",
	[1251554] = "alert",
	[1252054] = "alarm",
})

BigWigs:AddColors("Rak'tul, Vessel of Souls", {
	[1251023] = "purple",
	[1252676] = {"blue","orange"},
	[1253788] = "cyan",
})

BigWigs:AddSounds("Rak'tul, Vessel of Souls", {
	[1251023] = "alert",
	[1252676] = "alarm",
	[1253788] = "long",
})

BigWigs:AddColors("Maisara Caverns Trash", {
	["prisoners_freed"] = "green",
})

BigWigs:AddSounds("Maisara Caverns Trash", {
	["prisoners_freed"] = "info",
})

BigWigs:AddColors("Kystia Manaheart", {
	[474240] = "orange",
	[1253811] = "red",
	[1264095] = "cyan",
})

BigWigs:AddSounds("Kystia Manaheart", {
	[474240] = "alarm",
	[1253811] = "alarm",
	[1264095] = "info",
})

BigWigs:AddColors("Zaen Bladesorrow", {
	[474478] = "red",
	[474765] = "yellow",
	[1214357] = {"blue","orange"},
	[1218347] = "cyan",
	[1222795] = "purple",
})

BigWigs:AddSounds("Zaen Bladesorrow", {
	[474478] = "info",
	[474765] = "alert",
	[1214357] = "alarm",
	[1222795] = "alert",
})

BigWigs:AddColors("Xathuux the Annihilator", {
	[473898] = "purple",
	[474197] = "yellow",
	[1214637] = {"blue","red"},
	[1295453] = "orange",
})

BigWigs:AddSounds("Xathuux the Annihilator", {
	[473898] = "alert",
	[474197] = "long",
	[1214637] = "alarm",
	[1295453] = "alarm",
})

BigWigs:AddColors("Lithiel Cinderfury", {
	[474408] = "cyan",
	[1218203] = "orange",
	[1224478] = "red",
})

BigWigs:AddSounds("Lithiel Cinderfury", {
	[474408] = "info",
	[1218203] = "alarm",
	[1224478] = "warning",
})

BigWigs:AddColors("Murder Row Trash", {
	["snitches_interrogated"] = "green",
})

BigWigs:AddSounds("Murder Row Trash", {
	["snitches_interrogated"] = "info",
})

BigWigs:AddColors("Chief Corewright Kasreth", {
	[1251579] = "yellow",
	[1251772] = {"blue","red"},
	[1257509] = "cyan",
	[1264048] = "orange",
})

BigWigs:AddSounds("Chief Corewright Kasreth", {
	[1251579] = "info",
	[1251772] = "warning",
	[1257509] = "long",
	[1264048] = "alarm",
})

BigWigs:AddColors("Corewarden Nysarra", {
	[1247937] = "purple",
	[1249014] = {"blue","orange"},
	[1252703] = "cyan",
	[1264439] = "yellow",
})

BigWigs:AddSounds("Corewarden Nysarra", {
	[1247937] = "alarm",
	[1252703] = "info",
	[1264439] = "long",
})

BigWigs:AddColors("Lothraxion", {
	[1253855] = {"blue","yellow"},
	[1253950] = "purple",
	[1255531] = "red",
	[1257595] = "cyan",
})

BigWigs:AddSounds("Lothraxion", {
	[1253855] = "warning",
	[1253950] = "alert",
	[1255531] = "alarm",
	[1257595] = "long",
})

BigWigs:AddColors("Nexus-Point Xenas Trash", {
})

BigWigs:AddSounds("Nexus-Point Xenas Trash", {
})

BigWigs:AddColors("Lightblossom Trinity", {
	[1234753] = "purple",
	[1234850] = "red",
	[1235564] = "cyan",
	[1235640] = "yellow",
})

BigWigs:AddSounds("Lightblossom Trinity", {
	[1234753] = "alert",
	[1234850] = "alarm",
	[1235564] = "long",
	[1235640] = "alert",
})

BigWigs:AddColors("Ikuzz the Light Hunter", {
	[1236709] = "yellow",
	[1236746] = "orange",
	[1237090] = {"blue","red"},
})

BigWigs:AddSounds("Ikuzz the Light Hunter", {
	[1236709] = "long",
	[1236746] = "alert",
	[1237090] = "warning",
})

BigWigs:AddColors("Lightwarden Ruia", {
	[1239824] = {"blue","yellow"},
	[1239882] = "cyan",
	[1239883] = "cyan",
	[1239885] = "cyan",
	[1240098] = "orange",
	[1240210] = {"orange","yellow"},
	[1241058] = "red",
})

BigWigs:AddSounds("Lightwarden Ruia", {
	[1239824] = "warning",
	[1239882] = "info",
	[1239883] = "info",
	[1239885] = "info",
	[1240098] = "alarm",
	[1240210] = "alarm",
	[1241058] = "alert",
})

BigWigs:AddColors("Ziekket", {
	[1246372] = "cyan",
	[1246607] = {"blue","orange"},
	[1246858] = "yellow",
	[1247685] = "purple",
})

BigWigs:AddSounds("Ziekket", {
	[1246372] = "long",
	[1246607] = "alarm",
	[1246858] = "info",
	[1247685] = "alert",
})

BigWigs:AddColors("Taz'Rah", {
	[1222085] = "purple",
	[1222098] = {"blue","red"},
	[1222274] = "yellow",
	[1262901] = "cyan",
	[1296963] = "orange",
	[1297017] = "purple",
	[1300259] = "yellow",
})

BigWigs:AddSounds("Taz'Rah", {
	[1222085] = "alert",
	[1222098] = {"alarm","info"},
	[1222274] = "long",
	[1262901] = "info",
	[1296963] = "alarm",
	[1297017] = "alert",
	[1300259] = "long",
})

BigWigs:AddColors("Atroxus", {
	[1222371] = "cyan",
	[1222642] = "purple",
	[1222721] = "red",
	[1226120] = "yellow",
	[1262497] = "orange",
})

BigWigs:AddSounds("Atroxus", {
	[1222371] = "info",
	[1222642] = "alert",
	[1222721] = "alarm",
	[1226120] = "long",
	[1262497] = "alarm",
})

BigWigs:AddColors("Charonus", {
	[1222755] = "yellow",
	[1227264] = "red",
	[1263982] = "cyan",
	[1282770] = "orange",
})

BigWigs:AddSounds("Charonus", {
	[1222755] = "warning",
	[1227264] = "alarm",
	[1263982] = "info",
	[1282770] = "alert",
})

BigWigs:AddColors("Emberdawn", {
	[465904] = {"green","yellow"},
	[466064] = "purple",
	[466556] = {"blue","orange"},
})

BigWigs:AddSounds("Emberdawn", {
	[465904] = {"info","long"},
	[466064] = "alert",
	[466556] = "alarm",
})

BigWigs:AddColors("Derelict Duo", {
	[472736] = "yellow",
	[472745] = "orange",
	[472793] = "blue",
	[472888] = "purple",
	[474105] = {"blue","red"},
})

BigWigs:AddSounds("Derelict Duo", {
	[472736] = "long",
	[472888] = "alarm",
	[474105] = "alert",
})

BigWigs:AddColors("Commander Kroluk", {
	[467620] = "purple",
	[472081] = {"blue","orange"},
	[1250851] = {"cyan","green"},
	[1253272] = "red",
})

BigWigs:AddSounds("Commander Kroluk", {
	[467620] = "alert",
	[472081] = "alarm",
	[1250851] = {"info","long"},
	[1253272] = "warning",
})

BigWigs:AddColors("Restless Heart", {
	[468429] = "yellow",
	[472556] = "cyan",
	[472662] = "purple",
	[474528] = {"blue","red"},
	[1253986] = "orange",
})

BigWigs:AddSounds("Restless Heart", {
	[468429] = "long",
	[472556] = "info",
	[472662] = "alert",
})
