-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Leymor", {
	[374364] = "yellow",
	[374567] = "orange",
	[374720] = "red",
	[374789] = "purple",
	[386660] = "orange",
})

BigWigs:AddSounds("Leymor", {
	[374364] = "info",
	[374567] = "alarm",
	[374720] = "alert",
	[374789] = "alert",
	[386660] = "alarm",
})

BigWigs:AddColors("Azureblade", {
	[372222] = "purple",
	[384132] = {"cyan","green"},
	[384223] = "yellow",
	[385578] = "red",
})

BigWigs:AddSounds("Azureblade", {
	[372222] = "alarm",
	[384132] = {"alert","info","long"},
	[384223] = "info",
	[385578] = "alarm",
})

BigWigs:AddColors("Telash Greywing", {
	[386781] = {"blue","orange"},
	[387151] = {"blue","orange"},
	[388008] = {"blue","orange","red"},
})

BigWigs:AddSounds("Telash Greywing", {
	[386781] = "alert",
	[387151] = {"alarm","alert"},
	[388008] = {"alert","long"},
})

BigWigs:AddColors("Umbrelskul", {
	[384699] = "red",
	[384978] = {"blue","purple"},
	[385075] = "yellow",
	[385399] = "yellow",
	[386746] = "orange",
})

BigWigs:AddSounds("Umbrelskul", {
	[384699] = "alarm",
	[384978] = "alert",
	[385075] = "info",
	[385399] = "alarm",
	[386746] = "long",
})

BigWigs:AddColors("The Azure Vault Trash", {
	[370764] = "purple",
	[370766] = "orange",
	[371358] = "red",
	[375596] = {"blue","orange","yellow"},
	[375649] = "blue",
	[375652] = "yellow",
	[377488] = "yellow",
	[386546] = "yellow",
	[387067] = "red",
	[387564] = "red",
	[391118] = "purple",
	[391136] = {"blue","orange"},
	[396991] = "red",
	[397726] = {"cyan","red"},
})

BigWigs:AddSounds("The Azure Vault Trash", {
	[370764] = "alarm",
	[370766] = "alarm",
	[371358] = "long",
	[375596] = "alarm",
	[375649] = "underyou",
	[375652] = "alert",
	[377488] = "alert",
	[386546] = "alert",
	[387067] = "alarm",
	[387564] = "alert",
	[391118] = "alarm",
	[391136] = "alarm",
	[396991] = "alert",
	[397726] = {"long","warning"},
})
