-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Lieutenant Drake", {
	[31910] = "blue",
	[31911] = {"blue","orange"},
})

BigWigs:AddSounds("Lieutenant Drake", {
	[31910] = "alarm",
	[31911] = "warning",
})

BigWigs:AddColors("Captain Skarloc", {
	[13005] = {"blue","red"},
	[29427] = "orange",
	[38385] = "blue",
})

BigWigs:AddSounds("Captain Skarloc", {
	[13005] = "warning",
	[29427] = "alert",
	[38385] = "alarm",
})

BigWigs:AddColors("Epoch Hunter", {
	[31914] = "blue",
	[33834] = "orange",
})

BigWigs:AddSounds("Epoch Hunter", {
	[31914] = "warning",
	[33834] = "alert",
})

BigWigs:AddColors("Old Hillsbrad Foothills Trash", {
	["incendiary_bombs"] = "cyan",
})

BigWigs:AddSounds("Old Hillsbrad Foothills Trash", {
	["incendiary_bombs"] = "info",
})
