-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Rom'ogg Bonecrusher", {
	[75272] = {"blue","yellow"},
	[75539] = {"red","yellow"},
	[75543] = "orange",
})

BigWigs:AddSounds("Rom'ogg Bonecrusher", {
	[75272] = "alert",
	[75539] = "alarm",
})

BigWigs:AddColors("Corla, Herald of Twilight", {
	[75697] = {"blue","green"},
	[75823] = {"blue","orange","red"},
})

BigWigs:AddSounds("Corla, Herald of Twilight", {
	[75697] = "warning",
	[75823] = {"alarm","alert"},
})

BigWigs:AddColors("Karsh Steelbender", {
	[75842] = "yellow",
	[75846] = {"blue","red"},
})

BigWigs:AddSounds("Karsh Steelbender", {
	[75842] = "alert",
	[75846] = {"info","warning"},
})

BigWigs:AddColors("Beauty", {
	[76028] = {"blue","yellow"},
	[76031] = {"blue","orange"},
	[76628] = "blue",
})

BigWigs:AddSounds("Beauty", {
	[76628] = "alert",
})

BigWigs:AddColors("Ascendant Lord Obsidius", {
	[-2385] = {"orange","yellow"},
	[76188] = {"blue","red"},
	[76189] = {"blue","yellow"},
})

BigWigs:AddSounds("Ascendant Lord Obsidius", {
	[76188] = "alarm",
})
