-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Thrall", {
	[297574] = {"blue","green","yellow"},
	[297746] = "red",
	[297822] = "orange",
	[304251] = "red",
	[304976] = "red",
	[306828] = "red",
})

BigWigs:AddSounds("Thrall", {
	[297574] = {"alarm","info"},
	[297746] = "alarm",
	[297822] = "long",
	[304251] = "alert",
	[304976] = "warning",
	[306828] = "alarm",
})

BigWigs:AddColors("Oblivion Elemental", {
	[297574] = {"blue","green","yellow"},
})

BigWigs:AddSounds("Oblivion Elemental", {
	[297574] = {"alarm","info"},
})

BigWigs:AddColors("Inquisitor Gnshal", {
	[304976] = "red",
	[307863] = {"blue","yellow"},
})

BigWigs:AddSounds("Inquisitor Gnshal", {
	[304976] = "warning",
	[307863] = "long",
})

BigWigs:AddColors("Vez'okk the Lightless", {
	[306617] = "yellow",
	[306656] = "cyan",
	[306726] = "red",
})

BigWigs:AddSounds("Vez'okk the Lightless", {
	[306617] = "long",
	[306656] = "alert",
	[306726] = "alarm",
})

BigWigs:AddColors("Rexxar", {
	[304251] = "red",
	[304282] = "cyan",
	["adds"] = "yellow",
})

BigWigs:AddSounds("Rexxar", {
	[304251] = "alert",
	[304282] = "long",
	["adds"] = "info",
})

BigWigs:AddColors("Horrific Vision of Orgrimmar Trash", {
	[11641] = {"blue","orange"},
	[296492] = "orange",
	[296510] = "cyan",
	[296718] = "orange",
	[297146] = {"blue","yellow"},
	[297161] = "orange",
	[297237] = "cyan",
	[297302] = "orange",
	[297315] = "red",
	[298033] = "red",
	[298074] = "orange",
	[298502] = "yellow",
	[298510] = {"blue","yellow"},
	[298630] = "yellow",
	[299055] = {"blue","orange"},
	[299110] = "yellow",
	[300351] = "orange",
	[300388] = "red",
	[300530] = "orange",
	[303589] = "orange",
	[304101] = "orange",
	[304165] = {"blue","red","yellow"},
	[304169] = "orange",
	[305236] = "red",
	[305369] = "yellow",
	[305378] = "red",
	[305875] = "red",
	[306001] = "orange",
	[306199] = "yellow",
	[306583] = {"blue","green"},
	[306770] = "orange",
	[307870] = "green",
	[308018] = "orange",
	[308346] = "orange",
	[311390] = "blue",
	[311996] = "cyan",
	[312584] = "yellow",
	[319304] = {"blue","yellow"},
})

BigWigs:AddSounds("Horrific Vision of Orgrimmar Trash", {
	[11641] = "info",
	[296492] = "alarm",
	[296510] = "info",
	[296718] = "alarm",
	[297146] = "alert",
	[297161] = "alarm",
	[297237] = "info",
	[297302] = "alarm",
	[297315] = "alert",
	[298033] = "warning",
	[298074] = "alarm",
	[298502] = "alarm",
	[298510] = "alert",
	[298630] = "alarm",
	[299055] = "alarm",
	[299110] = "info",
	[300351] = "alarm",
	[300388] = "warning",
	[300530] = "info",
	[303589] = "alert",
	[304101] = "alarm",
	[304165] = {"alert","info"},
	[304169] = "alarm",
	[305236] = "alert",
	[305369] = "alarm",
	[305378] = "warning",
	[305875] = "alarm",
	[306001] = "alert",
	[306199] = "alarm",
	[306583] = {"alert","info"},
	[306770] = "alarm",
	[307870] = "info",
	[308018] = "alarm",
	[308346] = "alarm",
	[311390] = "info",
	[311996] = "long",
	[312584] = "info",
	[319304] = "alert",
})
