-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Avanoxx", {
	[438471] = "purple",
	[438473] = "red",
	[438476] = "yellow",
	[446794] = "orange",
})

BigWigs:AddSounds("Avanoxx", {
	[438471] = "alert",
	[438473] = "long",
	[438476] = "info",
	[446794] = "warning",
})

BigWigs:AddColors("Anub'zekt", {
	[433740] = {"blue","yellow"},
	[433766] = {"cyan","green"},
	[435012] = "purple",
	[439506] = {"blue","orange"},
	[442210] = "red",
	["bloodstained_webmage"] = "cyan",
})

BigWigs:AddSounds("Anub'zekt", {
	[433740] = "alert",
	[433766] = {"info","long"},
	[435012] = "alarm",
	[439506] = "alarm",
	[442210] = "alert",
	["bloodstained_webmage"] = "info",
})

BigWigs:AddColors("Ki'katal the Harvester", {
	[432031] = {"blue","yellow"},
	[432117] = "cyan",
	[432130] = "orange",
	[432227] = "red",
	[461487] = "red",
})

BigWigs:AddSounds("Ki'katal the Harvester", {
	[432031] = "info",
	[432117] = "long",
	[432130] = "alarm",
	[432227] = "alert",
	[461487] = "alarm",
})

BigWigs:AddColors("Ara-Kara, City of Echoes Trash", {
	[432967] = "cyan",
	[433002] = "purple",
	[433785] = "purple",
	[433841] = "red",
	[433845] = "orange",
	[434252] = "yellow",
	[434793] = "red",
	[434802] = "red",
	[434824] = "orange",
	[434830] = "blue",
	[436614] = {"blue","orange"},
	[438622] = "yellow",
	[438826] = {"blue","yellow"},
	[438877] = "cyan",
	[439208] = "green",
	[448248] = "red",
	[453161] = "orange",
	[465012] = "yellow",
})

BigWigs:AddSounds("Ara-Kara, City of Echoes Trash", {
	[432967] = {"info","warning"},
	[433002] = "alert",
	[433785] = "alert",
	[433841] = "alert",
	[433845] = "alarm",
	[434252] = "info",
	[434793] = "alert",
	[434802] = "warning",
	[434824] = "alarm",
	[434830] = "underyou",
	[436614] = "warning",
	[438622] = "alarm",
	[438826] = {"alert","underyou"},
	[438877] = "info",
	[439208] = "info",
	[448248] = "alert",
	[453161] = "alarm",
	[465012] = "alert",
})
