-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Witherbark", {
	[-10098] = "orange",
	[164275] = "cyan",
	[164294] = {"blue","yellow"},
	[164357] = "purple",
	[164438] = "cyan",
})

BigWigs:AddSounds("Witherbark", {
	[-10098] = "info",
	[164275] = "long",
	[164294] = {"alert","underyou"},
	[164357] = "alarm",
	[164438] = "info",
})

BigWigs:AddColors("Ancient Protectors", {
	[168082] = {"red","yellow"},
	[427459] = "yellow",
	[427498] = "cyan",
	[427509] = "cyan",
	[427510] = "purple",
	[427513] = "blue",
})

BigWigs:AddSounds("Ancient Protectors", {
	[168082] = "warning",
	[427459] = "warning",
	[427498] = "long",
	[427509] = "long",
	[427510] = "alert",
	[427513] = "underyou",
})

BigWigs:AddColors("Xeri'tac", {
	[-10502] = "cyan",
	[-10492] = "yellow",
	[169233] = "red",
	[169248] = "yellow",
	[169376] = "red",
	[169382] = "orange",
	[172643] = "orange",
	[173080] = "blue",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Xeri'tac", {
	[-10502] = "info",
	[169233] = "alert",
	[169248] = "warning",
	[169376] = "alert",
	[169382] = "alarm",
	[172643] = "alarm",
	[173080] = "alarm",
	["stages"] = "long",
})

BigWigs:AddColors("Archmage Sol", {
	[427899] = "red",
	[428082] = "orange",
	[428139] = "yellow",
})

BigWigs:AddSounds("Archmage Sol", {
	[427899] = "long",
	[428082] = "alarm",
	[428139] = "info",
})

BigWigs:AddColors("Yalnu", {
	[169179] = "orange",
	[169613] = "yellow",
	[169929] = "red",
	[428823] = "cyan",
})

BigWigs:AddSounds("Yalnu", {
	[169179] = "alarm",
	[169613] = "long",
	[169929] = "alarm",
	[428823] = "info",
})

BigWigs:AddColors("The Everbloom Trash", {
	[164886] = {"blue","purple"},
	[164887] = "red",
	[164965] = {"blue","orange","yellow"},
	[165123] = {"blue","red"},
	[165213] = "red",
	[169445] = "red",
	[169494] = {"blue","yellow"},
	[172578] = "orange",
	[426500] = "orange",
	[426845] = "yellow",
	[426974] = "red",
	[427223] = "orange",
})

BigWigs:AddSounds("The Everbloom Trash", {
	[164886] = "alert",
	[164887] = {"alert","warning"},
	[164965] = {"alarm","alert","info"},
	[165123] = {"alarm","alert"},
	[165213] = "alert",
	[169445] = "alert",
	[169494] = {"info","underyou"},
	[172578] = "alarm",
	[426500] = "alarm",
	[426845] = "alarm",
	[426974] = "alarm",
	[427223] = "alert",
})
