-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Faceless One", {
	[458849] = "orange",
	[458853] = "red",
	[458867] = "yellow",
})

BigWigs:AddSounds("Faceless One", {
	[458849] = "alarm",
	[458853] = "alert",
	[458867] = "long",
})

BigWigs:AddColors("Nerl'athekk the Skulking", {
	[440806] = "orange",
	[454762] = "red",
})

BigWigs:AddSounds("Nerl'athekk the Skulking", {
	[440806] = "alarm",
	[454762] = "alert",
})

BigWigs:AddColors("Speaker Xanventh", {
	[458834] = "yellow",
	[458874] = "orange",
	[458879] = {"red","yellow"},
})

BigWigs:AddSounds("Speaker Xanventh", {
	[458834] = "alarm",
	[458874] = "alarm",
	[458879] = {"alert","info"},
})
