-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Echo of Baine", {
	[-4141] = {"green","red"},
	[-4140] = {"blue","red"},
})

BigWigs:AddSounds("Echo of Baine", {
	[-4141] = {"alarm","info"},
	[-4140] = "alert",
})
