-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Akil'zon", {
	[43648] = {"blue","red"},
	[97318] = {"blue","red"},
})

BigWigs:AddSounds("Akil'zon", {
	[43648] = "alert",
	[97318] = "alert",
})

BigWigs:AddColors("Nalorakk", {
	[42398] = {"blue","yellow"},
	[42402] = {"blue","orange"},
	["stages"] = "red",
})

BigWigs:AddSounds("Nalorakk", {
	[42398] = "info",
	[42402] = "alarm",
})

BigWigs:AddColors("Jan'alai", {
	[-2625] = "yellow",
	[-2622] = "orange",
	[97497] = {"blue","red"},
})

BigWigs:AddSounds("Jan'alai", {
	[-2625] = "long",
	[-2622] = "info",
	[97497] = "alert",
})

BigWigs:AddColors("Halazzi", {
	[43139] = "red",
	[43302] = "orange",
	[43303] = {"blue","yellow"},
	[97499] = "orange",
	["stages"] = {"green","yellow"},
})

BigWigs:AddSounds("Halazzi", {
	[43302] = "alert",
	[43303] = "alarm",
	[97499] = "alert",
})

BigWigs:AddColors("Hex Lord Malacrass", {
	[43383] = "red",
	[43421] = {"blue","orange"},
	[43431] = "orange",
	[43451] = "orange",
	[43501] = {"blue","yellow"},
	[43548] = "orange",
})

BigWigs:AddSounds("Hex Lord Malacrass", {
	[43421] = "alarm",
	[43431] = "alarm",
	[43451] = "alarm",
	[43548] = "alarm",
})

BigWigs:AddColors("Daakara", {
	[17207] = "orange",
	[43093] = {"blue","yellow"},
	[43095] = "yellow",
	[43150] = {"blue","red"},
	["stages"] = "red",
})

BigWigs:AddSounds("Daakara", {
	[43093] = "alarm",
	[43095] = "warning",
	[43150] = "alert",
})
