-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Patrol Captain Gerdo", {
	[207261] = "orange",
	[207278] = "yellow",
	[207806] = "yellow",
	[207815] = "cyan",
	[215204] = {"blue","red"},
	[219488] = "red",
})

BigWigs:AddSounds("Patrol Captain Gerdo", {
	[207261] = "alarm",
	[207278] = "long",
	[207806] = "alert",
	[207815] = "info",
	[215204] = {"alert","warning"},
	[219488] = "info",
})

BigWigs:AddColors("Talixae Flamewreath", {
	[207881] = "orange",
	[207906] = "red",
	[208165] = "yellow",
})

BigWigs:AddSounds("Talixae Flamewreath", {
	[207881] = "long",
	[207906] = "info",
	[208165] = "alert",
})

BigWigs:AddColors("Advisor Melandrus", {
	[209602] = "red",
	[209628] = "orange",
	[209676] = "yellow",
	[224333] = {"blue","red","yellow"},
})

BigWigs:AddSounds("Advisor Melandrus", {
	[209602] = "info",
	[209628] = "alarm",
	[209676] = "warning",
	[224333] = "alert",
})

BigWigs:AddColors("Court of Stars Trash", {
	[207979] = "orange",
	[207980] = {"blue","red"},
	[209027] = "purple",
	[209033] = {"orange","yellow"},
	[209378] = "orange",
	[209404] = {"blue","orange","yellow"},
	[209410] = "yellow",
	[209413] = {"blue","orange","red"},
	[209477] = "orange",
	[209485] = "yellow",
	[209495] = "red",
	[209512] = "blue",
	[210261] = "red",
	[211299] = "red",
	[211391] = "blue",
	[211401] = "red",
	[211464] = "red",
	[211470] = {"blue","orange","yellow"},
	[211473] = "purple",
	[212031] = "red",
	[212773] = {"blue","orange","red"},
	[212784] = {"red","yellow"},
	[214688] = "yellow",
	[214690] = {"blue","orange"},
	[214692] = "yellow",
	[214697] = {"blue","cyan","green"},
	[216000] = "yellow",
	[216006] = "yellow",
	[216096] = "yellow",
	[216110] = "yellow",
	[224377] = "red",
	[225100] = "yellow",
	[397892] = "red",
	[397897] = "red",
	[397907] = {"blue","orange"},
	["announce_buff_items"] = "cyan",
	["spy_helper"] = {"cyan","green"},
})

BigWigs:AddSounds("Court of Stars Trash", {
	[207979] = "alarm",
	[207980] = {"alert","long"},
	[209027] = "alarm",
	[209033] = {"alert","info"},
	[209378] = "alarm",
	[209404] = "alert",
	[209410] = "alert",
	[209413] = {"alarm","alert"},
	[209477] = "alarm",
	[209485] = "alert",
	[209495] = "alarm",
	[209512] = "underyou",
	[210261] = "warning",
	[211299] = "alarm",
	[211391] = "underyou",
	[211401] = "alarm",
	[211464] = "alarm",
	[211470] = "alert",
	[211473] = "alarm",
	[212031] = "alarm",
	[212773] = {"alarm","warning"},
	[212784] = {"alarm","long"},
	[214688] = "alert",
	[214690] = "alert",
	[214692] = "alert",
	[214697] = {"info","long"},
	[216000] = "alert",
	[216006] = "alert",
	[216096] = "alert",
	[216110] = "alert",
	[224377] = "alarm",
	[225100] = "alert",
	[397892] = "alarm",
	[397897] = "alert",
	[397907] = "alarm",
	["announce_buff_items"] = "info",
	["spy_helper"] = "info",
})
