-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("The Maker", {
	[30923] = {"blue","red"},
})

BigWigs:AddSounds("The Maker", {
})

BigWigs:AddColors("Broggok", {
	[30916] = "blue",
})

BigWigs:AddSounds("Broggok", {
	[30916] = "alert",
})

BigWigs:AddColors("Keli'dan the Breaker", {
	[-5388] = "red",
})

BigWigs:AddSounds("Keli'dan the Breaker", {
})
