-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Falric", {
	[72422] = {"blue","orange"},
	[72426] = {"blue","red"},
})

BigWigs:AddSounds("Falric", {
	[72426] = "warning",
})

BigWigs:AddColors("Marwyn", {
	[72363] = "red",
	[72368] = {"blue","yellow"},
	[72383] = {"blue","orange"},
})

BigWigs:AddSounds("Marwyn", {
})
