-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Globgrog", {
	[324490] = "yellow",
	[324527] = "red",
	[324667] = "orange",
})

BigWigs:AddSounds("Globgrog", {
	[324490] = "long",
	[324527] = "warning",
	[324667] = "alarm",
})

BigWigs:AddColors("Doctor Ickus", {
	[67382] = "yellow",
	[321406] = "orange",
	[322358] = "red",
	[329110] = {"blue","purple","yellow"},
	[329217] = "yellow",
	[332617] = "cyan",
})

BigWigs:AddSounds("Doctor Ickus", {
	[67382] = "long",
	[321406] = "warning",
	[322358] = "alarm",
	[329110] = {"alert","info"},
	[329217] = "alarm",
	[332617] = "info",
})

BigWigs:AddColors("Domina Venomblade", {
	[325245] = {"blue","yellow"},
	[325552] = {"blue","purple"},
	[332313] = "cyan",
	[336258] = "blue",
	[336301] = {"blue","green","red"},
})

BigWigs:AddSounds("Domina Venomblade", {
	[325245] = "warning",
	[325552] = "alert",
	[332313] = "long",
	[336258] = "alarm",
	[336301] = {"alarm","info"},
})

BigWigs:AddColors("Margrave Stradama", {
	[322232] = "yellow",
	[322304] = "cyan",
	[322475] = "green",
	["stages"] = "green",
})

BigWigs:AddSounds("Margrave Stradama", {
	[322232] = "alert",
	[322304] = "info",
	[322475] = "long",
})

BigWigs:AddColors("Plaguefall Trash", {
	[318949] = "red",
	[319898] = "red",
	[320512] = {"blue","yellow"},
	[320517] = "yellow",
	[321935] = "red",
	[323572] = "red",
	[327233] = "red",
	[327515] = {"blue","yellow"},
	[327584] = "yellow",
	[327882] = {"blue","yellow"},
	[327995] = "red",
	[328016] = "orange",
	[328177] = "orange",
	[328180] = {"blue","orange","yellow"},
	[328338] = "red",
	[328429] = {"blue","yellow"},
	[328475] = "red",
	[329239] = "orange",
	[330069] = {"blue","yellow"},
	[330092] = {"blue","green","orange"},
	[330403] = "red",
	[330786] = "orange",
	[330816] = "yellow",
	[335882] = {"blue","green","yellow"},
	[336451] = "orange",
	["summon_stealthlings"] = "red",
})

BigWigs:AddSounds("Plaguefall Trash", {
	[318949] = "alarm",
	[319898] = "alarm",
	[320512] = "alert",
	[320517] = "alert",
	[321935] = "alarm",
	[323572] = "alarm",
	[327233] = "alarm",
	[327515] = "alert",
	[327584] = "long",
	[327882] = "alert",
	[327995] = "alarm",
	[328016] = "alert",
	[328177] = "alert",
	[328180] = {"alert","info"},
	[328338] = "alert",
	[328429] = "alert",
	[328475] = "alarm",
	[329239] = "alert",
	[330069] = {"alert","warning"},
	[330092] = {"info","long"},
	[330403] = "alarm",
	[330786] = "alert",
	[330816] = "info",
	[335882] = {"alert","info","underyou","warning"},
	[336451] = "alert",
	["summon_stealthlings"] = "warning",
})
