-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Shirrak the Dead Watcher", {
	[-5041] = {"blue","yellow"},
})

BigWigs:AddSounds("Shirrak the Dead Watcher", {
})

BigWigs:AddColors("Exarch Maladaar", {
	[32346] = {"blue","orange"},
	["avatar"] = {"red","yellow"},
})

BigWigs:AddSounds("Exarch Maladaar", {
	["avatar"] = "info",
})

BigWigs:AddColors("Watchkeeper Gargolmar", {
	[8362] = {"blue","yellow"},
	[11639] = {"blue","orange"},
	[12039] = "red",
	[14032] = {"blue","orange"},
	[36814] = {"blue","purple"},
})

BigWigs:AddSounds("Watchkeeper Gargolmar", {
	[8362] = {"alarm","warning"},
	[12039] = "warning",
})

BigWigs:AddColors("Omor the Unscarred", {
	[30695] = {"blue","orange"},
})

BigWigs:AddSounds("Omor the Unscarred", {
})

BigWigs:AddColors("Vazruden", {
	["stages"] = "cyan",
})

BigWigs:AddSounds("Vazruden", {
})

BigWigs:AddColors("Selin Fireheart", {
	[44320] = "red",
})

BigWigs:AddSounds("Selin Fireheart", {
	[44320] = "info",
})

BigWigs:AddColors("Vexallus", {
	[-5085] = "red",
	[44335] = {"blue","orange"},
})

BigWigs:AddSounds("Vexallus", {
})

BigWigs:AddColors("Priestess Delrissa", {
	[13323] = {"blue","orange"},
	[27621] = "yellow",
	[44141] = {"blue","red"},
	[44178] = "red",
	[46192] = {"blue","yellow"},
	[46193] = {"blue","yellow"},
})

BigWigs:AddSounds("Priestess Delrissa", {
})

BigWigs:AddColors("Kael'thas Sunstrider Magisters' Terrace", {
	[-5180] = "yellow",
	[-5167] = "red",
	[36819] = "red",
	[44194] = "orange",
	[44224] = "green",
})

BigWigs:AddSounds("Kael'thas Sunstrider Magisters' Terrace", {
	[36819] = "long",
	[44194] = "info",
})

BigWigs:AddColors("Magisters' Terrace Trash", {
	[44475] = {"blue","orange"},
	[44644] = "orange",
	[44765] = {"blue","yellow"},
})

BigWigs:AddSounds("Magisters' Terrace Trash", {
	[44475] = "alert",
	[44644] = {"alert","warning"},
	[44765] = "alarm",
})

BigWigs:AddColors("Pandemonius", {
	[38759] = "yellow",
})

BigWigs:AddSounds("Pandemonius", {
})

BigWigs:AddColors("Tavarok", {
	[32361] = {"blue","red"},
})

BigWigs:AddSounds("Tavarok", {
})

BigWigs:AddColors("Yor", {
	[36405] = "red",
	[38361] = "yellow",
})

BigWigs:AddSounds("Yor", {
	[36405] = "info",
	[38361] = "long",
})

BigWigs:AddColors("Nexus-Prince Shaffar", {
	[32365] = {"blue","red"},
})

BigWigs:AddSounds("Nexus-Prince Shaffar", {
	[32365] = "alert",
})

BigWigs:AddColors("Mana-Tombs Trash", {
	[13323] = {"blue","yellow"},
	[22883] = "orange",
	[33871] = {"blue","yellow"},
	[34322] = {"blue","red"},
	[34922] = {"blue","red"},
	[34925] = {"blue","yellow"},
})

BigWigs:AddSounds("Mana-Tombs Trash", {
	[13323] = "alert",
	[22883] = "alert",
	[33871] = "alarm",
	[34322] = "alert",
	[34922] = "alert",
	[34925] = "alert",
})

BigWigs:AddColors("Lieutenant Drake", {
	[31910] = "blue",
	[31911] = {"blue","orange"},
})

BigWigs:AddSounds("Lieutenant Drake", {
	[31910] = "alarm",
	[31911] = "warning",
})

BigWigs:AddColors("Captain Skarloc", {
	[13005] = {"blue","red"},
	[29427] = "orange",
	[38385] = "blue",
})

BigWigs:AddSounds("Captain Skarloc", {
	[13005] = "warning",
	[29427] = "alert",
	[38385] = "alarm",
})

BigWigs:AddColors("Epoch Hunter", {
	[31914] = "blue",
	[33834] = "orange",
})

BigWigs:AddSounds("Epoch Hunter", {
	[31914] = "warning",
	[33834] = "alert",
})

BigWigs:AddColors("Old Hillsbrad Foothills Trash", {
	["incendiary_bombs"] = "cyan",
})

BigWigs:AddSounds("Old Hillsbrad Foothills Trash", {
	["incendiary_bombs"] = "info",
})

BigWigs:AddColors("Darkweaver Syth", {
	[-5235] = "red",
	[12548] = {"blue","orange"},
	[15659] = {"blue","yellow"},
})

BigWigs:AddSounds("Darkweaver Syth", {
})

BigWigs:AddColors("Anzu", {
	[-5253] = {"green","orange"},
	[-5252] = {"blue","yellow"},
	[40184] = "red",
	[40303] = {"blue","yellow"},
})

BigWigs:AddSounds("Anzu", {
	[-5252] = "alert",
	[40184] = "warning",
	[40303] = "alarm",
})

BigWigs:AddColors("Talon King Ikiss", {
	[35032] = {"blue","red"},
	[38197] = "orange",
	[38245] = {"blue","yellow"},
})

BigWigs:AddSounds("Talon King Ikiss", {
	[35032] = "alarm",
	[38197] = "warning",
})

BigWigs:AddColors("Ambassador Hellmaw", {
})

BigWigs:AddSounds("Ambassador Hellmaw", {
})

BigWigs:AddColors("Blackheart the Inciter", {
	[33676] = {"red","yellow"},
})

BigWigs:AddSounds("Blackheart the Inciter", {
	[33676] = "alarm",
})

BigWigs:AddColors("Grandmaster Vorpil", {
	[-5267] = "orange",
	[38791] = {"blue","red"},
})

BigWigs:AddSounds("Grandmaster Vorpil", {
})

BigWigs:AddColors("Murmur", {
	[33923] = "red",
	[38794] = {"blue","yellow"},
})

BigWigs:AddSounds("Murmur", {
	[38794] = "alarm",
})

BigWigs:AddColors("Zereketh the Unbound", {
	[36119] = "blue",
	[36123] = {"blue","orange"},
	[39005] = "red",
})

BigWigs:AddSounds("Zereketh the Unbound", {
	[36119] = "alert",
})

BigWigs:AddColors("Dalliah the Doomsayer", {
	[36175] = {"blue","red"},
	[39009] = {"blue","yellow"},
	[39013] = "orange",
})

BigWigs:AddSounds("Dalliah the Doomsayer", {
	[36175] = "alert",
})

BigWigs:AddColors("Wrath-Scryer Soccothrates", {
	[-5293] = {"blue","orange","red"},
	[35759] = {"blue","yellow"},
})

BigWigs:AddSounds("Wrath-Scryer Soccothrates", {
})

BigWigs:AddColors("Harbinger Skyriss", {
	[-5335] = {"cyan","green"},
	[36924] = {"blue","red"},
	[37162] = {"blue","orange"},
	[39415] = {"blue","yellow"},
})

BigWigs:AddSounds("Harbinger Skyriss", {
})

BigWigs:AddColors("The Arcatraz Trash", {
	[36700] = {"blue","orange"},
	[36778] = {"blue","yellow"},
	[36866] = {"blue","red"},
	[36886] = {"blue","orange"},
	[38815] = "yellow",
	[38903] = "red",
})

BigWigs:AddSounds("The Arcatraz Trash", {
	[36700] = "alert",
	[36778] = "alarm",
	[36866] = "warning",
	[36886] = "long",
	[38815] = "alarm",
	[38903] = "warning",
})

BigWigs:AddColors("Chrono Lord Deja", {
})

BigWigs:AddSounds("Chrono Lord Deja", {
})

BigWigs:AddColors("Temporus", {
	[31458] = "red",
	[38592] = "orange",
})

BigWigs:AddSounds("Temporus", {
	[31458] = "warning",
})

BigWigs:AddColors("Aeonus", {
	[37605] = "orange",
})

BigWigs:AddSounds("Aeonus", {
})

BigWigs:AddColors("The Black Morass Trash", {
	["wave"] = "yellow",
})

BigWigs:AddSounds("The Black Morass Trash", {
	["wave"] = "info",
})

BigWigs:AddColors("The Maker", {
	[30923] = {"blue","red"},
})

BigWigs:AddSounds("The Maker", {
})

BigWigs:AddColors("Broggok", {
	[30916] = "blue",
})

BigWigs:AddSounds("Broggok", {
	[30916] = "alert",
})

BigWigs:AddColors("Keli'dan the Breaker", {
	[-5388] = "red",
})

BigWigs:AddSounds("Keli'dan the Breaker", {
})

BigWigs:AddColors("Commander Sarannis", {
	[-5411] = {"cyan","yellow"},
	[34794] = {"blue","red"},
	[35096] = "orange",
})

BigWigs:AddSounds("Commander Sarannis", {
	[-5411] = "info",
	[35096] = {"alarm","warning"},
})

BigWigs:AddColors("High Botanist Freywinn", {
	[34550] = {"green","red"},
	[34752] = {"blue","orange"},
})

BigWigs:AddSounds("High Botanist Freywinn", {
	[34550] = {"info","long"},
	[34752] = "alarm",
})

BigWigs:AddColors("Thorngrin the Tender", {
	[34659] = {"blue","red"},
	[34661] = {"blue","yellow"},
	[34670] = {"blue","orange"},
})

BigWigs:AddSounds("Thorngrin the Tender", {
	[34659] = {"alert","long"},
	[34670] = "warning",
})

BigWigs:AddColors("Laj", {
	[34697] = {"blue","red"},
})

BigWigs:AddSounds("Laj", {
})

BigWigs:AddColors("Warp Splinter", {
	[-5478] = {"green","red"},
	[34716] = {"blue","orange"},
})

BigWigs:AddSounds("Warp Splinter", {
	[-5478] = {"alarm","info"},
	[34716] = "alert",
})

BigWigs:AddColors("Mechano-Lord Capacitus", {
	[35158] = {"green","orange"},
	[35159] = {"green","orange"},
	[39096] = {"cyan","orange","red"},
})

BigWigs:AddSounds("Mechano-Lord Capacitus", {
	[39096] = "info",
})

BigWigs:AddColors("Gatewatcher Iron-Hand", {
	[35311] = {"blue","orange"},
	[39193] = "red",
	[39194] = {"blue","yellow"},
})

BigWigs:AddSounds("Gatewatcher Iron-Hand", {
	[35311] = "alarm",
	[39194] = {"alert","long"},
})

BigWigs:AddColors("Gatewatcher Gyro-Kill", {
	[35311] = {"blue","orange"},
	[39193] = "red",
})

BigWigs:AddSounds("Gatewatcher Gyro-Kill", {
	[35311] = "alarm",
})

BigWigs:AddColors("Nethermancer Sepethrea", {
	[-5488] = {"blue","cyan"},
	[35250] = {"blue","orange"},
	[35312] = "blue",
	[35314] = {"blue","red"},
	["fixate"] = {"blue","yellow"},
})

BigWigs:AddSounds("Nethermancer Sepethrea", {
	[-5488] = {"alert","info"},
	[35250] = "alarm",
	[35312] = "alert",
	[35314] = "warning",
	["fixate"] = "long",
})

BigWigs:AddColors("Pathaleon the Calculator", {
	[35280] = {"blue","red"},
	[35285] = "red",
})

BigWigs:AddSounds("Pathaleon the Calculator", {
})

BigWigs:AddColors("Grand Warlock Nethekurse", {
	[30496] = "blue",
	[30500] = {"blue","orange"},
	[30502] = {"green","red"},
})

BigWigs:AddSounds("Grand Warlock Nethekurse", {
	[30496] = "alarm",
	[30502] = "info",
})

BigWigs:AddColors("Blood Guard Porung", {
	[15496] = "blue",
})

BigWigs:AddSounds("Blood Guard Porung", {
	[15496] = "alert",
})

BigWigs:AddColors("Warbringer O'mrogg", {
	[-5894] = {"blue","yellow"},
})

BigWigs:AddSounds("Warbringer O'mrogg", {
	[-5894] = "warning",
})

BigWigs:AddColors("Warchief Kargath Bladefist", {
	[-5899] = "yellow",
})

BigWigs:AddSounds("Warchief Kargath Bladefist", {
	[-5899] = "warning",
})

BigWigs:AddColors("The Shattered Halls Trash", {
	[12542] = {"blue","red"},
	[15615] = {"blue","yellow"},
	[30980] = {"blue","yellow"},
	[35943] = "orange",
	[36020] = {"blue","red"},
	[36033] = {"blue","yellow"},
})

BigWigs:AddSounds("The Shattered Halls Trash", {
	[12542] = "alert",
	[15615] = "alarm",
	[30980] = "alarm",
	[35943] = "long",
	[36033] = "alarm",
})

BigWigs:AddColors("Mennu the Betrayer", {
	[31991] = "yellow",
	[34980] = "orange",
})

BigWigs:AddSounds("Mennu the Betrayer", {
})

BigWigs:AddColors("Rokmar the Crackler", {
	[31948] = {"blue","yellow"},
	[34970] = {"green","red"},
	[38801] = {"blue","orange"},
})

BigWigs:AddSounds("Rokmar the Crackler", {
})

BigWigs:AddColors("Quagmirran", {
	[38153] = {"blue","red"},
})

BigWigs:AddSounds("Quagmirran", {
})

BigWigs:AddColors("The Slave Pens Trash", {
	[15655] = {"blue","red"},
	[31554] = {"blue","yellow"},
	[32173] = {"blue","orange"},
	[33787] = {"blue","yellow"},
	[34984] = {"blue","red"},
	[39378] = "orange",
})

BigWigs:AddSounds("The Slave Pens Trash", {
	[15655] = "alarm",
	[31554] = "long",
	[32173] = "info",
	[33787] = "info",
	[34984] = "alert",
	[39378] = "alarm",
})

BigWigs:AddColors("Ahune", {
	[45954] = {"green","red"},
	["warmup"] = "cyan",
})

BigWigs:AddSounds("Ahune", {
	[45954] = {"info","long"},
	["warmup"] = "info",
})

BigWigs:AddColors("Hydromancer Thespia", {
	[25033] = "blue",
	[31481] = {"blue","yellow"},
	[31718] = {"blue","red"},
})

BigWigs:AddSounds("Hydromancer Thespia", {
	[25033] = "alert",
	[31481] = "alarm",
	[31718] = "warning",
})

BigWigs:AddColors("Mekgineer Steamrigger", {
	[31485] = {"blue","orange"},
	["mechanics"] = {"red","yellow"},
})

BigWigs:AddSounds("Mekgineer Steamrigger", {
	[31485] = "alert",
})

BigWigs:AddColors("Warlord Kalithresh", {
	[-6003] = "red",
	[16172] = {"blue","yellow"},
	[36453] = {"blue","orange"},
})

BigWigs:AddSounds("Warlord Kalithresh", {
	[-6003] = "warning",
	[16172] = "alarm",
	[36453] = "long",
})

BigWigs:AddColors("Hungarfen", {
	[-6008] = {"blue","orange","yellow"},
	[34168] = {"blue","orange"},
})

BigWigs:AddSounds("Hungarfen", {
	[-6008] = {"alarm","alert"},
	[34168] = {"info","underyou","warning"},
})

BigWigs:AddColors("Ghaz'an", {
	[15716] = {"green","orange"},
	[34268] = {"blue","red"},
	[38737] = "blue",
})

BigWigs:AddSounds("Ghaz'an", {
	[15716] = {"info","long"},
	[34268] = "warning",
	[38737] = "alert",
})

BigWigs:AddColors("Swamplord Musel'ek", {
	[31429] = {"blue","red"},
	[31615] = {"blue","yellow"},
	[34971] = {"blue","orange"},
})

BigWigs:AddSounds("Swamplord Musel'ek", {
	[31429] = "warning",
	[31615] = "alarm",
	[34971] = "long",
})

BigWigs:AddColors("The Black Stalker", {
	[31704] = {"blue","orange"},
	[31715] = {"blue","green","red"},
	[31717] = {"blue","yellow"},
})

BigWigs:AddSounds("The Black Stalker", {
	[31715] = "warning",
})
