-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Tomb-Raider Drywhisker", {
	[449242] = {"blue","yellow"},
	[449295] = "orange",
	[449339] = {"green","red"},
})

BigWigs:AddSounds("Tomb-Raider Drywhisker", {
	[449242] = {"long","underyou"},
	[449295] = "alarm",
	[449339] = {"alert","info"},
})
