-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Pandemonius", {
	[38759] = "yellow",
})

BigWigs:AddSounds("Pandemonius", {
})

BigWigs:AddColors("Tavarok", {
	[32361] = {"blue","red"},
})

BigWigs:AddSounds("Tavarok", {
})

BigWigs:AddColors("Yor", {
	[36405] = "red",
	[38361] = "yellow",
})

BigWigs:AddSounds("Yor", {
	[36405] = "info",
	[38361] = "long",
})

BigWigs:AddColors("Nexus-Prince Shaffar", {
	[32365] = {"blue","red"},
})

BigWigs:AddSounds("Nexus-Prince Shaffar", {
	[32365] = "alert",
})

BigWigs:AddColors("Mana-Tombs Trash", {
	[13323] = {"blue","yellow"},
	[22883] = "orange",
	[33871] = {"blue","yellow"},
	[34322] = {"blue","red"},
	[34922] = {"blue","red"},
	[34925] = {"blue","yellow"},
})

BigWigs:AddSounds("Mana-Tombs Trash", {
	[13323] = "alert",
	[22883] = "alert",
	[33871] = "alarm",
	[34322] = "alert",
	[34922] = "alert",
	[34925] = "alert",
})
