-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("An Affront of Challengers", {
	[320069] = "purple",
	[320182] = "yellow",
	[333231] = {"blue","yellow"},
	[1215600] = {"blue","red"},
	[1215738] = "orange",
	[1215741] = "red",
})

BigWigs:AddSounds("An Affront of Challengers", {
	[320069] = "alert",
	[320182] = "long",
	[333231] = "info",
	[1215600] = {"alert","info"},
	[1215738] = "alarm",
	[1215741] = "info",
})

BigWigs:AddColors("Gorechop", {
	[318406] = "orange",
	[321447] = "blue",
	[322795] = "yellow",
	[323515] = "purple",
	[323750] = "blue",
})

BigWigs:AddSounds("Gorechop", {
	[318406] = "alarm",
	[321447] = "underyou",
	[322795] = "long",
	[323515] = "alert",
	[323750] = "underyou",
})

BigWigs:AddColors("Xav the Unfallen", {
	[317231] = "red",
	[320114] = {"blue","cyan"},
	[320644] = "purple",
	[320729] = "orange",
	[331618] = {"green","red"},
	[339415] = "yellow",
})

BigWigs:AddSounds("Xav the Unfallen", {
	[317231] = "alarm",
	[320114] = {"info","long"},
	[320644] = "alert",
	[320729] = "alarm",
	[331618] = {"alert","info"},
	[339415] = "warning",
})

BigWigs:AddColors("Kul'tharok", {
	[473513] = "yellow",
	[474087] = "purple",
	[474298] = "cyan",
	[1215787] = {"blue","orange"},
	[1223803] = {"blue","red"},
})

BigWigs:AddSounds("Kul'tharok", {
	[473513] = "long",
	[474087] = "alarm",
	[474298] = "warning",
	[1215787] = {"info","underyou"},
	[1223803] = "alert",
})

BigWigs:AddColors("Mordretha, the Endless Empress", {
	[323608] = "orange",
	[323825] = "yellow",
	[323831] = {"blue","yellow"},
	[324079] = "purple",
	[324449] = "red",
	[339550] = "orange",
	[339573] = "cyan",
	[339706] = "red",
})

BigWigs:AddSounds("Mordretha, the Endless Empress", {
	[323608] = "alarm",
	[323825] = "alert",
	[323831] = {"info","warning"},
	[324079] = "alert",
	[324449] = "info",
	[339550] = "alarm",
	[339573] = "long",
	[339706] = "alarm",
})

BigWigs:AddColors("Theater Of Pain Trash", {
	[317605] = "orange",
	[321039] = "orange",
	[330532] = {"blue","yellow"},
	[330562] = "red",
	[330565] = "purple",
	[330586] = "purple",
	[330614] = {"blue","orange","yellow"},
	[330697] = {"blue","purple"},
	[330716] = "orange",
	[330725] = {"blue","yellow"},
	[330868] = "red",
	[331223] = {"blue","orange"},
	[331237] = "yellow",
	[331288] = "purple",
	[331316] = "purple",
	[333241] = "orange",
	[333294] = "orange",
	[333299] = {"blue","yellow"},
	[333827] = "yellow",
	[333845] = "purple",
	[333861] = {"blue","red"},
	[334023] = "orange",
	[336995] = {"blue","red"},
	[341902] = {"red","yellow"},
	[341949] = {"blue","yellow"},
	[341969] = "orange",
	[341977] = "red",
	[342103] = "blue",
	[342135] = "yellow",
	[342675] = "red",
	[1215850] = "red",
})

BigWigs:AddSounds("Theater Of Pain Trash", {
	[317605] = "alarm",
	[321039] = "alarm",
	[330532] = "alert",
	[330562] = "warning",
	[330565] = "alert",
	[330586] = "alert",
	[330614] = {"alarm","info"},
	[330697] = "alert",
	[330716] = "long",
	[330725] = "alert",
	[330868] = {"alert","warning"},
	[331223] = {"alarm","underyou"},
	[331237] = "long",
	[331288] = "alert",
	[331316] = "alert",
	[333241] = {"alarm","warning"},
	[333294] = "alarm",
	[333299] = "info",
	[333827] = "alert",
	[333845] = "alert",
	[333861] = {"alert","warning"},
	[334023] = "alarm",
	[336995] = {"alarm","underyou"},
	[341902] = {"alert","warning"},
	[341949] = "alert",
	[341969] = "warning",
	[341977] = "alert",
	[342103] = "underyou",
	[342135] = "warning",
	[342675] = "alert",
	[1215850] = "alarm",
})
