-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Zo'phex the Sentinel", {
	[345770] = {"blue","green"},
	[345990] = {"blue","green","red"},
	[346204] = {"blue","yellow"},
	[347949] = {"blue","orange"},
})

BigWigs:AddSounds("Zo'phex the Sentinel", {
	[345770] = {"alarm","info"},
	[345990] = {"alert","info","warning"},
	[346204] = {"alert","underyou"},
	[347949] = {"alert","warning"},
})

BigWigs:AddColors("The Grand Menagerie", {
	[349627] = {"blue","yellow"},
	[349663] = "red",
	[349797] = "red",
	[349934] = "red",
	[349954] = {"blue","yellow"},
	[349987] = "red",
	[350010] = {"blue","green"},
	[350086] = {"blue","red"},
	[350101] = {"blue","orange"},
})

BigWigs:AddSounds("The Grand Menagerie", {
	[349627] = "info",
	[349663] = "alarm",
	[349797] = "alarm",
	[349934] = "alert",
	[349954] = "alert",
	[349987] = "alarm",
	[350010] = "info",
	[350086] = {"alarm","underyou"},
	[350101] = "alert",
})

BigWigs:AddColors("Mailroom Mayhem", {
	[346286] = "yellow",
	[346296] = "green",
	[346742] = "red",
	[346947] = "yellow",
	[346962] = {"blue","orange"},
	["delivery_portal"] = "cyan",
})

BigWigs:AddSounds("Mailroom Mayhem", {
	[346286] = "alert",
	[346296] = "info",
	[346742] = "alarm",
	[346947] = "long",
	[346962] = "alert",
	["delivery_portal"] = "info",
})

BigWigs:AddColors("Myza's Oasis", {
	[350916] = "red",
	[350919] = "orange",
	[350922] = "orange",
	[353706] = "red",
	[353783] = "yellow",
	[353835] = "orange",
	[355438] = "red",
	[356482] = "yellow",
	[359028] = "red",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Myza's Oasis", {
	[350916] = "alarm",
	[350919] = "alert",
	[350922] = "warning",
	[353706] = "alert",
	[353783] = "alert",
	[353835] = "alarm",
	[355438] = "alarm",
	[356482] = "info",
	[359028] = "alarm",
	["stages"] = "long",
})

BigWigs:AddColors("So'azmi", {
	[347249] = "yellow",
	[347610] = "red",
	[347623] = "orange",
	[357188] = "orange",
})

BigWigs:AddSounds("So'azmi", {
	[347249] = "info",
	[347610] = "warning",
	[347623] = "alarm",
	[357188] = "alert",
})

BigWigs:AddColors("Hylbrande", {
	[346116] = "purple",
	[346766] = "cyan",
	[346959] = {"blue","orange"},
	[347094] = "red",
	[353312] = "yellow",
	["vault_purifier"] = "yellow",
})

BigWigs:AddSounds("Hylbrande", {
	[346116] = "alarm",
	[346766] = "long",
	[346959] = {"alert","underyou","warning"},
	[347094] = "alarm",
	[353312] = "info",
	["vault_purifier"] = "info",
})

BigWigs:AddColors("Timecap'n Hooktail", {
	[347149] = "red",
	[347151] = "orange",
	[347371] = "yellow",
	[350517] = "orange",
	[352345] = {"blue","red"},
	[354334] = {"blue","orange"},
})

BigWigs:AddSounds("Timecap'n Hooktail", {
	[347149] = "alarm",
	[347151] = "alert",
	[347371] = "alert",
	[350517] = "alert",
	[352345] = "alarm",
	[354334] = "alert",
})

BigWigs:AddColors("So'leah", {
	[350796] = "orange",
	[350804] = {"blue","green"},
	[351086] = "yellow",
	[351096] = "orange",
	[351119] = "red",
	[351124] = "yellow",
	[353635] = "red",
	["stages"] = "cyan",
})

BigWigs:AddSounds("So'leah", {
	[350796] = "alert",
	[350804] = "info",
	[351086] = "long",
	[351096] = "alert",
	[351119] = "warning",
	[351124] = "alert",
	[353635] = "alarm",
	["stages"] = "long",
})

BigWigs:AddColors("Tazavesh Trash", {
	[347721] = "yellow",
	[355057] = {"orange","red"},
	[355132] = {"red","yellow"},
	[355429] = "yellow",
	[355477] = "purple",
	[355480] = {"blue","red"},
	[355577] = {"blue","red"},
	[355584] = "yellow",
	[355637] = {"blue","yellow"},
	[355642] = "yellow",
	[355782] = "red",
	[355934] = {"orange","red"},
	[355980] = "yellow",
	[356001] = {"blue","orange"},
	[356031] = "yellow",
	[356133] = {"orange","red"},
	[356324] = "red",
	[356404] = "red",
	[356407] = {"orange","yellow"},
	[356548] = "yellow",
	[356929] = "orange",
	[356942] = {"blue","purple","yellow"},
	[356967] = "purple",
	[357029] = "blue",
	[357226] = "red",
	[357238] = "yellow",
	[357260] = "yellow",
	[357284] = "red",
	[357512] = {"blue","red"},
	["trading_game"] = "green",
})

BigWigs:AddSounds("Tazavesh Trash", {
	[347721] = "warning",
	[355057] = {"alert","warning"},
	[355132] = {"alert","warning"},
	[355429] = "warning",
	[355477] = "alert",
	[355480] = {"alert","warning"},
	[355577] = {"alert","underyou"},
	[355584] = "warning",
	[355637] = {"info","warning"},
	[355642] = "warning",
	[355782] = "warning",
	[355934] = {"alert","warning"},
	[355980] = "warning",
	[356001] = {"underyou","warning"},
	[356031] = "alert",
	[356133] = {"alert","warning"},
	[356324] = "warning",
	[356404] = "alarm",
	[356407] = {"alert","warning"},
	[356548] = "alert",
	[356929] = "info",
	[356942] = "alert",
	[356967] = "alert",
	[357029] = "alarm",
	[357226] = "alarm",
	[357238] = "warning",
	[357260] = "warning",
	[357284] = "warning",
	[357512] = {"alert","warning"},
	["trading_game"] = "info",
})
