-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Slad'ran", {
	[59842] = {"blue","yellow"},
})

BigWigs:AddSounds("Slad'ran", {
	[59842] = {"alarm","info"},
})

BigWigs:AddColors("Drakkari Colossus", {
	[59451] = "blue",
	["stages"] = {"red","yellow"},
})

BigWigs:AddSounds("Drakkari Colossus", {
	[59451] = "underyou",
	["stages"] = "long",
})

BigWigs:AddColors("Moorabi", {
	[55098] = {"green","orange"},
})

BigWigs:AddSounds("Moorabi", {
	[55098] = "warning",
})

BigWigs:AddColors("Eck the Ferocious", {
	[55817] = "blue",
})

BigWigs:AddSounds("Eck the Ferocious", {
	[55817] = "info",
})

BigWigs:AddColors("Gal'darah", {
	[59825] = "blue",
	[59827] = {"blue","yellow"},
	["forms"] = "yellow",
})

BigWigs:AddSounds("Gal'darah", {
	[59825] = "alarm",
	[59827] = "info",
})
