-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Corborus", {
	[86881] = "blue",
	["burrow"] = {"red","yellow"},
})

BigWigs:AddSounds("Corborus", {
	[86881] = "alarm",
	["burrow"] = "info",
})

BigWigs:AddColors("Slabhide", {
	[80801] = "blue",
	[92265] = "red",
})

BigWigs:AddSounds("Slabhide", {
	[80801] = "alarm",
	[92265] = "alert",
})

BigWigs:AddColors("Ozruk", {
	[78903] = "orange",
	[78939] = "red",
	[80467] = "yellow",
	[92426] = "red",
})

BigWigs:AddSounds("Ozruk", {
	[78903] = "alarm",
	[78939] = "alarm",
	[92426] = "alert",
})

BigWigs:AddColors("High Priestess Azil", {
	[79050] = "red",
	[79345] = {"blue","yellow"},
})

BigWigs:AddSounds("High Priestess Azil", {
	[79050] = "alert",
})
