-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Rokmora", {
	[188114] = "yellow",
	[188169] = "purple",
	[192800] = "blue",
	[198024] = "orange",
})

BigWigs:AddSounds("Rokmora", {
	[188114] = "alert",
	[188169] = "alarm",
	[192800] = "underyou",
	[198024] = "alert",
})

BigWigs:AddColors("Ularogg Cragshaper", {
	[193375] = "orange",
	[198428] = "red",
	[198496] = "purple",
	[198564] = {"cyan","green"},
})

BigWigs:AddSounds("Ularogg Cragshaper", {
	[193375] = "alert",
	[198428] = "warning",
	[198496] = "alert",
	[198564] = {"info","long"},
})

BigWigs:AddColors("Naraxas", {
	[198963] = "purple",
	[199178] = {"blue","green","purple","red"},
	[199246] = {"blue","red"},
	[199775] = "yellow",
	[199817] = "cyan",
	[205549] = "red",
	[210150] = "orange",
})

BigWigs:AddSounds("Naraxas", {
	[198963] = "warning",
	[199178] = {"alarm","alert","info","warning"},
	[199246] = "long",
	[199775] = "long",
	[199817] = "info",
	[205549] = "alert",
	[210150] = "alert",
})

BigWigs:AddColors("Dargrul", {
	[200154] = {"blue","red"},
	[200404] = "red",
	[200551] = "yellow",
	[200637] = "yellow",
	[200672] = "green",
	[200700] = "orange",
	[200732] = "purple",
	[216407] = "blue",
})

BigWigs:AddSounds("Dargrul", {
	[200154] = {"alert","warning"},
	[200404] = "long",
	[200551] = "alarm",
	[200637] = "alert",
	[200672] = "info",
	[200700] = "alarm",
	[200732] = "alert",
	[216407] = "underyou",
})

BigWigs:AddColors("Neltharions Lair Trash", {
	[183088] = "orange",
	[183407] = "blue",
	[183465] = "red",
	[183526] = "yellow",
	[183539] = "red",
	[183548] = "yellow",
	[186576] = {"blue","red"},
	[186616] = {"blue","red"},
	[188587] = "yellow",
	[193505] = "purple",
	[193585] = "red",
	[193803] = "red",
	[200154] = {"blue","orange","yellow"},
	[201983] = "yellow",
	[202108] = "yellow",
	[202181] = {"blue","red"},
	[226287] = "orange",
	[226296] = "purple",
	[226388] = "blue",
	[226406] = "purple",
})

BigWigs:AddSounds("Neltharions Lair Trash", {
	[183088] = "alarm",
	[183407] = "underyou",
	[183465] = "alarm",
	[183526] = "long",
	[183539] = "alarm",
	[183548] = "info",
	[186576] = "alert",
	[186616] = {"info","warning"},
	[188587] = "info",
	[193505] = "alert",
	[193585] = "warning",
	[193803] = "warning",
	[200154] = {"alert","info","warning"},
	[201983] = "warning",
	[202108] = "info",
	[202181] = {"alert","warning"},
	[226287] = "alarm",
	[226296] = "alarm",
	[226388] = "underyou",
	[226406] = "alert",
})
