-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Watcher Irideus", {
	[383840] = {"cyan","green","yellow"},
	[384014] = "orange",
	[384351] = "yellow",
	[384524] = "purple",
	[389179] = {"blue","red"},
	[389446] = "red",
})

BigWigs:AddSounds("Watcher Irideus", {
	[383840] = {"info","long"},
	[384014] = "alert",
	[384351] = "long",
	[384524] = "alarm",
	[389179] = "alert",
	[389446] = "alarm",
})

BigWigs:AddColors("Gulping Goliath", {
	[374389] = {"blue","red"},
	[385187] = "yellow",
	[385442] = "yellow",
	[385531] = {"blue","red"},
	[385551] = "orange",
	[385743] = "orange",
})

BigWigs:AddSounds("Gulping Goliath", {
	[374389] = {"alert","warning"},
	[385187] = "long",
	[385442] = "alert",
	[385531] = "alarm",
	[385551] = "alarm",
	[385743] = "info",
})

BigWigs:AddColors("Khajin the Unyielding", {
	[385963] = {"blue","purple"},
	[386559] = "yellow",
	[386757] = "red",
	[390111] = "orange",
})

BigWigs:AddSounds("Khajin the Unyielding", {
	[385963] = "alert",
	[386559] = "long",
	[386757] = "warning",
	[390111] = "alarm",
})

BigWigs:AddColors("Primal Tsunami", {
	[387504] = "purple",
	[387559] = "yellow",
	[388424] = "red",
	[388882] = "yellow",
	[389875] = "purple",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Primal Tsunami", {
	[387504] = "alert",
	[387559] = "alarm",
	[388424] = "alert",
	[388882] = "alert",
	[389875] = {"alert","warning"},
	["stages"] = {"info","long"},
})

BigWigs:AddColors("Halls of Infusion Trash", {
	[374045] = "yellow",
	[374073] = "orange",
	[374339] = "red",
	[374389] = {"blue","red"},
	[374563] = "orange",
	[374699] = "red",
	[374724] = {"blue","yellow"},
	[374741] = "orange",
	[374823] = "cyan",
	[375079] = "orange",
	[375351] = "purple",
	[375384] = "orange",
	[376171] = "red",
	[377341] = "yellow",
	[377402] = {"red","yellow"},
	[390290] = "orange",
	[391241] = {"cyan","green"},
	[391471] = "green",
	[391634] = "red",
	[393432] = "purple",
	[395694] = {"red","yellow"},
	[437719] = "yellow",
})

BigWigs:AddSounds("Halls of Infusion Trash", {
	[374045] = "warning",
	[374073] = "alarm",
	[374339] = "alert",
	[374389] = {"alert","warning"},
	[374563] = "alarm",
	[374699] = "warning",
	[374724] = "alert",
	[374741] = "alarm",
	[374823] = "long",
	[375079] = "alarm",
	[375351] = "alarm",
	[375384] = "alarm",
	[376171] = "alert",
	[377341] = "alert",
	[377402] = {"alert","warning"},
	[390290] = "alarm",
	[391241] = "info",
	[391471] = "info",
	[391634] = "long",
	[393432] = "alarm",
	[395694] = {"alarm","alert"},
	[437719] = "alert",
})
