-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Overseer Kaskel", {
	[448644] = "red",
	[449038] = "orange",
	[449072] = "cyan",
})

BigWigs:AddSounds("Overseer Kaskel", {
	[448644] = "alert",
	[449038] = "warning",
	[449072] = "info",
})

BigWigs:AddColors("The Puppetmaster", {
	[448663] = "red",
	[450197] = "yellow",
	[450509] = "purple",
	[450546] = {"blue","green","red"},
	[450714] = "orange",
	[451913] = {"blue","orange"},
})

BigWigs:AddSounds("The Puppetmaster", {
	[448663] = "warning",
	[450197] = "alarm",
	[450509] = "alarm",
	[450546] = "alert",
	[450714] = "alarm",
	[451913] = {"alarm","underyou"},
})
