-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Orator Krix'vizk", {
	[434722] = "purple",
	[434779] = "orange",
	[434829] = {"green","yellow"},
	[434926] = "blue",
	[448561] = {"blue","red"},
})

BigWigs:AddSounds("Orator Krix'vizk", {
	[434722] = "alert",
	[434779] = "alarm",
	[434829] = {"info","long"},
	[434926] = "underyou",
	[448561] = "alarm",
})

BigWigs:AddColors("Fangs of the Queen", {
	[439621] = "red",
	[439692] = "orange",
	[440218] = {"blue","yellow"},
	[440468] = "purple",
	[441298] = {"blue","yellow"},
	[441384] = "cyan",
	[458741] = {"blue","purple"},
})

BigWigs:AddSounds("Fangs of the Queen", {
	[439621] = "alarm",
	[439692] = "alarm",
	[440218] = "alert",
	[440468] = "alarm",
	[441298] = "info",
	[441384] = "long",
	[458741] = "warning",
})

BigWigs:AddColors("The Coaglamation", {
	[441289] = "red",
	[441395] = "yellow",
	[461825] = "blue",
	[461842] = "purple",
	[461880] = "orange",
})

BigWigs:AddSounds("The Coaglamation", {
	[441289] = "long",
	[441395] = "alert",
	[461825] = "underyou",
	[461842] = "alert",
	[461880] = "alarm",
})

BigWigs:AddColors("Izo, the Grand Splicer", {
	[437700] = "orange",
	[438860] = "yellow",
	[439341] = "red",
	[439401] = "yellow",
	[439646] = "purple",
})

BigWigs:AddSounds("Izo, the Grand Splicer", {
	[437700] = "alarm",
	[438860] = "long",
	[439341] = "alert",
	[439401] = "info",
	[439646] = "alarm",
})

BigWigs:AddColors("City of Threads Trash", {
	[434137] = "yellow",
	[436205] = "yellow",
	[441795] = "green",
	[443397] = {"blue","purple"},
	[443430] = "red",
	[443433] = {"blue","red"},
	[443437] = {"blue","yellow"},
	[443500] = "orange",
	[443507] = "yellow",
	[445813] = "orange",
	[446086] = "red",
	[446717] = "yellow",
	[447271] = "orange",
	[448047] = {"blue","cyan"},
	[448305] = "green",
	[450784] = "orange",
	[451222] = "yellow",
	[451423] = "red",
	[451543] = "orange",
	[452151] = {"blue","purple"},
	[452162] = "red",
})

BigWigs:AddSounds("City of Threads Trash", {
	[434137] = "long",
	[436205] = "info",
	[441795] = "info",
	[443397] = "alert",
	[443430] = "alert",
	[443433] = {"alert","underyou"},
	[443437] = "alarm",
	[443500] = "alarm",
	[443507] = "info",
	[445813] = "long",
	[446086] = "alert",
	[446717] = "alert",
	[447271] = "alarm",
	[448047] = "info",
	[448305] = "info",
	[450784] = "alarm",
	[451222] = "info",
	[451423] = "long",
	[451543] = "alarm",
	[452151] = "alert",
	[452162] = "alert",
})
