-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Rom'ogg Bonecrusher", {
	[75272] = {"blue","yellow"},
	[75539] = {"red","yellow"},
	[75543] = "orange",
})

BigWigs:AddSounds("Rom'ogg Bonecrusher", {
	[75272] = "alert",
	[75539] = "alarm",
})

BigWigs:AddColors("Corla, Herald of Twilight", {
	[75697] = {"blue","green"},
	[75823] = {"blue","orange","red"},
})

BigWigs:AddSounds("Corla, Herald of Twilight", {
	[75697] = "warning",
	[75823] = {"alarm","alert"},
})

BigWigs:AddColors("Karsh Steelbender", {
	[75842] = "yellow",
	[75846] = {"blue","red"},
})

BigWigs:AddSounds("Karsh Steelbender", {
	[75842] = "alert",
	[75846] = {"info","warning"},
})

BigWigs:AddColors("Beauty", {
	[76028] = {"blue","yellow"},
	[76031] = {"blue","orange"},
	[76628] = "blue",
})

BigWigs:AddSounds("Beauty", {
	[76628] = "alert",
})

BigWigs:AddColors("Ascendant Lord Obsidius", {
	[-2385] = {"orange","yellow"},
	[76188] = {"blue","red"},
	[76189] = {"blue","yellow"},
})

BigWigs:AddSounds("Ascendant Lord Obsidius", {
	[76188] = "alarm",
})

BigWigs:AddColors("Glubtok", {
	[87859] = "red",
	[87861] = "yellow",
	[88009] = "cyan",
})

BigWigs:AddSounds("Glubtok", {
	[87859] = "alert",
	[87861] = "alert",
	[88009] = "long",
})

BigWigs:AddColors("Helix Gearbreaker", {
	[88300] = {"blue","red"},
	[88352] = {"blue","orange"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("Helix Gearbreaker", {
	[88300] = "info",
	[88352] = "alert",
	["stages"] = "long",
})

BigWigs:AddColors("Foe Reaper 5000", {
	[88481] = "orange",
	[88495] = {"blue","red"},
	[88522] = "cyan",
})

BigWigs:AddSounds("Foe Reaper 5000", {
	[88481] = "alarm",
	[88495] = "alert",
	[88522] = "long",
})

BigWigs:AddColors("Admiral Ripsnarl", {
	[88836] = {"blue","red"},
	[88840] = "cyan",
	[92042] = "yellow",
})

BigWigs:AddSounds("Admiral Ripsnarl", {
	[88836] = "alarm",
	[88840] = "long",
	[92042] = "warning",
})

BigWigs:AddColors("Captain Cookie", {
	[89263] = "cyan",
	[89267] = "green",
	[89732] = "red",
})

BigWigs:AddSounds("Captain Cookie", {
	[89263] = "long",
	[89267] = "info",
	[89732] = "alarm",
})

BigWigs:AddColors("Vanessa VanCleef", {
	[-2065] = "orange",
	[-2063] = "red",
	[90932] = "green",
	[92614] = "orange",
	[95542] = "yellow",
})

BigWigs:AddSounds("Vanessa VanCleef", {
	[-2065] = "alarm",
	[-2063] = "warning",
	[90932] = "info",
	[92614] = "alert",
	[95542] = "long",
})

BigWigs:AddColors("Echo of Baine", {
	[-4141] = {"green","red"},
	[-4140] = {"blue","red"},
})

BigWigs:AddSounds("Echo of Baine", {
	[-4141] = {"alarm","info"},
	[-4140] = "alert",
})

BigWigs:AddColors("General Umbriss", {
	[74634] = "orange",
	[74670] = {"blue","red"},
	[74846] = {"blue","yellow"},
	[74853] = {"cyan","yellow"},
	[447261] = "purple",
	[448847] = "yellow",
	[448877] = "orange",
})

BigWigs:AddSounds("General Umbriss", {
	[74670] = "alert",
	[74853] = "long",
	[447261] = "alert",
	[448847] = "long",
	[448877] = "alarm",
})

BigWigs:AddColors("Forgemaster Throngus", {
	[74908] = "red",
	[74976] = "blue",
	[74981] = "red",
	[74987] = "blue",
	[75007] = "red",
	[75056] = {"blue","orange"},
	[447395] = "orange",
	[449444] = "red",
	[449474] = {"blue","yellow"},
	[449687] = {"green","purple"},
	[457664] = "cyan",
})

BigWigs:AddSounds("Forgemaster Throngus", {
	[74908] = "alert",
	[74976] = "long",
	[74981] = "alert",
	[74987] = "alarm",
	[75007] = "alert",
	[447395] = "alarm",
	[449444] = "alert",
	[449474] = "alert",
	[449687] = {"info","warning"},
	[457664] = "info",
})

BigWigs:AddColors("Drahga Shadowburner", {
	[75218] = "yellow",
	[82850] = {"blue","red"},
	[90950] = "red",
	[447966] = "red",
	[448013] = "yellow",
	[448105] = "red",
	[450095] = {"blue","red"},
	[456751] = "orange",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Drahga Shadowburner", {
	[75218] = "info",
	[82850] = "warning",
	[90950] = "alarm",
	[447966] = "alert",
	[448013] = "info",
	[448105] = "alarm",
	[450095] = "alert",
	[456751] = "alarm",
	["stages"] = "long",
})

BigWigs:AddColors("Erudax", {
	[75664] = "orange",
	[75755] = "red",
	[75763] = "red",
	[448057] = {"blue","red"},
	[449939] = "orange",
	[450077] = "yellow",
	[450087] = "blue",
	[450088] = "cyan",
	[450100] = "purple",
	["summon"] = "yellow",
})

BigWigs:AddSounds("Erudax", {
	[75664] = "alert",
	[75755] = "alarm",
	[75763] = "warning",
	[448057] = "alarm",
	[449939] = "info",
	[450077] = "alert",
	[450087] = "alarm",
	[450088] = "long",
	[450100] = "alert",
})

BigWigs:AddColors("Grim Batol Trash", {
	[76711] = "red",
	[451224] = {"blue","orange"},
	[451241] = "purple",
	[451364] = "purple",
	[451378] = "purple",
	[451387] = "cyan",
	[451391] = {"blue","cyan","orange"},
	[451395] = "blue",
	[451612] = {"blue","red"},
	[451614] = "blue",
	[451871] = "red",
	[451939] = "yellow",
	[451965] = "yellow",
	[451971] = "purple",
	[456696] = "orange",
	[456711] = "orange",
	[456713] = "red",
	[462216] = "yellow",
})

BigWigs:AddSounds("Grim Batol Trash", {
	[76711] = "alert",
	[451224] = "alert",
	[451241] = "alert",
	[451364] = "alert",
	[451378] = "alert",
	[451387] = "info",
	[451391] = {"alarm","info"},
	[451395] = "alert",
	[451612] = "alert",
	[451614] = "underyou",
	[451871] = "alert",
	[451939] = "alarm",
	[451965] = "info",
	[451971] = "alert",
	[456696] = "alarm",
	[456711] = "alarm",
	[456713] = "alarm",
	[462216] = "alarm",
})

BigWigs:AddColors("Temple Guardian Anhuur", {
	[74938] = {"red","yellow"},
	[75592] = {"blue","yellow"},
})

BigWigs:AddSounds("Temple Guardian Anhuur", {
	[74938] = "long",
	[75592] = "alert",
})

BigWigs:AddColors("Anraphet", {
	[75603] = {"blue","orange"},
	[75609] = "blue",
	[75622] = "red",
	[76184] = {"blue","yellow"},
})

BigWigs:AddSounds("Anraphet", {
	[75622] = "alarm",
	[76184] = "alert",
})

BigWigs:AddColors("Isiset", {
	[-2556] = {"cyan","green"},
	[74045] = "blue",
	[74135] = "blue",
	[74137] = "red",
	[74373] = "yellow",
})

BigWigs:AddSounds("Isiset", {
	[-2556] = "info",
	[74045] = "alert",
	[74135] = "alert",
	[74137] = "alarm",
})

BigWigs:AddColors("Ammunae", {
	[75790] = "yellow",
	[76043] = {"blue","orange","red"},
	[80968] = {"blue","yellow"},
})

BigWigs:AddSounds("Ammunae", {
	[75790] = "info",
	[76043] = {"alarm","alert"},
	[80968] = "long",
})

BigWigs:AddColors("Rajh", {
	[-2863] = "blue",
	[-2862] = "orange",
	[-2861] = "yellow",
	[76355] = {"cyan","green"},
})

BigWigs:AddSounds("Rajh", {
	[-2863] = "warning",
	[76355] = "long",
})

BigWigs:AddColors("Arcurion", {
	[102582] = "orange",
	[103252] = {"green","yellow"},
	[104050] = "cyan",
})

BigWigs:AddSounds("Arcurion", {
	[102582] = "alert",
	[103252] = {"alarm","info"},
	[104050] = "long",
})

BigWigs:AddColors("Asira Dawnslayer", {
	[102726] = {"blue","yellow"},
	[103419] = "red",
	[103558] = "orange",
})

BigWigs:AddSounds("Asira Dawnslayer", {
	[102726] = "alarm",
	[103419] = "long",
	[103558] = "alert",
})

BigWigs:AddColors("Archbishop Benedictus", {
	[103151] = {"blue","red"},
	[103363] = {"blue","red"},
	[103565] = "yellow",
	[103678] = "orange",
	[103767] = "yellow",
	[103780] = "orange",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Archbishop Benedictus", {
	[103151] = "alarm",
	[103363] = "alarm",
	[103565] = "alert",
	[103678] = "alarm",
	[103767] = "alert",
	[103780] = "alarm",
	["stages"] = "long",
})

BigWigs:AddColors("The Hour of Twilight Trash", {
})

BigWigs:AddSounds("The Hour of Twilight Trash", {
})

BigWigs:AddColors("General Husam", {
	[83113] = {"blue","yellow"},
	[83445] = "red",
	[91263] = "orange",
})

BigWigs:AddSounds("General Husam", {
	[83113] = "alert",
	[83445] = "info",
	[91263] = "alarm",
})

BigWigs:AddColors("Lockmaw", {
	[81630] = {"blue","yellow"},
	[81690] = {"blue","red"},
	[84784] = "orange",
})

BigWigs:AddSounds("Lockmaw", {
	[81690] = "alert",
})

BigWigs:AddColors("High Prophet Barim", {
	[82506] = "red",
	[82622] = "blue",
	[88814] = {"blue","yellow"},
})

BigWigs:AddSounds("High Prophet Barim", {
	[82622] = "alarm",
})

BigWigs:AddColors("Siamat", {
	["servant"] = "red",
	["stages"] = {"cyan","green"},
})

BigWigs:AddSounds("Siamat", {
	["servant"] = "alert",
	["stages"] = "info",
})

BigWigs:AddColors("Baron Ashbury", {
	[93423] = "red",
	[93581] = {"blue","orange"},
	[93757] = "yellow",
})

BigWigs:AddSounds("Baron Ashbury", {
	[93757] = "long",
})

BigWigs:AddColors("Baron Silverlaine", {
	[23224] = "orange",
	[93857] = {"cyan","yellow"},
})

BigWigs:AddSounds("Baron Silverlaine", {
	[23224] = "alert",
	[93857] = "info",
})

BigWigs:AddColors("Commander Springvale", {
	[93687] = "blue",
	[93844] = "orange",
	[93852] = {"blue","red"},
})

BigWigs:AddSounds("Commander Springvale", {
	[93687] = "alert",
	[93844] = "alarm",
})

BigWigs:AddColors("Lord Walden", {
	[93505] = "red",
	[93527] = "yellow",
	[93617] = {"blue","cyan","orange"},
	[93689] = "cyan",
	[93697] = "red",
})

BigWigs:AddSounds("Lord Walden", {
	[93617] = {"info","warning"},
	[93689] = "info",
})

BigWigs:AddColors("Lord Godfrey", {
	[93520] = {"blue","red"},
	[93629] = {"blue","orange"},
	[93675] = {"blue","yellow"},
	[93707] = "cyan",
})

BigWigs:AddSounds("Lord Godfrey", {
	[93520] = {"alert","long"},
	[93629] = "alarm",
	[93707] = "info",
})

BigWigs:AddColors("Corborus", {
	[86881] = "blue",
	["burrow"] = {"red","yellow"},
})

BigWigs:AddSounds("Corborus", {
	[86881] = "alarm",
	["burrow"] = "info",
})

BigWigs:AddColors("Slabhide", {
	[80801] = "blue",
	[92265] = "red",
})

BigWigs:AddSounds("Slabhide", {
	[80801] = "alarm",
	[92265] = "alert",
})

BigWigs:AddColors("Ozruk", {
	[78903] = "orange",
	[78939] = "red",
	[80467] = "yellow",
	[92426] = "red",
})

BigWigs:AddSounds("Ozruk", {
	[78903] = "alarm",
	[78939] = "alarm",
	[92426] = "alert",
})

BigWigs:AddColors("High Priestess Azil", {
	[79050] = "red",
	[79345] = {"blue","yellow"},
})

BigWigs:AddSounds("High Priestess Azil", {
	[79050] = "alert",
})

BigWigs:AddColors("Lady Naz'jar", {
	[75683] = "cyan",
	[427771] = "orange",
	[428054] = {"blue","red"},
	[428263] = "red",
	[428293] = "orange",
	[428374] = "yellow",
})

BigWigs:AddSounds("Lady Naz'jar", {
	[75683] = {"info","long"},
	[427771] = "alarm",
	[428054] = "alarm",
	[428263] = "alert",
	[428293] = "alarm",
	[428374] = "alert",
})

BigWigs:AddColors("Commander Ulthok", {
	[76026] = {"blue","orange"},
	[76047] = "red",
	[76094] = {"blue","yellow"},
	[76100] = "yellow",
	[427456] = "cyan",
	[427668] = "red",
	[427670] = "purple",
	[427672] = "orange",
})

BigWigs:AddSounds("Commander Ulthok", {
	[427456] = "long",
	[427668] = "alarm",
	[427670] = "alert",
	[427672] = "alarm",
})

BigWigs:AddColors("Mindbender Ghur'sha", {
	[76207] = {"blue","red"},
	[76230] = "blue",
	[76307] = "orange",
	[429037] = "yellow",
	[429048] = {"blue","red"},
	[429051] = "orange",
	[429172] = "red",
	[429878] = "cyan",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Mindbender Ghur'sha", {
	[76207] = "alert",
	[76230] = "alarm",
	[429037] = "info",
	[429048] = "alert",
	[429051] = "alarm",
	[429172] = "warning",
	[429878] = "long",
})

BigWigs:AddColors("Ozumat", {
	[428404] = "blue",
	[428407] = {"blue","red"},
	[428530] = "purple",
	[428594] = "orange",
	[428668] = {"blue","green"},
	[428868] = "yellow",
	[428889] = "purple",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Ozumat", {
	[428404] = "underyou",
	[428407] = "alarm",
	[428530] = "alarm",
	[428594] = "alarm",
	[428668] = "info",
	[428868] = "alert",
	[428889] = "warning",
	["stages"] = "long",
})

BigWigs:AddColors("Throne of the Tides Trash", {
	[75992] = {"blue","red"},
	[76590] = "orange",
	[76634] = "yellow",
	[76813] = "yellow",
	[76820] = {"blue","orange","red"},
	[426645] = "red",
	[426663] = {"blue","red"},
	[426684] = "orange",
	[426741] = "purple",
	[426783] = "red",
	[426808] = "yellow",
	[428542] = {"blue","orange"},
	[429021] = "purple",
})

BigWigs:AddSounds("Throne of the Tides Trash", {
	[75992] = "alarm",
	[76590] = "alarm",
	[76634] = "alert",
	[76813] = "alert",
	[76820] = {"alert","info"},
	[426645] = "alert",
	[426663] = {"info","warning"},
	[426684] = "alarm",
	[426741] = "alert",
	[426783] = "alert",
	[426808] = "alarm",
	[428542] = "alarm",
	[429021] = "alert",
})

BigWigs:AddColors("Grand Vizier Ertan", {
	[86292] = {"blue","green","orange","yellow"},
	[86340] = "yellow",
	[413151] = "yellow",
	[413562] = "red",
})

BigWigs:AddSounds("Grand Vizier Ertan", {
	[86292] = {"alert","info","long","underyou"},
	[86340] = "info",
	[413151] = "info",
	[413562] = "alarm",
})

BigWigs:AddColors("Altairus", {
	[-2425] = "cyan",
	[88282] = "green",
	[88286] = "red",
	[88308] = "orange",
	[413275] = "blue",
	[413295] = "yellow",
})

BigWigs:AddSounds("Altairus", {
	[-2425] = "alert",
	[88282] = "info",
	[88286] = "alarm",
	[88308] = "alarm",
	[413275] = "underyou",
	[413295] = "warning",
})

BigWigs:AddColors("Asaad", {
	[86911] = "green",
	[86930] = "red",
	[87618] = {"blue","red","yellow"},
	[87622] = {"blue","orange"},
	[96260] = "cyan",
	[413264] = "cyan",
})

BigWigs:AddSounds("Asaad", {
	[86911] = "info",
	[86930] = "alarm",
	[87618] = {"alert","warning"},
	[87622] = "alarm",
	[96260] = "alert",
	[413264] = "alert",
})

BigWigs:AddColors("The Vortex Pinnacle Trash", {
	[87761] = "red",
	[87762] = {"blue","orange"},
	[87772] = "orange",
	[87779] = "yellow",
	[88170] = "red",
	[88171] = "blue",
	[88182] = {"blue","purple"},
	[88186] = {"orange","red"},
	[88194] = "yellow",
	[410870] = "yellow",
	[410873] = {"blue","red"},
	[410999] = "orange",
	[411001] = "red",
	[411002] = "yellow",
	[411005] = "orange",
	[411012] = "orange",
	[411910] = "green",
	[413385] = {"blue","red"},
	[413387] = "orange",
})

BigWigs:AddSounds("The Vortex Pinnacle Trash", {
	[87761] = "alert",
	[87762] = {"alert","warning"},
	[87772] = "alert",
	[87779] = "warning",
	[88170] = "alert",
	[88171] = "underyou",
	[88182] = "alert",
	[88186] = "alert",
	[88194] = "long",
	[410870] = "alert",
	[410873] = "alert",
	[410999] = "alarm",
	[411001] = "alarm",
	[411002] = "long",
	[411005] = "alarm",
	[411012] = "alarm",
	[411910] = "info",
	[413385] = {"alarm","underyou"},
	[413387] = "alarm",
})

BigWigs:AddColors("Peroth'arn", {
	[105442] = {"blue","yellow"},
	[105493] = {"blue","yellow"},
	[105544] = {"blue","red"},
	["eyes"] = "green",
})

BigWigs:AddSounds("Peroth'arn", {
	[105442] = "long",
	[105493] = "long",
	[105544] = "alert",
	["eyes"] = "info",
})

BigWigs:AddColors("Queen Azshara WellOfEternity", {
	[-3969] = {"green","orange"},
	[-3968] = "yellow",
})

BigWigs:AddSounds("Queen Azshara WellOfEternity", {
	[-3969] = "long",
	[-3968] = "alert",
})

BigWigs:AddColors("Mannoroth and Varo'then", {
	[-4287] = "cyan",
})

BigWigs:AddSounds("Mannoroth and Varo'then", {
	[-4287] = "info",
})

BigWigs:AddColors("Well Of Eternity Trash", {
})

BigWigs:AddSounds("Well Of Eternity Trash", {
})

BigWigs:AddColors("Akil'zon", {
	[43648] = {"blue","red"},
	[97318] = {"blue","red"},
})

BigWigs:AddSounds("Akil'zon", {
	[43648] = "alert",
	[97318] = "alert",
})

BigWigs:AddColors("Nalorakk", {
	[42398] = {"blue","yellow"},
	[42402] = {"blue","orange"},
	["stages"] = "red",
})

BigWigs:AddSounds("Nalorakk", {
	[42398] = "info",
	[42402] = "alarm",
})

BigWigs:AddColors("Jan'alai", {
	[-2625] = "yellow",
	[-2622] = "orange",
	[97497] = {"blue","red"},
})

BigWigs:AddSounds("Jan'alai", {
	[-2625] = "long",
	[-2622] = "info",
	[97497] = "alert",
})

BigWigs:AddColors("Halazzi", {
	[43139] = "red",
	[43302] = "orange",
	[43303] = {"blue","yellow"},
	[97499] = "orange",
	["stages"] = {"green","yellow"},
})

BigWigs:AddSounds("Halazzi", {
	[43302] = "alert",
	[43303] = "alarm",
	[97499] = "alert",
})

BigWigs:AddColors("Hex Lord Malacrass", {
	[43383] = "red",
	[43421] = {"blue","orange"},
	[43431] = "orange",
	[43451] = "orange",
	[43501] = {"blue","yellow"},
	[43548] = "orange",
})

BigWigs:AddSounds("Hex Lord Malacrass", {
	[43421] = "alarm",
	[43431] = "alarm",
	[43451] = "alarm",
	[43548] = "alarm",
})

BigWigs:AddColors("Daakara", {
	[17207] = "orange",
	[43093] = {"blue","yellow"},
	[43095] = "yellow",
	[43150] = {"blue","red"},
	["stages"] = "red",
})

BigWigs:AddSounds("Daakara", {
	[43093] = "alarm",
	[43095] = "warning",
	[43150] = "alert",
})

BigWigs:AddColors("High Priest Venoxis", {
	[96466] = "orange",
	[96477] = {"blue","yellow"},
	[96509] = "red",
	[96653] = "green",
	[96842] = "red",
})

BigWigs:AddSounds("High Priest Venoxis", {
	[96466] = "alert",
	[96477] = "alarm",
	[96509] = "alarm",
	[96653] = "info",
	[96842] = "long",
})

BigWigs:AddColors("Bloodlord Mandokir", {
	[96684] = {"blue","yellow"},
	[96724] = "yellow",
	[96740] = "red",
	[96776] = "yellow",
	[96800] = "red",
})

BigWigs:AddSounds("Bloodlord Mandokir", {
	[96684] = "alert",
	[96724] = "info",
	[96740] = "info",
	[96776] = "alert",
	[96800] = "long",
})

BigWigs:AddColors("High Priestess Kilnara", {
	[-2702] = "red",
	[96423] = {"blue","yellow"},
	[96435] = "red",
	[96457] = "red",
	[96592] = {"blue","yellow"},
	["stages"] = "yellow",
})

BigWigs:AddSounds("High Priestess Kilnara", {
	[-2702] = "alert",
	[96423] = "alert",
	[96435] = "alert",
	[96592] = "alert",
	["stages"] = "info",
})

BigWigs:AddColors("Zanzil", {
	[96316] = {"blue","red","yellow"},
	[96338] = "yellow",
	[96914] = "yellow",
})

BigWigs:AddSounds("Zanzil", {
	[96316] = "alert",
	[96338] = "alert",
	[96914] = "info",
})

BigWigs:AddColors("Jin'do the Godbreaker", {
	[-2910] = {"blue","red"},
	[97170] = "red",
	[97172] = {"red","yellow"},
	["stages"] = "red",
})

BigWigs:AddSounds("Jin'do the Godbreaker", {
	[-2910] = "alert",
	[97170] = "long",
	[97172] = {"info","long"},
	["stages"] = "long",
})
