-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Commander Sarannis", {
	[-5411] = {"cyan","yellow"},
	[34794] = {"blue","red"},
	[35096] = "orange",
})

BigWigs:AddSounds("Commander Sarannis", {
	[-5411] = "info",
	[35096] = {"alarm","warning"},
})

BigWigs:AddColors("High Botanist Freywinn", {
	[34550] = {"green","red"},
	[34752] = {"blue","orange"},
})

BigWigs:AddSounds("High Botanist Freywinn", {
	[34550] = {"info","long"},
	[34752] = "alarm",
})

BigWigs:AddColors("Thorngrin the Tender", {
	[34659] = {"blue","red"},
	[34661] = {"blue","yellow"},
	[34670] = {"blue","orange"},
})

BigWigs:AddSounds("Thorngrin the Tender", {
	[34659] = {"alert","long"},
	[34670] = "warning",
})

BigWigs:AddColors("Laj", {
	[34697] = {"blue","red"},
})

BigWigs:AddSounds("Laj", {
})

BigWigs:AddColors("Warp Splinter", {
	[-5478] = {"green","red"},
	[34716] = {"blue","orange"},
})

BigWigs:AddSounds("Warp Splinter", {
	[-5478] = {"alarm","info"},
	[34716] = "alert",
})
