-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Fleshrender Nok'gar", {
	[164426] = {"green","orange"},
	[164632] = "red",
	[164734] = "yellow",
	[164835] = "yellow",
	[164837] = {"blue","red"},
	[166923] = "yellow",
	["stages"] = {"cyan","yellow"},
})

BigWigs:AddSounds("Fleshrender Nok'gar", {
	[164426] = {"info","warning"},
	[164632] = "long",
	[164734] = "alarm",
	[164835] = {"alert","warning"},
	[164837] = "alert",
	[166923] = "alert",
	["stages"] = {"info","long"},
})

BigWigs:AddColors("Grimrail Enforcers", {
	[163376] = "yellow",
	[163379] = "red",
	[163390] = "red",
	[163665] = "orange",
	[163689] = {"blue","green","red","yellow"},
	[163705] = "yellow",
	[163740] = {"blue","yellow"},
	[165152] = "red",
})

BigWigs:AddSounds("Grimrail Enforcers", {
	[163376] = "alert",
	[163379] = "alert",
	[163390] = "alarm",
	[163665] = "alarm",
	[163689] = {"alert","info","warning"},
	[163705] = "warning",
	[163740] = "alert",
	[165152] = "alarm",
})

BigWigs:AddColors("Oshir", {
	[161256] = "orange",
	[162415] = {"blue","green","red"},
	[178124] = "yellow",
})

BigWigs:AddSounds("Oshir", {
	[161256] = "alarm",
	[162415] = {"info","long"},
	[178124] = "alert",
})

BigWigs:AddColors("Skulloc", {
	[168227] = "orange",
	[168348] = {"blue","red"},
	[168929] = {"green","yellow"},
	[168965] = "orange",
})

BigWigs:AddSounds("Skulloc", {
	[168227] = "long",
	[168348] = {"alert","warning"},
	[168929] = {"alert","info"},
	[168965] = "alert",
})

BigWigs:AddColors("Iron Docks Trash", {
	[158337] = "orange",
	[164632] = "blue",
	[167233] = {"blue","red"},
	[167815] = "purple",
	[172636] = "blue",
	[172943] = "purple",
	[172952] = "yellow",
	[172963] = "blue",
	[172982] = "red",
	[173105] = {"blue","yellow"},
	[173135] = "yellow",
	[173324] = "blue",
	[173384] = "red",
	[173480] = {"blue","orange"},
	[173514] = "red",
})

BigWigs:AddSounds("Iron Docks Trash", {
	[158337] = "warning",
	[164632] = "underyou",
	[167233] = {"alarm","underyou"},
	[167815] = "alarm",
	[172636] = "underyou",
	[172943] = "alert",
	[172952] = "warning",
	[172963] = "underyou",
	[172982] = "alarm",
	[173105] = {"alarm","underyou"},
	[173135] = "alert",
	[173324] = "underyou",
	[173384] = "alarm",
	[173480] = {"alert","underyou"},
	[173514] = "alarm",
})
