-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Agronox", {
	[235751] = "orange",
	[236524] = "yellow",
	[236527] = "yellow",
	[236639] = "yellow",
	[236640] = "blue",
	[236650] = {"blue","yellow"},
	[238674] = "blue",
})

BigWigs:AddSounds("Agronox", {
	[235751] = "alarm",
	[236524] = "info",
	[236527] = "alert",
	[236639] = "alert",
	[236640] = "alert",
	[236650] = {"alert","warning"},
	[238674] = "alarm",
})

BigWigs:AddColors("Thrashbite the Scornful", {
	[237276] = "orange",
	[237726] = {"blue","orange"},
	[243124] = "red",
})

BigWigs:AddSounds("Thrashbite the Scornful", {
	[237276] = "alert",
	[237726] = "warning",
	[243124] = "alert",
})

BigWigs:AddColors("Domatrax", {
	[-15076] = "red",
	[234107] = "orange",
	[236543] = "yellow",
	[238410] = {"blue","orange"},
})

BigWigs:AddSounds("Domatrax", {
	[-15076] = "alarm",
	[234107] = "warning",
	[236543] = "alert",
	[238410] = {"alert","warning"},
})

BigWigs:AddColors("Mephistroth", {
	[233155] = "yellow",
	[233196] = {"blue","red","yellow"},
	[233206] = {"green","yellow"},
	[234817] = "yellow",
})

BigWigs:AddSounds("Mephistroth", {
	[233155] = "alarm",
	[233196] = {"alert","warning"},
	[233206] = {"long","warning"},
	[234817] = "alarm",
})

BigWigs:AddColors("Cathedral of Eternal Night Trash", {
	[236737] = {"blue","yellow"},
	[237391] = "orange",
	[237565] = "yellow",
	[238543] = "orange",
	[238653] = "orange",
	[239101] = "orange",
	[239232] = "orange",
	[239320] = "orange",
	[241598] = "yellow",
	[241772] = "orange",
	[242760] = "red",
	[242839] = "orange",
	[242841] = "orange",
})

BigWigs:AddSounds("Cathedral of Eternal Night Trash", {
	[236737] = "alert",
	[237391] = "warning",
	[237565] = "long",
	[238543] = "warning",
	[238653] = "alarm",
	[239101] = "warning",
	[239232] = "warning",
	[239320] = "warning",
	[241598] = "long",
	[241772] = "warning",
	[242760] = "alarm",
	[242839] = "warning",
	[242841] = "warning",
})
