-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Awakening the Machine", {
	[462802] = "red",
	[462826] = "orange",
	[462856] = "orange",
	[462892] = "yellow",
	[462936] = "red",
	[462983] = {"blue","yellow"},
	[463052] = "yellow",
	[463081] = "red",
	["stages"] = {"cyan","green"},
})

BigWigs:AddSounds("Awakening the Machine", {
	[462802] = "alert",
	[462826] = "alarm",
	[462856] = "info",
	[462892] = "alert",
	[462936] = "info",
	[462983] = "alarm",
	[463052] = "alert",
	[463081] = "alarm",
	["stages"] = "info",
})
