-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Tirathon Saltheril", {
	[190830] = "yellow",
	[191823] = "orange",
	[191853] = "blue",
	[191941] = {"blue","orange","red"},
	[192504] = "cyan",
	[202740] = "cyan",
})

BigWigs:AddSounds("Tirathon Saltheril", {
	[190830] = "warning",
	[191823] = "alarm",
	[191853] = "alert",
	[191941] = "alarm",
	[192504] = "info",
	[202740] = "info",
})

BigWigs:AddColors("Inquisitor Tormentorum", {
	[196208] = "orange",
	[199918] = "blue",
	[200898] = "yellow",
	[200904] = {"blue","red","yellow"},
	[201488] = "orange",
	[202455] = "green",
	[203685] = {"blue","orange"},
	[212564] = "orange",
})

BigWigs:AddSounds("Inquisitor Tormentorum", {
	[196208] = "warning",
	[199918] = "alert",
	[200898] = "info",
	[200904] = {"info","long","warning"},
	[201488] = "warning",
	[202455] = "info",
	[203685] = {"alarm","warning"},
	[212564] = "alarm",
})

BigWigs:AddColors("Ashgolm", {
	[-12727] = "green",
	[192517] = "green",
	[192519] = "blue",
	[192520] = "red",
	[192522] = "yellow",
})

BigWigs:AddSounds("Ashgolm", {
	[-12727] = "info",
	[192517] = "info",
	[192519] = "alert",
	[192520] = "long",
	[192522] = "alarm",
})

BigWigs:AddColors("Glazer", {
	[194323] = "orange",
	[194333] = "green",
	[194945] = {"blue","red"},
	[202046] = "blue",
})

BigWigs:AddSounds("Glazer", {
	[194323] = "info",
	[194333] = "info",
	[194945] = {"alarm","alert"},
	[202046] = "alert",
})

BigWigs:AddColors("Cordana Felsong", {
	[197333] = "red",
	[197422] = {"cyan","red"},
	[197796] = {"green","orange"},
	[204481] = {"cyan","green"},
	[206567] = {"blue","cyan","orange","yellow"},
	[213583] = "yellow",
	["kick_combo"] = "yellow",
})

BigWigs:AddSounds("Cordana Felsong", {
	[197333] = "alert",
	[197422] = "info",
	[197796] = "long",
	[204481] = "long",
	[206567] = {"alarm","info"},
	[213583] = "alarm",
	["kick_combo"] = "warning",
})

BigWigs:AddColors("Vault of the Wardens Trash", {
	[191527] = "red",
	[191735] = "red",
	[193069] = {"blue","orange","yellow"},
	[193164] = {"blue","orange"},
	[194071] = "blue",
	[196249] = "orange",
	[196796] = "orange",
	[196799] = "yellow",
	[202607] = "blue",
	[202615] = {"blue","orange"},
	[210202] = "blue",
})

BigWigs:AddSounds("Vault of the Wardens Trash", {
	[191527] = "alert",
	[191735] = "alert",
	[193069] = {"alarm","info"},
	[193164] = "alarm",
	[194071] = "alert",
	[196249] = "alarm",
	[196796] = "warning",
	[196799] = "alarm",
	[202607] = "alert",
	[202615] = "alarm",
	[210202] = "alert",
})
