-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Hackclaw's War-Band", {
	[377827] = {"blue","orange"},
	[377950] = "yellow",
	[377965] = "red",
	[378029] = "red",
	[378208] = {"blue","red"},
	[381444] = {"blue","red"},
	[381470] = "yellow",
	[381694] = {"blue","green","purple"},
})

BigWigs:AddSounds("Hackclaw's War-Band", {
	[377827] = {"alarm","long"},
	[377950] = "warning",
	[377965] = "long",
	[378029] = "alert",
	[378208] = "alarm",
	[381444] = {"alert","warning"},
	[381470] = "alert",
	[381694] = {"info","warning"},
})

BigWigs:AddColors("Treemouth", {
	[376811] = {"blue","yellow"},
	[376934] = "red",
	[377559] = "purple",
	[377859] = "orange",
	[378022] = {"blue","green","red"},
	[378054] = "blue",
	[383875] = "blue",
	[390968] = "red",
})

BigWigs:AddSounds("Treemouth", {
	[376811] = "alert",
	[376934] = "info",
	[377559] = "alarm",
	[377859] = "alarm",
	[378022] = {"info","long"},
	[378054] = "underyou",
	[383875] = "info",
	[390968] = "warning",
})

BigWigs:AddColors("Gutshot", {
	[384353] = "purple",
	[384416] = {"blue","orange"},
	[384577] = {"blue","purple"},
	[384633] = "red",
	[384827] = "orange",
	[385359] = {"blue","green","red","yellow"},
})

BigWigs:AddSounds("Gutshot", {
	[384353] = "alert",
	[384416] = {"alarm","alert"},
	[384577] = {"alarm","warning"},
	[384633] = "warning",
	[384827] = "long",
	[385359] = {"alarm","alert","info"},
})

BigWigs:AddColors("Decatriarch Wratheye", {
	[373917] = "purple",
	[373944] = "yellow",
	[373960] = "red",
	[376170] = "orange",
})

BigWigs:AddSounds("Decatriarch Wratheye", {
	[373917] = "alert",
	[373944] = "warning",
	[373960] = "long",
	[376170] = "alarm",
})

BigWigs:AddColors("Brackenhide Hollow Trash", {
	[367484] = {"blue","red","yellow"},
	[367500] = "red",
	[367503] = {"blue","orange"},
	[368081] = {"blue","yellow"},
	[368287] = {"blue","orange"},
	[372141] = "blue",
	[372711] = "red",
	[373897] = "yellow",
	[373929] = "purple",
	[373943] = "orange",
	[374057] = "yellow",
	[374245] = "blue",
	[374544] = {"blue","red"},
	[374569] = "orange",
	[382555] = {"blue","orange"},
	[382712] = "red",
	[383087] = {"blue","orange","yellow"},
	[383399] = {"blue","yellow"},
	[384847] = "yellow",
	[384854] = "orange",
	[384974] = {"blue","red"},
	[385029] = "yellow",
	[385827] = "yellow",
	[385832] = {"blue","red"},
	[388046] = "orange",
	[388060] = {"blue","red"},
	["captive_tuskarr_freed"] = "green",
})

BigWigs:AddSounds("Brackenhide Hollow Trash", {
	[367484] = {"alert","info","warning"},
	[367500] = "warning",
	[367503] = "alarm",
	[368081] = "alert",
	[368287] = {"alarm","underyou"},
	[372141] = "underyou",
	[372711] = "alert",
	[373897] = "alert",
	[373929] = "alarm",
	[373943] = "alarm",
	[374057] = "warning",
	[374245] = "underyou",
	[374544] = "alarm",
	[374569] = "alarm",
	[382555] = {"alarm","underyou"},
	[382712] = "alarm",
	[383087] = {"alarm","alert"},
	[383399] = {"long","underyou"},
	[384847] = "info",
	[384854] = "alarm",
	[384974] = {"alert","warning"},
	[385029] = "alert",
	[385827] = "warning",
	[385832] = "alert",
	[388046] = "alarm",
	[388060] = "alarm",
	["captive_tuskarr_freed"] = "info",
})
