-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Ivanyr", {
	[196392] = "red",
	[196562] = {"blue","orange"},
	[196805] = {"blue","yellow"},
})

BigWigs:AddSounds("Ivanyr", {
	[196392] = "long",
	[196562] = "alarm",
	[196805] = "info",
})

BigWigs:AddColors("Corstilax", {
	[195804] = {"blue","yellow"},
	[196068] = {"blue","orange"},
	[196115] = "orange",
	[220481] = {"blue","yellow"},
})

BigWigs:AddSounds("Corstilax", {
	[195804] = "info",
	[196068] = "alarm",
	[196115] = "alert",
	[220481] = "alarm",
})

BigWigs:AddColors("General Xakal", {
	[197776] = "yellow",
	[197810] = "orange",
	[212030] = "orange",
	["dread_felbat"] = "cyan",
})

BigWigs:AddSounds("General Xakal", {
	[197810] = "alert",
	[212030] = "alarm",
	["dread_felbat"] = "info",
})

BigWigs:AddColors("Naltira", {
	[-12687] = {"blue","orange"},
	[200040] = {"blue","orange"},
	[200284] = {"blue","green","yellow"},
	[211543] = {"blue","red"},
})

BigWigs:AddSounds("Naltira", {
	[-12687] = "alarm",
	[200040] = "alarm",
	[200284] = "warning",
	[211543] = "info",
})

BigWigs:AddColors("Advisor Vandros", {
	[202974] = "yellow",
	[203176] = {"blue","orange","yellow"},
	[203882] = "red",
	[220871] = {"blue","orange"},
})

BigWigs:AddSounds("Advisor Vandros", {
	[202974] = "info",
	[203176] = "alert",
	[203882] = "long",
	[220871] = "alarm",
})

BigWigs:AddColors("The Arcway Trash", {
	[210750] = "blue",
	[211115] = "yellow",
	[211217] = "orange",
	[211632] = "yellow",
	[211745] = "blue",
	[211757] = "orange",
	[226206] = "orange",
	[226285] = {"green","orange"},
})

BigWigs:AddSounds("The Arcway Trash", {
	[210750] = "warning",
	[211115] = "alarm",
	[211217] = "warning",
	[211632] = "alarm",
	[211745] = "warning",
	[211757] = "alarm",
	[226206] = "alarm",
	[226285] = {"alarm","info","warning"},
})
