-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Kyrioss", {
	[419870] = "yellow",
	[444123] = {"blue","cyan","yellow"},
	[474018] = "orange",
	[1214325] = "red",
})

BigWigs:AddSounds("Kyrioss", {
	[419870] = "alarm",
	[444123] = {"alert","long"},
	[474018] = "alarm",
	[1214325] = "info",
})

BigWigs:AddColors("Stormguard Gorren", {
	[424737] = {"blue","red"},
	[424797] = "blue",
	[424958] = "orange",
	[424966] = "blue",
	[425048] = "yellow",
})

BigWigs:AddSounds("Stormguard Gorren", {
	[424737] = "alert",
	[424958] = "alarm",
	[424966] = "underyou",
	[425048] = "long",
})

BigWigs:AddColors("Voidstone Monstrosity", {
	[423305] = "orange",
	[423393] = "purple",
	[424371] = "green",
	[429493] = {"blue","red"},
	[433067] = "blue",
	[445262] = {"cyan","green"},
	[445457] = "purple",
	[458082] = {"blue","green"},
})

BigWigs:AddSounds("Voidstone Monstrosity", {
	[423305] = "alarm",
	[423393] = "warning",
	[424371] = "info",
	[429493] = "alert",
	[433067] = "underyou",
	[445262] = "long",
	[445457] = "alarm",
	[458082] = "info",
})

BigWigs:AddColors("The Rookery Trash", {
	[426893] = "red",
	[427260] = "red",
	[427404] = "yellow",
	[427616] = {"blue","orange"},
	[430179] = {"blue","orange"},
	[430805] = {"blue","orange"},
	[430812] = "yellow",
	[443854] = "orange",
	[450628] = "cyan",
	[472764] = "cyan",
	[474018] = "orange",
	[474031] = {"blue","orange"},
	[1214523] = "red",
	[1214546] = "yellow",
	[1214628] = "yellow",
})

BigWigs:AddSounds("The Rookery Trash", {
	[426893] = "alarm",
	[427260] = "alert",
	[427404] = "info",
	[427616] = "alert",
	[430179] = "alert",
	[430805] = "alarm",
	[430812] = "info",
	[443854] = "alarm",
	[450628] = "info",
	[472764] = "info",
	[474018] = "alarm",
	[474031] = "alarm",
	[1214523] = "alert",
	[1214546] = "long",
	[1214628] = "long",
})
