-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Thalnos the Soulrender", {
	[-5865] = {"blue","yellow"},
	[115297] = {"blue","orange"},
})

BigWigs:AddSounds("Thalnos the Soulrender", {
	[-5865] = "alarm",
	[115297] = "info",
})

BigWigs:AddColors("Brother Korloff", {
	[114460] = "blue",
	["firestorm"] = "yellow",
	["fists"] = "orange",
})

BigWigs:AddSounds("Brother Korloff", {
	[114460] = "alarm",
	["fists"] = "alert",
})

BigWigs:AddColors("High Inquisitor Whitemane", {
	[113134] = "orange",
	["stages"] = "green",
	["steel"] = "yellow",
})

BigWigs:AddSounds("High Inquisitor Whitemane", {
	[113134] = "alarm",
})

BigWigs:AddColors("The Headless Horseman", {
	[414844] = "orange",
	[415047] = "red",
	[415262] = "yellow",
	[415864] = "blue",
	[418228] = "green",
	[423626] = "orange",
	["curses"] = "blue",
})

BigWigs:AddSounds("The Headless Horseman", {
	[414844] = "alarm",
	[415047] = "alert",
	[415262] = "alarm",
	[415864] = "info",
	[418228] = "info",
	[423626] = "long",
})
