-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Priestess Alun'za", {
	[255558] = {"blue","green"},
	[255577] = "red",
	[255579] = "purple",
	[255582] = {"blue","orange"},
	[259205] = "cyan",
	[277072] = "blue",
})

BigWigs:AddSounds("Priestess Alun'za", {
	[255558] = "warning",
	[255577] = "warning",
	[255579] = "alert",
	[255582] = "alert",
	[259205] = "info",
	[277072] = "underyou",
})

BigWigs:AddColors("Vol'kaal", {
	[250241] = "cyan",
	[250258] = "orange",
	[250585] = "blue",
	[259531] = "cyan",
	[259572] = "red",
})

BigWigs:AddSounds("Vol'kaal", {
	[250241] = "long",
	[250258] = "alarm",
	[250585] = "underyou",
	[259531] = "info",
	[259572] = {"alert","warning"},
})

BigWigs:AddColors("Rezan", {
	[255371] = "red",
	[255421] = {"blue","yellow"},
	[255434] = "purple",
	[257407] = {"blue","green","orange"},
})

BigWigs:AddSounds("Rezan", {
	[255371] = "warning",
	[255421] = "long",
	[255434] = "alert",
	[257407] = {"alarm","alert","info"},
})

BigWigs:AddColors("Yazma", {
	[249919] = "purple",
	[250036] = "blue",
	[250050] = "cyan",
	[250096] = {"blue","orange"},
	[259187] = "red",
})

BigWigs:AddSounds("Yazma", {
	[249919] = {"alarm","alert"},
	[250036] = "underyou",
	[250050] = "info",
	[250096] = "alert",
	[259187] = "warning",
})

BigWigs:AddColors("Atal'Dazar Trash", {
	[252687] = {"blue","orange"},
	[252781] = {"blue","red"},
	[253239] = "red",
	[253517] = "yellow",
	[253544] = "orange",
	[253583] = "red",
	[253721] = "yellow",
	[255041] = "orange",
	[255567] = {"blue","orange"},
	[255626] = "orange",
	[256849] = {"orange","yellow"},
	[256882] = "red",
	[260666] = {"blue","yellow"},
})

BigWigs:AddSounds("Atal'Dazar Trash", {
	[252687] = "info",
	[252781] = {"alarm","warning"},
	[253239] = "alert",
	[253517] = "alert",
	[253544] = "warning",
	[253583] = "alarm",
	[253721] = "long",
	[255041] = "warning",
	[255567] = "alarm",
	[255626] = "alarm",
	[256849] = "warning",
	[256882] = "alert",
	[260666] = {"alarm","alert"},
})
