-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Gu Cloudstrike", {
	[-5630] = {"blue","red"},
	[102573] = "orange",
	[107140] = "yellow",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Gu Cloudstrike", {
	[-5630] = {"alarm","underyou"},
	[102573] = "alarm",
	[107140] = "info",
	["stages"] = "long",
})

BigWigs:AddColors("Master Snowdrift", {
	[106434] = "orange",
	[106454] = "yellow",
	[106747] = "yellow",
	[106853] = "red",
	[118961] = {"blue","red"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("Master Snowdrift", {
	[106434] = "alert",
	[106454] = "alert",
	[106747] = "info",
	[106853] = "alarm",
	[118961] = {"alarm","info"},
	["stages"] = "long",
})

BigWigs:AddColors("Sha of Violence", {
	[38166] = "red",
	[106826] = "yellow",
	[106872] = {"blue","purple"},
})

BigWigs:AddSounds("Sha of Violence", {
	[38166] = "long",
	[106826] = "alert",
	[106872] = {"info","warning"},
})

BigWigs:AddColors("Taran Zhu", {
	[107087] = "blue",
	[107356] = "red",
	[115002] = "yellow",
	[131521] = "orange",
})

BigWigs:AddSounds("Taran Zhu", {
	[107087] = "long",
	[107356] = "warning",
	[115002] = "info",
	[131521] = "alarm",
})

BigWigs:AddColors("Shado-Pan Monastery Trash", {
	[106942] = "orange",
	[111690] = "green",
})

BigWigs:AddSounds("Shado-Pan Monastery Trash", {
	[106942] = "alarm",
	[111690] = "info",
})
