-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Geargrave", {
	[1215905] = "orange",
	[1215912] = "blue",
	[1215957] = "yellow",
	[1215975] = "red",
})

BigWigs:AddSounds("Geargrave", {
	[1215905] = "alarm",
	[1215912] = "underyou",
	[1215957] = "alarm",
	[1215975] = "info",
})

BigWigs:AddColors("Gold Elemental", {
	[473696] = "orange",
})

BigWigs:AddSounds("Gold Elemental", {
	[473696] = "alarm",
})

BigWigs:AddColors("Vindle Snapcrank", {
	[1215337] = "red",
	[1215374] = "cyan",
	[1215870] = "purple",
})

BigWigs:AddSounds("Vindle Snapcrank", {
	[1215337] = "info",
	[1215374] = "long",
	[1215870] = "alarm",
})
