-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Chronikar", {
	[401421] = "orange",
	[413013] = {"green","purple"},
	[413142] = {"blue","yellow"},
})

BigWigs:AddSounds("Chronikar", {
	[401421] = "alert",
	[413013] = {"alarm","info"},
	[413142] = "alarm",
})

BigWigs:AddColors("Manifested Timeways", {
	[405431] = "yellow",
	[405696] = {"blue","orange"},
	[414303] = "purple",
	[414307] = "purple",
})

BigWigs:AddSounds("Manifested Timeways", {
	[405431] = "long",
	[405696] = "alert",
	[414303] = "alarm",
	[414307] = "warning",
})

BigWigs:AddColors("Blight of Galakrond", {
	[406886] = "orange",
	[407147] = "blue",
	[407159] = "purple",
	[407406] = {"blue","red"},
	[407978] = "yellow",
	[408029] = {"blue","cyan","yellow"},
	[408141] = {"blue","orange"},
	[418346] = {"blue","yellow"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("Blight of Galakrond", {
	[406886] = "alert",
	[407147] = "underyou",
	[407159] = "alarm",
	[407406] = "info",
	[407978] = "long",
	[408029] = {"alert","info"},
	[408141] = "alarm",
	[418346] = "warning",
	["stages"] = "long",
})

BigWigs:AddColors("Iridikron the Stonescaled", {
	[409261] = {"blue","orange"},
	[409456] = {"green","red"},
	[409635] = "orange",
	[414184] = "red",
	[414535] = "yellow",
})

BigWigs:AddSounds("Iridikron the Stonescaled", {
	[409261] = {"alert","warning"},
	[409456] = {"alert","info"},
	[409635] = "alarm",
	[414184] = {"long","warning"},
	[414535] = "long",
})

BigWigs:AddColors("Tyr, the Infinite Keeper", {
	[400641] = "yellow",
	[400642] = "cyan",
	[400681] = {"blue","red"},
	[401248] = "purple",
	[401482] = "orange",
	[406543] = "blue",
	[408183] = {"blue","red"},
})

BigWigs:AddSounds("Tyr, the Infinite Keeper", {
	[400641] = "alert",
	[400642] = {"info","long"},
	[400681] = "alert",
	[401248] = "alarm",
	[401482] = "alarm",
	[406543] = "info",
	[408183] = "warning",
})

BigWigs:AddColors("Morchie", {
	[401200] = "blue",
	[401667] = {"blue","red"},
	[403891] = "cyan",
	[404364] = "orange",
	[404916] = "purple",
	[405279] = "yellow",
	[406481] = "green",
})

BigWigs:AddSounds("Morchie", {
	[401200] = "warning",
	[401667] = "alert",
	[403891] = "long",
	[404364] = "alarm",
	[404916] = "alarm",
	[405279] = "alert",
	[406481] = "info",
})

BigWigs:AddColors("Time-Lost Battlefield", {
	[408227] = "orange",
	[410235] = {"blue","red"},
	[410254] = "purple",
	[418046] = "cyan",
	[418047] = "cyan",
	[418054] = "orange",
	[418059] = "purple",
})

BigWigs:AddSounds("Time-Lost Battlefield", {
	[408227] = "alarm",
	[410235] = {"alarm","warning"},
	[410254] = "alert",
	[418046] = "info",
	[418047] = "info",
	[418054] = "alarm",
	[418059] = "alert",
})

BigWigs:AddColors("The Infinite Dragonflight", {
	[410904] = "yellow",
	[412027] = {"blue","yellow"},
	[416139] = "purple",
	[416152] = "red",
	[416264] = "red",
	[417413] = "blue",
	["stages"] = "cyan",
})

BigWigs:AddSounds("The Infinite Dragonflight", {
	[410904] = "alert",
	[412027] = "alert",
	[416139] = "alarm",
	[416152] = "info",
	[416264] = "long",
	[417413] = "underyou",
	["stages"] = "info",
})

BigWigs:AddColors("Dawn of the Infinite Trash", {
	[407124] = "red",
	[407125] = "orange",
	[407205] = {"blue","orange"},
	[407535] = "cyan",
	[407891] = "yellow",
	[407906] = "blue",
	[411300] = "yellow",
	[411407] = "red",
	[411952] = "orange",
	[411958] = "yellow",
	[411994] = "red",
	[412012] = "yellow",
	[412063] = "orange",
	[412129] = "orange",
	[412136] = "orange",
	[412156] = "orange",
	[412200] = "purple",
	[412215] = "orange",
	[412378] = "red",
	[412806] = "orange",
	[412922] = {"blue","red","yellow"},
	[413024] = "yellow",
	[413529] = "orange",
	[413544] = {"blue","purple","yellow"},
	[413607] = "red",
	[413621] = {"blue","orange","red"},
	[413622] = "yellow",
	[415437] = "red",
	[415769] = {"blue","yellow"},
	[415770] = "red",
	[415773] = "orange",
	[417002] = "blue",
	[417011] = "yellow",
	[417481] = "red",
	[418200] = {"blue","red","yellow"},
	[418684] = "cyan",
	[419351] = "purple",
	[419511] = "red",
	[419516] = {"blue","orange","yellow"},
	["rift_stability"] = "green",
})

BigWigs:AddSounds("Dawn of the Infinite Trash", {
	[407124] = "alert",
	[407125] = "alarm",
	[407205] = {"alarm","warning"},
	[407535] = "info",
	[407891] = "warning",
	[407906] = "underyou",
	[411300] = "alert",
	[411407] = "long",
	[411952] = "alarm",
	[411958] = "alert",
	[411994] = "alert",
	[412012] = "alert",
	[412063] = "alarm",
	[412129] = "alarm",
	[412136] = "alarm",
	[412156] = "alarm",
	[412200] = "alarm",
	[412215] = "alarm",
	[412378] = "warning",
	[412806] = "alarm",
	[412922] = {"alarm","info"},
	[413024] = "info",
	[413529] = "alarm",
	[413544] = "alert",
	[413607] = "alert",
	[413621] = {"alarm","info"},
	[413622] = "long",
	[415437] = "alert",
	[415769] = "alert",
	[415770] = "alert",
	[415773] = "alarm",
	[417002] = "underyou",
	[417011] = "warning",
	[417481] = "alert",
	[418200] = "alert",
	[418684] = "info",
	[419351] = "alarm",
	[419511] = "alert",
	[419516] = {"alarm","alert"},
	["rift_stability"] = "info",
})
