-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Elder Nadox", {
	[-6042] = "red",
	[56130] = {"blue","yellow"},
})

BigWigs:AddSounds("Elder Nadox", {
})

BigWigs:AddColors("Prince Taldaram", {
	[55931] = "red",
	[59513] = {"blue","green","red"},
})

BigWigs:AddSounds("Prince Taldaram", {
	[59513] = "warning",
})

BigWigs:AddColors("Jedoga Shadowseeker", {
	[60029] = "red",
})

BigWigs:AddSounds("Jedoga Shadowseeker", {
})

BigWigs:AddColors("Amanitar", {
	[57055] = "yellow",
})

BigWigs:AddSounds("Amanitar", {
	[57055] = "info",
})

BigWigs:AddColors("Herald Volazj", {
	[57496] = "red",
	[59978] = {"blue","yellow"},
})

BigWigs:AddSounds("Herald Volazj", {
})

BigWigs:AddColors("Ahn'kahet Trash", {
	[13338] = {"blue","yellow"},
	[56728] = {"blue","red"},
	[59102] = "red",
})

BigWigs:AddSounds("Ahn'kahet Trash", {
	[13338] = "alarm",
	[56728] = "alert",
	[59102] = {"long","warning"},
})

BigWigs:AddColors("Krik'thir the Gatewatcher", {
	[28747] = "red",
	[52592] = {"blue","yellow"},
})

BigWigs:AddSounds("Krik'thir the Gatewatcher", {
})

BigWigs:AddColors("Hadronox", {
	[53030] = "orange",
	[53400] = "yellow",
})

BigWigs:AddSounds("Hadronox", {
})

BigWigs:AddColors("Anub'arakAN", {
	[-6359] = "cyan",
	[53472] = "yellow",
})

BigWigs:AddSounds("Anub'arakAN", {
	[53472] = "warning",
})

BigWigs:AddColors("Trollgore", {
	[49637] = {"blue","orange"},
	[49639] = "red",
	[59803] = "yellow",
})

BigWigs:AddSounds("Trollgore", {
})

BigWigs:AddColors("Novos the Summoner", {
	[47346] = "blue",
	[49034] = "blue",
	[50089] = {"blue","orange"},
	[59910] = "yellow",
	["adds"] = "yellow",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Novos the Summoner", {
	[47346] = "alert",
	[49034] = "alert",
	["adds"] = "info",
})

BigWigs:AddColors("King Dred", {
	[48878] = {"blue","purple"},
	[59416] = "cyan",
})

BigWigs:AddSounds("King Dred", {
	[48878] = "alarm",
	[59416] = "info",
})

BigWigs:AddColors("The Prophet Tharon'ja", {
	[49527] = {"blue","orange"},
	[59971] = "blue",
	["stages"] = "cyan",
})

BigWigs:AddSounds("The Prophet Tharon'ja", {
	[59971] = "underyou",
})

BigWigs:AddColors("Slad'ran", {
	[59842] = {"blue","yellow"},
})

BigWigs:AddSounds("Slad'ran", {
	[59842] = {"alarm","info"},
})

BigWigs:AddColors("Drakkari Colossus", {
	[59451] = "blue",
	["stages"] = {"red","yellow"},
})

BigWigs:AddSounds("Drakkari Colossus", {
	[59451] = "underyou",
	["stages"] = "long",
})

BigWigs:AddColors("Moorabi", {
	[55098] = {"green","orange"},
})

BigWigs:AddSounds("Moorabi", {
	[55098] = "warning",
})

BigWigs:AddColors("Eck the Ferocious", {
	[55817] = "blue",
})

BigWigs:AddSounds("Eck the Ferocious", {
	[55817] = "info",
})

BigWigs:AddColors("Gal'darah", {
	[59825] = "blue",
	[59827] = {"blue","yellow"},
	["forms"] = "yellow",
})

BigWigs:AddSounds("Gal'darah", {
	[59825] = "alarm",
	[59827] = "info",
})

BigWigs:AddColors("General Bjarngrim", {
	[16856] = {"blue","red"},
	[41107] = {"green","orange"},
})

BigWigs:AddSounds("General Bjarngrim", {
})

BigWigs:AddColors("Volkhan", {
	[59529] = "orange",
})

BigWigs:AddSounds("Volkhan", {
})

BigWigs:AddColors("Ionar", {
	[52658] = {"blue","yellow"},
	[52770] = "cyan",
})

BigWigs:AddSounds("Ionar", {
	[52658] = "alarm",
	[52770] = "info",
})

BigWigs:AddColors("Loken", {
	[59835] = "orange",
})

BigWigs:AddSounds("Loken", {
	[59835] = "alert",
})

BigWigs:AddColors("Halls of Lightning Trash", {
	[59165] = {"blue","yellow"},
	[61581] = "red",
})

BigWigs:AddSounds("Halls of Lightning Trash", {
	[59165] = "alarm",
	[61581] = {"long","warning"},
})

BigWigs:AddColors("Falric", {
	[72422] = {"blue","orange"},
	[72426] = {"blue","red"},
})

BigWigs:AddSounds("Falric", {
	[72426] = "warning",
})

BigWigs:AddColors("Marwyn", {
	[72363] = "red",
	[72368] = {"blue","yellow"},
	[72383] = {"blue","orange"},
})

BigWigs:AddSounds("Marwyn", {
})

BigWigs:AddColors("Krystallus", {
	[50810] = "orange",
})

BigWigs:AddSounds("Krystallus", {
})

BigWigs:AddColors("Maiden of Grief", {
	[59726] = {"blue","orange","red"},
	[59772] = "blue",
})

BigWigs:AddSounds("Maiden of Grief", {
	[59726] = "warning",
	[59772] = "alert",
})

BigWigs:AddColors("Tribunal of Ages", {
	[59866] = "blue",
	[59868] = {"blue","orange"},
	["timers"] = "yellow",
})

BigWigs:AddSounds("Tribunal of Ages", {
	[59866] = "alert",
	[59868] = "alarm",
	["timers"] = "info",
})

BigWigs:AddColors("Sjonnir The Ironshaper", {
	[50834] = {"blue","yellow"},
	[50840] = "orange",
})

BigWigs:AddSounds("Sjonnir The Ironshaper", {
	[50834] = "alarm",
})

BigWigs:AddColors("Forgemaster Garfrost", {
	[68789] = "red",
	[70381] = {"blue","yellow"},
})

BigWigs:AddSounds("Forgemaster Garfrost", {
	[68789] = "alarm",
	[70381] = "alert",
})

BigWigs:AddColors("Ick & Krick", {
	[68987] = {"blue","yellow"},
	[68989] = "orange",
	[69263] = "red",
	[70274] = "blue",
})

BigWigs:AddSounds("Ick & Krick", {
	[68987] = "alert",
	[70274] = "underyou",
})

BigWigs:AddColors("Scourgelord Tyrannus", {
	[69167] = "red",
	[69172] = {"blue","yellow"},
	[69275] = {"blue","red"},
})

BigWigs:AddSounds("Scourgelord Tyrannus", {
	[69172] = "alert",
	[69275] = "alarm",
})

BigWigs:AddColors("Meathook", {
	[52696] = {"blue","red"},
})

BigWigs:AddSounds("Meathook", {
})

BigWigs:AddColors("Salramm the Fleshcrafter", {
	[58845] = {"blue","red"},
})

BigWigs:AddSounds("Salramm the Fleshcrafter", {
})

BigWigs:AddColors("Chrono-Lord Epoch", {
	[52772] = {"blue","red"},
})

BigWigs:AddSounds("Chrono-Lord Epoch", {
	[52772] = "alert",
})

BigWigs:AddColors("Mal'Ganis", {
	[52721] = {"blue","red"},
	[52723] = "orange",
})

BigWigs:AddSounds("Mal'Ganis", {
	[52723] = "info",
})

BigWigs:AddColors("Infinite Corruptor", {
	[60588] = {"blue","red"},
})

BigWigs:AddSounds("Infinite Corruptor", {
})

BigWigs:AddColors("The Culling of Stratholme Trash", {
})

BigWigs:AddSounds("The Culling of Stratholme Trash", {
})

BigWigs:AddColors("Bronjahm", {
	[68839] = {"blue","orange"},
	[68872] = "red",
})

BigWigs:AddSounds("Bronjahm", {
	[68839] = "alert",
})

BigWigs:AddColors("Devourer of Souls", {
	[68912] = "red",
	[69051] = {"blue","orange"},
})

BigWigs:AddSounds("Devourer of Souls", {
	[69051] = "alert",
})

BigWigs:AddColors("Commander Kolurg/Stoutbeard", {
	[38618] = "orange",
})

BigWigs:AddSounds("Commander Kolurg/Stoutbeard", {
	[38618] = "info",
})

BigWigs:AddColors("Grand Magus Telestra", {
	[-7395] = "green",
	[47731] = {"blue","orange"},
})

BigWigs:AddSounds("Grand Magus Telestra", {
	[47731] = "alert",
})

BigWigs:AddColors("Anomalus", {
	[47743] = "yellow",
})

BigWigs:AddSounds("Anomalus", {
})

BigWigs:AddColors("Ormorok the Tree-Shaper", {
	[47981] = "yellow",
	[48017] = "red",
})

BigWigs:AddSounds("Ormorok the Tree-Shaper", {
})

BigWigs:AddColors("Keristrasza", {
	[8599] = "red",
	[48095] = "blue",
	[48179] = "orange",
	[50997] = {"blue","yellow"},
})

BigWigs:AddSounds("Keristrasza", {
	[8599] = "info",
	[48095] = "alarm",
})

BigWigs:AddColors("The Nexus Trash", {
	[30849] = {"blue","yellow"},
	[47779] = {"blue","orange"},
})

BigWigs:AddSounds("The Nexus Trash", {
	[30849] = "alarm",
	[47779] = "alert",
})

BigWigs:AddColors("Drakos the Interrogator", {
	[50774] = "red",
})

BigWigs:AddSounds("Drakos the Interrogator", {
	[50774] = "alarm",
})

BigWigs:AddColors("Varos Cloudstrider", {
	[-7442] = "cyan",
	[51021] = "blue",
	[51054] = {"blue","red"},
})

BigWigs:AddSounds("Varos Cloudstrider", {
	[-7442] = "info",
	[51021] = "underyou",
})

BigWigs:AddColors("Mage-Lord Urom", {
	[51103] = "blue",
	[51110] = "yellow",
	[51121] = {"blue","orange"},
})

BigWigs:AddSounds("Mage-Lord Urom", {
	[51103] = "underyou",
	[51110] = "alarm",
	[51121] = "alert",
})

BigWigs:AddColors("Ley-Guardian Eregos", {
	[51162] = "red",
	[51170] = "yellow",
})

BigWigs:AddSounds("Ley-Guardian Eregos", {
})

BigWigs:AddColors("Erekem", {
	[54479] = "yellow",
	[54481] = "orange",
	[54516] = "red",
})

BigWigs:AddSounds("Erekem", {
	[54479] = "alert",
	[54481] = "warning",
	[54516] = "long",
})

BigWigs:AddColors("Moragg", {
	[54396] = {"blue","orange"},
})

BigWigs:AddSounds("Moragg", {
	[54396] = "alert",
})

BigWigs:AddColors("Ichoron", {
	[54241] = "orange",
	[54306] = {"green","yellow"},
	[54312] = "red",
})

BigWigs:AddSounds("Ichoron", {
	[54306] = {"info","long"},
	[54312] = {"alarm","alert"},
})

BigWigs:AddColors("Xevozz", {
	[54102] = "red",
	[54160] = "purple",
})

BigWigs:AddSounds("Xevozz", {
	[54102] = "alert",
	[54160] = {"info","warning"},
})

BigWigs:AddColors("Lavanthor", {
	[-7491] = "red",
	[54249] = {"blue","orange"},
	[54282] = "purple",
})

BigWigs:AddSounds("Lavanthor", {
	[-7491] = {"long","warning"},
	[54249] = "alarm",
	[54282] = "alert",
})

BigWigs:AddColors("Zuramat the Obliterator", {
	[54361] = {"blue","yellow"},
	[54524] = {"green","orange","red"},
})

BigWigs:AddSounds("Zuramat the Obliterator", {
	[54361] = "long",
	[54524] = {"alarm","alert","info","warning"},
})

BigWigs:AddColors("Cyanigosa", {
	[58688] = "purple",
	[58693] = "blue",
	[58694] = "yellow",
	[59374] = {"blue","red"},
})

BigWigs:AddSounds("Cyanigosa", {
	[58688] = "alert",
	[58693] = "alarm",
	[58694] = "info",
	[59374] = "alert",
})

BigWigs:AddColors("The Violet Hold Trash", {
	["portals"] = "cyan",
})

BigWigs:AddSounds("The Violet Hold Trash", {
	["portals"] = "info",
})

BigWigs:AddColors("Grand Champions", {
	[-7534] = "blue",
	[66043] = {"blue","yellow"},
	[67528] = "orange",
	[67534] = {"blue","yellow"},
})

BigWigs:AddSounds("Grand Champions", {
	[-7534] = "alarm",
})

BigWigs:AddColors("Eadric the Pure", {
	[66935] = "orange",
})

BigWigs:AddSounds("Eadric the Pure", {
})

BigWigs:AddColors("Argent Confessor Paletress", {
	[66515] = {"green","red","yellow"},
	[66537] = "orange",
	[66619] = {"blue","yellow"},
	["confess"] = {"red","yellow"},
})

BigWigs:AddSounds("Argent Confessor Paletress", {
	[66515] = "info",
})

BigWigs:AddColors("The Black Knight", {
	[-7598] = "orange",
	[67781] = "blue",
})

BigWigs:AddSounds("The Black Knight", {
	[67781] = "alarm",
})

BigWigs:AddColors("Trial of the Champion Trash", {
})

BigWigs:AddSounds("Trial of the Champion Trash", {
})

BigWigs:AddColors("Prince Keleseth", {
	[48400] = {"blue","red"},
})

BigWigs:AddSounds("Prince Keleseth", {
	[48400] = "warning",
})

BigWigs:AddColors("Skarvald & Dalronn", {
	[43650] = {"blue","yellow"},
	["stages"] = "green",
})

BigWigs:AddSounds("Skarvald & Dalronn", {
	["stages"] = "info",
})

BigWigs:AddColors("Ingvar the Plunderer", {
	[42669] = "yellow",
	[42708] = "red",
	[42730] = {"blue","orange"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("Ingvar the Plunderer", {
	[42708] = "warning",
	[42730] = "alarm",
})

BigWigs:AddColors("Svala Sorrowgrave", {
	[48267] = {"blue","red"},
	[48276] = {"orange","yellow"},
})

BigWigs:AddSounds("Svala Sorrowgrave", {
	[48276] = "info",
})

BigWigs:AddColors("Gortok Palehoof", {
	[59267] = "orange",
	[59268] = {"blue","yellow"},
})

BigWigs:AddSounds("Gortok Palehoof", {
})

BigWigs:AddColors("Skadi the Ruthless", {
	[59322] = {"blue","orange"},
})

BigWigs:AddSounds("Skadi the Ruthless", {
	[59322] = {"info","underyou"},
})

BigWigs:AddColors("King Ymiron", {
	[59300] = {"blue","orange"},
	[59301] = {"green","orange"},
})

BigWigs:AddSounds("King Ymiron", {
	[59301] = {"alert","info"},
})

BigWigs:AddColors("Utgarde Pinnacle Trash", {
	[49106] = {"blue","orange"},
})

BigWigs:AddSounds("Utgarde Pinnacle Trash", {
	[49106] = "alert",
})
