-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Essence of Order", {
	[134225] = "orange",
	[134234] = "yellow",
})

BigWigs:AddSounds("Essence of Order", {
	[134225] = "long",
	[134234] = "alert",
})

BigWigs:AddColors("Kanrethad Ebonlocke", {
	[1098] = "cyan",
	[138559] = "orange",
	[138560] = {"blue","green"},
	[138561] = "blue",
	[138564] = {"green","red"},
	[138685] = "yellow",
	[138751] = "yellow",
	[138755] = "yellow",
	[138789] = "yellow",
	[139060] = "orange",
})

BigWigs:AddSounds("Kanrethad Ebonlocke", {
	[138559] = "long",
	[138560] = "alarm",
	[138561] = "alert",
	[138564] = "warning",
	[139060] = "warning",
})

BigWigs:AddColors("Saboteur Kip'tilak", {
	[-5394] = "yellow",
	[107268] = {"blue","red"},
})

BigWigs:AddSounds("Saboteur Kip'tilak", {
	[107268] = "alarm",
})

BigWigs:AddColors("Striker Ga'dok", {
	[-5660] = {"blue","yellow"},
	[106933] = {"blue","red"},
	[115458] = "blue",
})

BigWigs:AddSounds("Striker Ga'dok", {
	[-5660] = "alert",
	[106933] = "info",
	[115458] = "alert",
})

BigWigs:AddColors("Commander Ri'mok", {
	[-5666] = {"blue","orange","red"},
	[106874] = "blue",
	[107120] = {"blue","yellow"},
})

BigWigs:AddSounds("Commander Ri'mok", {
	[-5666] = {"alarm","info"},
	[106874] = "alert",
	[107120] = {"alert","long"},
})

BigWigs:AddColors("Raigonn", {
	[111668] = "orange",
	[111723] = {"blue","red"},
	[111728] = "yellow",
	["stages"] = {"cyan","green"},
})

BigWigs:AddSounds("Raigonn", {
	[111668] = "alarm",
	[111723] = "long",
	[111728] = "alert",
	["stages"] = "info",
})

BigWigs:AddColors("Trial of the King", {
	[-6024] = {"blue","yellow"},
	[-6017] = {"blue","yellow"},
	[119922] = "orange",
	[119981] = "orange",
	[120100] = "yellow",
	[120195] = {"blue","red"},
	[123655] = {"blue","red"},
})

BigWigs:AddSounds("Trial of the King", {
	[-6024] = "alert",
	[-6017] = "alarm",
	[119922] = "alarm",
	[119981] = "alarm",
	[120100] = "long",
	[120195] = "alarm",
	[123655] = "alert",
})

BigWigs:AddColors("Gekkan", {
	[118903] = {"blue","red"},
	[118940] = "orange",
	[118963] = {"blue","purple","yellow"},
	[118988] = "red",
	["stages"] = "green",
})

BigWigs:AddSounds("Gekkan", {
	[118940] = "alert",
	[118963] = "warning",
	["stages"] = "info",
})

BigWigs:AddColors("Xin the Weaponmaster", {
	[-5974] = "cyan",
	[-5973] = "red",
	[-5972] = "cyan",
	[-5971] = "cyan",
	[119684] = "purple",
})

BigWigs:AddSounds("Xin the Weaponmaster", {
	[-5974] = "long",
	[-5973] = "alert",
	[-5972] = "long",
	[-5971] = "long",
	[119684] = "alarm",
})

BigWigs:AddColors("Houndmaster Braun", {
	[114259] = "orange",
	[116140] = {"green","yellow"},
})

BigWigs:AddSounds("Houndmaster Braun", {
	[114259] = "alert",
	[116140] = {"alert","info"},
})

BigWigs:AddColors("Armsmaster Harlan", {
	[-5378] = "cyan",
	[111216] = {"green","orange"},
	[111217] = "purple",
})

BigWigs:AddSounds("Armsmaster Harlan", {
	[-5378] = "info",
	[111216] = {"info","warning"},
})

BigWigs:AddColors("Flameweaver Koegler", {
	[113364] = "red",
	[113641] = {"green","yellow"},
	[113682] = "orange",
})

BigWigs:AddSounds("Flameweaver Koegler", {
	[113364] = "info",
	[113641] = "long",
	[113682] = "alert",
})

BigWigs:AddColors("Thalnos the Soulrender", {
	[-5865] = {"blue","yellow"},
	[115297] = {"blue","orange"},
})

BigWigs:AddSounds("Thalnos the Soulrender", {
	[-5865] = "alarm",
	[115297] = "info",
})

BigWigs:AddColors("Brother Korloff", {
	[114460] = "blue",
	["firestorm"] = "yellow",
	["fists"] = "orange",
})

BigWigs:AddSounds("Brother Korloff", {
	[114460] = "alarm",
	["fists"] = "alert",
})

BigWigs:AddColors("High Inquisitor Whitemane", {
	[113134] = "orange",
	["stages"] = "green",
	["steel"] = "yellow",
})

BigWigs:AddSounds("High Inquisitor Whitemane", {
	[113134] = "alarm",
})

BigWigs:AddColors("The Headless Horseman", {
	[414844] = "orange",
	[415047] = "red",
	[415262] = "yellow",
	[415864] = "blue",
	[418228] = "green",
	[423626] = "orange",
	["curses"] = "blue",
})

BigWigs:AddSounds("The Headless Horseman", {
	[414844] = "alarm",
	[415047] = "alert",
	[415262] = "alarm",
	[415864] = "info",
	[418228] = "info",
	[423626] = "long",
})

BigWigs:AddColors("Instructor Chillheart", {
	[111209] = "orange",
	[111441] = "cyan",
	[111610] = {"blue","yellow"},
	[111631] = {"blue","red"},
	[111854] = "cyan",
})

BigWigs:AddSounds("Instructor Chillheart", {
	[111209] = "alarm",
	[111441] = "long",
	[111610] = "alert",
	[111631] = "alert",
	[111854] = "info",
})

BigWigs:AddColors("Jandice Barov", {
	[-5535] = {"cyan","green"},
	[114059] = "orange",
	[114062] = "purple",
})

BigWigs:AddSounds("Jandice Barov", {
	[-5535] = {"info","long"},
	[114059] = "alarm",
	[114062] = "alarm",
})

BigWigs:AddColors("Rattlegore", {
	[113765] = "purple",
	[113996] = {"green","red"},
	[113999] = "yellow",
})

BigWigs:AddSounds("Rattlegore", {
	[113765] = "info",
	[113996] = {"alarm","info"},
	[113999] = "alert",
})

BigWigs:AddColors("Lilian Voss", {
	[111570] = "orange",
	[111775] = "red",
	[115350] = {"blue","yellow"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("Lilian Voss", {
	[111570] = "long",
	[111775] = "alert",
	[115350] = {"alert","warning"},
	["stages"] = "long",
})

BigWigs:AddColors("Darkmaster Gandling", {
	[113143] = "cyan",
	[113395] = {"blue","red"},
})

BigWigs:AddSounds("Darkmaster Gandling", {
	[113143] = "long",
	[113395] = "info",
})

BigWigs:AddColors("Gu Cloudstrike", {
	[-5630] = {"blue","red"},
	[102573] = "orange",
	[107140] = "yellow",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Gu Cloudstrike", {
	[-5630] = {"alarm","underyou"},
	[102573] = "alarm",
	[107140] = "info",
	["stages"] = "long",
})

BigWigs:AddColors("Master Snowdrift", {
	[106434] = "orange",
	[106454] = "yellow",
	[106747] = "yellow",
	[106853] = "red",
	[118961] = {"blue","red"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("Master Snowdrift", {
	[106434] = "alert",
	[106454] = "alert",
	[106747] = "info",
	[106853] = "alarm",
	[118961] = {"alarm","info"},
	["stages"] = "long",
})

BigWigs:AddColors("Sha of Violence", {
	[38166] = "red",
	[106826] = "yellow",
	[106872] = {"blue","purple"},
})

BigWigs:AddSounds("Sha of Violence", {
	[38166] = "long",
	[106826] = "alert",
	[106872] = {"info","warning"},
})

BigWigs:AddColors("Taran Zhu", {
	[107087] = "blue",
	[107356] = "red",
	[115002] = "yellow",
	[131521] = "orange",
})

BigWigs:AddSounds("Taran Zhu", {
	[107087] = "long",
	[107356] = "warning",
	[115002] = "info",
	[131521] = "alarm",
})

BigWigs:AddColors("Shado-Pan Monastery Trash", {
	[106942] = "orange",
	[111690] = "green",
})

BigWigs:AddSounds("Shado-Pan Monastery Trash", {
	[106942] = "alarm",
	[111690] = "info",
})

BigWigs:AddColors("Vizier Jin'bak", {
	[-5960] = "blue",
	[-5959] = "red",
	[-5958] = "yellow",
})

BigWigs:AddSounds("Vizier Jin'bak", {
	[-5960] = "alert",
	[-5959] = "alarm",
	[-5958] = "info",
})

BigWigs:AddColors("Commander Vo'jak", {
	[-6287] = {"blue","red"},
	[120778] = "blue",
	[120789] = {"blue","yellow"},
})

BigWigs:AddSounds("Commander Vo'jak", {
	[-6287] = {"alert","long"},
	[120778] = "warning",
	[120789] = "alarm",
})

BigWigs:AddColors("General Pa'valak", {
	[-5946] = "yellow",
	[119875] = "red",
	[124283] = "orange",
})

BigWigs:AddSounds("General Pa'valak", {
	[-5946] = "info",
	[119875] = "alert",
	[124283] = "alarm",
})

BigWigs:AddColors("Wing Leader Ner'onok", {
	[-6205] = {"blue","green"},
	[121284] = {"green","orange"},
	[121443] = "blue",
	["stages"] = "yellow",
})

BigWigs:AddSounds("Wing Leader Ner'onok", {
	[-6205] = {"alarm","info"},
	[121284] = {"long","warning"},
	[121443] = "alert",
})

BigWigs:AddColors("Ook-Ook", {
	[106648] = "blue",
	[106651] = "cyan",
	[106807] = "red",
})

BigWigs:AddSounds("Ook-Ook", {
	[106648] = "alert",
	[106651] = "info",
	[106807] = {"alarm","long"},
})

BigWigs:AddColors("Hoptallus", {
	[112944] = "red",
	[112992] = {"blue","yellow"},
	[114291] = "orange",
})

BigWigs:AddSounds("Hoptallus", {
	[112944] = "alarm",
	[112992] = {"alert","long"},
	[114291] = "alert",
})

BigWigs:AddColors("Yan-Zhu the Uncasked", {
	[-5658] = "red",
	[106546] = {"blue","yellow"},
	[106563] = {"green","orange"},
	[106851] = {"blue","yellow"},
	[114451] = "orange",
	[114548] = {"blue","red"},
	[115003] = "red",
	["summon"] = "cyan",
})

BigWigs:AddSounds("Yan-Zhu the Uncasked", {
	[-5658] = "long",
	[106546] = "alarm",
	[106563] = {"alert","info"},
	[106851] = {"alarm","warning"},
	[114451] = "warning",
	[114548] = "alert",
	[115003] = "long",
})

BigWigs:AddColors("Wise Mari", {
	[-6327] = {"green","red"},
	[106653] = "blue",
	[115167] = "blue",
	[397785] = "red",
	[397797] = {"blue","yellow"},
	["stages"] = "green",
})

BigWigs:AddSounds("Wise Mari", {
	[-6327] = {"alarm","info"},
	[106653] = "underyou",
	[115167] = "underyou",
	[397785] = "warning",
	[397797] = {"alarm","alert","underyou"},
	["stages"] = "info",
})

BigWigs:AddColors("Lorewalker Stonestep", {
	[-5549] = {"green","orange","red"},
	[396150] = "blue",
	[396152] = {"blue","green"},
	["stages"] = "green",
})

BigWigs:AddSounds("Lorewalker Stonestep", {
	[-5549] = {"alert","info","long","warning"},
	[396150] = {"alarm","alert","info"},
	[396152] = "info",
	["stages"] = "info",
})

BigWigs:AddColors("Liu Flameheart", {
	[106823] = {"blue","purple"},
	[106841] = {"blue","purple"},
	[106856] = "orange",
	[106864] = "orange",
	[107045] = {"blue","orange"},
	[118540] = "blue",
	[396907] = "purple",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Liu Flameheart", {
	[106823] = "alert",
	[106841] = "alert",
	[106856] = "alarm",
	[106864] = "alarm",
	[107045] = {"alarm","underyou"},
	[118540] = "underyou",
	[396907] = "alarm",
	["stages"] = {"info","long"},
})

BigWigs:AddColors("Sha of Doubt", {
	[106113] = {"blue","yellow"},
	[117665] = {"cyan","green","orange"},
})

BigWigs:AddSounds("Sha of Doubt", {
	[106113] = "alarm",
	[117665] = {"info","long"},
})

BigWigs:AddColors("Temple of the Jade Serpent Trash", {
	[110125] = {"blue","red"},
	[114646] = "purple",
	[395859] = "red",
	[395872] = {"blue","yellow"},
	[396001] = "orange",
	[396018] = {"purple","red"},
	[396020] = {"orange","yellow"},
	[396073] = "yellow",
	[397878] = "red",
	[397881] = "orange",
	[397889] = "yellow",
	[397899] = "orange",
	[397911] = {"blue","yellow"},
	[397914] = "red",
	[397931] = "purple",
	[398300] = "orange",
})

BigWigs:AddSounds("Temple of the Jade Serpent Trash", {
	[110125] = "alert",
	[114646] = "alert",
	[395859] = "warning",
	[395872] = {"alert","warning"},
	[396001] = "alarm",
	[396018] = {"alert","info"},
	[396020] = {"alarm","alert"},
	[396073] = "warning",
	[397878] = "long",
	[397881] = "alarm",
	[397889] = "alert",
	[397899] = "alarm",
	[397911] = {"alert","warning"},
	[397914] = "alert",
	[397931] = "alert",
	[398300] = "alarm",
})
