-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Krystallus", {
	[50810] = "orange",
})

BigWigs:AddSounds("Krystallus", {
})

BigWigs:AddColors("Maiden of Grief", {
	[59726] = {"blue","orange","red"},
	[59772] = "blue",
})

BigWigs:AddSounds("Maiden of Grief", {
	[59726] = "warning",
	[59772] = "alert",
})

BigWigs:AddColors("Tribunal of Ages", {
	[59866] = "blue",
	[59868] = {"blue","orange"},
	["timers"] = "yellow",
})

BigWigs:AddSounds("Tribunal of Ages", {
	[59866] = "alert",
	[59868] = "alarm",
	["timers"] = "info",
})

BigWigs:AddColors("Sjonnir The Ironshaper", {
	[50834] = {"blue","yellow"},
	[50840] = "orange",
})

BigWigs:AddSounds("Sjonnir The Ironshaper", {
	[50834] = "alarm",
})
