-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Craggle Fritzbrains", {
	[1214135] = "yellow",
	[1214504] = {"orange","red"},
})

BigWigs:AddSounds("Craggle Fritzbrains", {
	[1214135] = "long",
	[1214504] = {"alert","info","warning"},
})

BigWigs:AddColors("Harbinger Ul'thul", {
	[1213700] = {"blue","red"},
	[1213776] = {"blue","orange"},
	[1213785] = "yellow",
})

BigWigs:AddSounds("Harbinger Ul'thul", {
	[1213700] = {"alarm","warning"},
	[1213776] = {"alert","warning"},
	[1213785] = "info",
})

BigWigs:AddColors("Xel'anegh The Many", {
	[1213275] = "green",
	[1213425] = "red",
	[1213426] = "orange",
	[1213804] = "yellow",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Xel'anegh The Many", {
	[1213425] = "warning",
	[1213426] = "alarm",
	[1213804] = "long",
	["stages"] = "info",
})
