-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Archdruid Glaidalis", {
	[196354] = "yellow",
	[196376] = {"blue","red"},
	[198379] = "orange",
	[198477] = {"blue","red"},
	[212464] = {"blue","cyan"},
})

BigWigs:AddSounds("Archdruid Glaidalis", {
	[196354] = "alarm",
	[196376] = "alert",
	[198379] = "alarm",
	[198477] = "alert",
	[212464] = {"info","underyou"},
})

BigWigs:AddColors("Oakheart", {
	[204574] = {"blue","red","yellow"},
	[204611] = {"blue","orange","purple"},
	[204666] = "red",
	[204667] = "purple",
	[212786] = "cyan",
})

BigWigs:AddSounds("Oakheart", {
	[204574] = {"alert","info"},
	[204611] = {"alarm","alert"},
	[204666] = "alert",
	[204667] = "alarm",
	[212786] = "long",
})

BigWigs:AddColors("Dresaron", {
	[191325] = "orange",
	[199345] = "yellow",
	[199389] = "red",
	[199460] = "blue",
})

BigWigs:AddSounds("Dresaron", {
	[191325] = "alarm",
	[199345] = "long",
	[199389] = "alert",
	[199460] = "underyou",
})

BigWigs:AddColors("Shade of Xavius", {
	[200050] = "cyan",
	[200182] = {"blue","yellow"},
	[200185] = {"blue","yellow"},
	[200238] = {"blue","red"},
	[200243] = "blue",
	[200289] = {"blue","orange"},
})

BigWigs:AddSounds("Shade of Xavius", {
	[200050] = "long",
	[200182] = "alert",
	[200185] = "info",
	[200238] = "alert",
	[200243] = "alarm",
	[200289] = "alarm",
})

BigWigs:AddColors("Darkheart Thicket Trash", {
	[198904] = {"blue","yellow"},
	[198910] = "red",
	[200580] = "red",
	[200630] = "red",
	[200642] = {"blue","yellow"},
	[200658] = "yellow",
	[200684] = {"blue","red"},
	[200768] = "orange",
	[201129] = "orange",
	[201226] = "orange",
	[201272] = "yellow",
	[201365] = {"blue","yellow"},
	[201399] = "red",
	[201839] = {"blue","orange"},
	[204243] = "red",
	[204246] = {"blue","yellow"},
	[218759] = "blue",
	[225562] = "red",
})

BigWigs:AddSounds("Darkheart Thicket Trash", {
	[198904] = "alert",
	[198910] = "info",
	[200580] = "alarm",
	[200630] = "alert",
	[200642] = {"alert","warning"},
	[200658] = "alert",
	[200684] = "alert",
	[200768] = "alarm",
	[201129] = "alarm",
	[201226] = "alarm",
	[201272] = "info",
	[201365] = "alert",
	[201399] = "alert",
	[201839] = "alarm",
	[204243] = "alert",
	[204246] = "alarm",
	[218759] = "underyou",
	[225562] = "alert",
})
