-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("The Underpin", {
	[1213852] = "orange",
	[1214043] = "orange",
	[1214052] = {"cyan","green"},
	[1214147] = "yellow",
	[1215521] = "cyan",
	[1217371] = "red",
	[1218153] = "blue",
})

BigWigs:AddSounds("The Underpin", {
	[1213852] = "alarm",
	[1214043] = "alarm",
	[1214052] = {"info","warning"},
	[1214147] = "info",
	[1215521] = "long",
	[1217371] = "alarm",
	[1218153] = "underyou",
})

BigWigs:AddColors("The Underpin 2", {
	[1213852] = "orange",
	[1214043] = "orange",
	[1214147] = "yellow",
	[1217371] = "red",
	[1217661] = "cyan",
	[1217667] = {"cyan","green"},
	[1218153] = "blue",
})

BigWigs:AddSounds("The Underpin 2", {
	[1213852] = "alarm",
	[1214043] = "alarm",
	[1214147] = "info",
	[1217371] = "alarm",
	[1217661] = "long",
	[1217667] = {"info","warning"},
	[1218153] = "underyou",
})
