-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Agatha", {
	[236161] = "blue",
	[242989] = "cyan",
	[243027] = {"green","orange"},
	[243111] = {"green","red"},
	["fuming_imp"] = "orange",
	["imp_servant"] = "yellow",
})

BigWigs:AddSounds("Agatha", {
	[236161] = "alarm",
	[243027] = "alert",
	[243111] = "long",
	["fuming_imp"] = "warning",
	["imp_servant"] = "info",
})

BigWigs:AddColors("Archmage Xylem", {
	[231443] = "orange",
	[231522] = "red",
	[232672] = "blue",
	[233248] = "red",
	[234728] = "cyan",
	[242015] = "yellow",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Archmage Xylem", {
	[231443] = "alarm",
	[231522] = "alert",
	[232672] = "alarm",
	[233248] = "long",
})

BigWigs:AddColors("Kruul", {
	[233473] = "green",
	[234422] = "blue",
	[234423] = "orange",
	[234428] = "yellow",
	[234631] = "red",
	[234673] = "orange",
	[234676] = "orange",
	[234920] = "yellow",
	[236572] = "red",
	[240790] = "red",
	["nether_aberration"] = "cyan",
	["smoldering_infernal"] = "yellow",
	["stages"] = "green",
})

BigWigs:AddSounds("Kruul", {
	[233473] = "long",
	[234422] = "warning",
	[234423] = "alert",
	[234428] = "info",
	[234631] = "alarm",
	[234673] = "alert",
	[234676] = "warning",
	[234920] = "info",
	[236572] = "alarm",
	[240790] = "warning",
	["nether_aberration"] = "info",
	["smoldering_infernal"] = "info",
	["stages"] = "long",
})

BigWigs:AddColors("Lord Erdris Thorn", {
	[235823] = "orange",
	[235833] = "yellow",
	[235984] = "red",
	[236720] = "red",
	[237188] = "red",
	[237191] = "orange",
})

BigWigs:AddSounds("Lord Erdris Thorn", {
	[235823] = "alarm",
	[235833] = "alert",
	[235984] = "alert",
	[236720] = "alarm",
	[237188] = "warning",
	[237191] = "alarm",
})

BigWigs:AddColors("Raest", {
	[202081] = "red",
	[235308] = "green",
	[235578] = {"blue","orange"},
	["handFromBeyond"] = "cyan",
	["rune"] = "yellow",
	["thing"] = "yellow",
})

BigWigs:AddSounds("Raest", {
	[202081] = "long",
	[235308] = "info",
	[235578] = "alert",
	["rune"] = "warning",
	["thing"] = "alarm",
})

BigWigs:AddColors("Sigryn", {
	[237730] = "orange",
	[237857] = "yellow",
	[237914] = "red",
	[237945] = {"green","red"},
	[237947] = {"green","orange"},
	[237949] = {"green","orange"},
	[238691] = "blue",
	[238694] = "yellow",
})

BigWigs:AddSounds("Sigryn", {
	[237730] = "alarm",
	[237857] = "alarm",
	[237914] = "warning",
	[237945] = {"info","long"},
	[237947] = {"alarm","info"},
	[237949] = {"alert","info"},
	[238691] = "alarm",
	[238694] = "info",
})

BigWigs:AddColors("Tugar Bloodtotem", {
	[241687] = "red",
	[242733] = "orange",
	[243224] = {"blue","red"},
	["charge"] = "blue",
	["rupture"] = "yellow",
	["submerge"] = "orange",
})

BigWigs:AddSounds("Tugar Bloodtotem", {
	[241687] = "alert",
	[242733] = "warning",
	[243224] = "long",
	["charge"] = "alarm",
	["rupture"] = "alarm",
	["submerge"] = "alarm",
})

BigWigs:AddColors("Shivermaw", {
	[201354] = "orange",
	[201355] = "orange",
	[201379] = "yellow",
	[201672] = "red",
	[201960] = "cyan",
	[202062] = "red",
})

BigWigs:AddSounds("Shivermaw", {
	[201354] = "alarm",
	[201355] = "alert",
	[201379] = "warning",
	[201672] = "long",
	[201960] = "info",
	[202062] = "warning",
})

BigWigs:AddColors("Thalena", {
	[202779] = {"blue","green"},
	[202947] = "blue",
	[203381] = "yellow",
})

BigWigs:AddSounds("Thalena", {
	[202779] = {"alert","info"},
	[202947] = "alarm",
	[203381] = "long",
})

BigWigs:AddColors("Festerface", {
	[201598] = "red",
	[201729] = "orange",
})

BigWigs:AddSounds("Festerface", {
	[201598] = "alarm",
	[201729] = "alert",
})

BigWigs:AddColors("Millificent Manastorm", {
	[201159] = {"blue","orange"},
	[201240] = "yellow",
	[201392] = "red",
	[201572] = "cyan",
})

BigWigs:AddSounds("Millificent Manastorm", {
	[201240] = "info",
	[201392] = "alarm",
	[201572] = "warning",
})

BigWigs:AddColors("Kaahrj", {
	[201146] = {"blue","orange"},
	[201148] = "yellow",
	[201153] = "red",
})

BigWigs:AddSounds("Kaahrj", {
	[201146] = "alarm",
	[201148] = "info",
	[201153] = "long",
})

BigWigs:AddColors("Anub'esset", {
	[201863] = "orange",
	[202217] = {"blue","yellow"},
	[202341] = {"blue","red"},
	[202480] = "blue",
	[202485] = "blue",
})

BigWigs:AddSounds("Anub'esset", {
	[201863] = "info",
	[202217] = "alarm",
	[202341] = "long",
	[202480] = "warning",
	[202485] = "alarm",
})

BigWigs:AddColors("Saelorn", {
	[202306] = {"blue","orange"},
	[202414] = {"blue","yellow"},
	[202473] = "red",
})

BigWigs:AddSounds("Saelorn", {
	[202306] = "alarm",
	[202414] = "alert",
	[202473] = "long",
})

BigWigs:AddColors("Fel Lord Betrug", {
	[202328] = "orange",
	[203641] = "red",
	[205233] = {"blue","green","red"},
	[210879] = {"blue","yellow"},
})

BigWigs:AddSounds("Fel Lord Betrug", {
	[202328] = "long",
	[205233] = {"alarm","info"},
	[210879] = "alert",
})

BigWigs:AddColors("Assault on Violet Hold Trash", {
	[204140] = "red",
	[204608] = {"blue","orange"},
	[204876] = "red",
	[204901] = "red",
	[205088] = "red",
})

BigWigs:AddSounds("Assault on Violet Hold Trash", {
	[204140] = "alert",
	[204608] = "alarm",
	[204876] = "alert",
	[204901] = "alert",
	[205088] = "alert",
})

BigWigs:AddColors("Amalgam of Souls", {
	[194956] = "purple",
	[194966] = {"blue","orange"},
	[195254] = {"blue","yellow"},
	[196078] = "cyan",
	[196587] = "orange",
	[196930] = "yellow",
})

BigWigs:AddSounds("Amalgam of Souls", {
	[194956] = {"alert","warning"},
	[194966] = "alarm",
	[195254] = "alarm",
	[196078] = "long",
	[196587] = "alarm",
	[196930] = "alert",
})

BigWigs:AddColors("Illysanna Ravencrest", {
	[197418] = "purple",
	[197478] = {"blue","red"},
	[197546] = {"blue","yellow"},
	[197696] = {"blue","red"},
	[197797] = "yellow",
	[197974] = "orange",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Illysanna Ravencrest", {
	[197418] = "alert",
	[197478] = "alarm",
	[197546] = "alert",
	[197696] = "alarm",
	[197797] = "alert",
	[197974] = "alarm",
	["stages"] = "long",
})

BigWigs:AddColors("Smashspite", {
	[198073] = "yellow",
	[198079] = {"blue","orange"},
	[198245] = "purple",
	[198446] = {"blue","red"},
	[224188] = "green",
})

BigWigs:AddSounds("Smashspite", {
	[198073] = "alert",
	[198079] = {"alarm","warning"},
	[198245] = "alert",
	[198446] = {"alarm","alert"},
	[224188] = "info",
})

BigWigs:AddColors("Kurtalos Ravencrest", {
	[198635] = "purple",
	[198641] = "orange",
	[198820] = "yellow",
	[199143] = "orange",
	[199193] = "cyan",
	[199368] = "green",
	[201733] = {"blue","red"},
	[202019] = "yellow",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Kurtalos Ravencrest", {
	[198635] = "alert",
	[198641] = "alert",
	[198820] = "alarm",
	[199143] = "info",
	[199193] = "long",
	[199368] = "info",
	[201733] = "alert",
	[202019] = {"alert","warning"},
	["stages"] = "long",
})

BigWigs:AddColors("Black Rook Hold Trash", {
	[194966] = {"blue","orange"},
	[196916] = "orange",
	[200084] = {"blue","orange","yellow"},
	[200105] = "cyan",
	[200248] = "yellow",
	[200261] = "orange",
	[200291] = "orange",
	[200343] = "red",
	[200784] = "yellow",
	[200913] = "orange",
	[203163] = {"blue","orange"},
	[204896] = "red",
	[214001] = "orange",
	[214003] = "purple",
	[225573] = "red",
	[225908] = {"blue","yellow"},
	[227913] = "yellow",
})

BigWigs:AddSounds("Black Rook Hold Trash", {
	[194966] = "alarm",
	[196916] = "alarm",
	[200084] = "alert",
	[200105] = "info",
	[200248] = "alert",
	[200261] = "alarm",
	[200291] = "alert",
	[200343] = "alarm",
	[200784] = "alert",
	[200913] = "alarm",
	[203163] = {"alert","warning"},
	[204896] = "alert",
	[214001] = "alarm",
	[214003] = "alert",
	[225573] = "warning",
	[225908] = {"alert","warning"},
	[227913] = "alert",
})

BigWigs:AddColors("Agronox", {
	[235751] = "orange",
	[236524] = "yellow",
	[236527] = "yellow",
	[236639] = "yellow",
	[236640] = "blue",
	[236650] = {"blue","yellow"},
	[238674] = "blue",
})

BigWigs:AddSounds("Agronox", {
	[235751] = "alarm",
	[236524] = "info",
	[236527] = "alert",
	[236639] = "alert",
	[236640] = "alert",
	[236650] = {"alert","warning"},
	[238674] = "alarm",
})

BigWigs:AddColors("Thrashbite the Scornful", {
	[237276] = "orange",
	[237726] = {"blue","orange"},
	[243124] = "red",
})

BigWigs:AddSounds("Thrashbite the Scornful", {
	[237276] = "alert",
	[237726] = "warning",
	[243124] = "alert",
})

BigWigs:AddColors("Domatrax", {
	[-15076] = "red",
	[234107] = "orange",
	[236543] = "yellow",
	[238410] = {"blue","orange"},
})

BigWigs:AddSounds("Domatrax", {
	[-15076] = "alarm",
	[234107] = "warning",
	[236543] = "alert",
	[238410] = {"alert","warning"},
})

BigWigs:AddColors("Mephistroth", {
	[233155] = "yellow",
	[233196] = {"blue","red","yellow"},
	[233206] = {"green","yellow"},
	[234817] = "yellow",
})

BigWigs:AddSounds("Mephistroth", {
	[233155] = "alarm",
	[233196] = {"alert","warning"},
	[233206] = {"long","warning"},
	[234817] = "alarm",
})

BigWigs:AddColors("Cathedral of Eternal Night Trash", {
	[236737] = {"blue","yellow"},
	[237391] = "orange",
	[237565] = "yellow",
	[238543] = "orange",
	[238653] = "orange",
	[239101] = "orange",
	[239232] = "orange",
	[239320] = "orange",
	[241598] = "yellow",
	[241772] = "orange",
	[242760] = "red",
	[242839] = "orange",
	[242841] = "orange",
})

BigWigs:AddSounds("Cathedral of Eternal Night Trash", {
	[236737] = "alert",
	[237391] = "warning",
	[237565] = "long",
	[238543] = "warning",
	[238653] = "alarm",
	[239101] = "warning",
	[239232] = "warning",
	[239320] = "warning",
	[241598] = "long",
	[241772] = "warning",
	[242760] = "alarm",
	[242839] = "warning",
	[242841] = "warning",
})

BigWigs:AddColors("Patrol Captain Gerdo", {
	[207261] = "orange",
	[207278] = "yellow",
	[207806] = "yellow",
	[207815] = "cyan",
	[215204] = {"blue","red"},
	[219488] = "red",
})

BigWigs:AddSounds("Patrol Captain Gerdo", {
	[207261] = "alarm",
	[207278] = "long",
	[207806] = "alert",
	[207815] = "info",
	[215204] = {"alert","warning"},
	[219488] = "info",
})

BigWigs:AddColors("Talixae Flamewreath", {
	[207881] = "orange",
	[207906] = "red",
	[208165] = "yellow",
})

BigWigs:AddSounds("Talixae Flamewreath", {
	[207881] = "long",
	[207906] = "info",
	[208165] = "alert",
})

BigWigs:AddColors("Advisor Melandrus", {
	[209602] = "red",
	[209628] = "orange",
	[209676] = "yellow",
	[224333] = {"blue","red","yellow"},
})

BigWigs:AddSounds("Advisor Melandrus", {
	[209602] = "info",
	[209628] = "alarm",
	[209676] = "warning",
	[224333] = "alert",
})

BigWigs:AddColors("Court of Stars Trash", {
	[207979] = "orange",
	[207980] = {"blue","red"},
	[209027] = "purple",
	[209033] = {"orange","yellow"},
	[209378] = "orange",
	[209404] = {"blue","orange","yellow"},
	[209410] = "yellow",
	[209413] = {"blue","orange","red"},
	[209477] = "orange",
	[209485] = "yellow",
	[209495] = "red",
	[209512] = "blue",
	[210261] = "red",
	[211299] = "red",
	[211391] = "blue",
	[211401] = "red",
	[211464] = "red",
	[211470] = {"blue","orange","yellow"},
	[211473] = "purple",
	[212031] = "red",
	[212773] = {"blue","orange","red"},
	[212784] = {"red","yellow"},
	[214688] = "yellow",
	[214690] = {"blue","orange"},
	[214692] = "yellow",
	[214697] = {"blue","cyan","green"},
	[216000] = "yellow",
	[216006] = "yellow",
	[216096] = "yellow",
	[216110] = "yellow",
	[224377] = "red",
	[225100] = "yellow",
	[397892] = "red",
	[397897] = "red",
	[397907] = {"blue","orange"},
	["announce_buff_items"] = "cyan",
	["spy_helper"] = {"cyan","green"},
})

BigWigs:AddSounds("Court of Stars Trash", {
	[207979] = "alarm",
	[207980] = {"alert","long"},
	[209027] = "alarm",
	[209033] = {"alert","info"},
	[209378] = "alarm",
	[209404] = "alert",
	[209410] = "alert",
	[209413] = {"alarm","alert"},
	[209477] = "alarm",
	[209485] = "alert",
	[209495] = "alarm",
	[209512] = "underyou",
	[210261] = "warning",
	[211299] = "alarm",
	[211391] = "underyou",
	[211401] = "alarm",
	[211464] = "alarm",
	[211470] = "alert",
	[211473] = "alarm",
	[212031] = "alarm",
	[212773] = {"alarm","warning"},
	[212784] = {"alarm","long"},
	[214688] = "alert",
	[214690] = "alert",
	[214692] = "alert",
	[214697] = {"info","long"},
	[216000] = "alert",
	[216006] = "alert",
	[216096] = "alert",
	[216110] = "alert",
	[224377] = "alarm",
	[225100] = "alert",
	[397892] = "alarm",
	[397897] = "alert",
	[397907] = "alarm",
	["announce_buff_items"] = "info",
	["spy_helper"] = "info",
})

BigWigs:AddColors("Archdruid Glaidalis", {
	[196354] = "yellow",
	[196376] = {"blue","red"},
	[198379] = "orange",
	[198477] = {"blue","red"},
	[212464] = {"blue","cyan"},
})

BigWigs:AddSounds("Archdruid Glaidalis", {
	[196354] = "alarm",
	[196376] = "alert",
	[198379] = "alarm",
	[198477] = "alert",
	[212464] = {"info","underyou"},
})

BigWigs:AddColors("Oakheart", {
	[204574] = {"blue","red","yellow"},
	[204611] = {"blue","orange","purple"},
	[204666] = "red",
	[204667] = "purple",
	[212786] = "cyan",
})

BigWigs:AddSounds("Oakheart", {
	[204574] = {"alert","info"},
	[204611] = {"alarm","alert"},
	[204666] = "alert",
	[204667] = "alarm",
	[212786] = "long",
})

BigWigs:AddColors("Dresaron", {
	[191325] = "orange",
	[199345] = "yellow",
	[199389] = "red",
	[199460] = "blue",
})

BigWigs:AddSounds("Dresaron", {
	[191325] = "alarm",
	[199345] = "long",
	[199389] = "alert",
	[199460] = "underyou",
})

BigWigs:AddColors("Shade of Xavius", {
	[200050] = "cyan",
	[200182] = {"blue","yellow"},
	[200185] = {"blue","yellow"},
	[200238] = {"blue","red"},
	[200243] = "blue",
	[200289] = {"blue","orange"},
})

BigWigs:AddSounds("Shade of Xavius", {
	[200050] = "long",
	[200182] = "alert",
	[200185] = "info",
	[200238] = "alert",
	[200243] = "alarm",
	[200289] = "alarm",
})

BigWigs:AddColors("Darkheart Thicket Trash", {
	[198904] = {"blue","yellow"},
	[198910] = "red",
	[200580] = "red",
	[200630] = "red",
	[200642] = {"blue","yellow"},
	[200658] = "yellow",
	[200684] = {"blue","red"},
	[200768] = "orange",
	[201129] = "orange",
	[201226] = "orange",
	[201272] = "yellow",
	[201365] = {"blue","yellow"},
	[201399] = "red",
	[201839] = {"blue","orange"},
	[204243] = "red",
	[204246] = {"blue","yellow"},
	[218759] = "blue",
	[225562] = "red",
})

BigWigs:AddSounds("Darkheart Thicket Trash", {
	[198904] = "alert",
	[198910] = "info",
	[200580] = "alarm",
	[200630] = "alert",
	[200642] = {"alert","warning"},
	[200658] = "alert",
	[200684] = "alert",
	[200768] = "alarm",
	[201129] = "alarm",
	[201226] = "alarm",
	[201272] = "info",
	[201365] = "alert",
	[201399] = "alert",
	[201839] = "alarm",
	[204243] = "alert",
	[204246] = "alarm",
	[218759] = "underyou",
	[225562] = "alert",
})

BigWigs:AddColors("Warlord Parjesh", {
	[191900] = "yellow",
	[192053] = "blue",
	[192072] = "yellow",
	[192094] = {"blue","red"},
	[192131] = {"blue","red"},
	[196563] = "yellow",
	[197064] = "orange",
	[197502] = "green",
})

BigWigs:AddSounds("Warlord Parjesh", {
	[191900] = "alert",
	[192053] = "alarm",
	[192072] = "info",
	[192094] = "warning",
	[192131] = "alarm",
	[196563] = "info",
	[197064] = "alert",
	[197502] = {"long","warning"},
})

BigWigs:AddColors("Lady Hatecoil", {
	[193597] = "orange",
	[193611] = "yellow",
	[193682] = "red",
	[193698] = "blue",
	[196610] = "yellow",
})

BigWigs:AddSounds("Lady Hatecoil", {
	[193597] = "warning",
	[193611] = "alert",
	[193682] = "info",
	[193698] = "alarm",
})

BigWigs:AddColors("Serpentrix", {
	[191855] = {"blue","red"},
	[191873] = "yellow",
})

BigWigs:AddSounds("Serpentrix", {
	[191855] = "alarm",
	[191873] = "long",
})

BigWigs:AddColors("King Deepbeard", {
	[193018] = "blue",
	[193051] = "yellow",
	[193093] = "orange",
	[193152] = {"blue","red"},
})

BigWigs:AddSounds("King Deepbeard", {
	[193018] = "warning",
	[193051] = "long",
	[193093] = "info",
	[193152] = "alert",
})

BigWigs:AddColors("Wrath of Azshara", {
	[192617] = "yellow",
	[192675] = "orange",
	[192706] = {"blue","red"},
	[192985] = "green",
	[197365] = {"blue","red"},
})

BigWigs:AddSounds("Wrath of Azshara", {
	[192617] = "warning",
	[192675] = "alert",
	[192706] = "alarm",
	[192985] = "long",
	[197365] = "alarm",
})

BigWigs:AddColors("Eye of Azshara Trash", {
	[195046] = "yellow",
	[195109] = "yellow",
	[195129] = "red",
	[195284] = "yellow",
	[196027] = "yellow",
	[196127] = "yellow",
	[196870] = "yellow",
	[197105] = {"blue","yellow"},
	[225089] = "orange",
})

BigWigs:AddSounds("Eye of Azshara Trash", {
	[195046] = "alarm",
	[195109] = "alarm",
	[195129] = {"info","warning"},
	[195284] = "long",
	[196027] = "alarm",
	[196127] = "long",
	[196870] = "long",
	[197105] = "info",
	[225089] = "warning",
})

BigWigs:AddColors("Hymdall", {
	[191284] = "red",
	[193092] = "purple",
	[193235] = {"blue","orange"},
})

BigWigs:AddSounds("Hymdall", {
	[191284] = "long",
	[193092] = "alarm",
	[193235] = {"alert","underyou"},
})

BigWigs:AddColors("Hyrja", {
	[192018] = "purple",
	[192048] = {"blue","yellow"},
	[192307] = "orange",
	[200901] = "orange",
})

BigWigs:AddSounds("Hyrja", {
	[192018] = "alert",
	[192048] = "alarm",
	[192307] = "long",
	[200901] = "long",
})

BigWigs:AddColors("Fenryr", {
	[196512] = "red",
	[196543] = "orange",
	[196838] = {"blue","orange"},
	[197558] = {"blue","yellow"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("Fenryr", {
	[196512] = "alert",
	[196543] = "alert",
	[196838] = "warning",
	[197558] = "alarm",
	["stages"] = "long",
})

BigWigs:AddColors("God-King Skovald", {
	[193659] = {"blue","red"},
	[193668] = "purple",
	[193702] = "blue",
	[193783] = {"cyan","green"},
	[193826] = "orange",
})

BigWigs:AddSounds("God-King Skovald", {
	[193659] = "alarm",
	[193668] = {"alarm","alert"},
	[193702] = "underyou",
	[193783] = "info",
	[193826] = "long",
})

BigWigs:AddColors("Odyn", {
	[197961] = {"orange","yellow"},
	[198077] = "red",
	[198263] = "red",
	[200988] = "orange",
	[201215] = "yellow",
	["warmup"] = "cyan",
})

BigWigs:AddSounds("Odyn", {
	[197961] = {"alarm","warning"},
	[198077] = "alert",
	[198263] = "long",
	[200988] = "alert",
	[201215] = "info",
	["warmup"] = "info",
})

BigWigs:AddColors("Halls of Valor Trash", {
	[191508] = "red",
	[192158] = "orange",
	[192288] = "yellow",
	[192563] = "red",
	[198745] = "yellow",
	[198888] = "purple",
	[198892] = {"blue","red"},
	[198931] = "red",
	[198934] = "yellow",
	[198959] = "yellow",
	[199034] = {"blue","yellow"},
	[199050] = "purple",
	[199090] = "orange",
	[199146] = "yellow",
	[199210] = "orange",
	[199341] = "red",
	[199726] = "red",
	[199805] = "blue",
	[200901] = "orange",
	[200969] = "yellow",
	[210875] = "red",
	[215430] = {"blue","orange"},
	[215433] = "red",
})

BigWigs:AddSounds("Halls of Valor Trash", {
	[191508] = "alarm",
	[192158] = "long",
	[192288] = "alert",
	[192563] = "alarm",
	[198745] = "alert",
	[198888] = "alarm",
	[198892] = {"alert","underyou"},
	[198931] = "alert",
	[198934] = "alarm",
	[198959] = "alert",
	[199034] = "alert",
	[199050] = "alarm",
	[199090] = "alarm",
	[199146] = "alarm",
	[199210] = "alarm",
	[199341] = "alarm",
	[199726] = "alert",
	[199805] = {"alarm","underyou"},
	[200901] = "long",
	[200969] = "info",
	[210875] = "alarm",
	[215430] = "alarm",
	[215433] = "alarm",
})

BigWigs:AddColors("Maiden of Virtue", {
	[227508] = "yellow",
	[227789] = {"blue","green","red"},
	[227800] = "yellow",
	[227809] = {"blue","red"},
	[227823] = {"orange","red"},
})

BigWigs:AddSounds("Maiden of Virtue", {
	[227508] = "warning",
	[227789] = {"alarm","info","warning"},
	[227800] = "alarm",
	[227823] = {"alarm","alert"},
})

BigWigs:AddColors("Opera Hall: Wikket", {
	[227410] = "orange",
	[227447] = "yellow",
	[227477] = "orange",
	[227776] = "red",
})

BigWigs:AddSounds("Opera Hall: Wikket", {
	[227410] = "warning",
	[227447] = "info",
	[227477] = "alert",
	[227776] = "long",
})

BigWigs:AddColors("Opera Hall: Westfall Story", {
	[227453] = "orange",
	[227568] = "yellow",
	[227777] = "red",
	[227783] = "orange",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Opera Hall: Westfall Story", {
	[227453] = "alert",
	[227568] = "alarm",
	[227777] = "warning",
	[227783] = "info",
	["stages"] = "long",
})

BigWigs:AddColors("Opera Hall: Beautiful Beast", {
	[227985] = {"blue","purple"},
	[227987] = {"red","yellow"},
	[228019] = "orange",
	[228025] = "red",
	[228221] = {"blue","yellow"},
	[228225] = "yellow",
	[232153] = "orange",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Opera Hall: Beautiful Beast", {
	[227985] = "alarm",
	[227987] = {"alert","warning"},
	[228019] = "alert",
	[228025] = "warning",
	[228221] = {"alert","warning"},
	[228225] = "warning",
	[232153] = "info",
	["stages"] = "long",
})

BigWigs:AddColors("Attumen the Huntsman", {
	[227363] = "orange",
	[227365] = "yellow",
	[227493] = "red",
	[228852] = "orange",
	[228895] = "red",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Attumen the Huntsman", {
	[227363] = "alarm",
	[227365] = "alert",
	[227493] = "alarm",
	[228852] = "info",
	[228895] = "long",
	["stages"] = {"info","long"},
})

BigWigs:AddColors("Moroes", {
	[227463] = {"blue","orange"},
	[227545] = "orange",
	[227578] = "red",
	[227616] = "red",
	[227646] = {"blue","yellow"},
	[227672] = "red",
	[227736] = "yellow",
	[227742] = {"blue","orange"},
	[227851] = {"blue","orange","purple"},
	[227872] = {"cyan","yellow"},
	["cc"] = "cyan",
})

BigWigs:AddSounds("Moroes", {
	[227463] = "warning",
	[227545] = "warning",
	[227578] = "warning",
	[227616] = "info",
	[227646] = {"long","underyou"},
	[227672] = "alarm",
	[227742] = "info",
	[227851] = {"alarm","warning"},
	[227872] = "info",
	["cc"] = "info",
})

BigWigs:AddColors("The Curator", {
	[227254] = {"cyan","green"},
	[227267] = "yellow",
	[227279] = {"blue","orange"},
})

BigWigs:AddSounds("The Curator", {
	[227254] = {"info","long"},
	[227267] = "info",
	[227279] = {"alert","underyou"},
})

BigWigs:AddColors("Shade of Medivh", {
	[227592] = {"blue","orange"},
	[227615] = {"orange","red"},
	[227628] = "purple",
	[227779] = {"blue","yellow"},
	[228269] = {"blue","red","yellow"},
	[228334] = {"cyan","yellow"},
})

BigWigs:AddSounds("Shade of Medivh", {
	[227592] = {"alarm","warning"},
	[227615] = "alert",
	[227628] = "alert",
	[227779] = {"long","warning"},
	[228269] = {"long","warning"},
	[228334] = {"info","long"},
})

BigWigs:AddColors("Mana Devourer", {
	[227297] = "orange",
	[227457] = "orange",
	[227502] = "blue",
	[227523] = {"blue","yellow"},
	[227618] = "red",
})

BigWigs:AddSounds("Mana Devourer", {
	[227297] = "long",
	[227457] = "alarm",
	[227523] = {"info","underyou"},
	[227618] = "warning",
})

BigWigs:AddColors("Viz'aduum the Watcher", {
	[229083] = {"blue","red","yellow"},
	[229151] = "yellow",
	[229159] = {"blue","red"},
	[229248] = {"blue","orange"},
	[229284] = "orange",
	[229905] = "blue",
	[230066] = "red",
	[230084] = {"green","orange"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("Viz'aduum the Watcher", {
	[229083] = {"alert","info"},
	[229151] = "alarm",
	[229159] = "warning",
	[229248] = "alarm",
	[229905] = "underyou",
	[230066] = "alarm",
	[230084] = {"info","long"},
	["stages"] = "long",
})

BigWigs:AddColors("Nightbane", {
	[228785] = "red",
	[228790] = {"green","red"},
	[228792] = {"green","red"},
	[228796] = {"blue","red"},
	[228808] = {"blue","orange"},
	[228829] = {"blue","orange"},
	[228834] = "red",
	[228835] = {"blue","orange"},
	[228837] = "yellow",
	[229307] = "yellow",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Nightbane", {
	[228785] = "alert",
	[228790] = "info",
	[228792] = "info",
	[228796] = "warning",
	[228808] = {"alarm","alert"},
	[228829] = "info",
	[228835] = "alarm",
	[228837] = "warning",
	[229307] = "alarm",
	["stages"] = "long",
})

BigWigs:AddColors("Karazhan Trash", {
	[227966] = "yellow",
	[227999] = "yellow",
	[228278] = "red",
	[228279] = "yellow",
	[228280] = {"blue","orange"},
	[228528] = "yellow",
	[228575] = "red",
	[228576] = {"blue","orange"},
	[228603] = "purple",
	[228625] = "yellow",
	[229489] = {"green","red"},
	[241828] = "red",
})

BigWigs:AddSounds("Karazhan Trash", {
	[227966] = "alarm",
	[227999] = "alert",
	[228278] = "warning",
	[228279] = "warning",
	[228280] = "warning",
	[228528] = "alarm",
	[228575] = "alert",
	[228576] = "warning",
	[228603] = "alert",
	[228625] = "alert",
	[229489] = {"info","long"},
	[241828] = "warning",
})

BigWigs:AddColors("Ymiron", {
	[193211] = "orange",
	[193364] = "red",
	[193566] = "yellow",
	[193977] = "yellow",
})

BigWigs:AddSounds("Ymiron", {
	[193211] = "alert",
	[193364] = "long",
	[193566] = "warning",
	[193977] = "alarm",
})

BigWigs:AddColors("Harbaron", {
	[194216] = "orange",
	[194231] = "yellow",
	[194325] = {"blue","red"},
	[194668] = "blue",
})

BigWigs:AddSounds("Harbaron", {
	[194216] = "alert",
	[194231] = "info",
	[194325] = "warning",
	[194668] = "alarm",
})

BigWigs:AddColors("Helya", {
	[185539] = "blue",
	[196947] = "cyan",
	[197262] = {"blue","yellow"},
	[198495] = "red",
	[202088] = "orange",
	[227233] = "orange",
	["destructor_tentacle"] = "yellow",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Helya", {
	[185539] = "warning",
	[196947] = "info",
	[197262] = "alert",
	[198495] = "warning",
	[202088] = "alarm",
	[227233] = "alarm",
	["destructor_tentacle"] = "warning",
	["stages"] = "info",
})

BigWigs:AddColors("Maw of Souls Trash", {
	[192019] = "yellow",
	[194615] = "yellow",
	[194657] = "orange",
	[195293] = "orange",
	[198324] = {"blue","red"},
	[198405] = {"red","yellow"},
	[199514] = {"blue","orange"},
	[199589] = {"blue","orange"},
	[216197] = "orange",
})

BigWigs:AddSounds("Maw of Souls Trash", {
	[192019] = "long",
	[194615] = "alarm",
	[194657] = "alarm",
	[195293] = "long",
	[198324] = {"alarm","warning"},
	[198405] = {"info","warning"},
	[199514] = {"alarm","alert"},
	[199589] = {"alarm","alert"},
	[216197] = "alarm",
})

BigWigs:AddColors("Rokmora", {
	[188114] = "yellow",
	[188169] = "purple",
	[192800] = "blue",
	[198024] = "orange",
})

BigWigs:AddSounds("Rokmora", {
	[188114] = "alert",
	[188169] = "alarm",
	[192800] = "underyou",
	[198024] = "alert",
})

BigWigs:AddColors("Ularogg Cragshaper", {
	[193375] = "orange",
	[198428] = "red",
	[198496] = "purple",
	[198564] = {"cyan","green"},
})

BigWigs:AddSounds("Ularogg Cragshaper", {
	[193375] = "alert",
	[198428] = "warning",
	[198496] = "alert",
	[198564] = {"info","long"},
})

BigWigs:AddColors("Naraxas", {
	[198963] = "purple",
	[199178] = {"blue","green","purple","red"},
	[199246] = {"blue","red"},
	[199775] = "yellow",
	[199817] = "cyan",
	[205549] = "red",
	[210150] = "orange",
})

BigWigs:AddSounds("Naraxas", {
	[198963] = "warning",
	[199178] = {"alarm","alert","info","warning"},
	[199246] = "long",
	[199775] = "long",
	[199817] = "info",
	[205549] = "alert",
	[210150] = "alert",
})

BigWigs:AddColors("Dargrul", {
	[200154] = {"blue","red"},
	[200404] = "red",
	[200551] = "yellow",
	[200637] = "yellow",
	[200672] = "green",
	[200700] = "orange",
	[200732] = "purple",
	[216407] = "blue",
})

BigWigs:AddSounds("Dargrul", {
	[200154] = {"alert","warning"},
	[200404] = "long",
	[200551] = "alarm",
	[200637] = "alert",
	[200672] = "info",
	[200700] = "alarm",
	[200732] = "alert",
	[216407] = "underyou",
})

BigWigs:AddColors("Neltharions Lair Trash", {
	[183088] = "orange",
	[183407] = "blue",
	[183465] = "red",
	[183526] = "yellow",
	[183539] = "red",
	[183548] = "yellow",
	[186576] = {"blue","red"},
	[186616] = {"blue","red"},
	[188587] = "yellow",
	[193505] = "purple",
	[193585] = "red",
	[193803] = "red",
	[200154] = {"blue","orange","yellow"},
	[201983] = "yellow",
	[202108] = "yellow",
	[202181] = {"blue","red"},
	[226287] = "orange",
	[226296] = "purple",
	[226388] = "blue",
	[226406] = "purple",
})

BigWigs:AddSounds("Neltharions Lair Trash", {
	[183088] = "alarm",
	[183407] = "underyou",
	[183465] = "alarm",
	[183526] = "long",
	[183539] = "alarm",
	[183548] = "info",
	[186576] = "alert",
	[186616] = {"info","warning"},
	[188587] = "info",
	[193505] = "alert",
	[193585] = "warning",
	[193803] = "warning",
	[200154] = {"alert","info","warning"},
	[201983] = "warning",
	[202108] = "info",
	[202181] = {"alert","warning"},
	[226287] = "alarm",
	[226296] = "alarm",
	[226388] = "underyou",
	[226406] = "alert",
})

BigWigs:AddColors("Zuraal", {
	[244433] = "blue",
	[244579] = "orange",
	[244602] = "yellow",
	[244621] = {"cyan","green"},
	[244653] = "blue",
	[246134] = "red",
})

BigWigs:AddSounds("Zuraal", {
	[244433] = "warning",
	[244579] = "warning",
	[244602] = "alert",
	[244621] = {"info","long"},
	[244653] = "warning",
	[246134] = "alarm",
})

BigWigs:AddColors("Saprish", {
	[245802] = {"blue","yellow"},
	[245873] = "cyan",
	[247206] = "yellow",
	[247245] = {"blue","orange"},
	[248831] = "red",
})

BigWigs:AddSounds("Saprish", {
	[245802] = {"alert","long"},
	[245873] = "info",
	[247206] = "alarm",
	[247245] = "alert",
	[248831] = "warning",
})

BigWigs:AddColors("Viceroy Nezhar", {
	[-15926] = "yellow",
	[244751] = "orange",
	[244906] = "blue",
	[246324] = {"green","red"},
	[248736] = {"cyan","green"},
	[248804] = {"cyan","yellow"},
})

BigWigs:AddSounds("Viceroy Nezhar", {
	[-15926] = "info",
	[244751] = "alarm",
	[244906] = "alert",
	[246324] = "long",
	[248736] = "long",
	[248804] = "info",
})

BigWigs:AddColors("L'ura", {
	[245164] = "red",
	[247795] = "red",
	[247816] = "green",
	[247930] = "yellow",
	[248535] = "cyan",
	[249009] = "orange",
})

BigWigs:AddSounds("L'ura", {
	[245164] = "warning",
	[247795] = "warning",
	[247816] = "long",
	[247930] = "alert",
	[248535] = "info",
	[249009] = "alarm",
})

BigWigs:AddColors("Seat of the Triumvirate Trash", {
	[245510] = "blue",
	[248227] = "red",
	[249078] = "yellow",
	[249081] = "blue",
})

BigWigs:AddSounds("Seat of the Triumvirate Trash", {
	[245510] = "alarm",
	[248227] = "warning",
	[249078] = "info",
	[249081] = "alarm",
})

BigWigs:AddColors("Ivanyr", {
	[196392] = "red",
	[196562] = {"blue","orange"},
	[196805] = {"blue","yellow"},
})

BigWigs:AddSounds("Ivanyr", {
	[196392] = "long",
	[196562] = "alarm",
	[196805] = "info",
})

BigWigs:AddColors("Corstilax", {
	[195804] = {"blue","yellow"},
	[196068] = {"blue","orange"},
	[196115] = "orange",
	[220481] = {"blue","yellow"},
})

BigWigs:AddSounds("Corstilax", {
	[195804] = "info",
	[196068] = "alarm",
	[196115] = "alert",
	[220481] = "alarm",
})

BigWigs:AddColors("General Xakal", {
	[197776] = "yellow",
	[197810] = "orange",
	[212030] = "orange",
	["dread_felbat"] = "cyan",
})

BigWigs:AddSounds("General Xakal", {
	[197810] = "alert",
	[212030] = "alarm",
	["dread_felbat"] = "info",
})

BigWigs:AddColors("Naltira", {
	[-12687] = {"blue","orange"},
	[200040] = {"blue","orange"},
	[200284] = {"blue","green","yellow"},
	[211543] = {"blue","red"},
})

BigWigs:AddSounds("Naltira", {
	[-12687] = "alarm",
	[200040] = "alarm",
	[200284] = "warning",
	[211543] = "info",
})

BigWigs:AddColors("Advisor Vandros", {
	[202974] = "yellow",
	[203176] = {"blue","orange","yellow"},
	[203882] = "red",
	[220871] = {"blue","orange"},
})

BigWigs:AddSounds("Advisor Vandros", {
	[202974] = "info",
	[203176] = "alert",
	[203882] = "long",
	[220871] = "alarm",
})

BigWigs:AddColors("The Arcway Trash", {
	[210750] = "blue",
	[211115] = "yellow",
	[211217] = "orange",
	[211632] = "yellow",
	[211745] = "blue",
	[211757] = "orange",
	[226206] = "orange",
	[226285] = {"green","orange"},
})

BigWigs:AddSounds("The Arcway Trash", {
	[210750] = "warning",
	[211115] = "alarm",
	[211217] = "warning",
	[211632] = "alarm",
	[211745] = "warning",
	[211757] = "alarm",
	[226206] = "alarm",
	[226285] = {"alarm","info","warning"},
})

BigWigs:AddColors("Tirathon Saltheril", {
	[190830] = "yellow",
	[191823] = "orange",
	[191853] = "blue",
	[191941] = {"blue","orange","red"},
	[192504] = "cyan",
	[202740] = "cyan",
})

BigWigs:AddSounds("Tirathon Saltheril", {
	[190830] = "warning",
	[191823] = "alarm",
	[191853] = "alert",
	[191941] = "alarm",
	[192504] = "info",
	[202740] = "info",
})

BigWigs:AddColors("Inquisitor Tormentorum", {
	[196208] = "orange",
	[199918] = "blue",
	[200898] = "yellow",
	[200904] = {"blue","red","yellow"},
	[201488] = "orange",
	[202455] = "green",
	[203685] = {"blue","orange"},
	[212564] = "orange",
})

BigWigs:AddSounds("Inquisitor Tormentorum", {
	[196208] = "warning",
	[199918] = "alert",
	[200898] = "info",
	[200904] = {"info","long","warning"},
	[201488] = "warning",
	[202455] = "info",
	[203685] = {"alarm","warning"},
	[212564] = "alarm",
})

BigWigs:AddColors("Ashgolm", {
	[-12727] = "green",
	[192517] = "green",
	[192519] = "blue",
	[192520] = "red",
	[192522] = "yellow",
})

BigWigs:AddSounds("Ashgolm", {
	[-12727] = "info",
	[192517] = "info",
	[192519] = "alert",
	[192520] = "long",
	[192522] = "alarm",
})

BigWigs:AddColors("Glazer", {
	[194323] = "orange",
	[194333] = "green",
	[194945] = {"blue","red"},
	[202046] = "blue",
})

BigWigs:AddSounds("Glazer", {
	[194323] = "info",
	[194333] = "info",
	[194945] = {"alarm","alert"},
	[202046] = "alert",
})

BigWigs:AddColors("Cordana Felsong", {
	[197333] = "red",
	[197422] = {"cyan","red"},
	[197796] = {"green","orange"},
	[204481] = {"cyan","green"},
	[206567] = {"blue","cyan","orange","yellow"},
	[213583] = "yellow",
	["kick_combo"] = "yellow",
})

BigWigs:AddSounds("Cordana Felsong", {
	[197333] = "alert",
	[197422] = "info",
	[197796] = "long",
	[204481] = "long",
	[206567] = {"alarm","info"},
	[213583] = "alarm",
	["kick_combo"] = "warning",
})

BigWigs:AddColors("Vault of the Wardens Trash", {
	[191527] = "red",
	[191735] = "red",
	[193069] = {"blue","orange","yellow"},
	[193164] = {"blue","orange"},
	[194071] = "blue",
	[196249] = "orange",
	[196796] = "orange",
	[196799] = "yellow",
	[202607] = "blue",
	[202615] = {"blue","orange"},
	[210202] = "blue",
})

BigWigs:AddSounds("Vault of the Wardens Trash", {
	[191527] = "alert",
	[191735] = "alert",
	[193069] = {"alarm","info"},
	[193164] = "alarm",
	[194071] = "alert",
	[196249] = "alarm",
	[196796] = "warning",
	[196799] = "alarm",
	[202607] = "alert",
	[202615] = "alarm",
	[210202] = "alert",
})
