-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Adderis and Aspix", {
	[263246] = "cyan",
	[263257] = "orange",
	[263309] = "yellow",
	[263371] = {"blue","orange"},
	[263424] = "orange",
})

BigWigs:AddSounds("Adderis and Aspix", {
	[263246] = "info",
	[263257] = "alarm",
	[263309] = "alert",
	[263371] = "warning",
	[263424] = "alert",
})

BigWigs:AddColors("Merektha", {
	[263912] = "yellow",
	[263914] = "red",
	[263927] = "blue",
	[263958] = {"blue","red"},
	[264206] = {"cyan","green"},
})

BigWigs:AddSounds("Merektha", {
	[263912] = "alert",
	[263914] = "warning",
	[263927] = "alarm",
	[263958] = "warning",
	[264206] = {"info","long"},
})

BigWigs:AddColors("Galvazzt", {
	[266512] = {"orange","red"},
	[266923] = {"blue","orange"},
})

BigWigs:AddSounds("Galvazzt", {
	[266512] = {"alarm","warning"},
	[266923] = {"alert","info"},
})

BigWigs:AddColors("Avatar of Sethraliss", {
	[268007] = {"blue","purple"},
	[268008] = {"blue","orange"},
	[268024] = "yellow",
	[269686] = {"blue","orange"},
	[269688] = "orange",
	[274149] = {"blue","green"},
	["adds"] = "orange",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Avatar of Sethraliss", {
	[268007] = "alert",
	[268008] = "alert",
	[268024] = "alert",
	[269686] = "alarm",
	[269688] = "info",
	[274149] = "info",
	["adds"] = "warning",
	["stages"] = {"info","long"},
})

BigWigs:AddColors("Temple of Sethraliss Trash", {
	[258908] = {"orange","red"},
	[264574] = "orange",
	[265912] = "orange",
	[265968] = "yellow",
	[267237] = "yellow",
	[268008] = {"blue","orange","red"},
	[272657] = "orange",
	[272659] = {"blue","orange","yellow"},
	[272700] = "orange",
	[273563] = {"blue","red"},
	[273995] = "red",
})

BigWigs:AddSounds("Temple of Sethraliss Trash", {
	[258908] = {"alarm","alert"},
	[264574] = "alarm",
	[265912] = "alert",
	[265968] = "alert",
	[267237] = "alert",
	[268008] = {"alert","info"},
	[272657] = "alarm",
	[272659] = {"alert","info"},
	[272700] = "alert",
	[273563] = "info",
	[273995] = "alarm",
})
