-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Brew Master Aldryr", {
	[431895] = {"blue","green"},
	[432179] = "red",
	[432196] = "blue",
	[432198] = "orange",
	[432229] = "purple",
	[442525] = {"cyan","green"},
})

BigWigs:AddSounds("Brew Master Aldryr", {
	[431895] = "info",
	[432179] = "alert",
	[432196] = "underyou",
	[432198] = "alarm",
	[432229] = "alert",
	[442525] = "long",
})

BigWigs:AddColors("I'pa", {
	[439031] = "purple",
	[439202] = {"blue","orange"},
	[439365] = "yellow",
	[440147] = "cyan",
	[441179] = "blue",
})

BigWigs:AddSounds("I'pa", {
	[439031] = "alert",
	[439202] = "alert",
	[439365] = "long",
	[440147] = "warning",
	[441179] = "underyou",
})

BigWigs:AddColors("Benk Buzzbee", {
	[438025] = "yellow",
	[438971] = "orange",
	[439524] = "red",
	[440134] = {"blue","purple"},
})

BigWigs:AddSounds("Benk Buzzbee", {
	[438025] = "info",
	[438971] = "info",
	[439524] = "alert",
	[440134] = {"alarm","underyou"},
})

BigWigs:AddColors("Goldie Baronbottom", {
	[435560] = "cyan",
	[435622] = "yellow",
	[436592] = "purple",
	[436644] = {"blue","orange"},
})

BigWigs:AddSounds("Goldie Baronbottom", {
	[435560] = "info",
	[435622] = "long",
	[436592] = "alert",
	[436644] = "alarm",
})

BigWigs:AddColors("Cinderbrew Meadery Trash", {
	[434706] = "orange",
	[434756] = {"blue","red"},
	[434998] = "red",
	[437721] = "red",
	[437956] = {"blue","yellow"},
	[439467] = "orange",
	[440687] = "red",
	[440876] = "yellow",
	[441119] = {"blue","orange"},
	[441179] = "blue",
	[441214] = "yellow",
	[441242] = "red",
	[441351] = "red",
	[441408] = "cyan",
	[441434] = "cyan",
	[441627] = "red",
	[442589] = "orange",
	[442995] = "yellow",
	[448619] = {"blue","orange"},
	[463206] = "yellow",
	[463218] = "yellow",
})

BigWigs:AddSounds("Cinderbrew Meadery Trash", {
	[434706] = "alarm",
	[434756] = "alert",
	[434998] = "long",
	[437721] = "alert",
	[437956] = "alarm",
	[439467] = "alarm",
	[440687] = "alert",
	[440876] = "alarm",
	[441119] = "alarm",
	[441179] = "underyou",
	[441214] = "info",
	[441242] = "alert",
	[441351] = "alert",
	[441408] = "info",
	[441434] = "info",
	[441627] = "alert",
	[442589] = "alarm",
	[442995] = "alert",
	[448619] = "alarm",
	[463206] = "alert",
	[463218] = "info",
})
