-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Hakkar the Soulflayer", {
	[322736] = "purple",
	[322746] = {"blue","red"},
	[322759] = "orange",
	[323569] = "blue",
})

BigWigs:AddSounds("Hakkar the Soulflayer", {
	[322736] = "alert",
	[322746] = "warning",
	[322759] = "alarm",
	[323569] = "underyou",
})

BigWigs:AddColors("The Manastorms", {
	[320132] = {"blue","red"},
	[320141] = "red",
	[320787] = "yellow",
	[320823] = "orange",
	[321061] = "red",
	[323877] = {"blue","red"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("The Manastorms", {
	[320132] = {"alert","warning"},
	[320141] = "long",
	[320787] = "info",
	[320823] = "info",
	[321061] = "long",
	[323877] = "warning",
	["stages"] = "long",
})

BigWigs:AddColors("Dealer Xy'exa", {
	[320230] = "orange",
	[321948] = {"blue","red"},
	[323687] = "blue",
})

BigWigs:AddSounds("Dealer Xy'exa", {
	[320230] = "long",
	[321948] = "warning",
	[323687] = "alarm",
})

BigWigs:AddColors("Mueh'zala", {
	[325258] = "yellow",
	[325725] = "blue",
	[326171] = "red",
	[327646] = "yellow",
	[334970] = "cyan",
})

BigWigs:AddSounds("Mueh'zala", {
	[325258] = "warning",
	[325725] = "alarm",
	[326171] = "long",
	[327646] = "alert",
	[334970] = "info",
})

BigWigs:AddColors("De Other Side Trash", {
	[328740] = "yellow",
	[331548] = "purple",
	[331846] = {"blue","orange"},
	[331927] = "yellow",
	[332084] = "red",
	[332157] = "blue",
	[332605] = "yellow",
	[332608] = {"blue","orange"},
	[332612] = "red",
	[332672] = {"blue","yellow"},
	[332678] = {"blue","purple"},
	[332706] = "red",
	[333227] = {"green","red"},
	[333250] = "blue",
	[333787] = "red",
	[334051] = "orange",
	[340026] = "orange",
	["soporific_shimmerdust"] = "blue",
})

BigWigs:AddSounds("De Other Side Trash", {
	[328740] = "alarm",
	[331548] = "alert",
	[331846] = {"alarm","alert"},
	[331927] = "warning",
	[332084] = "warning",
	[332157] = "alarm",
	[332605] = "alert",
	[332608] = "alarm",
	[332612] = "warning",
	[332672] = {"alarm","info"},
	[332678] = "alert",
	[332706] = "warning",
	[333227] = {"alert","info","warning"},
	[333250] = "underyou",
	[333787] = "warning",
	[334051] = "alert",
	[340026] = "alert",
	["soporific_shimmerdust"] = {"alarm","warning"},
})
