-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("The Sand Queen", {
	[257092] = "yellow",
	[257495] = "orange",
	[257608] = {"blue","red"},
	[257609] = "yellow",
})

BigWigs:AddSounds("The Sand Queen", {
	[257092] = "alert",
	[257495] = "long",
	[257608] = "alarm",
	[257609] = "info",
})

BigWigs:AddColors("Jes Howlis", {
	[257777] = {"blue","yellow"},
	[257785] = "red",
	[257791] = "orange",
	[257793] = "cyan",
	[257827] = {"blue","green","orange"},
	[260067] = {"blue","red"},
})

BigWigs:AddSounds("Jes Howlis", {
	[257777] = "alarm",
	[257785] = "warning",
	[257791] = "alert",
	[257793] = "long",
	[257827] = {"alert","info"},
	[260067] = "alert",
})

BigWigs:AddColors("Knight Captain Valyri", {
	[256955] = "red",
	[256970] = "yellow",
	[257028] = {"blue","yellow"},
})

BigWigs:AddSounds("Knight Captain Valyri", {
	[256955] = "warning",
	[256970] = "alert",
	[257028] = "alarm",
})

BigWigs:AddColors("Overseer Korgus", {
	[256038] = {"blue","green","orange","red"},
	[256083] = "yellow",
	[256105] = {"blue","orange"},
	[256198] = "cyan",
	[256199] = "cyan",
	[263345] = "yellow",
})

BigWigs:AddSounds("Overseer Korgus", {
	[256038] = {"info","warning"},
	[256083] = "alert",
	[256105] = {"alarm","warning"},
	[256198] = "info",
	[256199] = "info",
	[263345] = "alert",
})

BigWigs:AddColors("Tol Dagor Trash", {
	[258079] = {"blue","orange"},
	[258128] = "yellow",
	[258153] = "yellow",
	[258313] = "red",
	[258634] = "orange",
	[258864] = "orange",
	[258917] = "red",
	[258935] = "orange",
})

BigWigs:AddSounds("Tol Dagor Trash", {
	[258079] = "alarm",
	[258128] = "alert",
	[258153] = "alert",
	[258313] = "warning",
	[258634] = "alarm",
	[258864] = "long",
	[258917] = "alarm",
	[258935] = "warning",
})
