-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Ingra Maloch", {
	[323057] = "orange",
	[323059] = {"cyan","green"},
	[323137] = "yellow",
	[323149] = "orange",
	[323177] = "red",
	[323250] = "blue",
	[328756] = "red",
})

BigWigs:AddSounds("Ingra Maloch", {
	[323057] = "alert",
	[323059] = {"info","long"},
	[323137] = "alarm",
	[323149] = "info",
	[323177] = "alarm",
	[323250] = "underyou",
	[328756] = "warning",
})

BigWigs:AddColors("Mistcaller", {
	[321828] = "blue",
	[321834] = "orange",
	[321891] = {"blue","red"},
	[336499] = "cyan",
	[341709] = "yellow",
})

BigWigs:AddSounds("Mistcaller", {
	[321828] = "warning",
	[321834] = "alarm",
	[321891] = {"alert","warning"},
	[336499] = "long",
	[341709] = "alert",
})

BigWigs:AddColors("Tred'ova", {
	[322450] = "cyan",
	[322527] = "green",
	[322550] = "yellow",
	[322563] = {"blue","yellow"},
	[322614] = {"blue","green","purple"},
	[322654] = "yellow",
	[326309] = "blue",
	[463602] = "orange",
})

BigWigs:AddSounds("Tred'ova", {
	[322450] = "long",
	[322527] = "info",
	[322550] = "info",
	[322563] = "warning",
	[322614] = {"alert","info"},
	[322654] = "alert",
	[326309] = "underyou",
	[463602] = "alarm",
})

BigWigs:AddColors("Mists of Tirna Scithe Trash", {
	[321968] = "red",
	[322486] = {"blue","yellow"},
	[322557] = {"blue","purple","yellow"},
	[322569] = "red",
	[322938] = "red",
	[322968] = "yellow",
	[324776] = "orange",
	[324909] = "yellow",
	[324914] = {"orange","red"},
	[324923] = "orange",
	[325021] = {"blue","yellow"},
	[325224] = {"blue","yellow"},
	[325418] = {"blue","orange"},
	[326017] = "blue",
	[326021] = "yellow",
	[326046] = {"orange","red"},
	[326090] = {"blue","orange"},
	[340160] = "orange",
	[340189] = "cyan",
	[340208] = "purple",
	[340279] = {"blue","orange","yellow"},
	[340289] = "purple",
	[340300] = "purple",
	[340304] = "red",
	[340305] = "orange",
	[340544] = "red",
	[460092] = "yellow",
	[463217] = "purple",
	[463248] = {"blue","red"},
	[463256] = {"blue","orange"},
})

BigWigs:AddSounds("Mists of Tirna Scithe Trash", {
	[321968] = "alarm",
	[322486] = "alert",
	[322557] = {"alert","info"},
	[322569] = "alert",
	[322938] = "alert",
	[322968] = "alarm",
	[324776] = "alert",
	[324909] = "long",
	[324914] = {"alert","warning"},
	[324923] = "alarm",
	[325021] = "alert",
	[325224] = "alarm",
	[325418] = "alert",
	[326017] = "underyou",
	[326021] = "alarm",
	[326046] = {"alert","warning"},
	[326090] = "alert",
	[340160] = "alarm",
	[340189] = "info",
	[340208] = "alert",
	[340279] = {"alarm","info"},
	[340289] = "alert",
	[340300] = "alert",
	[340304] = "alarm",
	[340305] = "alarm",
	[340544] = "alert",
	[460092] = "alert",
	[463217] = "alert",
	[463248] = "alert",
	[463256] = {"alarm","underyou"},
})
