-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Bronjahm", {
	[68839] = {"blue","orange"},
	[68872] = "red",
})

BigWigs:AddSounds("Bronjahm", {
	[68839] = "alert",
})

BigWigs:AddColors("Devourer of Souls", {
	[68912] = "red",
	[69051] = {"blue","orange"},
})

BigWigs:AddSounds("Devourer of Souls", {
	[69051] = "alert",
})
