-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Grand Champions", {
	[-7534] = "blue",
	[66043] = {"blue","yellow"},
	[67528] = "orange",
	[67534] = {"blue","yellow"},
})

BigWigs:AddSounds("Grand Champions", {
	[-7534] = "alarm",
})

BigWigs:AddColors("Eadric the Pure", {
	[66935] = "orange",
})

BigWigs:AddSounds("Eadric the Pure", {
})

BigWigs:AddColors("Argent Confessor Paletress", {
	[66515] = {"green","red","yellow"},
	[66537] = "orange",
	[66619] = {"blue","yellow"},
	["confess"] = {"red","yellow"},
})

BigWigs:AddSounds("Argent Confessor Paletress", {
	[66515] = "info",
})

BigWigs:AddColors("The Black Knight", {
	[-7598] = "orange",
	[67781] = "blue",
})

BigWigs:AddSounds("The Black Knight", {
	[67781] = "alarm",
})

BigWigs:AddColors("Trial of the Champion Trash", {
})

BigWigs:AddSounds("Trial of the Champion Trash", {
})
