-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Sadana Bloodfury", {
	[153094] = "orange",
	[153153] = "cyan",
	[153224] = "blue",
	[153240] = "yellow",
	[164974] = "red",
})

BigWigs:AddSounds("Sadana Bloodfury", {
	[153094] = "alarm",
	[153153] = "alert",
	[153224] = "underyou",
	[153240] = "alert",
	[164974] = "warning",
})

BigWigs:AddColors("Nhallish", {
	[152792] = "purple",
	[152801] = "yellow",
	[152979] = "red",
	[153067] = "orange",
	[153623] = "yellow",
})

BigWigs:AddSounds("Nhallish", {
	[152792] = "alarm",
	[152801] = "alarm",
	[152979] = "info",
	[153067] = "long",
	[153623] = "alert",
})

BigWigs:AddColors("Bonemaw", {
	[153804] = {"green","orange","yellow"},
	[154175] = "orange",
	[165578] = "red",
	["submerge"] = "cyan",
	["summon_worms"] = "cyan",
})

BigWigs:AddSounds("Bonemaw", {
	[153804] = {"info","long","warning"},
	[154175] = "alarm",
	[165578] = "alert",
	["submerge"] = "info",
	["summon_worms"] = "info",
})

BigWigs:AddColors("Ner'zhul", {
	[154350] = "red",
	[154442] = "yellow",
	[154469] = {"blue","orange","red"},
})

BigWigs:AddSounds("Ner'zhul", {
	[154350] = "alert",
	[154442] = "alarm",
	[154469] = {"alert","underyou","warning"},
})

BigWigs:AddColors("Shadowmoon Burial Grounds Trash", {
	[152818] = "yellow",
	[152819] = {"blue","yellow"},
	[152964] = "red",
	[153268] = "yellow",
	[153395] = "red",
	[156718] = "orange",
	[164907] = "purple",
	[394512] = "orange",
	[398150] = {"blue","red"},
	[398151] = "yellow",
	[398154] = "orange",
	[398206] = "red",
})

BigWigs:AddSounds("Shadowmoon Burial Grounds Trash", {
	[152818] = "alert",
	[152819] = "alert",
	[152964] = "alert",
	[153268] = "alert",
	[153395] = "alarm",
	[156718] = "warning",
	[164907] = {"alarm","alert"},
	[394512] = "long",
	[398150] = {"alarm","warning"},
	[398151] = "alert",
	[398154] = "alarm",
	[398206] = "warning",
})
