-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Darkweaver Syth", {
	[-5235] = "red",
	[12548] = {"blue","orange"},
	[15659] = {"blue","yellow"},
})

BigWigs:AddSounds("Darkweaver Syth", {
})

BigWigs:AddColors("Anzu", {
	[-5253] = {"green","orange"},
	[-5252] = {"blue","yellow"},
	[40184] = "red",
	[40303] = {"blue","yellow"},
})

BigWigs:AddSounds("Anzu", {
	[-5252] = "alert",
	[40184] = "warning",
	[40303] = "alarm",
})

BigWigs:AddColors("Talon King Ikiss", {
	[35032] = {"blue","red"},
	[38197] = "orange",
	[38245] = {"blue","yellow"},
})

BigWigs:AddSounds("Talon King Ikiss", {
	[35032] = "alarm",
	[38197] = "warning",
})
