-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Hearthsinger Forresten", {
	[16244] = "yellow",
	[16798] = {"blue","orange","red"},
})

BigWigs:AddSounds("Hearthsinger Forresten", {
	[16244] = "alert",
	[16798] = {"alarm","alert"},
})

BigWigs:AddColors("The Unforgiven", {
	[14907] = "yellow",
	[122832] = {"blue","yellow"},
})

BigWigs:AddSounds("The Unforgiven", {
	[14907] = "alert",
	[122832] = "alert",
})

BigWigs:AddColors("Timmy the Cruel", {
	[8599] = "cyan",
	[12021] = {"blue","red"},
	[17470] = "purple",
})

BigWigs:AddSounds("Timmy the Cruel", {
	[8599] = "long",
	[12021] = "alarm",
	[17470] = "alert",
})

BigWigs:AddColors("Commander Malor", {
	[12734] = "orange",
	[15493] = "red",
	[16172] = "purple",
	[17228] = "red",
})

BigWigs:AddSounds("Commander Malor", {
	[12734] = {"alarm","alert"},
	[15493] = "alert",
	[16172] = "alert",
	[17228] = "alert",
})

BigWigs:AddColors("Willey Hopebreaker", {
	[10101] = "purple",
	[17279] = "cyan",
	[110762] = "purple",
})

BigWigs:AddSounds("Willey Hopebreaker", {
	[10101] = "alert",
	[17279] = "info",
	[110762] = "alert",
})

BigWigs:AddColors("Instructor Galford", {
	[17274] = "red",
	[17293] = {"blue","orange","yellow"},
	[17366] = "yellow",
	[33975] = "red",
})

BigWigs:AddSounds("Instructor Galford", {
	[17274] = "alert",
	[17293] = {"alarm","alert"},
	[17366] = "alarm",
	[33975] = "alert",
})

BigWigs:AddColors("Balnazzar", {
	[12098] = {"blue","cyan","red"},
	[13704] = "yellow",
	[17286] = "orange",
	[17287] = "red",
	[17405] = {"blue","cyan","orange"},
	[80750] = "red",
	[452927] = "orange",
	[452928] = {"blue","cyan","red"},
})

BigWigs:AddSounds("Balnazzar", {
	[12098] = {"alert","info"},
	[13704] = "info",
	[17286] = "info",
	[17287] = "alert",
	[17405] = {"info","warning"},
	[80750] = "alert",
	[452927] = "alarm",
	[452928] = {"alert","info"},
})

BigWigs:AddColors("Baroness Anastari", {
	[16867] = {"blue","yellow"},
	[17244] = {"blue","green","yellow"},
	[18327] = "orange",
})

BigWigs:AddSounds("Baroness Anastari", {
	[16867] = "info",
	[17244] = {"info","warning"},
	[18327] = "alarm",
})

BigWigs:AddColors("Nerub'enkan", {
	[4962] = {"blue","yellow"},
	[6016] = "purple",
	[17235] = "cyan",
})

BigWigs:AddSounds("Nerub'enkan", {
	[4962] = "alarm",
	[6016] = "alert",
	[17235] = "info",
})

BigWigs:AddColors("Maleki the Pallid", {
	[16869] = {"blue","red","yellow"},
	[17620] = "orange",
})

BigWigs:AddSounds("Maleki the Pallid", {
	[16869] = {"alert","warning"},
	[17620] = "alert",
})

BigWigs:AddColors("Magistrate Barthilas", {
	[10887] = "red",
	[14099] = "purple",
	[16791] = "yellow",
	[455596] = "orange",
})

BigWigs:AddSounds("Magistrate Barthilas", {
	[10887] = "alert",
	[14099] = "alarm",
	[16791] = "info",
	[455596] = "alarm",
})

BigWigs:AddColors("Ramstein the Gorger", {
	[5568] = "yellow",
	[17307] = {"blue","purple"},
})

BigWigs:AddSounds("Ramstein the Gorger", {
	[5568] = "info",
	[17307] = "alert",
})

BigWigs:AddColors("Postmaster Malown", {
	[6253] = "purple",
	[12741] = {"blue","yellow"},
})

BigWigs:AddSounds("Postmaster Malown", {
	[6253] = "alert",
	[12741] = "alert",
})

BigWigs:AddColors("Lord Aurius Rivendare", {
	[17434] = "red",
	[17471] = "yellow",
	[17473] = "cyan",
})

BigWigs:AddSounds("Lord Aurius Rivendare", {
	[17434] = "alert",
	[17473] = "info",
})
