-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Avanoxx", {
	[438471] = "purple",
	[438473] = "red",
	[438476] = "yellow",
	[446794] = "orange",
})

BigWigs:AddSounds("Avanoxx", {
	[438471] = "alert",
	[438473] = "long",
	[438476] = "info",
	[446794] = "warning",
})

BigWigs:AddColors("Anub'zekt", {
	[433740] = {"blue","yellow"},
	[433766] = {"cyan","green"},
	[433781] = "blue",
	[435012] = "purple",
	[439506] = {"blue","orange"},
	[442210] = "red",
	["bloodstained_webmage"] = "cyan",
})

BigWigs:AddSounds("Anub'zekt", {
	[433740] = "alert",
	[433766] = {"info","long"},
	[433781] = "underyou",
	[435012] = "alarm",
	[439506] = "alarm",
	[442210] = "alert",
	["bloodstained_webmage"] = "info",
})

BigWigs:AddColors("Ki'katal the Harvester", {
	[432031] = {"blue","yellow"},
	[432117] = "cyan",
	[432130] = "orange",
	[432227] = "red",
	[461487] = {"blue","red","yellow"},
})

BigWigs:AddSounds("Ki'katal the Harvester", {
	[432031] = "info",
	[432117] = "long",
	[432130] = "alarm",
	[432227] = "alert",
	[461487] = {"alarm","info"},
})

BigWigs:AddColors("Ara-Kara, City of Echoes Trash", {
	[432967] = "cyan",
	[433002] = "purple",
	[433841] = "red",
	[433845] = "orange",
	[434793] = "red",
	[434802] = "red",
	[434824] = "orange",
	[434830] = "blue",
	[436614] = {"blue","orange"},
	[438826] = {"blue","yellow"},
	[438877] = "cyan",
	[439208] = "green",
	[448248] = "red",
	[453161] = "orange",
	[1241693] = "yellow",
	[1241785] = {"blue","purple"},
})

BigWigs:AddSounds("Ara-Kara, City of Echoes Trash", {
	[432967] = {"info","warning"},
	[433002] = "alert",
	[433841] = "alert",
	[433845] = "alarm",
	[434793] = "alert",
	[434802] = "warning",
	[434824] = "alarm",
	[434830] = "underyou",
	[436614] = "warning",
	[438826] = {"alert","underyou"},
	[438877] = "info",
	[439208] = "info",
	[448248] = "alert",
	[453161] = "alarm",
	[1241693] = "info",
	[1241785] = "alert",
})

BigWigs:AddColors("Brew Master Aldryr", {
	[431895] = {"blue","green"},
	[432179] = {"blue","red","yellow"},
	[432196] = "blue",
	[432198] = "orange",
	[432229] = "purple",
	[442525] = {"cyan","green"},
})

BigWigs:AddSounds("Brew Master Aldryr", {
	[431895] = "info",
	[432179] = "info",
	[432196] = "underyou",
	[432198] = "alarm",
	[432229] = "alert",
	[442525] = "long",
})

BigWigs:AddColors("I'pa", {
	[439031] = "purple",
	[439202] = {"blue","orange"},
	[439365] = "yellow",
	[440087] = "blue",
	[440147] = "cyan",
})

BigWigs:AddSounds("I'pa", {
	[439031] = "alert",
	[439202] = "alert",
	[439365] = "long",
	[440087] = "underyou",
	[440147] = "warning",
})

BigWigs:AddColors("Benk Buzzbee", {
	[438025] = "yellow",
	[438971] = "orange",
	[439524] = "red",
	[440134] = {"blue","green","purple"},
})

BigWigs:AddSounds("Benk Buzzbee", {
	[438025] = "info",
	[438971] = "info",
	[439524] = "alert",
	[440134] = {"alarm","info","underyou"},
})

BigWigs:AddColors("Goldie Baronbottom", {
	[435560] = "cyan",
	[435622] = "yellow",
	[436592] = "purple",
	[436644] = {"blue","orange"},
})

BigWigs:AddSounds("Goldie Baronbottom", {
	[435560] = "info",
	[435622] = "long",
	[436592] = "alert",
	[436644] = "alarm",
})

BigWigs:AddColors("Cinderbrew Meadery Trash", {
	[434706] = "orange",
	[434756] = {"blue","red"},
	[434773] = {"blue","yellow"},
	[434998] = "red",
	[437721] = "red",
	[437956] = {"blue","yellow"},
	[439467] = "orange",
	[440687] = "red",
	[440876] = "yellow",
	[441119] = {"blue","orange"},
	[441179] = "blue",
	[441214] = "yellow",
	[441242] = "red",
	[441351] = "red",
	[441408] = "cyan",
	[441434] = "cyan",
	[441627] = "red",
	[442589] = "orange",
	[442995] = "yellow",
	[448619] = {"blue","orange"},
	[463206] = "yellow",
	[463218] = "yellow",
})

BigWigs:AddSounds("Cinderbrew Meadery Trash", {
	[434706] = "alarm",
	[434756] = "alert",
	[434773] = "info",
	[434998] = "long",
	[437721] = "alert",
	[437956] = "alarm",
	[439467] = "alarm",
	[440687] = "alert",
	[440876] = "alarm",
	[441119] = "alarm",
	[441179] = "underyou",
	[441214] = "info",
	[441242] = "alert",
	[441351] = "alert",
	[441408] = "info",
	[441434] = "info",
	[441627] = "alert",
	[442589] = "alarm",
	[442995] = "alert",
	[448619] = "alarm",
	[463206] = "alert",
	[463218] = "info",
})

BigWigs:AddColors("Orator Krix'vizk", {
	[434722] = "purple",
	[434779] = "orange",
	[434829] = {"green","yellow"},
	[434926] = "blue",
	[448561] = {"blue","red"},
})

BigWigs:AddSounds("Orator Krix'vizk", {
	[434722] = "alert",
	[434779] = "alarm",
	[434829] = {"info","long"},
	[434926] = "underyou",
	[448561] = "alarm",
})

BigWigs:AddColors("Fangs of the Queen", {
	[439621] = "red",
	[439692] = "orange",
	[440218] = {"blue","yellow"},
	[440468] = "purple",
	[441298] = {"blue","yellow"},
	[441384] = "cyan",
	[458741] = {"blue","purple"},
})

BigWigs:AddSounds("Fangs of the Queen", {
	[439621] = "alarm",
	[439692] = "alarm",
	[440218] = "alert",
	[440468] = "alarm",
	[441298] = "info",
	[441384] = "long",
	[458741] = "warning",
})

BigWigs:AddColors("The Coaglamation", {
	[441289] = "red",
	[441395] = "yellow",
	[461825] = "blue",
	[461842] = "purple",
	[461880] = "orange",
})

BigWigs:AddSounds("The Coaglamation", {
	[441289] = "long",
	[441395] = "alert",
	[461825] = "underyou",
	[461842] = "alert",
	[461880] = "alarm",
})

BigWigs:AddColors("Izo, the Grand Splicer", {
	[437700] = "orange",
	[438860] = "yellow",
	[439341] = "red",
	[439401] = "yellow",
	[439646] = "purple",
})

BigWigs:AddSounds("Izo, the Grand Splicer", {
	[437700] = "alarm",
	[438860] = "long",
	[439341] = "alert",
	[439401] = "info",
	[439646] = "alarm",
})

BigWigs:AddColors("City of Threads Trash", {
	[434137] = "yellow",
	[436205] = "yellow",
	[441795] = "green",
	[443397] = {"blue","purple"},
	[443430] = "red",
	[443433] = {"blue","red"},
	[443437] = {"blue","yellow"},
	[443500] = "orange",
	[443507] = "yellow",
	[445813] = "orange",
	[446086] = "red",
	[446717] = "yellow",
	[447271] = "orange",
	[448047] = {"blue","cyan"},
	[448305] = "green",
	[450784] = "orange",
	[451222] = "yellow",
	[451423] = "red",
	[451543] = "orange",
	[452151] = {"blue","purple"},
	[452162] = "red",
})

BigWigs:AddSounds("City of Threads Trash", {
	[434137] = "long",
	[436205] = "info",
	[441795] = "info",
	[443397] = "alert",
	[443430] = "alert",
	[443433] = {"alert","underyou"},
	[443437] = "alarm",
	[443500] = "alarm",
	[443507] = "info",
	[445813] = "long",
	[446086] = "alert",
	[446717] = "alert",
	[447271] = "alarm",
	[448047] = "info",
	[448305] = "info",
	[450784] = "alarm",
	[451222] = "info",
	[451423] = "long",
	[451543] = "alarm",
	[452151] = "alert",
	[452162] = "alert",
})

BigWigs:AddColors("Ol' Waxbeard", {
	[422116] = {"blue","orange"},
	[422163] = {"blue","red"},
	[422245] = "purple",
	[429093] = {"cyan","yellow"},
})

BigWigs:AddSounds("Ol' Waxbeard", {
	[422116] = "alarm",
	[422163] = {"info","warning"},
	[422245] = "alert",
	[429093] = {"info","long"},
})

BigWigs:AddColors("Blazikon", {
	[421817] = {"blue","yellow"},
	[421910] = "cyan",
	[423109] = "red",
	[424212] = {"blue","orange"},
	[425394] = "cyan",
	[443835] = "purple",
})

BigWigs:AddSounds("Blazikon", {
	[421817] = "long",
	[421910] = {"info","warning"},
	[423109] = "alarm",
	[424212] = {"alarm","underyou"},
	[425394] = "info",
	[443835] = "warning",
})

BigWigs:AddColors("The Candle King", {
	[420659] = "cyan",
	[420696] = {"blue","orange"},
	[421067] = "blue",
	[421653] = "blue",
	[422648] = {"blue","yellow"},
	[426145] = "red",
})

BigWigs:AddSounds("The Candle King", {
	[420659] = "info",
	[420696] = "alert",
	[421067] = "underyou",
	[421653] = "info",
	[422648] = {"alarm","warning"},
	[426145] = "warning",
})

BigWigs:AddColors("The Darkness", {
	[426943] = "yellow",
	[427011] = {"blue","red"},
	[427025] = "orange",
	[427157] = "cyan",
	[427176] = "red",
	[428266] = "yellow",
})

BigWigs:AddSounds("The Darkness", {
	[426943] = "warning",
	[427011] = "alarm",
	[427025] = "alarm",
	[427157] = "alert",
	[427176] = "alert",
	[428266] = "long",
})

BigWigs:AddColors("Darkflame Cleft Trash", {
	[422393] = "yellow",
	[422541] = "cyan",
	[423501] = "orange",
	[424322] = "red",
	[425536] = "yellow",
	[426260] = "orange",
	[426261] = "yellow",
	[426295] = "red",
	[426619] = {"blue","red"},
	[426883] = "orange",
	[428019] = {"blue","red","yellow"},
	[428066] = "yellow",
	[428650] = {"blue","red"},
	[430171] = "yellow",
	[440652] = {"blue","orange"},
	[469620] = {"blue","purple"},
	[1218117] = "yellow",
	[1218131] = {"blue","cyan"},
	["minecart"] = {"cyan","green"},
})

BigWigs:AddSounds("Darkflame Cleft Trash", {
	[422393] = "alert",
	[422541] = "info",
	[423501] = "alarm",
	[424322] = "alert",
	[425536] = "alert",
	[426260] = "alarm",
	[426261] = "alarm",
	[426295] = "alert",
	[426619] = {"alarm","info"},
	[426883] = "alarm",
	[428019] = "alert",
	[428066] = "info",
	[428650] = "warning",
	[430171] = "info",
	[440652] = {"alarm","underyou"},
	[469620] = {"alert","warning"},
	[1218117] = "alert",
	[1218131] = {"info","underyou"},
	["minecart"] = {"info","long"},
})

BigWigs:AddColors("Azhiccar", {
	[1217232] = "cyan",
	[1217247] = {"blue","red"},
	[1217327] = "yellow",
	[1217446] = "blue",
	[1217664] = "purple",
	[1227745] = {"blue","orange"},
})

BigWigs:AddSounds("Azhiccar", {
	[1217232] = "long",
	[1217247] = {"alarm","info"},
	[1217327] = "alert",
	[1217446] = "underyou",
	[1217664] = "warning",
	[1227745] = "alarm",
})

BigWigs:AddColors("Taah'bat and A'wazj", {
	[1219457] = "yellow",
	[1219482] = "purple",
	[1219700] = {"cyan","green"},
	[1227918] = {"blue","orange"},
	[1236130] = {"blue","red"},
})

BigWigs:AddSounds("Taah'bat and A'wazj", {
	[1219457] = "info",
	[1219482] = "alert",
	[1219700] = "long",
	[1227918] = {"alarm","warning"},
	[1236130] = "info",
})

BigWigs:AddColors("Soul-Scribe", {
	[1224793] = "cyan",
	[1224865] = "green",
	[1225174] = "red",
	[1225218] = "orange",
	[1226444] = "blue",
	[1236703] = "yellow",
})

BigWigs:AddSounds("Soul-Scribe", {
	[1224793] = "alert",
	[1224865] = "info",
	[1225174] = "alarm",
	[1225218] = "alarm",
	[1226444] = "warning",
	[1236703] = "long",
})

BigWigs:AddColors("Eco-Dome Al'dani Trash", {
	[1215850] = "orange",
	[1221152] = "orange",
	[1221190] = {"blue","yellow"},
	[1221483] = {"blue","yellow"},
	[1221532] = "yellow",
	[1222202] = "blue",
	[1222341] = "purple",
	[1222356] = "orange",
	[1223000] = "orange",
	[1223007] = "orange",
	[1226111] = {"blue","orange"},
	[1226492] = "green",
	[1229474] = "red",
	[1229510] = "red",
	[1231244] = "yellow",
	[1235368] = "purple",
	[1236981] = {"blue","green"},
	[1237195] = {"blue","yellow"},
	[1237220] = "red",
	[1239229] = "green",
	[1248699] = "red",
})

BigWigs:AddSounds("Eco-Dome Al'dani Trash", {
	[1215850] = "alarm",
	[1221152] = "alarm",
	[1221190] = "info",
	[1221483] = "alert",
	[1221532] = "alert",
	[1222202] = "underyou",
	[1222341] = "alert",
	[1222356] = "alarm",
	[1223000] = "info",
	[1223007] = "alarm",
	[1226111] = "alarm",
	[1226492] = "info",
	[1229474] = "alert",
	[1229510] = "alert",
	[1231244] = "long",
	[1235368] = {"alarm","alert"},
	[1236981] = "info",
	[1237195] = "alarm",
	[1237220] = "info",
	[1239229] = "info",
	[1248699] = "long",
})

BigWigs:AddColors("Big M.O.M.M.A.", {
	[460156] = "green",
	[469981] = "cyan",
	[471585] = "cyan",
	[472452] = "orange",
	[473220] = {"blue","yellow"},
	[473287] = "blue",
	[473351] = "purple",
	[1214780] = "red",
})

BigWigs:AddSounds("Big M.O.M.M.A.", {
	[460156] = {"info","long"},
	[469981] = "info",
	[471585] = "info",
	[472452] = "alarm",
	[473220] = {"alarm","warning"},
	[473287] = "underyou",
	[473351] = "alert",
	[1214780] = "warning",
})

BigWigs:AddColors("Demolition Duo", {
	[459779] = {"blue","green","red"},
	[459799] = "purple",
	[460602] = {"blue","yellow"},
	[460867] = "yellow",
	[470090] = "cyan",
	[473690] = {"blue","orange"},
	[1217653] = "orange",
})

BigWigs:AddSounds("Demolition Duo", {
	[459779] = {"alarm","info"},
	[459799] = "alert",
	[460602] = "alert",
	[460867] = "long",
	[470090] = "long",
	[473690] = {"alarm","info"},
	[1217653] = "alarm",
})

BigWigs:AddColors("Swampface", {
	[469478] = "purple",
	[470039] = "blue",
	[473070] = "yellow",
	[473114] = "orange",
})

BigWigs:AddSounds("Swampface", {
	[469478] = "alert",
	[470039] = "info",
	[473070] = "long",
	[473114] = "alarm",
})

BigWigs:AddColors("Geezle Gigazap", {
	[465463] = "orange",
	[466190] = "purple",
	[468723] = "blue",
	[468813] = "yellow",
	[468841] = {"blue","red"},
})

BigWigs:AddSounds("Geezle Gigazap", {
	[465463] = "long",
	[466190] = {"alarm","alert"},
	[468723] = "underyou",
	[468813] = "info",
	[468841] = "warning",
})

BigWigs:AddColors("Operation: Floodgate Trash", {
	[462771] = {"blue","red"},
	[463058] = "red",
	[463169] = {"blue","yellow"},
	[465120] = "yellow",
	[465408] = "cyan",
	[465666] = "purple",
	[465682] = "orange",
	[465754] = "yellow",
	[465813] = {"blue","orange","yellow"},
	[465827] = "yellow",
	[468631] = "red",
	[468726] = "cyan",
	[469799] = {"blue","orange"},
	[471733] = "red",
	[471736] = "orange",
	[474337] = {"blue","orange"},
	[1214337] = "green",
	[1214468] = "red",
	[1216039] = "orange",
	["weapons_stockpiles_pilfered"] = "green",
})

BigWigs:AddSounds("Operation: Floodgate Trash", {
	[462771] = {"alert","underyou"},
	[463058] = "alert",
	[463169] = "info",
	[465120] = "alarm",
	[465408] = "info",
	[465666] = "alert",
	[465682] = "alarm",
	[465754] = "alarm",
	[465813] = "alert",
	[465827] = "info",
	[468631] = "alert",
	[468726] = "info",
	[469799] = "info",
	[471733] = "alert",
	[471736] = "alarm",
	[474337] = {"alarm","underyou"},
	[1214337] = "info",
	[1214468] = "alert",
	[1216039] = "alarm",
	["weapons_stockpiles_pilfered"] = "info",
})

BigWigs:AddColors("Captain Dailcry", {
	[424414] = "purple",
	[424419] = "red",
	[447439] = {"blue","green","yellow"},
	[1238780] = {"blue","orange"},
})

BigWigs:AddSounds("Captain Dailcry", {
	[424414] = "alert",
	[424419] = "warning",
	[447439] = {"alert","info"},
	[1238780] = {"alarm","underyou"},
})

BigWigs:AddColors("Baron Braunpyke", {
	[422969] = "cyan",
	[423015] = "orange",
	[423051] = "red",
	[423062] = "yellow",
	[446368] = {"cyan","green"},
	[446403] = {"blue","yellow"},
})

BigWigs:AddSounds("Baron Braunpyke", {
	[422969] = "info",
	[423015] = "alert",
	[423051] = "warning",
	[423062] = "alarm",
	[446368] = "info",
	[446403] = "info",
})

BigWigs:AddColors("Prioress Murrpray", {
	[423588] = {"cyan","green"},
	[423664] = "green",
	[425556] = "blue",
	[428169] = "red",
	[444546] = {"blue","orange"},
	[444608] = "red",
	[451605] = "yellow",
})

BigWigs:AddSounds("Prioress Murrpray", {
	[423588] = {"info","long"},
	[423664] = "info",
	[425556] = "underyou",
	[428169] = "warning",
	[444546] = {"alert","warning"},
	[444608] = "info",
	[451605] = "alarm",
})

BigWigs:AddColors("Priory of the Sacred Flame Trash", {
	[424423] = "red",
	[424429] = {"blue","orange"},
	[424431] = "yellow",
	[424462] = "yellow",
	[424621] = "orange",
	[427342] = "yellow",
	[427356] = "red",
	[427484] = {"blue","orange"},
	[427596] = "purple",
	[427601] = "yellow",
	[427609] = "red",
	[427621] = "orange",
	[427897] = "orange",
	[427900] = "blue",
	[427950] = "red",
	[428150] = {"green","red"},
	[435088] = "green",
	[435165] = "purple",
	[444728] = "yellow",
	[444743] = "red",
	[446776] = "red",
	[448485] = "purple",
	[448492] = "red",
	[448515] = {"blue","purple"},
	[448787] = {"blue","red"},
	[448791] = "yellow",
	[453458] = {"blue","yellow"},
	[462859] = {"blue","orange"},
})

BigWigs:AddSounds("Priory of the Sacred Flame Trash", {
	[424423] = "alert",
	[424429] = {"alarm","underyou"},
	[424431] = "alert",
	[424462] = "long",
	[424621] = "alarm",
	[427342] = "info",
	[427356] = "warning",
	[427484] = {"alarm","underyou"},
	[427596] = "alert",
	[427601] = "long",
	[427609] = "alarm",
	[427621] = "alert",
	[427897] = "alarm",
	[427900] = "underyou",
	[427950] = "alert",
	[428150] = {"alert","info"},
	[435088] = "info",
	[435165] = "alert",
	[444728] = "alert",
	[444743] = "alert",
	[446776] = "alert",
	[448485] = {"alarm","info"},
	[448492] = "alert",
	[448515] = "alert",
	[448787] = "alert",
	[448791] = "alert",
	[453458] = {"alarm","info"},
	[462859] = "alert",
})

BigWigs:AddColors("Awakening the Machine", {
	[462802] = "red",
	[462826] = "orange",
	[462856] = "orange",
	[462892] = "yellow",
	[462936] = "red",
	[462983] = {"blue","yellow"},
	[463052] = "yellow",
	[463081] = "red",
	["stages"] = {"cyan","green"},
})

BigWigs:AddSounds("Awakening the Machine", {
	[462802] = "alert",
	[462826] = "alarm",
	[462856] = "info",
	[462892] = "alert",
	[462936] = "info",
	[462983] = "alarm",
	[463052] = "alert",
	[463081] = "alarm",
	["stages"] = "info",
})

BigWigs:AddColors("Shadowcrown", {
	[425264] = "purple",
	[426735] = {"blue","yellow"},
	[428086] = "red",
	[445996] = "orange",
	[451026] = "cyan",
	[453140] = {"blue","orange"},
	[453212] = "purple",
})

BigWigs:AddSounds("Shadowcrown", {
	[425264] = "alarm",
	[426735] = "alert",
	[428086] = "alert",
	[445996] = "long",
	[451026] = "warning",
	[453140] = {"long","underyou"},
	[453212] = "alarm",
})

BigWigs:AddColors("Anub'ikkaj", {
	[426787] = "yellow",
	[426860] = {"blue","orange"},
	[427001] = "purple",
	[452127] = {"blue","cyan"},
})

BigWigs:AddSounds("Anub'ikkaj", {
	[426787] = "alert",
	[426860] = "alarm",
	[427001] = "alarm",
	[452127] = "info",
})

BigWigs:AddColors("Rasha'nan Dawnbreaker", {
	[434089] = "orange",
	[434407] = "red",
	[434655] = {"blue","cyan","green"},
	[435793] = "purple",
	[448213] = "orange",
	[448888] = "yellow",
	[449528] = "green",
	[449734] = {"green","yellow"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("Rasha'nan Dawnbreaker", {
	[434089] = "alert",
	[434407] = "alert",
	[434655] = {"info","long"},
	[435793] = "warning",
	[448213] = "alarm",
	[448888] = "alert",
	[449528] = "info",
	[449734] = {"alert","info"},
	["stages"] = "long",
})

BigWigs:AddColors("The Dawnbreaker Trash", {
	[431309] = {"blue","orange"},
	[431349] = {"blue","red"},
	[431364] = {"blue","yellow"},
	[431491] = "purple",
	[431494] = "purple",
	[432448] = {"blue","orange"},
	[432520] = "orange",
	[432565] = "yellow",
	[446615] = "cyan",
	[449042] = "green",
	[450756] = "red",
	[450854] = "orange",
	[451091] = "green",
	[451097] = "red",
	[451098] = "orange",
	[451102] = "yellow",
	[451107] = {"blue","yellow"},
	[451112] = "yellow",
	[451117] = "purple",
	[451119] = {"blue","red"},
	[1242074] = "purple",
})

BigWigs:AddSounds("The Dawnbreaker Trash", {
	[431309] = "info",
	[431349] = "alarm",
	[431364] = "alert",
	[431491] = "alert",
	[431494] = "alarm",
	[432448] = "alarm",
	[432520] = "alert",
	[432565] = "alarm",
	[446615] = "info",
	[449042] = "info",
	[450756] = "info",
	[450854] = "alarm",
	[451091] = "info",
	[451097] = "alert",
	[451098] = "alarm",
	[451102] = "alert",
	[451107] = "alarm",
	[451112] = "info",
	[451117] = "alarm",
	[451119] = {"alarm","alert"},
	[1242074] = "info",
})

BigWigs:AddColors("Kyrioss", {
	[419870] = "yellow",
	[444123] = {"blue","cyan","yellow"},
	[474018] = "orange",
	[1214325] = "red",
})

BigWigs:AddSounds("Kyrioss", {
	[419870] = "alarm",
	[444123] = {"alert","long"},
	[474018] = "alarm",
	[1214325] = "info",
})

BigWigs:AddColors("Stormguard Gorren", {
	[424737] = {"blue","red"},
	[424797] = "blue",
	[424958] = "orange",
	[424966] = "blue",
	[425048] = "yellow",
})

BigWigs:AddSounds("Stormguard Gorren", {
	[424737] = "alert",
	[424958] = "alarm",
	[424966] = "underyou",
	[425048] = "long",
})

BigWigs:AddColors("Voidstone Monstrosity", {
	[423305] = "orange",
	[423393] = "purple",
	[424371] = "green",
	[429493] = {"blue","red"},
	[433067] = "blue",
	[445262] = {"cyan","green"},
	[445457] = "purple",
	[458082] = {"blue","green"},
})

BigWigs:AddSounds("Voidstone Monstrosity", {
	[423305] = "alarm",
	[423393] = "warning",
	[424371] = "info",
	[429493] = "alert",
	[433067] = "underyou",
	[445262] = "long",
	[445457] = "alarm",
	[458082] = "info",
})

BigWigs:AddColors("The Rookery Trash", {
	[426893] = "red",
	[427260] = "red",
	[427404] = "yellow",
	[427616] = {"blue","orange"},
	[430179] = {"blue","orange"},
	[430805] = {"blue","orange"},
	[430812] = "yellow",
	[443854] = "orange",
	[450628] = "cyan",
	[472764] = "cyan",
	[474018] = "orange",
	[474031] = {"blue","orange"},
	[1214523] = "red",
	[1214546] = "yellow",
	[1214628] = "yellow",
})

BigWigs:AddSounds("The Rookery Trash", {
	[426893] = "alarm",
	[427260] = "alert",
	[427404] = "info",
	[427616] = "alert",
	[430179] = "alert",
	[430805] = "alarm",
	[430812] = "info",
	[443854] = "alarm",
	[450628] = "info",
	[472764] = "info",
	[474018] = "alarm",
	[474031] = "alarm",
	[1214523] = "alert",
	[1214546] = "long",
	[1214628] = "long",
})

BigWigs:AddColors("E.D.N.A.", {
	[424795] = {"blue","red"},
	[424879] = "yellow",
	[424888] = "purple",
	[424889] = {"blue","red"},
	[424903] = "orange",
})

BigWigs:AddSounds("E.D.N.A.", {
	[424795] = "alarm",
	[424879] = "long",
	[424888] = "alert",
	[424889] = "warning",
	[424903] = "info",
})

BigWigs:AddColors("Skarmorak", {
	[422233] = "purple",
	[423200] = {"cyan","green"},
	[423538] = "orange",
	[423572] = "green",
})

BigWigs:AddSounds("Skarmorak", {
	[422233] = "alert",
	[423200] = {"info","long"},
	[423538] = "alarm",
	[423572] = "info",
})

BigWigs:AddColors("Master Machinists", {
	[428202] = "yellow",
	[428508] = "red",
	[428711] = "purple",
	[430097] = "red",
	[439577] = "cyan",
	[445541] = "orange",
	[449167] = "orange",
})

BigWigs:AddSounds("Master Machinists", {
	[428202] = "long",
	[428508] = "alarm",
	[428711] = "alert",
	[430097] = "alert",
	[439577] = "long",
	[445541] = "alarm",
	[449167] = "alarm",
})

BigWigs:AddColors("Void Speaker Eirich", {
	[427461] = {"blue","green","yellow"},
	[427852] = "red",
	[427869] = "orange",
	[457465] = "blue",
})

BigWigs:AddSounds("Void Speaker Eirich", {
	[427461] = {"info","warning"},
	[427852] = "alert",
	[427869] = "alarm",
	[457465] = "underyou",
})

BigWigs:AddColors("The Stonevault Trash", {
	[425027] = "purple",
	[425974] = "yellow",
	[426308] = {"blue","yellow"},
	[426345] = "purple",
	[426771] = "yellow",
	[428703] = "orange",
	[428879] = "purple",
	[428894] = "purple",
	[429109] = "red",
	[429427] = "cyan",
	[429545] = "yellow",
	[445207] = "red",
	[447141] = "orange",
	[448640] = "red",
	[449130] = "orange",
	[449154] = "yellow",
	[449455] = "red",
	[459210] = "purple",
	[462500] = "green",
})

BigWigs:AddSounds("The Stonevault Trash", {
	[425027] = "alarm",
	[425974] = "alert",
	[426308] = "alert",
	[426345] = "alarm",
	[426771] = "alert",
	[428703] = "alarm",
	[428879] = "alarm",
	[428894] = "alert",
	[429109] = "warning",
	[429427] = "info",
	[429545] = "alert",
	[445207] = "alert",
	[447141] = "alarm",
	[448640] = "alarm",
	[449130] = "alarm",
	[449154] = "alert",
	[449455] = "warning",
	[459210] = "alert",
	[462500] = "info",
})
