-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Melidrussa Chillworn", {
	[372682] = {"blue","red"},
	[372851] = {"blue","yellow"},
	[372988] = "green",
	[373046] = "yellow",
	[373680] = {"green","red"},
	[396044] = "orange",
})

BigWigs:AddSounds("Melidrussa Chillworn", {
	[372682] = {"alert","warning"},
	[372851] = {"alarm","alert"},
	[372988] = "info",
	[373046] = "long",
	[373680] = {"info","long"},
	[396044] = "alarm",
})

BigWigs:AddColors("Kokia Blazehoof", {
	[372107] = {"blue","yellow"},
	[372858] = "purple",
	[372863] = "orange",
	[373017] = "red",
	[373087] = "orange",
})

BigWigs:AddSounds("Kokia Blazehoof", {
	[372107] = "alarm",
	[372858] = "alert",
	[372863] = "long",
	[373017] = "warning",
	[373087] = "alarm",
})

BigWigs:AddColors("Kyrakka and Erkhart Stormvein", {
	[381512] = {"blue","purple"},
	[381516] = "red",
	[381517] = "yellow",
	[381525] = "orange",
	[381602] = "red",
	[381862] = "blue",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Kyrakka and Erkhart Stormvein", {
	[381512] = {"alarm","alert"},
	[381516] = "warning",
	[381517] = "alert",
	[381525] = "alarm",
	[381602] = "alert",
	[381862] = "alarm",
	["stages"] = {"info","long"},
})

BigWigs:AddColors("Ruby Life Pools Trash", {
	[372047] = "purple",
	[372087] = "orange",
	[372696] = "orange",
	[372735] = "yellow",
	[372743] = "red",
	[373614] = "orange",
	[373692] = "red",
	[373693] = {"blue","yellow"},
	[373972] = "red",
	[385313] = {"blue","yellow"},
	[385536] = "yellow",
	[391050] = "yellow",
	[391723] = "orange",
	[391726] = "orange",
	[392394] = "purple",
	[392395] = "purple",
	[392451] = "red",
	[392486] = "orange",
	[392569] = "red",
	[392640] = {"blue","red"},
})

BigWigs:AddSounds("Ruby Life Pools Trash", {
	[372047] = "alert",
	[372087] = "alarm",
	[372696] = "alarm",
	[372735] = "alert",
	[372743] = "alert",
	[373614] = "alarm",
	[373692] = "alert",
	[373693] = "alert",
	[373972] = "info",
	[385313] = "alert",
	[385536] = "alert",
	[391050] = "info",
	[391723] = "alarm",
	[391726] = "alarm",
	[392394] = "alert",
	[392395] = "alert",
	[392451] = "alert",
	[392486] = "long",
	[392569] = "long",
	[392640] = "alert",
})
