-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Elder Leaxa", {
	[260879] = "red",
	[260894] = "orange",
	[264603] = "cyan",
	[264757] = "yellow",
})

BigWigs:AddSounds("Elder Leaxa", {
	[260879] = "alert",
	[260894] = "alarm",
	[264603] = "long",
	[264757] = "alarm",
})

BigWigs:AddColors("Cragmaw the Infested", {
	[260292] = "yellow",
	[260333] = "orange",
	[260793] = "purple",
})

BigWigs:AddSounds("Cragmaw the Infested", {
	[260292] = "alert",
	[260333] = "long",
	[260793] = "alarm",
})

BigWigs:AddColors("Sporecaller Zancha", {
	[259718] = {"blue","orange"},
	[259732] = "red",
	[259830] = "cyan",
	[272457] = "purple",
	[273285] = "yellow",
})

BigWigs:AddSounds("Sporecaller Zancha", {
	[259718] = {"alarm","warning"},
	[259732] = "alarm",
	[259830] = "info",
	[272457] = "alert",
	[273285] = "long",
})

BigWigs:AddColors("Unbound Abomination", {
	[269301] = {"blue","orange"},
	[269310] = "green",
	[269843] = "red",
	["stages"] = {"cyan","yellow"},
})

BigWigs:AddSounds("Unbound Abomination", {
	[269301] = {"alarm","warning"},
	[269310] = "long",
	[269843] = "warning",
	["stages"] = "info",
})

BigWigs:AddColors("Underrot Trash", {
	[265016] = {"blue","orange"},
	[265019] = "red",
	[265081] = "red",
	[265089] = "orange",
	[265091] = {"red","yellow"},
	[265377] = {"blue","yellow"},
	[265433] = "red",
	[265487] = "orange",
	[265523] = "yellow",
	[265540] = "yellow",
	[265568] = {"blue","cyan"},
	[265668] = "blue",
	[266106] = "red",
	[266107] = "blue",
	[266209] = {"blue","orange","red"},
	[266265] = {"blue","yellow"},
	[272183] = "yellow",
	[272592] = "cyan",
	[272609] = "orange",
	[278755] = "red",
	[278961] = {"blue","orange","yellow"},
	[413044] = "red",
})

BigWigs:AddSounds("Underrot Trash", {
	[265016] = "info",
	[265019] = "alarm",
	[265081] = "long",
	[265089] = "warning",
	[265091] = {"alarm","alert"},
	[265377] = "alert",
	[265433] = "alert",
	[265487] = "alert",
	[265523] = "info",
	[265540] = "alarm",
	[265568] = {"alarm","alert"},
	[265668] = "underyou",
	[266106] = "warning",
	[266107] = "alarm",
	[266209] = {"alarm","alert"},
	[266265] = "info",
	[272183] = "alert",
	[272592] = "long",
	[272609] = "alarm",
	[278755] = "warning",
	[278961] = {"alert","warning"},
	[413044] = "warning",
})
