-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("E.D.N.A.", {
	[424795] = {"blue","red"},
	[424879] = "yellow",
	[424888] = "purple",
	[424889] = {"blue","red"},
	[424903] = "orange",
})

BigWigs:AddSounds("E.D.N.A.", {
	[424795] = "alarm",
	[424879] = "long",
	[424888] = "alert",
	[424889] = "warning",
	[424903] = "info",
})

BigWigs:AddColors("Skarmorak", {
	[422233] = "purple",
	[423200] = {"cyan","green"},
	[423538] = "orange",
	[423572] = "green",
})

BigWigs:AddSounds("Skarmorak", {
	[422233] = "alert",
	[423200] = {"info","long"},
	[423538] = "alarm",
	[423572] = "info",
})

BigWigs:AddColors("Master Machinists", {
	[428202] = "yellow",
	[428508] = "red",
	[428711] = "purple",
	[430097] = "red",
	[439577] = "cyan",
	[445541] = "orange",
	[449167] = "orange",
})

BigWigs:AddSounds("Master Machinists", {
	[428202] = "long",
	[428508] = "alarm",
	[428711] = "alert",
	[430097] = "alert",
	[439577] = "long",
	[445541] = "alarm",
	[449167] = "alarm",
})

BigWigs:AddColors("Void Speaker Eirich", {
	[427461] = {"blue","green","yellow"},
	[427852] = "red",
	[427869] = "orange",
	[457465] = "blue",
})

BigWigs:AddSounds("Void Speaker Eirich", {
	[427461] = {"info","warning"},
	[427852] = "alert",
	[427869] = "alarm",
	[457465] = "underyou",
})

BigWigs:AddColors("The Stonevault Trash", {
	[425027] = "purple",
	[425974] = "yellow",
	[426308] = {"blue","yellow"},
	[426345] = "purple",
	[426771] = "yellow",
	[428703] = "orange",
	[428879] = "purple",
	[428894] = "purple",
	[429109] = "red",
	[429427] = "cyan",
	[429545] = "yellow",
	[445207] = "red",
	[447141] = "orange",
	[448640] = "red",
	[449130] = "orange",
	[449154] = "yellow",
	[449455] = "red",
	[459210] = "purple",
	[462500] = "green",
})

BigWigs:AddSounds("The Stonevault Trash", {
	[425027] = "alarm",
	[425974] = "alert",
	[426308] = "alert",
	[426345] = "alarm",
	[426771] = "alert",
	[428703] = "alarm",
	[428879] = "alarm",
	[428894] = "alert",
	[429109] = "warning",
	[429427] = "info",
	[429545] = "alert",
	[445207] = "alert",
	[447141] = "alarm",
	[448640] = "alarm",
	[449130] = "alarm",
	[449154] = "alert",
	[449455] = "warning",
	[459210] = "alert",
	[462500] = "info",
})
