-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Glubtok", {
	[87859] = "red",
	[87861] = "yellow",
	[88009] = "cyan",
})

BigWigs:AddSounds("Glubtok", {
	[87859] = "alert",
	[87861] = "alert",
	[88009] = "long",
})

BigWigs:AddColors("Helix Gearbreaker", {
	[88300] = {"blue","red"},
	[88352] = {"blue","orange"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("Helix Gearbreaker", {
	[88300] = "info",
	[88352] = "alert",
	["stages"] = "long",
})

BigWigs:AddColors("Foe Reaper 5000", {
	[88481] = "orange",
	[88495] = {"blue","red"},
	[88522] = "cyan",
})

BigWigs:AddSounds("Foe Reaper 5000", {
	[88481] = "alarm",
	[88495] = "alert",
	[88522] = "long",
})

BigWigs:AddColors("Admiral Ripsnarl", {
	[88836] = {"blue","red"},
	[88840] = "cyan",
	[92042] = "yellow",
})

BigWigs:AddSounds("Admiral Ripsnarl", {
	[88836] = "alarm",
	[88840] = "long",
	[92042] = "warning",
})

BigWigs:AddColors("Captain Cookie", {
	[89263] = "cyan",
	[89267] = "green",
	[89732] = "red",
})

BigWigs:AddSounds("Captain Cookie", {
	[89263] = "long",
	[89267] = "info",
	[89732] = "alarm",
})

BigWigs:AddColors("Vanessa VanCleef", {
	[-2065] = "orange",
	[-2063] = "red",
	[90932] = "green",
	[92614] = "orange",
	[95542] = "yellow",
})

BigWigs:AddSounds("Vanessa VanCleef", {
	[-2065] = "alarm",
	[-2063] = "warning",
	[90932] = "info",
	[92614] = "alert",
	[95542] = "long",
})
