-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Shivermaw", {
	[201354] = "orange",
	[201355] = "orange",
	[201379] = "yellow",
	[201672] = "red",
	[201960] = "cyan",
	[202062] = "red",
})

BigWigs:AddSounds("Shivermaw", {
	[201354] = "alarm",
	[201355] = "alert",
	[201379] = "warning",
	[201672] = "long",
	[201960] = "info",
	[202062] = "warning",
})

BigWigs:AddColors("Thalena", {
	[202779] = {"blue","green"},
	[202947] = "blue",
	[203381] = "yellow",
})

BigWigs:AddSounds("Thalena", {
	[202779] = {"alert","info"},
	[202947] = "alarm",
	[203381] = "long",
})

BigWigs:AddColors("Festerface", {
	[201598] = "red",
	[201729] = "orange",
})

BigWigs:AddSounds("Festerface", {
	[201598] = "alarm",
	[201729] = "alert",
})

BigWigs:AddColors("Millificent Manastorm", {
	[201159] = {"blue","orange"},
	[201240] = "yellow",
	[201392] = "red",
	[201572] = "cyan",
})

BigWigs:AddSounds("Millificent Manastorm", {
	[201240] = "info",
	[201392] = "alarm",
	[201572] = "warning",
})

BigWigs:AddColors("Kaahrj", {
	[201146] = {"blue","orange"},
	[201148] = "yellow",
	[201153] = "red",
})

BigWigs:AddSounds("Kaahrj", {
	[201146] = "alarm",
	[201148] = "info",
	[201153] = "long",
})

BigWigs:AddColors("Anub'esset", {
	[201863] = "orange",
	[202217] = {"blue","yellow"},
	[202341] = {"blue","red"},
	[202480] = "blue",
	[202485] = "blue",
})

BigWigs:AddSounds("Anub'esset", {
	[201863] = "info",
	[202217] = "alarm",
	[202341] = "long",
	[202480] = "warning",
	[202485] = "alarm",
})

BigWigs:AddColors("Saelorn", {
	[202306] = {"blue","orange"},
	[202414] = {"blue","yellow"},
	[202473] = "red",
})

BigWigs:AddSounds("Saelorn", {
	[202306] = "alarm",
	[202414] = "alert",
	[202473] = "long",
})

BigWigs:AddColors("Fel Lord Betrug", {
	[202328] = "orange",
	[203641] = "red",
	[205233] = {"blue","green","red"},
	[210879] = {"blue","yellow"},
})

BigWigs:AddSounds("Fel Lord Betrug", {
	[202328] = "long",
	[205233] = {"alarm","info"},
	[210879] = "alert",
})

BigWigs:AddColors("Assault on Violet Hold Trash", {
	[204140] = "red",
	[204608] = {"blue","orange"},
	[204876] = "red",
	[204901] = "red",
	[205088] = "red",
})

BigWigs:AddSounds("Assault on Violet Hold Trash", {
	[204140] = "alert",
	[204608] = "alarm",
	[204876] = "alert",
	[204901] = "alert",
	[205088] = "alert",
})
