-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Vigilant Kaathar", {
	[152954] = "red",
	[153002] = {"blue","orange"},
	[153006] = "red",
	[153430] = "blue",
})

BigWigs:AddSounds("Vigilant Kaathar", {
	[153002] = "alert",
	[153006] = "warning",
	[153430] = "alarm",
})

BigWigs:AddColors("Soulbinder Nyami", {
	[153994] = "yellow",
	[154477] = {"blue","red"},
	[155327] = "orange",
})

BigWigs:AddSounds("Soulbinder Nyami", {
	[153994] = "alert",
	[154477] = "alarm",
	[155327] = "warning",
})

BigWigs:AddColors("Azzakel", {
	[153392] = {"blue","red"},
	[153764] = "yellow",
})

BigWigs:AddSounds("Azzakel", {
	[153392] = "warning",
})

BigWigs:AddColors("Teron'gor", {
	[156854] = "yellow",
	[156856] = "blue",
	[156921] = {"blue","yellow"},
	[156975] = "yellow",
	[157001] = {"blue","red"},
	[157039] = {"blue","orange"},
	[157168] = {"blue","green"},
	["stages"] = {"green","yellow"},
})

BigWigs:AddSounds("Teron'gor", {
	[156854] = "long",
	[156856] = "alarm",
	[156921] = "alert",
	[156975] = "long",
	[157001] = "alert",
	[157039] = "alarm",
	[157168] = "warning",
	["stages"] = "info",
})

BigWigs:AddColors("Auchindoun Trash", {
	[157168] = {"blue","red"},
})

BigWigs:AddSounds("Auchindoun Trash", {
	[157168] = "alert",
})

BigWigs:AddColors("Magmolatus", {
	[150023] = "orange",
	[150038] = "orange",
	[150076] = "green",
	[150078] = "green",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Magmolatus", {
	[150023] = "info",
	[150038] = "warning",
	[150076] = "info",
	[150078] = "info",
})

BigWigs:AddColors("Slave Watcher Crushto", {
	[150751] = {"blue","red"},
	[150753] = "yellow",
	[150759] = "orange",
	[153679] = "yellow",
})

BigWigs:AddSounds("Slave Watcher Crushto", {
	[150751] = "alert",
	[150753] = "long",
	[150759] = "warning",
	[153679] = "alarm",
})

BigWigs:AddColors("Roltall", {
	[152940] = "red",
	[153247] = "orange",
	[167739] = "blue",
})

BigWigs:AddSounds("Roltall", {
	[152940] = "alert",
	[153247] = "warning",
	[167739] = "alarm",
})

BigWigs:AddColors("Gug'rokk", {
	[150677] = "yellow",
	[150678] = {"blue","yellow"},
	[150755] = "red",
	[150776] = "orange",
})

BigWigs:AddSounds("Gug'rokk", {
	[150677] = "long",
	[150755] = "warning",
	[150776] = "info",
})

BigWigs:AddColors("Bloodmaul Slag Mines Trash", {
	[151447] = "orange",
	[151545] = "red",
	[151697] = "red",
})

BigWigs:AddSounds("Bloodmaul Slag Mines Trash", {
	[151447] = "alarm",
	[151545] = "warning",
	[151697] = "alert",
})

BigWigs:AddColors("Rocketspark and Borka", {
	[161090] = "red",
	[161091] = "red",
	[161092] = "red",
	[162171] = "yellow",
	[162407] = "orange",
	[162500] = "red",
	[162617] = "orange",
	[163947] = "green",
})

BigWigs:AddSounds("Rocketspark and Borka", {
	[161090] = "warning",
	[161091] = "long",
	[161092] = "long",
	[162171] = "alert",
	[162407] = "long",
	[162500] = "alarm",
	[162617] = "alert",
	[163947] = "info",
})

BigWigs:AddColors("Nitrogg Thundertower", {
	[156357] = {"blue","green","orange"},
	[160681] = {"blue","red"},
	[160965] = {"blue","green","orange"},
	[161073] = {"blue","green","yellow"},
	[163550] = "yellow",
	[166570] = {"blue","orange"},
	["adds"] = "yellow",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Nitrogg Thundertower", {
	[156357] = "info",
	[160681] = "alert",
	[160965] = "info",
	[163550] = "alert",
	[166570] = {"alert","underyou"},
	["adds"] = "alert",
	["stages"] = "long",
})

BigWigs:AddColors("Skylord Tovra", {
	[161588] = "blue",
	[161801] = "red",
	[162058] = "yellow",
	[162066] = {"blue","orange","yellow"},
	[163447] = {"blue","orange"},
})

BigWigs:AddSounds("Skylord Tovra", {
	[161588] = "underyou",
	[161801] = "long",
	[162058] = "alarm",
	[162066] = {"alert","info"},
	[163447] = "info",
})

BigWigs:AddColors("Grimrail Depot Trash", {
	[156301] = "yellow",
	[163966] = "red",
	[164168] = "purple",
	[164192] = "yellow",
	[166335] = {"red","yellow"},
	[166341] = {"blue","yellow"},
	[166380] = "orange",
	[166397] = "yellow",
	[166675] = {"blue","red"},
	[176023] = {"blue","red"},
	[176032] = {"blue","orange"},
	[176127] = "orange",
})

BigWigs:AddSounds("Grimrail Depot Trash", {
	[156301] = "alert",
	[163966] = "alarm",
	[164168] = "alert",
	[164192] = "warning",
	[166335] = "warning",
	[166341] = {"alert","underyou"},
	[166380] = "alarm",
	[166397] = "long",
	[166675] = {"alert","underyou"},
	[176023] = {"alert","warning"},
	[176032] = {"alarm","underyou"},
	[176127] = "alarm",
})

BigWigs:AddColors("Fleshrender Nok'gar", {
	[164426] = {"green","orange"},
	[164632] = "red",
	[164734] = "yellow",
	[164835] = "yellow",
	[164837] = {"blue","red"},
	[166923] = "yellow",
	["stages"] = {"cyan","yellow"},
})

BigWigs:AddSounds("Fleshrender Nok'gar", {
	[164426] = {"info","warning"},
	[164632] = "long",
	[164734] = "alarm",
	[164835] = {"alert","warning"},
	[164837] = "alert",
	[166923] = "alert",
	["stages"] = {"info","long"},
})

BigWigs:AddColors("Grimrail Enforcers", {
	[163376] = "yellow",
	[163379] = "red",
	[163390] = "red",
	[163665] = "orange",
	[163689] = {"blue","green","red","yellow"},
	[163705] = "yellow",
	[163740] = {"blue","yellow"},
	[165152] = "red",
})

BigWigs:AddSounds("Grimrail Enforcers", {
	[163376] = "alert",
	[163379] = "alert",
	[163390] = "alarm",
	[163665] = "alarm",
	[163689] = {"alert","info","warning"},
	[163705] = "warning",
	[163740] = "alert",
	[165152] = "alarm",
})

BigWigs:AddColors("Oshir", {
	[161256] = "orange",
	[162415] = {"blue","green","red"},
	[178124] = "yellow",
})

BigWigs:AddSounds("Oshir", {
	[161256] = "alarm",
	[162415] = {"info","long"},
	[178124] = "alert",
})

BigWigs:AddColors("Skulloc", {
	[168227] = "orange",
	[168348] = {"blue","red"},
	[168929] = {"green","yellow"},
	[168965] = "orange",
})

BigWigs:AddSounds("Skulloc", {
	[168227] = "long",
	[168348] = {"alert","warning"},
	[168929] = {"alert","info"},
	[168965] = "alert",
})

BigWigs:AddColors("Iron Docks Trash", {
	[158337] = "orange",
	[164632] = "blue",
	[167233] = {"blue","red"},
	[167815] = "purple",
	[172636] = "blue",
	[172943] = "purple",
	[172952] = "yellow",
	[172963] = "blue",
	[172982] = "red",
	[173105] = {"blue","yellow"},
	[173135] = "yellow",
	[173324] = "blue",
	[173384] = "red",
	[173480] = {"blue","orange"},
	[173514] = "red",
})

BigWigs:AddSounds("Iron Docks Trash", {
	[158337] = "warning",
	[164632] = "underyou",
	[167233] = {"alarm","underyou"},
	[167815] = "alarm",
	[172636] = "underyou",
	[172943] = "alert",
	[172952] = "warning",
	[172963] = "underyou",
	[172982] = "alarm",
	[173105] = {"alarm","underyou"},
	[173135] = "alert",
	[173324] = "underyou",
	[173384] = "alarm",
	[173480] = {"alert","underyou"},
	[173514] = "alarm",
})

BigWigs:AddColors("Sadana Bloodfury", {
	[153094] = "orange",
	[153153] = "cyan",
	[153224] = "blue",
	[153240] = "yellow",
	[164974] = "red",
})

BigWigs:AddSounds("Sadana Bloodfury", {
	[153094] = "alarm",
	[153153] = "alert",
	[153224] = "underyou",
	[153240] = "alert",
	[164974] = "warning",
})

BigWigs:AddColors("Nhallish", {
	[152792] = "purple",
	[152801] = "yellow",
	[152979] = "red",
	[153067] = "orange",
	[153623] = "yellow",
})

BigWigs:AddSounds("Nhallish", {
	[152792] = "alarm",
	[152801] = "alarm",
	[152979] = "info",
	[153067] = "long",
	[153623] = "alert",
})

BigWigs:AddColors("Bonemaw", {
	[153804] = {"green","orange","yellow"},
	[154175] = "orange",
	[165578] = "red",
	["submerge"] = "cyan",
	["summon_worms"] = "cyan",
})

BigWigs:AddSounds("Bonemaw", {
	[153804] = {"info","long","warning"},
	[154175] = "alarm",
	[165578] = "alert",
	["submerge"] = "info",
	["summon_worms"] = "info",
})

BigWigs:AddColors("Ner'zhul", {
	[154350] = "red",
	[154442] = "yellow",
	[154469] = {"blue","orange","red"},
})

BigWigs:AddSounds("Ner'zhul", {
	[154350] = "alert",
	[154442] = "alarm",
	[154469] = {"alert","underyou","warning"},
})

BigWigs:AddColors("Shadowmoon Burial Grounds Trash", {
	[152818] = "yellow",
	[152819] = {"blue","yellow"},
	[152964] = "red",
	[153268] = "yellow",
	[153395] = "red",
	[156718] = "orange",
	[164907] = "purple",
	[394512] = "orange",
	[398150] = {"blue","red"},
	[398151] = "yellow",
	[398154] = "orange",
	[398206] = "red",
})

BigWigs:AddSounds("Shadowmoon Burial Grounds Trash", {
	[152818] = "alert",
	[152819] = "alert",
	[152964] = "alert",
	[153268] = "alert",
	[153395] = "alarm",
	[156718] = "warning",
	[164907] = {"alarm","alert"},
	[394512] = "long",
	[398150] = {"alarm","warning"},
	[398151] = "alert",
	[398154] = "alarm",
	[398206] = "warning",
})

BigWigs:AddColors("Ranjit", {
	[153315] = "red",
	[156793] = "orange",
	[165731] = {"blue","yellow"},
})

BigWigs:AddSounds("Ranjit", {
	[156793] = "warning",
	[165731] = "alarm",
})

BigWigs:AddColors("Araknath", {
	[154110] = "orange",
	[154135] = "red",
	[154159] = "yellow",
})

BigWigs:AddSounds("Araknath", {
	[154110] = "warning",
	[154135] = "info",
	[154159] = "long",
})

BigWigs:AddColors("Rukhran", {
	[153794] = "yellow",
	[153810] = "red",
	[159382] = {"green","orange"},
	[167757] = "blue",
})

BigWigs:AddSounds("Rukhran", {
	[153794] = "warning",
	[153810] = "info",
	[159382] = "long",
	[167757] = "alarm",
})

BigWigs:AddColors("High Sage Viryx", {
	[153954] = {"blue","yellow"},
	[154055] = "orange",
	["adds"] = "red",
})

BigWigs:AddSounds("High Sage Viryx", {
	[153954] = "warning",
	[154055] = "long",
	["adds"] = "info",
})

BigWigs:AddColors("Witherbark", {
	[-10098] = "orange",
	[164275] = "cyan",
	[164294] = {"blue","yellow"},
	[164357] = "purple",
	[164438] = "cyan",
})

BigWigs:AddSounds("Witherbark", {
	[-10098] = "info",
	[164275] = "long",
	[164294] = {"alert","underyou"},
	[164357] = "alarm",
	[164438] = "info",
})

BigWigs:AddColors("Ancient Protectors", {
	[168082] = {"red","yellow"},
	[427459] = "yellow",
	[427498] = "cyan",
	[427509] = "cyan",
	[427510] = "purple",
	[427513] = "blue",
})

BigWigs:AddSounds("Ancient Protectors", {
	[168082] = "warning",
	[427459] = "warning",
	[427498] = "long",
	[427509] = "long",
	[427510] = "alert",
	[427513] = "underyou",
})

BigWigs:AddColors("Xeri'tac", {
	[-10502] = "cyan",
	[-10492] = "yellow",
	[169233] = "red",
	[169248] = "yellow",
	[169376] = "red",
	[169382] = "orange",
	[172643] = "orange",
	[173080] = "blue",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Xeri'tac", {
	[-10502] = "info",
	[169233] = "alert",
	[169248] = "warning",
	[169376] = "alert",
	[169382] = "alarm",
	[172643] = "alarm",
	[173080] = "alarm",
	["stages"] = "long",
})

BigWigs:AddColors("Archmage Sol", {
	[427899] = "red",
	[428082] = "orange",
	[428139] = "yellow",
})

BigWigs:AddSounds("Archmage Sol", {
	[427899] = "long",
	[428082] = "alarm",
	[428139] = "info",
})

BigWigs:AddColors("Yalnu", {
	[169179] = "orange",
	[169613] = "yellow",
	[169929] = "red",
	[428823] = "cyan",
})

BigWigs:AddSounds("Yalnu", {
	[169179] = "alarm",
	[169613] = "long",
	[169929] = "alarm",
	[428823] = "info",
})

BigWigs:AddColors("The Everbloom Trash", {
	[164886] = {"blue","purple"},
	[164887] = "red",
	[164965] = {"blue","orange","yellow"},
	[165123] = {"blue","red"},
	[165213] = "red",
	[169445] = "red",
	[169494] = {"blue","yellow"},
	[172578] = "orange",
	[426500] = "orange",
	[426845] = "yellow",
	[426974] = "red",
	[427223] = "orange",
})

BigWigs:AddSounds("The Everbloom Trash", {
	[164886] = "alert",
	[164887] = {"alert","warning"},
	[164965] = {"alarm","alert","info"},
	[165123] = {"alarm","alert"},
	[165213] = "alert",
	[169445] = "alert",
	[169494] = {"info","underyou"},
	[172578] = "alarm",
	[426500] = "alarm",
	[426845] = "alarm",
	[426974] = "alarm",
	[427223] = "alert",
})

BigWigs:AddColors("Orebender Gor'ashan", {
	[154448] = "orange",
	[166168] = {"green","red","yellow"},
})

BigWigs:AddSounds("Orebender Gor'ashan", {
	[154448] = "alert",
	[166168] = {"long","warning"},
})

BigWigs:AddColors("Kyrak", {
	[155037] = "red",
	[161199] = "yellow",
	[161203] = {"blue","orange"},
	[161288] = "blue",
})

BigWigs:AddSounds("Kyrak", {
	[155037] = "info",
	[161199] = "alert",
	[161203] = {"long","warning"},
	[161288] = "alarm",
})

BigWigs:AddColors("Commander Tharbek", {
	[161833] = "blue",
	[161882] = "orange",
	[161989] = "red",
	[162090] = {"blue","yellow"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("Commander Tharbek", {
	[161833] = "underyou",
	[161882] = "long",
	[162090] = "alert",
	["stages"] = "info",
})

BigWigs:AddColors("Ragewing the Untamed", {
	[-10740] = {"green","red"},
	[154996] = "yellow",
	[155057] = "blue",
	[155620] = "orange",
})

BigWigs:AddSounds("Ragewing the Untamed", {
	[-10740] = "long",
	[154996] = "warning",
	[155057] = "alarm",
	[155620] = "info",
})

BigWigs:AddColors("Warlord Zaela", {
	[155721] = {"blue","yellow"},
	["stages"] = {"green","red"},
})

BigWigs:AddSounds("Warlord Zaela", {
	[155721] = "alert",
	["stages"] = "info",
})
