-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Ranjit", {
	[153315] = "red",
	[156793] = "orange",
	[165731] = {"blue","yellow"},
})

BigWigs:AddSounds("Ranjit", {
	[156793] = "warning",
	[165731] = "alarm",
})

BigWigs:AddColors("Araknath", {
	[154110] = "orange",
	[154135] = "red",
	[154159] = "yellow",
})

BigWigs:AddSounds("Araknath", {
	[154110] = "warning",
	[154135] = "info",
	[154159] = "long",
})

BigWigs:AddColors("Rukhran", {
	[153794] = "yellow",
	[153810] = "red",
	[159382] = {"green","orange"},
	[167757] = "blue",
})

BigWigs:AddSounds("Rukhran", {
	[153794] = "warning",
	[153810] = "info",
	[159382] = "long",
	[167757] = "alarm",
})

BigWigs:AddColors("High Sage Viryx", {
	[153954] = {"blue","yellow"},
	[154055] = "orange",
	["adds"] = "red",
})

BigWigs:AddSounds("High Sage Viryx", {
	[153954] = "warning",
	[154055] = "long",
	["adds"] = "info",
})
