-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Agatha", {
	[236161] = "blue",
	[242989] = "cyan",
	[243027] = {"green","orange"},
	[243111] = {"green","red"},
	["fuming_imp"] = "orange",
	["imp_servant"] = "yellow",
})

BigWigs:AddSounds("Agatha", {
	[236161] = "alarm",
	[243027] = "alert",
	[243111] = "long",
	["fuming_imp"] = "warning",
	["imp_servant"] = "info",
})

BigWigs:AddColors("Archmage Xylem", {
	[231443] = "orange",
	[231522] = "red",
	[232672] = "blue",
	[233248] = "red",
	[234728] = "cyan",
	[242015] = "yellow",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Archmage Xylem", {
	[231443] = "alarm",
	[231522] = "alert",
	[232672] = "alarm",
	[233248] = "long",
})

BigWigs:AddColors("Kruul", {
	[233473] = "green",
	[234422] = "blue",
	[234423] = "orange",
	[234428] = "yellow",
	[234631] = "red",
	[234673] = "orange",
	[234676] = "orange",
	[234920] = "yellow",
	[236572] = "red",
	[240790] = "red",
	["nether_aberration"] = "cyan",
	["smoldering_infernal"] = "yellow",
	["stages"] = "green",
})

BigWigs:AddSounds("Kruul", {
	[233473] = "long",
	[234422] = "warning",
	[234423] = "alert",
	[234428] = "info",
	[234631] = "alarm",
	[234673] = "alert",
	[234676] = "warning",
	[234920] = "info",
	[236572] = "alarm",
	[240790] = "warning",
	["nether_aberration"] = "info",
	["smoldering_infernal"] = "info",
	["stages"] = "long",
})

BigWigs:AddColors("Lord Erdris Thorn", {
	[235823] = "orange",
	[235833] = "yellow",
	[235984] = "red",
	[236720] = "red",
	[237188] = "red",
	[237191] = "orange",
})

BigWigs:AddSounds("Lord Erdris Thorn", {
	[235823] = "alarm",
	[235833] = "alert",
	[235984] = "alert",
	[236720] = "alarm",
	[237188] = "warning",
	[237191] = "alarm",
})

BigWigs:AddColors("Raest", {
	[202081] = "red",
	[235308] = "green",
	[235578] = {"blue","orange"},
	["handFromBeyond"] = "cyan",
	["rune"] = "yellow",
	["thing"] = "yellow",
})

BigWigs:AddSounds("Raest", {
	[202081] = "long",
	[235308] = "info",
	[235578] = "alert",
	["rune"] = "warning",
	["thing"] = "alarm",
})

BigWigs:AddColors("Sigryn", {
	[237730] = "orange",
	[237857] = "yellow",
	[237914] = "red",
	[237945] = {"green","red"},
	[237947] = {"green","orange"},
	[237949] = {"green","orange"},
	[238691] = "blue",
	[238694] = "yellow",
})

BigWigs:AddSounds("Sigryn", {
	[237730] = "alarm",
	[237857] = "alarm",
	[237914] = "warning",
	[237945] = {"info","long"},
	[237947] = {"alarm","info"},
	[237949] = {"alert","info"},
	[238691] = "alarm",
	[238694] = "info",
})

BigWigs:AddColors("Tugar Bloodtotem", {
	[241687] = "red",
	[242733] = "orange",
	[243224] = {"blue","red"},
	["charge"] = "blue",
	["rupture"] = "yellow",
	["submerge"] = "orange",
})

BigWigs:AddSounds("Tugar Bloodtotem", {
	[241687] = "alert",
	[242733] = "warning",
	[243224] = "long",
	["charge"] = "alarm",
	["rupture"] = "alarm",
	["submerge"] = "alarm",
})
