-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Tendris Warpwood", {
	[5568] = "yellow",
	[22924] = "red",
	[22994] = {"blue","orange","yellow"},
})

BigWigs:AddSounds("Tendris Warpwood", {
	[22924] = "alert",
	[22994] = {"alarm","alert"},
})

BigWigs:AddColors("Illyanna Ravenoak", {
	[22910] = "orange",
	[22911] = {"blue","red"},
	[22914] = "yellow",
	[30933] = "red",
})

BigWigs:AddSounds("Illyanna Ravenoak", {
	[22910] = "info",
	[22911] = "alarm",
	[22914] = "alert",
	[30933] = "alarm",
})

BigWigs:AddColors("Magister Kalendris", {
	[7645] = {"blue","yellow"},
	[22917] = "cyan",
})

BigWigs:AddSounds("Magister Kalendris", {
	[7645] = "alert",
	[22917] = "info",
})

BigWigs:AddColors("Immol'thar", {
	[5568] = "orange",
	[22899] = "cyan",
	[22950] = {"blue","yellow"},
	[451127] = "cyan",
	[452516] = "orange",
})

BigWigs:AddSounds("Immol'thar", {
	[22899] = "info",
	[22950] = "alert",
	[451127] = "info",
})

BigWigs:AddColors("Prince Tortheldrin", {
	[22995] = {"blue","cyan"},
	[67037] = "orange",
})

BigWigs:AddSounds("Prince Tortheldrin", {
	[22995] = "info",
	[67037] = "alarm",
})

BigWigs:AddColors("Guard Mol'dar", {
	[8269] = "cyan",
	[11972] = {"blue","orange"},
	[14516] = "purple",
	[15749] = {"blue","yellow"},
})

BigWigs:AddSounds("Guard Mol'dar", {
	[8269] = "long",
	[11972] = "alarm",
	[14516] = "alert",
	[15749] = "alert",
})

BigWigs:AddColors("Stomper Kreeg", {
	[15578] = "yellow",
	[16740] = "red",
	[22833] = "purple",
	[22835] = "cyan",
})

BigWigs:AddSounds("Stomper Kreeg", {
	[15578] = "alert",
	[16740] = "alert",
	[22833] = "alarm",
	[22835] = "long",
})

BigWigs:AddColors("King Gordok", {
	[15572] = "purple",
	[16727] = "red",
	[16856] = "purple",
	[22886] = {"blue","yellow"},
})

BigWigs:AddSounds("King Gordok", {
	[15572] = "alert",
	[16727] = "alarm",
	[16856] = "alarm",
	[22886] = "info",
})

BigWigs:AddColors("Lethtendris", {
	[11962] = "orange",
	[13338] = {"blue","yellow"},
	[15744] = "yellow",
	[16247] = {"blue","yellow"},
	[17228] = "red",
	[22710] = "yellow",
	[22713] = {"blue","orange"},
})

BigWigs:AddSounds("Lethtendris", {
	[11962] = "alert",
	[13338] = "alert",
	[15744] = "alert",
	[16247] = "alert",
	[17228] = "alert",
	[22710] = "alert",
	[22713] = "alert",
})

BigWigs:AddColors("Hydrospawn", {
	[22419] = "red",
	[22421] = "orange",
	[22714] = "cyan",
})

BigWigs:AddSounds("Hydrospawn", {
	[22419] = "alert",
	[22421] = "alarm",
	[22714] = "info",
})

BigWigs:AddColors("Zevrim Thornhoof", {
	[17228] = "red",
	[22478] = "orange",
	[22651] = {"blue","yellow"},
})

BigWigs:AddSounds("Zevrim Thornhoof", {
	[17228] = "alert",
	[22478] = "alert",
	[22651] = "alarm",
})

BigWigs:AddColors("Alzzin the Wildshaper", {
	[7948] = "yellow",
	[10101] = "purple",
	[22415] = "orange",
	[22661] = "yellow",
	[22662] = {"blue","orange","red"},
	[22689] = {"blue","orange"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("Alzzin the Wildshaper", {
	[7948] = "warning",
	[10101] = "alert",
	[22415] = "alert",
	[22661] = "alert",
	[22662] = {"alarm","alert"},
	[22689] = "alarm",
	["stages"] = "long",
})

BigWigs:AddColors("Dire Maul Trash", {
})

BigWigs:AddSounds("Dire Maul Trash", {
})
