-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Big M.O.M.M.A.", {
	[460156] = "green",
	[469981] = "cyan",
	[471585] = "cyan",
	[472452] = "orange",
	[473220] = {"blue","yellow"},
	[473287] = "blue",
	[473351] = "purple",
	[1214780] = "red",
})

BigWigs:AddSounds("Big M.O.M.M.A.", {
	[460156] = {"info","long"},
	[469981] = "info",
	[471585] = "info",
	[472452] = "alarm",
	[473220] = {"alarm","warning"},
	[473287] = "underyou",
	[473351] = "alert",
	[1214780] = "warning",
})

BigWigs:AddColors("Demolition Duo", {
	[459779] = {"blue","green","red"},
	[459799] = "purple",
	[460867] = "yellow",
	[470090] = "cyan",
	[473690] = {"blue","orange"},
	[1217653] = "orange",
})

BigWigs:AddSounds("Demolition Duo", {
	[459779] = {"alarm","info"},
	[459799] = "alert",
	[460867] = "long",
	[470090] = "long",
	[473690] = {"alarm","info"},
	[1217653] = "alarm",
})

BigWigs:AddColors("Swampface", {
	[469478] = "purple",
	[470039] = "blue",
	[473070] = "yellow",
	[473114] = "orange",
})

BigWigs:AddSounds("Swampface", {
	[469478] = "alert",
	[470039] = "info",
	[473070] = "long",
	[473114] = "alarm",
})

BigWigs:AddColors("Geezle Gigazap", {
	[465463] = "orange",
	[466190] = "purple",
	[468723] = "blue",
	[468813] = "yellow",
	[468841] = {"blue","red"},
})

BigWigs:AddSounds("Geezle Gigazap", {
	[465463] = "long",
	[466190] = {"alarm","alert"},
	[468723] = "underyou",
	[468813] = "info",
	[468841] = "warning",
})

BigWigs:AddColors("Operation: Floodgate Trash", {
	[462771] = {"blue","red"},
	[463058] = "red",
	[465120] = "yellow",
	[465408] = "cyan",
	[465666] = "purple",
	[465682] = "orange",
	[465754] = "yellow",
	[465813] = {"blue","orange","yellow"},
	[465827] = "yellow",
	[468631] = "red",
	[468726] = "cyan",
	[469721] = "yellow",
	[469799] = {"blue","orange"},
	[469818] = "red",
	[471733] = "red",
	[471736] = "orange",
	[474337] = {"blue","orange"},
	[1214337] = "green",
	[1214468] = "red",
	[1216039] = "orange",
	[1217496] = "orange",
	["weapons_stockpiles_pilfered"] = "green",
})

BigWigs:AddSounds("Operation: Floodgate Trash", {
	[462771] = {"alert","underyou"},
	[463058] = "alert",
	[465120] = "alarm",
	[465408] = "info",
	[465666] = "alert",
	[465682] = "alarm",
	[465754] = "alarm",
	[465813] = "alert",
	[465827] = "info",
	[468631] = "alert",
	[468726] = "info",
	[469721] = "alert",
	[469799] = "info",
	[469818] = "alarm",
	[471733] = "alert",
	[471736] = "alarm",
	[474337] = {"alarm","underyou"},
	[1214337] = "info",
	[1214468] = "alert",
	[1216039] = "alarm",
	[1217496] = "alarm",
	["weapons_stockpiles_pilfered"] = "info",
})
