-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Watchkeeper Gargolmar", {
	[8362] = {"blue","yellow"},
	[11639] = {"blue","orange"},
	[12039] = "red",
	[14032] = {"blue","orange"},
	[36814] = {"blue","purple"},
})

BigWigs:AddSounds("Watchkeeper Gargolmar", {
	[8362] = {"alarm","warning"},
	[12039] = "warning",
})

BigWigs:AddColors("Omor the Unscarred", {
	[30695] = {"blue","orange"},
})

BigWigs:AddSounds("Omor the Unscarred", {
})

BigWigs:AddColors("Vazruden", {
	["stages"] = "cyan",
})

BigWigs:AddSounds("Vazruden", {
})
