-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Hydromancer Thespia", {
	[25033] = "blue",
	[31481] = {"blue","yellow"},
	[31718] = {"blue","red"},
})

BigWigs:AddSounds("Hydromancer Thespia", {
	[25033] = "alert",
	[31481] = "alarm",
	[31718] = "warning",
})

BigWigs:AddColors("Mekgineer Steamrigger", {
	[31485] = {"blue","orange"},
	["mechanics"] = {"red","yellow"},
})

BigWigs:AddSounds("Mekgineer Steamrigger", {
	[31485] = "alert",
})

BigWigs:AddColors("Warlord Kalithresh", {
	[-6003] = "red",
	[16172] = {"blue","yellow"},
	[36453] = {"blue","orange"},
})

BigWigs:AddSounds("Warlord Kalithresh", {
	[-6003] = "warning",
	[16172] = "alarm",
	[36453] = "long",
})
