-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Mechano-Lord Capacitus", {
	[35158] = {"green","orange"},
	[35159] = {"green","orange"},
	[39096] = {"cyan","orange","red"},
})

BigWigs:AddSounds("Mechano-Lord Capacitus", {
	[39096] = "info",
})

BigWigs:AddColors("Gatewatcher Iron-Hand", {
	[35311] = {"blue","orange"},
	[39193] = "red",
	[39194] = {"blue","yellow"},
})

BigWigs:AddSounds("Gatewatcher Iron-Hand", {
	[35311] = "alarm",
	[39194] = {"alert","long"},
})

BigWigs:AddColors("Gatewatcher Gyro-Kill", {
	[35311] = {"blue","orange"},
	[39193] = "red",
})

BigWigs:AddSounds("Gatewatcher Gyro-Kill", {
	[35311] = "alarm",
})

BigWigs:AddColors("Nethermancer Sepethrea", {
	[-5488] = {"blue","cyan"},
	[35250] = {"blue","orange"},
	[35312] = "blue",
	[35314] = {"blue","red"},
	["fixate"] = {"blue","yellow"},
})

BigWigs:AddSounds("Nethermancer Sepethrea", {
	[-5488] = {"alert","info"},
	[35250] = "alarm",
	[35312] = "alert",
	[35314] = "warning",
	["fixate"] = "long",
})

BigWigs:AddColors("Pathaleon the Calculator", {
	[35280] = {"blue","red"},
	[35285] = "red",
})

BigWigs:AddSounds("Pathaleon the Calculator", {
})
