-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("General Husam", {
	[83113] = {"blue","yellow"},
	[83445] = "red",
	[91263] = "orange",
})

BigWigs:AddSounds("General Husam", {
	[83113] = "alert",
	[83445] = "info",
	[91263] = "alarm",
})

BigWigs:AddColors("Lockmaw", {
	[81630] = {"blue","yellow"},
	[81690] = {"blue","red"},
	[84784] = "orange",
})

BigWigs:AddSounds("Lockmaw", {
	[81690] = "alert",
})

BigWigs:AddColors("High Prophet Barim", {
	[82506] = "red",
	[82622] = "blue",
	[88814] = {"blue","yellow"},
})

BigWigs:AddSounds("High Prophet Barim", {
	[82622] = "alarm",
})

BigWigs:AddColors("Siamat", {
	["servant"] = "red",
	["stages"] = {"cyan","green"},
})

BigWigs:AddSounds("Siamat", {
	["servant"] = "alert",
	["stages"] = "info",
})
