-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Web General Ab'enar", {
	[448412] = "yellow",
	[448443] = "red",
	[448444] = "orange",
})

BigWigs:AddSounds("Web General Ab'enar", {
	[448412] = "long",
	[448443] = "alert",
	[448444] = "alert",
})

BigWigs:AddColors("Maklin Drillstab", {
	[1217903] = {"blue","red"},
	[1217905] = "orange",
	[1217913] = "yellow",
})

BigWigs:AddSounds("Maklin Drillstab", {
	[1217903] = "alert",
	[1217905] = "alarm",
	[1217913] = "info",
})

BigWigs:AddColors("The Biggest Bug", {
	[448443] = "red",
	[448444] = "orange",
})

BigWigs:AddSounds("The Biggest Bug", {
	[448443] = "alert",
	[448444] = "alert",
})
