-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Ymiron", {
	[193211] = "orange",
	[193364] = "red",
	[193566] = "yellow",
	[193977] = "yellow",
})

BigWigs:AddSounds("Ymiron", {
	[193211] = "alert",
	[193364] = "long",
	[193566] = "warning",
	[193977] = "alarm",
})

BigWigs:AddColors("Harbaron", {
	[194216] = "orange",
	[194231] = "yellow",
	[194325] = {"blue","red"},
	[194668] = "blue",
})

BigWigs:AddSounds("Harbaron", {
	[194216] = "alert",
	[194231] = "info",
	[194325] = "warning",
	[194668] = "alarm",
})

BigWigs:AddColors("Helya", {
	[185539] = "blue",
	[196947] = "cyan",
	[197262] = {"blue","yellow"},
	[198495] = "red",
	[202088] = "orange",
	[227233] = "orange",
	["destructor_tentacle"] = "yellow",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Helya", {
	[185539] = "warning",
	[196947] = "info",
	[197262] = "alert",
	[198495] = "warning",
	[202088] = "alarm",
	[227233] = "alarm",
	["destructor_tentacle"] = "warning",
	["stages"] = "info",
})

BigWigs:AddColors("Maw of Souls Trash", {
	[192019] = "yellow",
	[194615] = "yellow",
	[194657] = "orange",
	[195293] = "orange",
	[198324] = {"blue","red"},
	[198405] = {"red","yellow"},
	[199514] = {"blue","orange"},
	[199589] = {"blue","orange"},
	[216197] = "orange",
})

BigWigs:AddSounds("Maw of Souls Trash", {
	[192019] = "long",
	[194615] = "alarm",
	[194657] = "alarm",
	[195293] = "long",
	[198324] = {"alarm","warning"},
	[198405] = {"info","warning"},
	[199514] = {"alarm","alert"},
	[199589] = {"alarm","alert"},
	[216197] = "alarm",
})
