-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Kin-Tara", {
	[320966] = "purple",
	[321009] = {"blue","yellow"},
	[324368] = "cyan",
	[327481] = {"blue","orange"},
	[331251] = {"blue","red"},
})

BigWigs:AddSounds("Kin-Tara", {
	[320966] = "alarm",
	[321009] = {"alert","underyou"},
	[324368] = "long",
	[327481] = "alert",
	[331251] = {"alert","warning"},
})

BigWigs:AddColors("Ventunax", {
	[324146] = "yellow",
	[324205] = "red",
	[334485] = "cyan",
})

BigWigs:AddSounds("Ventunax", {
	[324146] = "alert",
	[324205] = "warning",
	[334485] = "long",
})

BigWigs:AddColors("Oryphrion", {
	[324046] = "yellow",
	[324427] = "red",
	[324608] = "yellow",
	[334053] = {"blue","red"},
	["stages"] = {"cyan","green","orange"},
})

BigWigs:AddSounds("Oryphrion", {
	[324046] = "alert",
	[324427] = "warning",
	[324608] = "alert",
	[334053] = "warning",
	["stages"] = {"info","long"},
})

BigWigs:AddColors("Devos, Paragon of Doubt", {
	[322818] = {"blue","green","yellow"},
	[323943] = {"blue","orange"},
	[334625] = "yellow",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Devos, Paragon of Doubt", {
	[322818] = {"alarm","info"},
	[323943] = "alert",
	[334625] = "warning",
	["stages"] = "long",
})

BigWigs:AddColors("Spires of Ascension Trash", {
	[317661] = {"blue","yellow"},
	[317936] = "orange",
	[317963] = {"blue","orange","yellow"},
	[317985] = "red",
	[327332] = {"blue","yellow"},
	[327413] = "red",
	[327648] = "orange",
	[327655] = {"blue","yellow"},
	[328288] = {"blue","yellow"},
	[328295] = "orange",
	[328458] = "red",
	[328462] = "orange",
})

BigWigs:AddSounds("Spires of Ascension Trash", {
	[317661] = "alert",
	[317936] = "alert",
	[317963] = "alert",
	[317985] = "alarm",
	[327332] = "info",
	[327413] = "alert",
	[327648] = "alert",
	[327655] = "info",
	[328288] = "info",
	[328295] = "alert",
	[328458] = "alarm",
	[328462] = "alert",
})
